package sqlparse

import (
	"encoding/json"
	"strings"
	"testing"
)

// TestSplitStatementsToJSON verifies that SplitStatements output can be
// marshaled to a valid JSON array, as used by the build handler's .split.json
// companion file generation.
func TestSplitStatementsToJSON(t *testing.T) {
	t.Run("multi-statement DDL", func(t *testing.T) {
		ddl := "CREATE TABLE t (id int);\nCREATE INDEX idx ON t (id);"
		stmts, err := SplitStatements(ddl)
		if err != nil {
			t.Fatalf("SplitStatements: %v", err)
		}
		if len(stmts) != 2 {
			t.Fatalf("expected 2 statements, got %d: %v", len(stmts), stmts)
		}

		data, err := json.MarshalIndent(stmts, "", "  ")
		if err != nil {
			t.Fatalf("json.MarshalIndent: %v", err)
		}

		// Verify it's valid JSON.
		var parsed []string
		if err := json.Unmarshal(data, &parsed); err != nil {
			t.Fatalf("round-trip unmarshal: %v", err)
		}
		if len(parsed) != 2 {
			t.Fatalf("expected 2 elements after round-trip, got %d", len(parsed))
		}
		if parsed[0] != "CREATE TABLE t (id int);" {
			t.Errorf("stmt[0]: expected %q, got %q", "CREATE TABLE t (id int);", parsed[0])
		}
		if parsed[1] != "CREATE INDEX idx ON t (id);" {
			t.Errorf("stmt[1]: expected %q, got %q", "CREATE INDEX idx ON t (id);", parsed[1])
		}
	})

	t.Run("header stripping before split", func(t *testing.T) {
		// Simulate the build handler's header stripping logic.
		header := "-- Generated by pgdesign -- do not edit\n\n"
		ddl := "CREATE TABLE t (id int);\nCREATE TABLE u (id int);"
		content := header + ddl

		stripped := strings.TrimPrefix(content, header)
		stmts, err := SplitStatements(stripped)
		if err != nil {
			t.Fatalf("SplitStatements: %v", err)
		}
		if len(stmts) != 2 {
			t.Fatalf("expected 2 statements, got %d: %v", len(stmts), stmts)
		}

		data, err := json.MarshalIndent(stmts, "", "  ")
		if err != nil {
			t.Fatalf("json.MarshalIndent: %v", err)
		}

		var parsed []string
		if err := json.Unmarshal(data, &parsed); err != nil {
			t.Fatalf("round-trip unmarshal: %v", err)
		}
		if len(parsed) != 2 {
			t.Fatalf("expected 2 elements, got %d", len(parsed))
		}
	})

	t.Run("dollar-quoted function body stays single statement", func(t *testing.T) {
		ddl := `CREATE TABLE t (id int);
CREATE FUNCTION test() RETURNS void AS $$
BEGIN
  INSERT INTO t VALUES (1);
END;
$$ LANGUAGE plpgsql;
CREATE TABLE u (id int);`
		stmts, err := SplitStatements(ddl)
		if err != nil {
			t.Fatalf("SplitStatements: %v", err)
		}
		if len(stmts) != 3 {
			t.Fatalf("expected 3 statements, got %d: %v", len(stmts), stmts)
		}

		data, err := json.MarshalIndent(stmts, "", "  ")
		if err != nil {
			t.Fatalf("json.MarshalIndent: %v", err)
		}

		var parsed []string
		if err := json.Unmarshal(data, &parsed); err != nil {
			t.Fatalf("round-trip unmarshal: %v", err)
		}
		if len(parsed) != 3 {
			t.Fatalf("expected 3 elements, got %d", len(parsed))
		}
		if !strings.HasPrefix(parsed[1], "CREATE FUNCTION") {
			t.Errorf("stmt[1] should be the function, got %q", parsed[1])
		}
	})

	t.Run("empty DDL produces null JSON", func(t *testing.T) {
		stmts, err := SplitStatements("")
		if err != nil {
			t.Fatalf("SplitStatements: %v", err)
		}
		if stmts != nil {
			t.Fatalf("expected nil, got %v", stmts)
		}

		data, err := json.MarshalIndent(stmts, "", "  ")
		if err != nil {
			t.Fatalf("json.MarshalIndent: %v", err)
		}
		if string(data) != "null" {
			t.Errorf("expected %q, got %q", "null", string(data))
		}
	})
}
