package sqlparse

import (
	"encoding/json"
	"strings"
	"testing"
)

// splitJSONPayload mirrors the versioned .split.json format used by the build handler.
type splitJSONPayload struct {
	Version    int      `json:"version"`
	Statements []string `json:"statements"`
}

// TestSplitStatementsToJSON verifies that SplitStatements output can be
// marshaled to the versioned .split.json format used by the build handler.
func TestSplitStatementsToJSON(t *testing.T) {
	t.Run("multi-statement DDL", func(t *testing.T) {
		ddl := "CREATE TABLE t (id int);\nCREATE INDEX idx ON t (id);"
		stmts, err := SplitStatements(ddl)
		if err != nil {
			t.Fatalf("SplitStatements: %v", err)
		}
		if len(stmts) != 2 {
			t.Fatalf("expected 2 statements, got %d: %v", len(stmts), stmts)
		}

		payload := splitJSONPayload{Version: 1, Statements: stmts}
		data, err := json.MarshalIndent(payload, "", "  ")
		if err != nil {
			t.Fatalf("json.MarshalIndent: %v", err)
		}

		// Verify it's a valid versioned JSON object.
		var parsed splitJSONPayload
		if err := json.Unmarshal(data, &parsed); err != nil {
			t.Fatalf("round-trip unmarshal: %v", err)
		}
		if parsed.Version != 1 {
			t.Errorf("expected version 1, got %d", parsed.Version)
		}
		if len(parsed.Statements) != 2 {
			t.Fatalf("expected 2 statements after round-trip, got %d", len(parsed.Statements))
		}
		if parsed.Statements[0] != "CREATE TABLE t (id int);" {
			t.Errorf("stmt[0]: expected %q, got %q", "CREATE TABLE t (id int);", parsed.Statements[0])
		}
		if parsed.Statements[1] != "CREATE INDEX idx ON t (id);" {
			t.Errorf("stmt[1]: expected %q, got %q", "CREATE INDEX idx ON t (id);", parsed.Statements[1])
		}
	})

	t.Run("header stripping before split", func(t *testing.T) {
		// Simulate the build handler's header stripping logic.
		header := "-- Generated by pgdesign -- do not edit\n\n"
		ddl := "CREATE TABLE t (id int);\nCREATE TABLE u (id int);"
		content := header + ddl

		stripped := strings.TrimPrefix(content, header)
		stmts, err := SplitStatements(stripped)
		if err != nil {
			t.Fatalf("SplitStatements: %v", err)
		}
		if len(stmts) != 2 {
			t.Fatalf("expected 2 statements, got %d: %v", len(stmts), stmts)
		}

		payload := splitJSONPayload{Version: 1, Statements: stmts}
		data, err := json.MarshalIndent(payload, "", "  ")
		if err != nil {
			t.Fatalf("json.MarshalIndent: %v", err)
		}

		var parsed splitJSONPayload
		if err := json.Unmarshal(data, &parsed); err != nil {
			t.Fatalf("round-trip unmarshal: %v", err)
		}
		if parsed.Version != 1 {
			t.Errorf("expected version 1, got %d", parsed.Version)
		}
		if len(parsed.Statements) != 2 {
			t.Fatalf("expected 2 statements, got %d", len(parsed.Statements))
		}
	})

	t.Run("dollar-quoted function body stays single statement", func(t *testing.T) {
		ddl := `CREATE TABLE t (id int);
CREATE FUNCTION test() RETURNS void AS $$
BEGIN
  INSERT INTO t VALUES (1);
END;
$$ LANGUAGE plpgsql;
CREATE TABLE u (id int);`
		stmts, err := SplitStatements(ddl)
		if err != nil {
			t.Fatalf("SplitStatements: %v", err)
		}
		if len(stmts) != 3 {
			t.Fatalf("expected 3 statements, got %d: %v", len(stmts), stmts)
		}

		payload := splitJSONPayload{Version: 1, Statements: stmts}
		data, err := json.MarshalIndent(payload, "", "  ")
		if err != nil {
			t.Fatalf("json.MarshalIndent: %v", err)
		}

		var parsed splitJSONPayload
		if err := json.Unmarshal(data, &parsed); err != nil {
			t.Fatalf("round-trip unmarshal: %v", err)
		}
		if parsed.Version != 1 {
			t.Errorf("expected version 1, got %d", parsed.Version)
		}
		if len(parsed.Statements) != 3 {
			t.Fatalf("expected 3 statements, got %d", len(parsed.Statements))
		}
		if !strings.HasPrefix(parsed.Statements[1], "CREATE FUNCTION") {
			t.Errorf("stmt[1] should be the function, got %q", parsed.Statements[1])
		}
	})

	t.Run("empty DDL produces empty statements", func(t *testing.T) {
		stmts, err := SplitStatements("")
		if err != nil {
			t.Fatalf("SplitStatements: %v", err)
		}
		if stmts != nil {
			t.Fatalf("expected nil, got %v", stmts)
		}

		payload := splitJSONPayload{Version: 1, Statements: stmts}
		data, err := json.MarshalIndent(payload, "", "  ")
		if err != nil {
			t.Fatalf("json.MarshalIndent: %v", err)
		}

		var parsed splitJSONPayload
		if err := json.Unmarshal(data, &parsed); err != nil {
			t.Fatalf("round-trip unmarshal: %v", err)
		}
		if parsed.Version != 1 {
			t.Errorf("expected version 1, got %d", parsed.Version)
		}
		if parsed.Statements != nil {
			t.Errorf("expected nil statements for empty DDL, got %v", parsed.Statements)
		}
	})
}
