package codegen

import (
	"strings"
	"testing"

	"github.com/smm-h/pgdesign/internal/model"
)

func testSchema() *model.Schema {
	return &model.Schema{
		Name: "game",
		Tables: []model.Table{
			{
				Name:   "session",
				Schema: "game",
				Columns: []model.Column{
					{Name: "id", PGType: "uuid"},
					{Name: "game_id", PGType: "uuid"},
					{Name: "status", PGType: "text"},
					{Name: "room_code", PGType: "text"},
				},
			},
			{
				Name:   "player",
				Schema: "game",
				Columns: []model.Column{
					{Name: "id", PGType: "uuid"},
					{Name: "display_name", PGType: "text"},
					{Name: "created_at", PGType: "timestamptz"},
				},
			},
			{
				Name:   "chat_message",
				Schema: "game",
				Columns: []model.Column{
					{Name: "id", PGType: "uuid"},
					{Name: "sender_id", PGType: "uuid"},
					{Name: "body", PGType: "text"},
				},
			},
		},
	}
}

func TestPythonConstantsGenerator(t *testing.T) {
	schema := testSchema()
	gen := &PythonConstantsGenerator{}
	out, diags := gen.Generate(schema)
	if len(diags) > 0 {
		t.Fatalf("unexpected diagnostics: %v", diags)
	}

	result := string(out)

	// Header.
	if !strings.Contains(result, "# Generated by pgdesign -- do not edit manually.") {
		t.Error("missing header comment")
	}
	if !strings.Contains(result, "# Schema: game") {
		t.Error("missing schema name in header")
	}

	// Session table.
	if !strings.Contains(result, `TABLE_SESSION = "game.session"`) {
		t.Error("missing TABLE_SESSION constant")
	}
	if !strings.Contains(result, `SESSION_COLUMNS = ["id", "game_id", "status", "room_code"]`) {
		t.Error("missing SESSION_COLUMNS constant")
	}

	// Player table.
	if !strings.Contains(result, `TABLE_PLAYER = "game.player"`) {
		t.Error("missing TABLE_PLAYER constant")
	}
	if !strings.Contains(result, `PLAYER_COLUMNS = ["id", "display_name", "created_at"]`) {
		t.Error("missing PLAYER_COLUMNS constant")
	}

	// Chat message table.
	if !strings.Contains(result, `TABLE_CHAT_MESSAGE = "game.chat_message"`) {
		t.Error("missing TABLE_CHAT_MESSAGE constant")
	}
	if !strings.Contains(result, `CHAT_MESSAGE_COLUMNS = ["id", "sender_id", "body"]`) {
		t.Error("missing CHAT_MESSAGE_COLUMNS constant")
	}

	// Per-column constants for session.
	if !strings.Contains(result, `SESSION_COL_ID = "id"`) {
		t.Error("missing SESSION_COL_ID constant")
	}
	if !strings.Contains(result, `SESSION_COL_GAME_ID = "game_id"`) {
		t.Error("missing SESSION_COL_GAME_ID constant")
	}
	if !strings.Contains(result, `SESSION_COL_STATUS = "status"`) {
		t.Error("missing SESSION_COL_STATUS constant")
	}
	if !strings.Contains(result, `SESSION_COL_ROOM_CODE = "room_code"`) {
		t.Error("missing SESSION_COL_ROOM_CODE constant")
	}

	// Per-column constants for player.
	if !strings.Contains(result, `PLAYER_COL_ID = "id"`) {
		t.Error("missing PLAYER_COL_ID constant")
	}
	if !strings.Contains(result, `PLAYER_COL_DISPLAY_NAME = "display_name"`) {
		t.Error("missing PLAYER_COL_DISPLAY_NAME constant")
	}
	if !strings.Contains(result, `PLAYER_COL_CREATED_AT = "created_at"`) {
		t.Error("missing PLAYER_COL_CREATED_AT constant")
	}

	// Per-column constants for chat_message.
	if !strings.Contains(result, `CHAT_MESSAGE_COL_SENDER_ID = "sender_id"`) {
		t.Error("missing CHAT_MESSAGE_COL_SENDER_ID constant")
	}
	if !strings.Contains(result, `CHAT_MESSAGE_COL_BODY = "body"`) {
		t.Error("missing CHAT_MESSAGE_COL_BODY constant")
	}

	// All tables covered.
	tableCount := strings.Count(result, "TABLE_")
	if tableCount != 3 {
		t.Errorf("expected 3 TABLE_ constants, got %d", tableCount)
	}
}

func TestZigConstantsGenerator(t *testing.T) {
	schema := testSchema()
	gen := &ZigConstantsGenerator{}
	out, diags := gen.Generate(schema)
	if len(diags) > 0 {
		t.Fatalf("unexpected diagnostics: %v", diags)
	}

	result := string(out)

	// Header.
	if !strings.Contains(result, "// Generated by pgdesign -- do not edit manually.") {
		t.Error("missing header comment")
	}
	if !strings.Contains(result, "// Schema: game") {
		t.Error("missing schema name in header")
	}

	// Session table.
	if !strings.Contains(result, `pub const table_session = "game.session";`) {
		t.Error("missing table_session constant")
	}
	if !strings.Contains(result, `pub const session_columns = [_][]const u8{ "id", "game_id", "status", "room_code" };`) {
		t.Error("missing session_columns constant")
	}

	// Player table.
	if !strings.Contains(result, `pub const table_player = "game.player";`) {
		t.Error("missing table_player constant")
	}
	if !strings.Contains(result, `pub const player_columns = [_][]const u8{ "id", "display_name", "created_at" };`) {
		t.Error("missing player_columns constant")
	}

	// Chat message table.
	if !strings.Contains(result, `pub const table_chat_message = "game.chat_message";`) {
		t.Error("missing table_chat_message constant")
	}
	if !strings.Contains(result, `pub const chat_message_columns = [_][]const u8{ "id", "sender_id", "body" };`) {
		t.Error("missing chat_message_columns constant")
	}

	// Per-column constants for session.
	if !strings.Contains(result, `pub const session_col_id = "id";`) {
		t.Error("missing session_col_id constant")
	}
	if !strings.Contains(result, `pub const session_col_game_id = "game_id";`) {
		t.Error("missing session_col_game_id constant")
	}
	if !strings.Contains(result, `pub const session_col_status = "status";`) {
		t.Error("missing session_col_status constant")
	}
	if !strings.Contains(result, `pub const session_col_room_code = "room_code";`) {
		t.Error("missing session_col_room_code constant")
	}

	// Per-column constants for player.
	if !strings.Contains(result, `pub const player_col_id = "id";`) {
		t.Error("missing player_col_id constant")
	}
	if !strings.Contains(result, `pub const player_col_display_name = "display_name";`) {
		t.Error("missing player_col_display_name constant")
	}
	if !strings.Contains(result, `pub const player_col_created_at = "created_at";`) {
		t.Error("missing player_col_created_at constant")
	}

	// Per-column constants for chat_message.
	if !strings.Contains(result, `pub const chat_message_col_sender_id = "sender_id";`) {
		t.Error("missing chat_message_col_sender_id constant")
	}
	if !strings.Contains(result, `pub const chat_message_col_body = "body";`) {
		t.Error("missing chat_message_col_body constant")
	}

	// All tables covered.
	tableCount := strings.Count(result, "pub const table_")
	if tableCount != 3 {
		t.Errorf("expected 3 table_ constants, got %d", tableCount)
	}
}

func TestPythonConstantsGenerator_NoSchema(t *testing.T) {
	schema := &model.Schema{
		Tables: []model.Table{
			{
				Name: "items",
				Columns: []model.Column{
					{Name: "id", PGType: "uuid"},
				},
			},
		},
	}

	gen := &PythonConstantsGenerator{}
	out, diags := gen.Generate(schema)
	if len(diags) > 0 {
		t.Fatalf("unexpected diagnostics: %v", diags)
	}

	result := string(out)

	// No schema prefix on table name.
	if !strings.Contains(result, `TABLE_ITEMS = "items"`) {
		t.Error("missing TABLE_ITEMS constant without schema prefix")
	}
	// Per-column constant present.
	if !strings.Contains(result, `ITEMS_COL_ID = "id"`) {
		t.Error("missing ITEMS_COL_ID constant")
	}
	// No Schema: line in header.
	if strings.Contains(result, "# Schema:") {
		t.Error("should not have Schema header when schema name is empty")
	}
}

func TestZigConstantsGenerator_NoSchema(t *testing.T) {
	schema := &model.Schema{
		Tables: []model.Table{
			{
				Name: "items",
				Columns: []model.Column{
					{Name: "id", PGType: "uuid"},
				},
			},
		},
	}

	gen := &ZigConstantsGenerator{}
	out, diags := gen.Generate(schema)
	if len(diags) > 0 {
		t.Fatalf("unexpected diagnostics: %v", diags)
	}

	result := string(out)

	if !strings.Contains(result, `pub const table_items = "items";`) {
		t.Error("missing table_items constant without schema prefix")
	}
	// Per-column constant present.
	if !strings.Contains(result, `pub const items_col_id = "id";`) {
		t.Error("missing items_col_id constant")
	}
	if strings.Contains(result, "// Schema:") {
		t.Error("should not have Schema header when schema name is empty")
	}
}
