package codegen

import (
	"bytes"
	"fmt"
	"strings"

	"github.com/smm-h/pgdesign/internal/diagnostic"
	"github.com/smm-h/pgdesign/internal/model"
)

// ConstantsLang captures the formatting differences between target languages
// for the constants generator.
type ConstantsLang struct {
	CommentPrefix  string
	TableConstFmt  func(name, fqn string) string
	ColumnsConstFmt func(name, joined string) string
	ColConstFmt    func(tableName, colName, rawColName string) string
	CaseFn         func(string) string
	RegenCmd       string
}

// PythonConstantsGenerator generates Python constants for table and column names.
type PythonConstantsGenerator struct{}

// Generate produces a Python file with table name and column name constants
// for every table in the schema.
func (g *PythonConstantsGenerator) Generate(schema *model.Schema) ([]byte, []diagnostic.Diagnostic) {
	return generateConstants(schema, ConstantsLang{
		CommentPrefix: "# ",
		TableConstFmt: func(name, fqn string) string {
			return fmt.Sprintf("TABLE_%s = %q\n", name, fqn)
		},
		ColumnsConstFmt: func(name, joined string) string {
			return fmt.Sprintf("%s_COLUMNS = [%s]\n", name, joined)
		},
		ColConstFmt: func(tableName, colName, rawColName string) string {
			return fmt.Sprintf("%s_COL_%s = %q\n", tableName, colName, rawColName)
		},
		CaseFn:   strings.ToUpper,
		RegenCmd: "pgdesign codegen --lang python --mode constants <schema-files>",
	})
}

// ZigConstantsGenerator generates Zig constants for table and column names.
type ZigConstantsGenerator struct{}

// Generate produces a Zig file with table name and column name constants
// for every table in the schema.
func (g *ZigConstantsGenerator) Generate(schema *model.Schema) ([]byte, []diagnostic.Diagnostic) {
	return generateConstants(schema, ConstantsLang{
		CommentPrefix: "// ",
		TableConstFmt: func(name, fqn string) string {
			return fmt.Sprintf("pub const table_%s = %q;\n", name, fqn)
		},
		ColumnsConstFmt: func(name, joined string) string {
			return fmt.Sprintf("pub const %s_columns = [_][]const u8{ %s };\n", name, joined)
		},
		ColConstFmt: func(tableName, colName, rawColName string) string {
			return fmt.Sprintf("pub const %s_col_%s = %q;\n", tableName, colName, rawColName)
		},
		CaseFn:   strings.ToLower,
		RegenCmd: "pgdesign codegen --lang zig --mode constants <schema-files>",
	})
}

// generateConstants produces constants output for any language using the
// provided ConstantsLang formatting rules.
func generateConstants(schema *model.Schema, lang ConstantsLang) ([]byte, []diagnostic.Diagnostic) {
	var buf bytes.Buffer
	buf.WriteString(lang.CommentPrefix + "Generated by pgdesign -- do not edit manually.\n")
	buf.WriteString(lang.CommentPrefix + "Regenerate with: " + lang.RegenCmd + "\n")
	if schema.Name != "" {
		buf.WriteString(fmt.Sprintf("%sSchema: %s\n", lang.CommentPrefix, schema.Name))
	}

	for i, tbl := range schema.Tables {
		if i > 0 {
			buf.WriteString("\n")
		}

		fqn := tbl.Name
		if tbl.Schema != "" {
			fqn = tbl.Schema + "." + tbl.Name
		}

		name := lang.CaseFn(tbl.Name)

		buf.WriteString(fmt.Sprintf("\n%sTable: %s\n", lang.CommentPrefix, fqn))
		buf.WriteString(lang.TableConstFmt(name, fqn))

		cols := make([]string, len(tbl.Columns))
		for j, col := range tbl.Columns {
			cols[j] = fmt.Sprintf("%q", col.Name)
		}
		buf.WriteString(lang.ColumnsConstFmt(name, strings.Join(cols, ", ")))

		for _, col := range tbl.Columns {
			colName := lang.CaseFn(col.Name)
			buf.WriteString(lang.ColConstFmt(name, colName, col.Name))
		}
	}

	return buf.Bytes(), nil
}
