package codegen

import (
	"bytes"
	"fmt"
	"strings"

	"github.com/smm-h/pgdesign/internal/model"
)

// PythonConstantsGenerator generates Python constants for table and column names.
type PythonConstantsGenerator struct{}

// Generate produces a Python file with table name and column name constants
// for every table in the schema.
func (g *PythonConstantsGenerator) Generate(schema *model.Schema) ([]byte, error) {
	var buf bytes.Buffer

	buf.WriteString("# Generated by pgdesign -- do not edit manually.\n")
	buf.WriteString("# Regenerate with: pgdesign codegen --lang python --mode constants <schema-files>\n")
	if schema.Name != "" {
		buf.WriteString(fmt.Sprintf("# Schema: %s\n", schema.Name))
	}

	for i, tbl := range schema.Tables {
		if i > 0 {
			buf.WriteString("\n")
		}

		fqn := tbl.Name
		if tbl.Schema != "" {
			fqn = tbl.Schema + "." + tbl.Name
		}

		upper := toUpperSnake(tbl.Name)

		buf.WriteString(fmt.Sprintf("\n# Table: %s\n", fqn))
		buf.WriteString(fmt.Sprintf("TABLE_%s = %q\n", upper, fqn))

		cols := make([]string, len(tbl.Columns))
		for j, col := range tbl.Columns {
			cols[j] = fmt.Sprintf("%q", col.Name)
		}
		buf.WriteString(fmt.Sprintf("%s_COLUMNS = [%s]\n", upper, strings.Join(cols, ", ")))
	}

	return buf.Bytes(), nil
}

// toUpperSnake converts a lowercase_name to UPPER_SNAKE_CASE.
func toUpperSnake(name string) string {
	return strings.ToUpper(name)
}
