package codegen

import (
	"strings"
	"testing"

	"github.com/smm-h/pgdesign/internal/model"
)

func TestEnumsGenerator_Python(t *testing.T) {
	schema := &model.Schema{
		Enums: []model.Enum{
			{Name: "status", Schema: "public", Values: []string{"active", "inactive"}},
		},
	}
	gen := &EnumsGenerator{Lang: LangPython}
	out, diags := gen.Generate(schema)
	if len(diags) > 0 {
		t.Fatalf("unexpected diagnostics: %v", diags)
	}
	s := string(out)
	if !strings.Contains(s, "from enum import StrEnum") {
		t.Error("expected StrEnum import")
	}
	if !strings.Contains(s, "class Status(StrEnum):") {
		t.Error("expected StrEnum class definition")
	}
	if !strings.Contains(s, "ACTIVE") {
		t.Error("expected ACTIVE enum value")
	}
}

func TestEnumsGenerator_Go(t *testing.T) {
	schema := &model.Schema{
		Enums: []model.Enum{
			{Name: "status", Schema: "public", Values: []string{"active", "inactive"}},
		},
	}
	gen := &EnumsGenerator{Lang: LangGo}
	out, diags := gen.Generate(schema)
	if len(diags) > 0 {
		t.Fatalf("unexpected diagnostics: %v", diags)
	}
	s := string(out)
	if strings.Contains(s, "StrEnum") {
		t.Error("Go output should not contain StrEnum")
	}
	if !strings.Contains(s, "Status") {
		t.Error("expected Status type in Go output")
	}
}

func TestEnumsGenerator_EmptySchema(t *testing.T) {
	schema := &model.Schema{}
	gen := &EnumsGenerator{Lang: LangPython}
	out, diags := gen.Generate(schema)
	if len(diags) > 0 {
		t.Fatalf("unexpected diagnostics: %v", diags)
	}
	s := string(out)
	if !strings.Contains(s, "Generated by pgdesign") {
		t.Error("expected header comment")
	}
	if strings.Contains(s, "class") {
		t.Error("empty schema should produce no enum classes")
	}
}
