package codegen

import (
	"strings"
	"testing"

	"github.com/smm-h/pgdesign/internal/model"
	"github.com/smm-h/pgdesign/internal/typeinfo"
)

func TestGoConstraintsGenerator_Generate(t *testing.T) {
	schema := &model.Schema{
		Name: "app",
		Enums: []model.Enum{
			{Name: "role", Values: []string{"admin", "user", "guest"}},
		},
		Tables: []model.Table{
			{
				Name: "users",
				Columns: []model.Column{
					{Name: "id", PGType: typeinfo.MustParse("bigint"), NotNull: true},
					{Name: "name", PGType: typeinfo.MustParse("text"), NotNull: true},
					{Name: "email", PGType: typeinfo.MustParse("text"), NotNull: true},
					{Name: "role", PGType: typeinfo.MustParse("role"), NotNull: true, TypeKind: "enum"},
					{Name: "age", PGType: typeinfo.MustParse("integer"), NotNull: true},
					{Name: "slug", PGType: typeinfo.MustParse("varchar"), NotNull: true},
					{Name: "profile_data", PGType: typeinfo.MustParse("jsonb"), NotNull: true, JSONSchema: "schemas/profile.json"},
				},
				PK: []string{"id"},
				Checks: []model.CheckConstraint{
					{Name: "ck_users_age_range", Expr: "age >= 0 AND age <= 150"},
					{Name: "ck_users_email_fmt", Expr: "email LIKE '%@%'"},
					{Name: "ck_users_slug_len", Expr: "LENGTH(slug) <= 100"},
				},
			},
		},
	}

	gen := &GoConstraintsGenerator{}
	out, diags := gen.Generate(schema)
	if len(diags) > 0 {
		t.Fatalf("unexpected diagnostics: %v", diags)
	}

	result := string(out)

	// Header.
	if !strings.Contains(result, "Code generated by pgdesign") {
		t.Error("missing header comment")
	}
	// Validators share the branded types' package so row structs and branded
	// enums are referenced without a cross-package import (none is configurable).
	if !strings.Contains(result, "package schema") {
		t.Error("missing package declaration")
	}

	// ValidationError type.
	if !strings.Contains(result, "type ValidationError struct") {
		t.Error("missing ValidationError struct")
	}

	// Validate function.
	if !strings.Contains(result, "func ValidateUsers(row Users) []ValidationError") {
		t.Error("missing ValidateUsers function signature")
	}

	// NOT NULL checks for string-type columns.
	if !strings.Contains(result, `row.Name == ""`) {
		t.Error("missing NOT NULL check for Name")
	}
	if !strings.Contains(result, `row.Email == ""`) {
		t.Error("missing NOT NULL check for Email")
	}
	if !strings.Contains(result, `row.Slug == ""`) {
		t.Error("missing NOT NULL check for Slug")
	}

	// Enum check switches on the branded value's .String().
	if !strings.Contains(result, "switch row.Role.String()") {
		t.Error("missing branded enum switch for Role")
	}
	if !strings.Contains(result, `"admin"`) {
		t.Error("missing enum value 'admin'")
	}
	if !strings.Contains(result, `"user"`) {
		t.Error("missing enum value 'user'")
	}
	if !strings.Contains(result, `"guest"`) {
		t.Error("missing enum value 'guest'")
	}

	// Range check for age.
	if !strings.Contains(result, "row.Age") {
		t.Error("missing age range check")
	}
	if !strings.Contains(result, "150") {
		t.Error("missing age upper bound 150")
	}

	// LIKE check for email -> regexp.
	if !strings.Contains(result, "regexp.MustCompile") {
		t.Error("missing regexp.MustCompile for email LIKE check")
	}
	if !strings.Contains(result, `"regexp"`) {
		t.Error("missing regexp import")
	}

	// Length check for slug.
	if !strings.Contains(result, "len(row.Slug)") {
		t.Error("missing length check for Slug")
	}
	if !strings.Contains(result, "100") {
		t.Error("missing length limit 100")
	}
}

// TestGoConstraintsGenerator_NullableCheckNilGuard pins the nullable-column
// CHECK handling: a nullable column maps to a Go pointer field, so a CHECK on it
// must be nil-guarded and dereferenced (go_constraints.go:164-171). Without the
// guard the generated code would dereference a nil pointer at runtime; without
// the deref it would not type-check against the pointer field. The check is a
// LENGTH check so the emitted deref appears inside len(...).
func TestGoConstraintsGenerator_NullableCheckNilGuard(t *testing.T) {
	schema := &model.Schema{
		Tables: []model.Table{
			{
				Name: "notes",
				Columns: []model.Column{
					{Name: "id", PGType: typeinfo.MustParse("bigint"), NotNull: true},
					// Nullable text column with a CHECK -> pointer field + deref.
					{Name: "body", PGType: typeinfo.MustParse("text"), NotNull: false},
				},
				PK: []string{"id"},
				Checks: []model.CheckConstraint{
					{Name: "ck_notes_body_len", Expr: "LENGTH(body) <= 500"},
				},
			},
		},
	}

	gen := &GoConstraintsGenerator{}
	out, diags := gen.Generate(schema)
	if len(diags) > 0 {
		t.Fatalf("unexpected diagnostics: %v", diags)
	}
	result := string(out)

	// The nullable column's CHECK is wrapped in a nil guard.
	if !strings.Contains(result, "if row.Body != nil {") {
		t.Errorf("missing nil guard for nullable CHECK column, got:\n%s", result)
	}
	// The value is dereferenced when used.
	if !strings.Contains(result, "len((*row.Body))") {
		t.Errorf("missing deref of nullable CHECK column, got:\n%s", result)
	}
}

func TestGoConstraintsGenerator_EmptySchema(t *testing.T) {
	schema := &model.Schema{
		Name: "empty",
	}

	gen := &GoConstraintsGenerator{}
	out, diags := gen.Generate(schema)
	if len(diags) > 0 {
		t.Fatalf("unexpected diagnostics: %v", diags)
	}

	result := string(out)
	if !strings.Contains(result, "No tables with extractable constraints.") {
		t.Error("missing empty-schema comment")
	}
	if strings.Contains(result, "func Validate") {
		t.Error("should not contain any Validate functions for empty schema")
	}
}

func TestGoConstraintsGenerator_ILIKEPattern(t *testing.T) {
	schema := &model.Schema{
		Tables: []model.Table{
			{
				Name: "items",
				Columns: []model.Column{
					{Name: "id", PGType: typeinfo.MustParse("bigint"), NotNull: true},
					{Name: "code", PGType: typeinfo.MustParse("text"), NotNull: true},
				},
				PK: []string{"id"},
				Checks: []model.CheckConstraint{
					{Name: "ck_code_ilike", Expr: "code ILIKE 'abc%'"},
				},
			},
		},
	}

	gen := &GoConstraintsGenerator{}
	out, diags := gen.Generate(schema)
	if len(diags) > 0 {
		t.Fatalf("unexpected diagnostics: %v", diags)
	}

	result := string(out)

	// ILIKE should produce (?i) prefix in the regex pattern.
	if !strings.Contains(result, `(?i)`) {
		t.Error("ILIKE pattern should produce (?i) prefix in Go regex")
	}
	if !strings.Contains(result, "regexp.MustCompile") {
		t.Error("missing regexp.MustCompile for ILIKE check")
	}
}

func TestGoConstraintsGenerator_NoConstraints(t *testing.T) {
	schema := &model.Schema{
		Tables: []model.Table{
			{
				Name: "simple",
				Columns: []model.Column{
					{Name: "id", PGType: typeinfo.MustParse("bigint"), NotNull: true},
				},
				PK: []string{"id"},
			},
		},
	}

	gen := &GoConstraintsGenerator{}
	out, diags := gen.Generate(schema)
	if len(diags) > 0 {
		t.Fatalf("unexpected diagnostics: %v", diags)
	}

	result := string(out)
	if !strings.Contains(result, "No tables with extractable constraints.") {
		t.Error("missing no-constraints comment")
	}
}
