package codegen

import (
	"bytes"
	"fmt"
	"strings"

	"github.com/smm-h/pgdesign/internal/diagnostic"
	"github.com/smm-h/pgdesign/internal/model"
)

// GoConstraintsGenerator generates Go validation functions for table constraints.
type GoConstraintsGenerator struct{}

// Generate produces a Go file with Validate<TableName> functions for each table
// that has extractable constraints (NOT NULL, enum, CHECK, JSON schema).
func (g *GoConstraintsGenerator) Generate(schema *model.Schema) ([]byte, []diagnostic.Diagnostic) {
	var buf bytes.Buffer
	buf.WriteString("// Code generated by pgdesign -- do not edit.\n")
	buf.WriteString("// Regenerate with: pgdesign codegen --lang go --mode constraints <schema-files>\n")
	if schema.Name != "" {
		fmt.Fprintf(&buf, "// Schema: %s\n", schema.Name)
	}
	buf.WriteString("\npackage constraints\n")

	needsRegexp := false

	// Collect tables with constraints.
	type tableWork struct {
		table model.Table
		cs    ConstraintSet
	}
	var work []tableWork
	for _, tbl := range schema.Tables {
		cs := ExtractConstraints(tbl, *schema)
		if !cs.HasConstraints() {
			continue
		}
		work = append(work, tableWork{table: tbl, cs: cs})
		for _, expr := range cs.CheckExprs {
			if pat := classifyCheck(expr); pat != nil {
				if _, ok := pat.(*likePattern); ok {
					needsRegexp = true
				}
			}
		}
	}

	if len(work) == 0 {
		buf.WriteString("\n// No tables with extractable constraints.\n")
		return buf.Bytes(), nil
	}

	// Write imports.
	var imports []string
	imports = append(imports, "fmt")
	if needsRegexp {
		imports = append(imports, "regexp")
	}
	buf.WriteString("\nimport (\n")
	for _, imp := range imports {
		fmt.Fprintf(&buf, "\t%q\n", imp)
	}
	buf.WriteString(")\n")

	// Write ValidationError type.
	buf.WriteString(`
// ValidationError describes a single constraint violation.
type ValidationError struct {
	Field   string
	Message string
}

// Error implements the error interface.
func (e ValidationError) Error() string {
	return fmt.Sprintf("%s: %s", e.Field, e.Message)
}
`)

	// Generate per-table validators.
	for _, tw := range work {
		writeGoValidator(&buf, tw.table, tw.cs)
	}

	return buf.Bytes(), nil
}

func writeGoValidator(buf *bytes.Buffer, table model.Table, cs ConstraintSet) {
	funcName := "Validate" + toPascalCase(table.Name)
	typeName := toPascalCase(table.Name)

	fmt.Fprintf(buf, "\n// %s validates constraint rules for the %s table.\n", funcName, table.Name)
	fmt.Fprintf(buf, "func %s(row %s) []ValidationError {\n", funcName, typeName)
	buf.WriteString("\tvar errs []ValidationError\n")

	// NOT NULL checks (only meaningful for string types in Go).
	for _, col := range cs.NotNullFields {
		goField := toPascalCase(col)
		pgType := columnPGType(table, col)
		if isStringPGType(pgType) {
			fmt.Fprintf(buf, "\tif row.%s == \"\" {\n", goField)
			fmt.Fprintf(buf, "\t\terrs = append(errs, ValidationError{Field: %q, Message: \"must not be empty\"})\n", col)
			buf.WriteString("\t}\n")
		}
	}

	// Enum checks.
	for col, values := range cs.EnumFields {
		goField := toPascalCase(col)
		fmt.Fprintf(buf, "\tswitch row.%s {\n", goField)
		fmt.Fprintf(buf, "\tcase ")
		for i, v := range values {
			if i > 0 {
				buf.WriteString(", ")
			}
			fmt.Fprintf(buf, "%q", v)
		}
		buf.WriteString(":\n")
		buf.WriteString("\t\t// valid\n")
		buf.WriteString("\tdefault:\n")
		fmt.Fprintf(buf, "\t\terrs = append(errs, ValidationError{Field: %q, Message: fmt.Sprintf(\"invalid value %%q\", row.%s)})\n", col, goField)
		buf.WriteString("\t}\n")
	}

	// CHECK constraint checks.
	for col, expr := range cs.CheckExprs {
		goField := toPascalCase(col)
		pat := classifyCheck(expr)
		if pat == nil {
			fmt.Fprintf(buf, "\t// CHECK on %s: %s (unrecognized pattern, skipped)\n", col, expr)
			continue
		}
		writeGoCheckPattern(buf, col, goField, pat)
	}

	buf.WriteString("\treturn errs\n")
	buf.WriteString("}\n")
}

func writeGoCheckPattern(buf *bytes.Buffer, col, goField string, pat checkPattern) {
	switch p := pat.(type) {
	case *rangePattern:
		// The CHECK passes when value >= low (if LowIncl) or value > low (if !LowIncl).
		// The validation fails on the inverse condition.
		var lowOp, highOp string
		if p.LowIncl {
			lowOp = "<" // fails when value < low
		} else {
			lowOp = "<=" // fails when value <= low
		}
		if p.HighIncl {
			highOp = ">" // fails when value > high
		} else {
			highOp = ">=" // fails when value >= high
		}
		fmt.Fprintf(buf, "\tif row.%s %s %s || row.%s %s %s {\n", goField, lowOp, p.Low, goField, highOp, p.High)
		fmt.Fprintf(buf, "\t\terrs = append(errs, ValidationError{Field: %q, Message: \"value out of range\"})\n", col)
		buf.WriteString("\t}\n")

	case *comparisonPattern:
		failOp := invertComparisonOp(p.Op)
		fmt.Fprintf(buf, "\tif row.%s %s %s {\n", goField, failOp, p.Value)
		fmt.Fprintf(buf, "\t\terrs = append(errs, ValidationError{Field: %q, Message: \"failed check: %s\"})\n", col, escapeGoString(p.Op+" "+p.Value))
		buf.WriteString("\t}\n")

	case *lengthPattern:
		failOp := invertComparisonOp(p.Op)
		fmt.Fprintf(buf, "\tif len(row.%s) %s %d {\n", goField, failOp, p.Value)
		fmt.Fprintf(buf, "\t\terrs = append(errs, ValidationError{Field: %q, Message: fmt.Sprintf(\"length must be %s %d, got %%d\", len(row.%s))})\n", col, p.Op, p.Value, goField)
		buf.WriteString("\t}\n")

	case *likePattern:
		regex := likeToRegex(p.Pattern)
		varName := col + "Re"
		fmt.Fprintf(buf, "\t%s := regexp.MustCompile(%q)\n", varName, regex)
		if strings.HasPrefix(strings.ToUpper(p.Op), "NOT") {
			fmt.Fprintf(buf, "\tif %s.MatchString(row.%s) {\n", varName, goField)
		} else {
			fmt.Fprintf(buf, "\tif !%s.MatchString(row.%s) {\n", varName, goField)
		}
		fmt.Fprintf(buf, "\t\terrs = append(errs, ValidationError{Field: %q, Message: \"does not match required pattern\"})\n", col)
		buf.WriteString("\t}\n")
	}
}

// columnPGType returns the PostgreSQL type for a column in the table.
func columnPGType(table model.Table, colName string) string {
	for _, c := range table.Columns {
		if c.Name == colName {
			return c.PGType.Base
		}
	}
	return ""
}

// isStringPGType returns true if the PostgreSQL type maps to a Go string.
func isStringPGType(pgType string) bool {
	switch pgType {
	case "text", "varchar", "character varying", "char", "character", "name", "citext":
		return true
	}
	return false
}
