package codegen

import (
	"bytes"
	"fmt"
	"sort"
	"strings"

	"github.com/smm-h/pgdesign/internal/diagnostic"
	"github.com/smm-h/pgdesign/internal/model"
)

// GoGormGenerator generates Go structs with GORM struct tags corresponding to
// database tables, including BelongsTo and HasMany relationship fields.
type GoGormGenerator struct{}

// Generate produces a Go source file with one GORM-tagged struct per table in
// the schema, plus relationship fields derived from foreign key metadata.
func (g *GoGormGenerator) Generate(schema *model.Schema) ([]byte, []diagnostic.Diagnostic) {
	var buf bytes.Buffer
	header := "// Code generated by pgdesign -- do not edit.\n\npackage schema\n"

	if len(schema.Tables) == 0 {
		buf.WriteString(header)
		return buf.Bytes(), nil
	}

	// Build reverse-FK index: for each table, which other tables have single-column
	// FKs pointing to it.
	type reverseFK struct {
		FromTable string // the table that has the FK
		FKColumn  string // the FK column name in FromTable
	}
	reverseFKs := make(map[string][]reverseFK) // key: referenced table name
	for _, tbl := range schema.Tables {
		for _, fk := range tbl.FKs {
			if len(fk.Columns) == 1 {
				reverseFKs[fk.RefTable] = append(reverseFKs[fk.RefTable], reverseFK{
					FromTable: tbl.Name,
					FKColumn:  fk.Columns[0],
				})
			}
		}
	}

	// Build PK set, unique single-column index map, and non-unique single-column
	// index map per table for GORM tag generation.
	type fieldInfo struct {
		Name   string
		GoType string
		Tag    string
		IsRel  bool // relationship field (no tag alignment with column fields)
	}
	type structInfo struct {
		Name      string
		TableName string
		Fields    []fieldInfo
	}

	var structs []structInfo
	imports := make(map[string]bool)

	for _, tbl := range schema.Tables {
		si := structInfo{
			Name:      toPascalCase(tbl.Name),
			TableName: tbl.Name,
		}

		// Build PK set for this table.
		pkSet := make(map[string]bool, len(tbl.PK))
		for _, pk := range tbl.PK {
			pkSet[pk] = true
		}

		// Build unique single-column index map: column name -> index name.
		uniqueIndexCol := make(map[string]string)
		for _, idx := range tbl.Indexes {
			if idx.Unique && len(idx.Columns) == 1 {
				uniqueIndexCol[idx.Columns[0]] = idx.Name
			}
		}
		for _, uc := range tbl.Uniques {
			if len(uc.Columns) == 1 {
				uniqueIndexCol[uc.Columns[0]] = uc.Name
			}
		}

		// Build non-unique single-column index map: column name -> index name.
		nonUniqueIndexCol := make(map[string]string)
		for _, idx := range tbl.Indexes {
			if !idx.Unique && len(idx.Columns) == 1 {
				nonUniqueIndexCol[idx.Columns[0]] = idx.Name
			}
		}

		// Generate column fields.
		for _, col := range tbl.Columns {
			var goType string
			var importPath string
			isBytea := strings.ToLower(col.PGType) == "bytea"

			if col.SemanticTypeName == "money" {
				goType = LookupMoneyType(LangGo)
			} else {
				m := LookupType(col.PGType, LangGo)
				goType = m.Type
				importPath = m.Import
			}
			goType = applyModifiers(goType, col, isBytea)

			if importPath != "" {
				imports[importPath] = true
			}

			// Build GORM tag.
			var tagParts []string
			tagParts = append(tagParts, "column:"+col.Name)

			if pkSet[col.Name] {
				tagParts = append(tagParts, "primaryKey")
			}
			if col.NotNull {
				tagParts = append(tagParts, "not null")
			}

			pgTypeStr := col.PGType
			if col.Array {
				pgTypeStr += "[]"
			}
			tagParts = append(tagParts, "type:"+pgTypeStr)

			if col.Default != nil {
				tagParts = append(tagParts, "default:"+*col.Default)
			}

			if idxName, ok := uniqueIndexCol[col.Name]; ok {
				tagParts = append(tagParts, "uniqueIndex:"+idxName)
			}
			if idxName, ok := nonUniqueIndexCol[col.Name]; ok {
				tagParts = append(tagParts, "index:"+idxName)
			}

			tag := strings.Join(tagParts, ";")

			si.Fields = append(si.Fields, fieldInfo{
				Name:   toPascalCase(col.Name),
				GoType: goType,
				Tag:    fmt.Sprintf("`gorm:%q`", tag),
			})
		}

		// BelongsTo relationships: this table's single-column FKs.
		for _, fk := range tbl.FKs {
			if len(fk.Columns) == 1 {
				refType := toPascalCase(fk.RefTable)
				si.Fields = append(si.Fields, fieldInfo{
					Name:   refType,
					GoType: refType,
					Tag:    fmt.Sprintf("`gorm:\"foreignKey:%s\"`", toPascalCase(fk.Columns[0])),
					IsRel:  true,
				})
			}
		}

		// HasMany relationships: other tables' single-column FKs pointing here.
		if refs, ok := reverseFKs[tbl.Name]; ok {
			for _, ref := range refs {
				refType := toPascalCase(ref.FromTable)
				si.Fields = append(si.Fields, fieldInfo{
					Name:   refType + "s",
					GoType: "[]" + refType,
					Tag:    fmt.Sprintf("`gorm:\"foreignKey:%s\"`", toPascalCase(ref.FKColumn)),
					IsRel:  true,
				})
			}
		}

		structs = append(structs, si)
	}

	// Write header and package.
	buf.WriteString(header)

	// Write imports if any are needed.
	if len(imports) > 0 {
		var stdlibs []string
		var thirdParty []string
		for imp := range imports {
			if isStdlib(imp) {
				stdlibs = append(stdlibs, imp)
			} else {
				thirdParty = append(thirdParty, imp)
			}
		}
		sort.Strings(stdlibs)
		sort.Strings(thirdParty)

		buf.WriteString("\nimport (\n")
		for _, imp := range stdlibs {
			fmt.Fprintf(&buf, "\t%q\n", imp)
		}
		if len(stdlibs) > 0 && len(thirdParty) > 0 {
			buf.WriteString("\n")
		}
		for _, imp := range thirdParty {
			fmt.Fprintf(&buf, "\t%q\n", imp)
		}
		buf.WriteString(")\n")
	}

	// Write enums.
	enumBlock := GenerateEnums(schema.Enums, LangGo)
	if enumBlock != "" {
		buf.WriteString("\n")
		buf.WriteString(enumBlock)
	}

	// Write structs.
	for _, si := range structs {
		buf.WriteString("\n")
		if si.TableName != "" {
			fmt.Fprintf(&buf, "// %s represents the %s table.\n", si.Name, si.TableName)
		}
		fmt.Fprintf(&buf, "type %s struct {\n", si.Name)

		// Calculate max field name and type lengths for alignment.
		maxNameLen := 0
		maxTypeLen := 0
		for _, f := range si.Fields {
			if len(f.Name) > maxNameLen {
				maxNameLen = len(f.Name)
			}
			if len(f.GoType) > maxTypeLen {
				maxTypeLen = len(f.GoType)
			}
		}

		for _, f := range si.Fields {
			fmt.Fprintf(&buf, "\t%-*s %-*s %s\n", maxNameLen, f.Name, maxTypeLen, f.GoType, f.Tag)
		}
		buf.WriteString("}\n")
	}

	return buf.Bytes(), nil
}
