package codegen

import (
	"strings"
	"testing"

	"github.com/smm-h/pgdesign/internal/model"
	"github.com/smm-h/pgdesign/internal/typeinfo"
)

// containsGormField checks that a line exists containing the field name, Go type,
// and a gorm tag containing the specified substring.
func containsGormField(s, fieldName, goType, gormTagSubstr string) bool {
	for _, line := range strings.Split(s, "\n") {
		line = strings.TrimSpace(line)
		if strings.Contains(line, fieldName) &&
			strings.Contains(line, goType) &&
			strings.Contains(line, "gorm:") &&
			strings.Contains(line, gormTagSubstr) {
			return true
		}
	}
	return false
}

func TestGoGormGenerator_Basic(t *testing.T) {
	schema := &model.Schema{
		Tables: []model.Table{{
			Name:    "users",
			Comment: "Application users",
			PK:      []string{"id"},
			Columns: []model.Column{
				{Name: "id", PGType: typeinfo.MustParse("uuid"), NotNull: true},
				{Name: "email", PGType: typeinfo.MustParse("text"), NotNull: true},
				{Name: "score", PGType: typeinfo.MustParse("bigint"), NotNull: true},
				{Name: "is_active", PGType: typeinfo.MustParse("boolean"), NotNull: true},
				{Name: "created_at", PGType: typeinfo.MustParse("timestamptz"), NotNull: true},
			},
			Indexes: []model.Index{
				{Name: "idx_users_email", Columns: []string{"email"}, Unique: true},
			},
		}},
	}

	gen := &GoGormGenerator{}
	out, diags := gen.Generate(schema)
	if len(diags) > 0 {
		t.Fatalf("unexpected diagnostics: %v", diags)
	}

	result := string(out)

	// Header.
	if !strings.Contains(result, "// Code generated by pgdesign -- do not edit.") {
		t.Error("missing generated header comment")
	}

	// Package declaration.
	if !strings.Contains(result, "package schema") {
		t.Error("missing package declaration")
	}

	// Struct declaration.
	if !strings.Contains(result, "type Users struct {") {
		t.Error("missing struct declaration")
	}

	// Id field: primaryKey, not null, type:uuid.
	if !containsGormField(result, "Id", "uuid.UUID", "column:id") {
		t.Error("missing Id column:id tag")
	}
	if !containsGormField(result, "Id", "uuid.UUID", "primaryKey") {
		t.Error("missing Id primaryKey tag")
	}
	if !containsGormField(result, "Id", "uuid.UUID", "not null") {
		t.Error("missing Id not null tag")
	}
	if !containsGormField(result, "Id", "uuid.UUID", "type:uuid") {
		t.Error("missing Id type:uuid tag")
	}

	// Email field: uniqueIndex.
	if !containsGormField(result, "Email", "string", "column:email") {
		t.Error("missing Email column:email tag")
	}
	if !containsGormField(result, "Email", "string", "not null") {
		t.Error("missing Email not null tag")
	}
	if !containsGormField(result, "Email", "string", "type:text") {
		t.Error("missing Email type:text tag")
	}
	if !containsGormField(result, "Email", "string", "uniqueIndex:idx_users_email") {
		t.Error("missing Email uniqueIndex tag")
	}

	// Score field.
	if !containsGormField(result, "Score", "int64", "column:score") {
		t.Error("missing Score column:score tag")
	}
	if !containsGormField(result, "Score", "int64", "type:int8") {
		t.Error("missing Score type:int8 tag")
	}

	// IsActive field.
	if !containsGormField(result, "IsActive", "bool", "column:is_active") {
		t.Error("missing IsActive column:is_active tag")
	}
	if !containsGormField(result, "IsActive", "bool", "type:bool") {
		t.Error("missing IsActive type:bool tag")
	}

	// CreatedAt field.
	if !containsGormField(result, "CreatedAt", "time.Time", "column:created_at") {
		t.Error("missing CreatedAt column:created_at tag")
	}
	if !containsGormField(result, "CreatedAt", "time.Time", "type:timestamptz") {
		t.Error("missing CreatedAt type:timestamptz tag")
	}
}

func TestGoGormGenerator_Defaults(t *testing.T) {
	schema := &model.Schema{
		Tables: []model.Table{{
			Name:    "configs",
			Comment: "Configs",
			PK:      []string{"id"},
			Columns: []model.Column{
				{Name: "id", PGType: typeinfo.MustParse("integer"), NotNull: true},
				{Name: "enabled", PGType: typeinfo.MustParse("boolean"), NotNull: true, Default: model.StrPtr("true")},
				{Name: "retries", PGType: typeinfo.MustParse("integer"), NotNull: true, Default: model.StrPtr("3")},
			},
		}},
	}

	gen := &GoGormGenerator{}
	out, diags := gen.Generate(schema)
	if len(diags) > 0 {
		t.Fatalf("unexpected diagnostics: %v", diags)
	}

	result := string(out)

	if !containsGormField(result, "Enabled", "bool", "default:true") {
		t.Error("missing Enabled default:true tag")
	}
	if !containsGormField(result, "Retries", "int32", "default:3") {
		t.Error("missing Retries default:3 tag")
	}
}

func TestGoGormGenerator_Relationships(t *testing.T) {
	schema := &model.Schema{
		Tables: []model.Table{
			{
				Name:    "users",
				Comment: "Users",
				PK:      []string{"id"},
				Columns: []model.Column{
					{Name: "id", PGType: typeinfo.MustParse("uuid"), NotNull: true},
					{Name: "name", PGType: typeinfo.MustParse("text"), NotNull: true},
				},
			},
			{
				Name:    "orders",
				Comment: "Orders",
				PK:      []string{"id"},
				Columns: []model.Column{
					{Name: "id", PGType: typeinfo.MustParse("uuid"), NotNull: true},
					{Name: "user_id", PGType: typeinfo.MustParse("uuid"), NotNull: true},
					{Name: "total", PGType: typeinfo.MustParse("numeric"), NotNull: true},
				},
				FKs: []model.FK{
					{Name: "fk_orders_user", Columns: []string{"user_id"}, RefTable: "users", RefColumns: []string{"id"}},
				},
			},
		},
	}

	gen := &GoGormGenerator{}
	out, diags := gen.Generate(schema)
	if len(diags) > 0 {
		t.Fatalf("unexpected diagnostics: %v", diags)
	}

	result := string(out)

	// Orders struct should have BelongsTo: Users Users with foreignKey:UserId.
	if !containsGormField(result, "Users", "Users", "foreignKey:UserId") {
		t.Error("missing BelongsTo Users field on Orders struct")
	}

	// Users struct should have HasMany: Orderss []Orders with foreignKey:UserId.
	if !containsGormField(result, "Orderss", "[]Orders", "foreignKey:UserId") {
		t.Error("missing HasMany Orderss field on Users struct")
	}
}

func TestGoGormGenerator_NullableAndArray(t *testing.T) {
	schema := &model.Schema{
		Tables: []model.Table{{
			Name:    "items",
			Comment: "Items",
			PK:      []string{"id"},
			Columns: []model.Column{
				{Name: "id", PGType: typeinfo.MustParse("integer"), NotNull: true},
				{Name: "name", PGType: typeinfo.MustParse("text"), NotNull: false},
				{Name: "tags", PGType: typeinfo.MustParse("text"), NotNull: true, Array: true},
				{Name: "scores", PGType: typeinfo.MustParse("integer"), NotNull: false, Array: true},
			},
		}},
	}

	gen := &GoGormGenerator{}
	out, diags := gen.Generate(schema)
	if len(diags) > 0 {
		t.Fatalf("unexpected diagnostics: %v", diags)
	}

	result := string(out)

	// Nullable text -> *string, tag should NOT contain "not null".
	if !containsGormField(result, "Name", "*string", "column:name") {
		t.Error("missing Name *string field")
	}
	// Verify no "not null" in the Name line.
	for _, line := range strings.Split(result, "\n") {
		line = strings.TrimSpace(line)
		if strings.Contains(line, "Name") && strings.Contains(line, "*string") &&
			strings.Contains(line, "not null") {
			t.Error("Name field should not have 'not null' tag")
		}
	}

	// Array text -> []string, tag should contain type:text[].
	if !containsGormField(result, "Tags", "[]string", "type:text[]") {
		t.Error("missing Tags []string with type:text[] tag")
	}

	// Nullable array integer -> *[]int32, tag should contain type:int4[].
	if !containsGormField(result, "Scores", "*[]int32", "type:int4[]") {
		t.Error("missing Scores *[]int32 with type:int4[] tag")
	}
}

func TestGoGormGenerator_EmptySchema(t *testing.T) {
	schema := &model.Schema{Tables: []model.Table{}}

	gen := &GoGormGenerator{}
	out, diags := gen.Generate(schema)
	if len(diags) > 0 {
		t.Fatalf("unexpected diagnostics: %v", diags)
	}

	result := string(out)

	if !strings.Contains(result, "// Code generated by pgdesign -- do not edit.") {
		t.Error("missing generated header comment")
	}
	if !strings.Contains(result, "package schema") {
		t.Error("missing package declaration")
	}
	if strings.Contains(result, "type ") {
		t.Error("empty schema should not have type declarations")
	}
}

func TestGoGormGenerator_Enums(t *testing.T) {
	schema := &model.Schema{
		Enums: []model.Enum{{Name: "status", Values: []string{"active", "inactive"}}},
		Tables: []model.Table{{
			Name:    "users",
			Comment: "Users",
			PK:      []string{"id"},
			Columns: []model.Column{
				{Name: "id", PGType: typeinfo.MustParse("integer"), NotNull: true},
				{Name: "status", PGType: typeinfo.MustParse("status"), NotNull: true},
			},
		}},
	}

	gen := &GoGormGenerator{}
	out, diags := gen.Generate(schema)
	if len(diags) > 0 {
		t.Fatalf("unexpected diagnostics: %v", diags)
	}

	result := string(out)

	// Enum const should be present.
	if !strings.Contains(result, "StatusActive") {
		t.Error("missing StatusActive enum const")
	}
	if !strings.Contains(result, "StatusInactive") {
		t.Error("missing StatusInactive enum const")
	}

	// Status column maps to string (fallback for unrecognized PG type).
	if !containsGormField(result, "Status", "string", "column:status") {
		t.Error("missing Status string field")
	}
}

func TestGoGormGenerator_NonUniqueIndex(t *testing.T) {
	schema := &model.Schema{
		Tables: []model.Table{{
			Name:    "events",
			Comment: "Events",
			PK:      []string{"id"},
			Columns: []model.Column{
				{Name: "id", PGType: typeinfo.MustParse("integer"), NotNull: true},
				{Name: "created_at", PGType: typeinfo.MustParse("timestamptz"), NotNull: true},
			},
			Indexes: []model.Index{
				{Name: "idx_events_created_at", Columns: []string{"created_at"}, Unique: false},
			},
		}},
	}

	gen := &GoGormGenerator{}
	out, diags := gen.Generate(schema)
	if len(diags) > 0 {
		t.Fatalf("unexpected diagnostics: %v", diags)
	}

	result := string(out)

	// Should have non-unique index tag.
	if !containsGormField(result, "CreatedAt", "time.Time", "index:idx_events_created_at") {
		t.Error("missing CreatedAt index tag")
	}

	// Should NOT have uniqueIndex.
	for _, line := range strings.Split(result, "\n") {
		line = strings.TrimSpace(line)
		if strings.Contains(line, "CreatedAt") && strings.Contains(line, "uniqueIndex") {
			t.Error("CreatedAt should not have uniqueIndex tag")
		}
	}
}

func TestGoGormGenerator_DefaultExpr(t *testing.T) {
	schema := &model.Schema{
		Tables: []model.Table{{
			Name:    "items",
			Comment: "Items",
			PK:      []string{"id"},
			Columns: []model.Column{
				{Name: "id", PGType: typeinfo.MustParse("uuid"), NotNull: true, DefaultExpr: "gen_random_uuid()"},
			},
		}},
	}

	gen := &GoGormGenerator{}
	out, diags := gen.Generate(schema)
	if len(diags) > 0 {
		t.Fatalf("unexpected diagnostics: %v", diags)
	}

	result := string(out)

	if !containsGormField(result, "Id", "uuid.UUID", "default:gen_random_uuid()") {
		t.Error("missing default:gen_random_uuid() in gorm tag for DefaultExpr column")
	}
}
