package codegen

import (
	"bytes"
	"fmt"
	"sort"
	"strings"

	"github.com/smm-h/pgdesign/internal/diagnostic"
	"github.com/smm-h/pgdesign/internal/model"
)

// GoTypesGenerator generates Go struct types corresponding to database tables.
type GoTypesGenerator struct{}

// Generate produces a Go source file with one struct per table in the schema.
// Each struct has exported fields matching the table's columns, with db struct
// tags for the original column names.
func (g *GoTypesGenerator) Generate(schema *model.Schema) ([]byte, []diagnostic.Diagnostic) {
	var buf bytes.Buffer
	header := "// Code generated by pgdesign -- do not edit.\n\npackage schema\n"

	if len(schema.Tables) == 0 {
		buf.WriteString(header)
		return buf.Bytes(), nil
	}

	// First pass: determine all Go types to figure out which imports are needed.
	type fieldInfo struct {
		Name   string
		GoType string
		DBTag  string
	}
	type structInfo struct {
		Name      string
		TableName string
		Fields    []fieldInfo
	}

	var structs []structInfo
	imports := make(map[string]bool)

	for _, tbl := range schema.Tables {
		si := structInfo{
			Name:      toPascalCase(tbl.Name),
			TableName: tbl.Name,
		}
		for _, col := range tbl.Columns {
			var goType string
			var importPath string
			isBytea := strings.ToLower(col.PGType) == "bytea"

			if col.SemanticTypeName == "money" {
				goType = LookupMoneyType(LangGo)
			} else {
				m := LookupType(col.PGType, LangGo)
				goType = m.Type
				importPath = m.Import
			}
			goType = applyModifiers(goType, col, isBytea)

			if importPath != "" {
				imports[importPath] = true
			}
			si.Fields = append(si.Fields, fieldInfo{
				Name:   toPascalCase(col.Name),
				GoType: goType,
				DBTag:  col.Name,
			})
		}
		structs = append(structs, si)
	}

	// Write header and package.
	buf.WriteString(header)

	// Write imports if any are needed.
	if len(imports) > 0 {
		var stdlibs []string
		var thirdParty []string
		for imp := range imports {
			if isStdlib(imp) {
				stdlibs = append(stdlibs, imp)
			} else {
				thirdParty = append(thirdParty, imp)
			}
		}
		sort.Strings(stdlibs)
		sort.Strings(thirdParty)

		buf.WriteString("\nimport (\n")
		for _, imp := range stdlibs {
			fmt.Fprintf(&buf, "\t%q\n", imp)
		}
		if len(stdlibs) > 0 && len(thirdParty) > 0 {
			buf.WriteString("\n")
		}
		for _, imp := range thirdParty {
			fmt.Fprintf(&buf, "\t%q\n", imp)
		}
		buf.WriteString(")\n")
	}

	// Write enums.
	enumBlock := GenerateEnums(schema.Enums, LangGo)
	if enumBlock != "" {
		buf.WriteString("\n")
		buf.WriteString(enumBlock)
	}

	// Write structs.
	for _, si := range structs {
		buf.WriteString("\n")
		if si.TableName != "" {
			fmt.Fprintf(&buf, "// %s represents the %s table.\n", si.Name, si.TableName)
		}
		fmt.Fprintf(&buf, "type %s struct {\n", si.Name)

		// Calculate max field name length for alignment.
		maxNameLen := 0
		maxTypeLen := 0
		for _, f := range si.Fields {
			if len(f.Name) > maxNameLen {
				maxNameLen = len(f.Name)
			}
			if len(f.GoType) > maxTypeLen {
				maxTypeLen = len(f.GoType)
			}
		}

		for _, f := range si.Fields {
			fmt.Fprintf(&buf, "\t%-*s %-*s `db:%q`\n", maxNameLen, f.Name, maxTypeLen, f.GoType, f.DBTag)
		}
		buf.WriteString("}\n")
	}

	return buf.Bytes(), nil
}

// applyModifiers wraps a base Go type with slice/pointer prefixes based on
// the column's Array and NotNull flags.
func applyModifiers(goType string, col model.Column, isBytea bool) string {
	if isBytea {
		// bytea base type is already []byte (a slice).
		if col.Array {
			// Array of bytea: [][]byte.
			goType = "[]" + goType
			if !col.NotNull {
				// Nullable array of bytea: *[][]byte.
				goType = "*" + goType
			}
		}
		// Non-array bytea: []byte is already nil-able, no pointer needed
		// regardless of nullability.
		return goType
	}

	if col.Array && !col.NotNull {
		// Nullable array: *[]<type>.
		return "*[]" + goType
	}
	if col.Array {
		// Non-nullable array: []<type>.
		return "[]" + goType
	}
	if !col.NotNull {
		// Nullable scalar: *<type>.
		return "*" + goType
	}
	return goType
}

// isStdlib returns true if the import path is a Go standard library package.
func isStdlib(path string) bool {
	return !strings.Contains(path, ".")
}
