package codegen

import (
	"strings"
	"testing"

	"github.com/smm-h/pgdesign/internal/model"
)

// containsJavaField checks that at least one line in s contains the Java type
// and field name in record parameter format (e.g., "    UUID id," or "    UUID id").
func containsJavaField(s, fieldName, javaType string) bool {
	for _, line := range strings.Split(s, "\n") {
		trimmed := strings.TrimSpace(line)
		trimmed = strings.TrimSuffix(trimmed, ",")
		if trimmed == javaType+" "+fieldName {
			return true
		}
	}
	return false
}

func TestJavaTypesGenerator_Basic(t *testing.T) {
	schema := &model.Schema{
		Tables: []model.Table{
			{
				Name:    "users",
				Schema:  "public",
				Comment: "Application users",
				Columns: []model.Column{
					{Name: "id", PGType: "uuid", NotNull: true},
					{Name: "email", PGType: "text", NotNull: true},
					{Name: "score", PGType: "bigint", NotNull: true},
					{Name: "is_active", PGType: "boolean", NotNull: true},
					{Name: "created_at", PGType: "timestamptz", NotNull: true},
					{Name: "metadata", PGType: "jsonb", NotNull: true},
					{Name: "age", PGType: "integer", NotNull: true},
					{Name: "rating", PGType: "double precision", NotNull: true},
					{Name: "avatar", PGType: "bytea", NotNull: true},
					{Name: "balance", PGType: "numeric", NotNull: true},
				},
			},
		},
	}

	gen := &JavaTypesGenerator{}
	out, diags := gen.Generate(schema)
	if len(diags) > 0 {
		t.Fatalf("unexpected diagnostics: %v", diags)
	}

	result := string(out)

	// Header.
	if !strings.Contains(result, "// Code generated by pgdesign -- do not edit.") {
		t.Error("missing generated header comment")
	}

	// Record comment and declaration.
	if !strings.Contains(result, "/** Represents the users table. */") {
		t.Error("missing record comment")
	}
	if !strings.Contains(result, "public record Users(") {
		t.Error("missing record declaration")
	}

	// Fields with correct types.
	if !containsJavaField(result, "id", "UUID") {
		t.Error("missing or incorrect id field (expected UUID for uuid)")
	}
	if !containsJavaField(result, "email", "String") {
		t.Error("missing or incorrect email field (expected String)")
	}
	if !containsJavaField(result, "score", "long") {
		t.Error("missing or incorrect score field (expected long for bigint)")
	}
	if !containsJavaField(result, "isActive", "boolean") {
		t.Error("missing or incorrect isActive field (expected boolean)")
	}
	if !containsJavaField(result, "createdAt", "Instant") {
		t.Error("missing or incorrect createdAt field (expected Instant for timestamptz)")
	}
	if !containsJavaField(result, "metadata", "JsonNode") {
		t.Error("missing or incorrect metadata field (expected JsonNode for jsonb)")
	}
	if !containsJavaField(result, "age", "int") {
		t.Error("missing or incorrect age field (expected int for integer)")
	}
	if !containsJavaField(result, "rating", "double") {
		t.Error("missing or incorrect rating field (expected double for double precision)")
	}
	if !containsJavaField(result, "avatar", "byte[]") {
		t.Error("missing or incorrect avatar field (expected byte[] for bytea)")
	}
	if !containsJavaField(result, "balance", "BigDecimal") {
		t.Error("missing or incorrect balance field (expected BigDecimal for numeric)")
	}

	// Check imports are present.
	if !strings.Contains(result, "import java.math.BigDecimal;") {
		t.Error("missing BigDecimal import")
	}
	if !strings.Contains(result, "import java.time.Instant;") {
		t.Error("missing Instant import")
	}
	if !strings.Contains(result, "import java.util.UUID;") {
		t.Error("missing UUID import")
	}
	if !strings.Contains(result, "import com.fasterxml.jackson.databind.JsonNode;") {
		t.Error("missing JsonNode import")
	}
}

func TestJavaTypesGenerator_NullableAndArray(t *testing.T) {
	schema := &model.Schema{
		Tables: []model.Table{
			{
				Name:    "items",
				Comment: "Test items",
				Columns: []model.Column{
					{Name: "id", PGType: "integer", NotNull: true},
					{Name: "count", PGType: "integer", NotNull: false},
					{Name: "tags", PGType: "text", NotNull: true, Array: true},
					{Name: "scores", PGType: "integer", NotNull: false, Array: true},
					{Name: "status", PGType: "user_status", NotNull: true},
				},
			},
		},
	}

	gen := &JavaTypesGenerator{}
	out, diags := gen.Generate(schema)
	if len(diags) > 0 {
		t.Fatalf("unexpected diagnostics: %v", diags)
	}

	result := string(out)

	// Not-null, not-array: primitive type.
	if !containsJavaField(result, "id", "int") {
		t.Error("missing or incorrect id field (expected int)")
	}

	// Nullable: wrapper type.
	if !containsJavaField(result, "count", "Integer") {
		t.Error("missing or incorrect count field (expected Integer for nullable int)")
	}

	// Array: List<T>.
	if !containsJavaField(result, "tags", "List<String>") {
		t.Error("missing or incorrect tags field (expected List<String>)")
	}

	// Nullable + array: List<T> (same as non-nullable array).
	if !containsJavaField(result, "scores", "List<Integer>") {
		t.Error("missing or incorrect scores field (expected List<Integer>)")
	}

	// Enum (unrecognized PG type): String.
	if !containsJavaField(result, "status", "String") {
		t.Error("missing or incorrect status field (expected String for enum)")
	}

	// Check List import.
	if !strings.Contains(result, "import java.util.List;") {
		t.Error("missing List import")
	}
}

func TestJavaTypesGenerator_EmptySchema(t *testing.T) {
	schema := &model.Schema{Tables: []model.Table{}}

	gen := &JavaTypesGenerator{}
	out, diags := gen.Generate(schema)
	if len(diags) > 0 {
		t.Fatalf("unexpected diagnostics: %v", diags)
	}

	result := string(out)

	if !strings.Contains(result, "// Code generated by pgdesign -- do not edit.") {
		t.Error("missing generated header comment")
	}
	if strings.Contains(result, "public record") {
		t.Error("empty schema should not have record declarations")
	}
	if strings.Contains(result, "import ") {
		t.Error("empty schema should not have imports")
	}
}

func TestJavaTypesGenerator_MoneySemanticType(t *testing.T) {
	schema := &model.Schema{
		Tables: []model.Table{
			{
				Name:    "products",
				Comment: "Products",
				Columns: []model.Column{
					{Name: "id", PGType: "integer", NotNull: true},
					{Name: "price", PGType: "bigint", NotNull: true, SemanticTypeName: "money"},
				},
			},
		},
	}

	gen := &JavaTypesGenerator{}
	out, diags := gen.Generate(schema)
	if len(diags) > 0 {
		t.Fatalf("unexpected diagnostics: %v", diags)
	}

	result := string(out)

	// Money semantic type should map to long.
	if !containsJavaField(result, "price", "long") {
		t.Error("missing or incorrect price field (expected long for money semantic type)")
	}
}

func TestJavaTypesGenerator_MultipleTables(t *testing.T) {
	schema := &model.Schema{
		Tables: []model.Table{
			{
				Name:    "orders",
				Comment: "Orders",
				Columns: []model.Column{
					{Name: "id", PGType: "uuid", NotNull: true},
					{Name: "total", PGType: "numeric", NotNull: true},
				},
			},
			{
				Name:    "order_items",
				Comment: "Order items",
				Columns: []model.Column{
					{Name: "id", PGType: "integer", NotNull: true},
					{Name: "quantity", PGType: "smallint", NotNull: true},
				},
			},
		},
	}

	gen := &JavaTypesGenerator{}
	out, diags := gen.Generate(schema)
	if len(diags) > 0 {
		t.Fatalf("unexpected diagnostics: %v", diags)
	}

	result := string(out)

	// Both record declarations present.
	if !strings.Contains(result, "public record Orders(") {
		t.Error("missing Orders record declaration")
	}
	if !strings.Contains(result, "public record OrderItems(") {
		t.Error("missing OrderItems record declaration")
	}

	// Spot-check a field from the second table.
	if !containsJavaField(result, "quantity", "short") {
		t.Error("missing or incorrect quantity field (expected short)")
	}
}
