package codegen

import (
	"strings"
	"testing"

	"github.com/smm-h/pgdesign/internal/model"
	"github.com/smm-h/pgdesign/internal/typeinfo"
)

func TestJavaConstraintsGenerator_Generate(t *testing.T) {
	schema := &model.Schema{
		Name: "app",
		Enums: []model.Enum{
			{Name: "role", Values: []string{"admin", "user", "guest"}},
		},
		Tables: []model.Table{
			{
				Name: "users",
				Columns: []model.Column{
					{Name: "id", PGType: typeinfo.MustParse("bigint"), NotNull: true},
					{Name: "name", PGType: typeinfo.MustParse("text"), NotNull: true},
					{Name: "email", PGType: typeinfo.MustParse("text"), NotNull: true},
					{Name: "role", PGType: typeinfo.MustParse("role"), NotNull: true, TypeKind: "enum"},
					{Name: "age", PGType: typeinfo.MustParse("integer"), NotNull: true},
					{Name: "slug", PGType: typeinfo.MustParse("varchar"), NotNull: true},
				},
				PK: []string{"id"},
				Checks: []model.CheckConstraint{
					{Name: "ck_users_age_range", Expr: "age >= 0 AND age <= 150"},
					{Name: "ck_users_email_fmt", Expr: "email LIKE '%@%'"},
					{Name: "ck_users_slug_len", Expr: "LENGTH(slug) <= 100"},
				},
			},
		},
	}

	gen := &JavaConstraintsGenerator{}
	out, diags := gen.Generate(schema)
	if len(diags) > 0 {
		t.Fatalf("unexpected diagnostics: %v", diags)
	}

	result := string(out)

	// Header.
	if !strings.Contains(result, "Code generated by pgdesign") {
		t.Error("missing header comment")
	}

	// ValidationError record.
	if !strings.Contains(result, "public record ValidationError") {
		t.Error("missing ValidationError record")
	}

	// Validate method signature.
	if !strings.Contains(result, "public static List<ValidationError> validateUsers(Users row)") {
		t.Error("missing validateUsers method signature")
	}

	// NOT NULL checks for string-type columns (using getter style).
	if !strings.Contains(result, "row.name() == null") {
		t.Error("missing NOT NULL check for name")
	}
	if !strings.Contains(result, "row.email() == null") {
		t.Error("missing NOT NULL check for email")
	}
	if !strings.Contains(result, "row.slug() == null") {
		t.Error("missing NOT NULL check for slug")
	}

	// String-type columns get isEmpty check.
	if !strings.Contains(result, "row.name().isEmpty()") {
		t.Error("missing isEmpty check for name")
	}

	// Enum check with Set.of.
	if !strings.Contains(result, "Set.of(") {
		t.Error("missing Set.of() for enum check")
	}
	if !strings.Contains(result, `"admin"`) {
		t.Error("missing enum value 'admin'")
	}
	if !strings.Contains(result, `"user"`) {
		t.Error("missing enum value 'user'")
	}
	if !strings.Contains(result, `"guest"`) {
		t.Error("missing enum value 'guest'")
	}

	// Range check for age.
	if !strings.Contains(result, "row.age()") {
		t.Error("missing age range check")
	}
	if !strings.Contains(result, "150") {
		t.Error("missing age upper bound 150")
	}

	// LIKE check for email -> Pattern.matches.
	if !strings.Contains(result, "Pattern.matches(") {
		t.Error("missing Pattern.matches for email LIKE check")
	}
	if !strings.Contains(result, "java.util.regex.Pattern") {
		t.Error("missing Pattern import")
	}

	// Length check for slug.
	if !strings.Contains(result, "row.slug().length()") {
		t.Error("missing length check for slug")
	}
	if !strings.Contains(result, "100") {
		t.Error("missing length limit 100")
	}
}

func TestJavaConstraintsGenerator_EmptySchema(t *testing.T) {
	schema := &model.Schema{
		Name: "empty",
	}

	gen := &JavaConstraintsGenerator{}
	out, diags := gen.Generate(schema)
	if len(diags) > 0 {
		t.Fatalf("unexpected diagnostics: %v", diags)
	}

	result := string(out)
	if !strings.Contains(result, "No tables with extractable constraints.") {
		t.Error("missing empty-schema comment")
	}
	if strings.Contains(result, "validateUsers") {
		t.Error("should not contain any validate methods for empty schema")
	}
}

func TestJavaConstraintsGenerator_NoConstraints(t *testing.T) {
	schema := &model.Schema{
		Tables: []model.Table{
			{
				Name: "simple",
				Columns: []model.Column{
					{Name: "id", PGType: typeinfo.MustParse("bigint"), NotNull: true},
				},
				PK: []string{"id"},
			},
		},
	}

	gen := &JavaConstraintsGenerator{}
	out, diags := gen.Generate(schema)
	if len(diags) > 0 {
		t.Fatalf("unexpected diagnostics: %v", diags)
	}

	result := string(out)
	if !strings.Contains(result, "No tables with extractable constraints.") {
		t.Error("missing no-constraints comment")
	}
}

func TestJavaConstraintsGenerator_NoPatternWithoutLike(t *testing.T) {
	schema := &model.Schema{
		Tables: []model.Table{
			{
				Name: "items",
				Columns: []model.Column{
					{Name: "id", PGType: typeinfo.MustParse("bigint"), NotNull: true},
					{Name: "price", PGType: typeinfo.MustParse("integer"), NotNull: true},
				},
				PK: []string{"id"},
				Checks: []model.CheckConstraint{
					{Name: "ck_items_price", Expr: "price >= 0"},
				},
			},
		},
	}

	gen := &JavaConstraintsGenerator{}
	out, diags := gen.Generate(schema)
	if len(diags) > 0 {
		t.Fatalf("unexpected diagnostics: %v", diags)
	}

	result := string(out)
	if strings.Contains(result, "java.util.regex.Pattern") {
		t.Error("should not import Pattern when no LIKE patterns exist")
	}
}
