package codegen

import (
	"strings"
	"testing"

	"github.com/smm-h/pgdesign/internal/model"
)

// containsJPAField checks that at least one line in s contains a JPA entity
// field declaration: "    private <javaType> <fieldName>;".
func containsJPAField(s, fieldName, javaType string) bool {
	target := "    private " + javaType + " " + fieldName + ";"
	return strings.Contains(s, target)
}

// containsAnnotation checks that s contains the given annotation string.
func containsAnnotation(s, annotation string) bool {
	return strings.Contains(s, annotation)
}

func TestJavaJPAGenerator_Basic(t *testing.T) {
	schema := &model.Schema{
		Tables: []model.Table{
			{
				Name:    "users",
				Schema:  "public",
				Comment: "Application users",
				Columns: []model.Column{
					{Name: "id", PGType: "uuid", NotNull: true},
					{Name: "email", PGType: "text", NotNull: true},
					{Name: "score", PGType: "bigint", NotNull: true},
					{Name: "is_active", PGType: "boolean", NotNull: true},
					{Name: "created_at", PGType: "timestamptz", NotNull: true},
					{Name: "metadata", PGType: "jsonb", NotNull: true},
					{Name: "age", PGType: "integer", NotNull: true},
					{Name: "rating", PGType: "double precision", NotNull: true},
					{Name: "avatar", PGType: "bytea", NotNull: true},
					{Name: "balance", PGType: "numeric", NotNull: true},
				},
				PK: []string{"id"},
			},
		},
	}

	gen := &JavaJPAGenerator{}
	out, diags := gen.Generate(schema)
	if len(diags) > 0 {
		t.Fatalf("unexpected diagnostics: %v", diags)
	}

	result := string(out)

	// Header.
	if !strings.Contains(result, "// Code generated by pgdesign -- do not edit.") {
		t.Error("missing generated header comment")
	}

	// Entity annotation and class declaration.
	if !containsAnnotation(result, "@Entity") {
		t.Error("missing @Entity annotation")
	}
	if !containsAnnotation(result, `@Table(name = "users")`) {
		t.Error("missing @Table annotation with correct table name")
	}
	if !strings.Contains(result, "public class Users {") {
		t.Error("missing class declaration")
	}

	// @Id annotation on primary key.
	if !containsAnnotation(result, "@Id") {
		t.Error("missing @Id annotation on primary key")
	}

	// @Column annotations.
	if !containsAnnotation(result, `@Column(name = "id", nullable = false)`) {
		t.Error("missing @Column annotation for id")
	}
	if !containsAnnotation(result, `@Column(name = "email", nullable = false)`) {
		t.Error("missing @Column annotation for email")
	}

	// Field types.
	if !containsJPAField(result, "id", "UUID") {
		t.Error("missing or incorrect id field (expected UUID)")
	}
	if !containsJPAField(result, "email", "String") {
		t.Error("missing or incorrect email field (expected String)")
	}
	if !containsJPAField(result, "score", "long") {
		t.Error("missing or incorrect score field (expected long for bigint)")
	}
	if !containsJPAField(result, "isActive", "boolean") {
		t.Error("missing or incorrect isActive field (expected boolean)")
	}
	if !containsJPAField(result, "createdAt", "Instant") {
		t.Error("missing or incorrect createdAt field (expected Instant for timestamptz)")
	}
	if !containsJPAField(result, "metadata", "JsonNode") {
		t.Error("missing or incorrect metadata field (expected JsonNode for jsonb)")
	}
	if !containsJPAField(result, "age", "int") {
		t.Error("missing or incorrect age field (expected int for integer)")
	}
	if !containsJPAField(result, "rating", "double") {
		t.Error("missing or incorrect rating field (expected double for double precision)")
	}
	if !containsJPAField(result, "avatar", "byte[]") {
		t.Error("missing or incorrect avatar field (expected byte[] for bytea)")
	}
	if !containsJPAField(result, "balance", "BigDecimal") {
		t.Error("missing or incorrect balance field (expected BigDecimal for numeric)")
	}

	// Imports.
	if !strings.Contains(result, "import java.math.BigDecimal;") {
		t.Error("missing BigDecimal import")
	}
	if !strings.Contains(result, "import java.time.Instant;") {
		t.Error("missing Instant import")
	}
	if !strings.Contains(result, "import java.util.UUID;") {
		t.Error("missing UUID import")
	}
	if !strings.Contains(result, "import javax.persistence.*;") {
		t.Error("missing javax.persistence import")
	}
	if !strings.Contains(result, "import com.fasterxml.jackson.databind.JsonNode;") {
		t.Error("missing JsonNode import")
	}
}

func TestJavaJPAGenerator_NullableAndArray(t *testing.T) {
	schema := &model.Schema{
		Tables: []model.Table{
			{
				Name:    "items",
				Comment: "Test items",
				Columns: []model.Column{
					{Name: "id", PGType: "integer", NotNull: true},
					{Name: "count", PGType: "integer", NotNull: false},
					{Name: "tags", PGType: "text", NotNull: true, Array: true},
					{Name: "scores", PGType: "integer", NotNull: false, Array: true},
					{Name: "status", PGType: "user_status", NotNull: true},
				},
				PK: []string{"id"},
			},
		},
	}

	gen := &JavaJPAGenerator{}
	out, diags := gen.Generate(schema)
	if len(diags) > 0 {
		t.Fatalf("unexpected diagnostics: %v", diags)
	}

	result := string(out)

	// Not-null, not-array: primitive type.
	if !containsJPAField(result, "id", "int") {
		t.Error("missing or incorrect id field (expected int)")
	}

	// Nullable: wrapper type.
	if !containsJPAField(result, "count", "Integer") {
		t.Error("missing or incorrect count field (expected Integer for nullable int)")
	}
	if !containsAnnotation(result, `@Column(name = "count", nullable = true)`) {
		t.Error("missing @Column annotation with nullable = true for count")
	}

	// Array: List<T>.
	if !containsJPAField(result, "tags", "List<String>") {
		t.Error("missing or incorrect tags field (expected List<String>)")
	}

	// Nullable + array: List<T> (wrapper element type).
	if !containsJPAField(result, "scores", "List<Integer>") {
		t.Error("missing or incorrect scores field (expected List<Integer>)")
	}

	// Enum (unrecognized PG type): String.
	if !containsJPAField(result, "status", "String") {
		t.Error("missing or incorrect status field (expected String for unrecognized enum type)")
	}

	// List import.
	if !strings.Contains(result, "import java.util.List;") {
		t.Error("missing List import")
	}
}

func TestJavaJPAGenerator_EmptySchema(t *testing.T) {
	schema := &model.Schema{Tables: []model.Table{}}

	gen := &JavaJPAGenerator{}
	out, diags := gen.Generate(schema)
	if len(diags) > 0 {
		t.Fatalf("unexpected diagnostics: %v", diags)
	}

	result := string(out)

	// Header present.
	if !strings.Contains(result, "// Code generated by pgdesign -- do not edit.") {
		t.Error("missing generated header comment")
	}

	// No entity declarations.
	if strings.Contains(result, "@Entity") {
		t.Error("empty schema should not have @Entity annotations")
	}
	if strings.Contains(result, "public class") {
		t.Error("empty schema should not have class declarations")
	}
}

func TestJavaJPAGenerator_MoneySemanticType(t *testing.T) {
	schema := &model.Schema{
		Tables: []model.Table{
			{
				Name:    "products",
				Comment: "Products",
				Columns: []model.Column{
					{Name: "id", PGType: "integer", NotNull: true},
					{Name: "price", PGType: "bigint", NotNull: true, SemanticTypeName: "money"},
				},
				PK: []string{"id"},
			},
		},
	}

	gen := &JavaJPAGenerator{}
	out, diags := gen.Generate(schema)
	if len(diags) > 0 {
		t.Fatalf("unexpected diagnostics: %v", diags)
	}

	result := string(out)

	// Money semantic type maps to long (same as bigint base type).
	if !containsJPAField(result, "price", "long") {
		t.Error("missing or incorrect price field (expected long for money semantic type)")
	}
}

func TestJavaJPAGenerator_ForeignKeys(t *testing.T) {
	schema := &model.Schema{
		Tables: []model.Table{
			{
				Name:    "users",
				Schema:  "public",
				Comment: "Users",
				Columns: []model.Column{
					{Name: "id", PGType: "uuid", NotNull: true},
					{Name: "name", PGType: "text", NotNull: true},
				},
				PK: []string{"id"},
			},
			{
				Name:    "orders",
				Schema:  "public",
				Comment: "Orders",
				Columns: []model.Column{
					{Name: "id", PGType: "uuid", NotNull: true},
					{Name: "user_id", PGType: "uuid", NotNull: true},
					{Name: "total", PGType: "integer", NotNull: true},
				},
				PK: []string{"id"},
				FKs: []model.FK{
					{
						Name:       "fk_orders_user",
						Columns:    []string{"user_id"},
						RefTable:   "users",
						RefColumns: []string{"id"},
						OnDelete:   "CASCADE",
					},
				},
			},
		},
	}

	gen := &JavaJPAGenerator{}
	out, diags := gen.Generate(schema)
	if len(diags) > 0 {
		t.Fatalf("unexpected diagnostics: %v", diags)
	}

	result := string(out)

	// Orders entity: @ManyToOne with @JoinColumn for user FK.
	if !containsAnnotation(result, "@ManyToOne(fetch = FetchType.LAZY)") {
		t.Error("missing @ManyToOne annotation on FK field")
	}
	if !containsAnnotation(result, `@JoinColumn(name = "user_id", nullable = false)`) {
		t.Error("missing @JoinColumn annotation for user_id FK")
	}
	// The FK field should be typed as the referenced entity.
	if !containsJPAField(result, "user", "Users") {
		t.Error("missing or incorrect ManyToOne field (expected Users user)")
	}

	// Users entity: @OneToMany(mappedBy) inverse relationship.
	if !containsAnnotation(result, `@OneToMany(mappedBy = "user")`) {
		t.Error("missing @OneToMany annotation with mappedBy on Users entity")
	}
	if !containsJPAField(result, "orders", "List<Orders>") {
		t.Error("missing or incorrect OneToMany field (expected List<Orders> orders)")
	}

	// FK column (user_id) should NOT appear as a separate @Column field.
	if containsAnnotation(result, `@Column(name = "user_id"`) {
		t.Error("FK column user_id should not be duplicated as a @Column field")
	}

	// Non-FK column total should still be present.
	if !containsJPAField(result, "total", "int") {
		t.Error("missing or incorrect total field (expected int)")
	}
}

func TestJavaJPAGenerator_MultipleTables(t *testing.T) {
	schema := &model.Schema{
		Tables: []model.Table{
			{
				Name:    "orders",
				Comment: "Orders",
				Columns: []model.Column{
					{Name: "id", PGType: "uuid", NotNull: true},
					{Name: "total", PGType: "numeric", NotNull: true},
				},
				PK: []string{"id"},
			},
			{
				Name:    "order_items",
				Comment: "Order items",
				Columns: []model.Column{
					{Name: "id", PGType: "integer", NotNull: true},
					{Name: "quantity", PGType: "smallint", NotNull: true},
				},
				PK: []string{"id"},
			},
		},
	}

	gen := &JavaJPAGenerator{}
	out, diags := gen.Generate(schema)
	if len(diags) > 0 {
		t.Fatalf("unexpected diagnostics: %v", diags)
	}

	result := string(out)

	// Both entity classes present.
	if !strings.Contains(result, "public class Orders {") {
		t.Error("missing Orders class declaration")
	}
	if !strings.Contains(result, "public class OrderItems {") {
		t.Error("missing OrderItems class declaration")
	}

	// @Table annotations with correct names.
	if !containsAnnotation(result, `@Table(name = "orders")`) {
		t.Error("missing @Table annotation for orders")
	}
	if !containsAnnotation(result, `@Table(name = "order_items")`) {
		t.Error("missing @Table annotation for order_items")
	}

	// Field types.
	if !containsJPAField(result, "total", "BigDecimal") {
		t.Error("missing or incorrect total field (expected BigDecimal for numeric)")
	}
	if !containsJPAField(result, "quantity", "short") {
		t.Error("missing or incorrect quantity field (expected short for smallint)")
	}
}
