package codegen

import (
	"bytes"
	"fmt"
	"sort"
	"strings"

	"github.com/smm-h/pgdesign/internal/diagnostic"
	"github.com/smm-h/pgdesign/internal/model"
	"github.com/smm-h/pgdesign/internal/typeinfo"
)

// JavaJPAGenerator generates JPA entity classes corresponding to database tables,
// including @ManyToOne and @OneToMany relationship annotations derived from
// foreign key metadata.
type JavaJPAGenerator struct{}

// Generate produces a Java source file with one @Entity class per table in the
// schema.
func (g *JavaJPAGenerator) Generate(schema *model.Schema) ([]byte, []diagnostic.Diagnostic) {
	var buf bytes.Buffer
	header := "// Code generated by pgdesign -- do not edit.\n"

	if len(schema.Tables) == 0 {
		buf.WriteString(header)
		return buf.Bytes(), nil
	}

	if schema.FKGraph == nil {
		schema.BuildFKGraph()
	}

	// Collect entity information and imports.
	type fieldInfo struct {
		Annotations []string
		JavaType    string
		Name        string
		Group       int // 0=columns, 1=ManyToOne, 2=OneToMany
	}
	type entityInfo struct {
		TableName string
		ClassName string
		Fields    []fieldInfo
	}

	imports := make(map[string]bool)
	imports["javax.persistence.*"] = true
	var entities []entityInfo

	for _, tbl := range schema.Tables {
		ei := entityInfo{
			TableName: tbl.Name,
			ClassName: toPascalCase(tbl.Name),
		}

		// Build PK set.
		pkSet := make(map[string]bool, len(tbl.PK))
		for _, pk := range tbl.PK {
			pkSet[pk] = true
		}

		// Build set of columns that are single-column FK sources.
		fkColSet := make(map[string]model.FK)
		for _, fk := range tbl.FKs {
			if len(fk.Columns) == 1 {
				fkColSet[fk.Columns[0]] = fk
			}
		}

		// Regular columns (skipping single-column FK columns).
		for _, col := range tbl.Columns {
			if _, isFKCol := fkColSet[col.Name]; isFKCol {
				continue
			}

			javaType, typeImports := pgBaseTypeToJava(col)
			if col.Array {
				wrapperType, wrapperImports := toJavaWrapper(javaType, typeImports)
				javaType = "List<" + wrapperType + ">"
				typeImports = append([]string{"java.util.List"}, wrapperImports...)
			} else if !col.NotNull {
				javaType, typeImports = toJavaWrapper(javaType, typeImports)
			}
			for _, imp := range typeImports {
				imports[imp] = true
			}

			var annotations []string
			if pkSet[col.Name] {
				annotations = append(annotations, "@Id")
			}
			nullable := "false"
			if !col.NotNull {
				nullable = "true"
			}
			if col.Default == nil && col.DefaultExpr != "" {
				pgTypeStr := typeinfo.Reconstruct(col.PGType)
				if col.Array {
					pgTypeStr += "[]"
				}
				annotations = append(annotations, fmt.Sprintf("@Column(name = %q, nullable = %s, columnDefinition = %q)", col.Name, nullable, pgTypeStr+" DEFAULT "+col.DefaultExpr))
			} else {
				annotations = append(annotations, fmt.Sprintf("@Column(name = %q, nullable = %s)", col.Name, nullable))
			}

			ei.Fields = append(ei.Fields, fieldInfo{
				Annotations: annotations,
				JavaType:    javaType,
				Name:        toCamelCase(col.Name),
				Group:       0,
			})
		}

		// @ManyToOne fields for single-column FKs.
		for _, fk := range tbl.FKs {
			if len(fk.Columns) != 1 {
				continue
			}
			col := findColumn(tbl, fk.Columns[0])
			refType := toPascalCase(fk.RefTable)
			fieldName := jpaRelFieldName(fk.Columns[0], fk.RefTable)

			nullable := "false"
			if col != nil && !col.NotNull {
				nullable = "true"
			}

			annotations := []string{
				"@ManyToOne(fetch = FetchType.LAZY)",
				fmt.Sprintf("@JoinColumn(name = %q, nullable = %s)", fk.Columns[0], nullable),
			}

			ei.Fields = append(ei.Fields, fieldInfo{
				Annotations: annotations,
				JavaType:    refType,
				Name:        fieldName,
				Group:       1,
			})
		}

		// @OneToMany fields from reverse FK map.
		if edges := schema.FKGraph.Reverse[tbl.Name]; len(edges) > 0 {
			fkColCount := make(map[string]int)
			for _, e := range edges {
				fkColCount[e.FKName]++
			}
			seen := make(map[string]bool)
			for _, e := range edges {
				if fkColCount[e.FKName] != 1 || seen[e.FKName] {
					continue
				}
				seen[e.FKName] = true
				imports["java.util.List"] = true
				refType := toPascalCase(e.FromTable)
				fieldName := jpaRelFieldName(e.FromColumn, tbl.Name)
				annotations := []string{
					fmt.Sprintf("@OneToMany(mappedBy = %q)", fieldName),
				}
				ei.Fields = append(ei.Fields, fieldInfo{
					Annotations: annotations,
					JavaType:    "List<" + refType + ">",
					Name:        toCamelCase(e.FromTable),
					Group:       2,
				})
			}
		}

		entities = append(entities, ei)
	}

	// Separate imports into groups: java.*, javax.*, third-party.
	var javaImports, javaxImports, thirdPartyImports []string
	for imp := range imports {
		switch {
		case strings.HasPrefix(imp, "javax."):
			javaxImports = append(javaxImports, imp)
		case strings.HasPrefix(imp, "java."):
			javaImports = append(javaImports, imp)
		default:
			thirdPartyImports = append(thirdPartyImports, imp)
		}
	}
	sort.Strings(javaImports)
	sort.Strings(javaxImports)
	sort.Strings(thirdPartyImports)

	// Write output.
	buf.WriteString(header)

	// Write imports.
	buf.WriteString("\n")
	for _, imp := range javaImports {
		fmt.Fprintf(&buf, "import %s;\n", imp)
	}
	if len(javaImports) > 0 && (len(javaxImports) > 0 || len(thirdPartyImports) > 0) {
		buf.WriteString("\n")
	}
	for _, imp := range javaxImports {
		fmt.Fprintf(&buf, "import %s;\n", imp)
	}
	if len(thirdPartyImports) > 0 {
		buf.WriteString("\n")
		for _, imp := range thirdPartyImports {
			fmt.Fprintf(&buf, "import %s;\n", imp)
		}
	}

	// Write entity classes.
	for _, ei := range entities {
		buf.WriteString("\n")
		fmt.Fprintf(&buf, "@Entity\n")
		fmt.Fprintf(&buf, "@Table(name = %q)\n", ei.TableName)
		fmt.Fprintf(&buf, "public class %s {\n", ei.ClassName)

		// Write fields, inserting blank lines between groups.
		lastGroup := -1
		for _, f := range ei.Fields {
			if lastGroup >= 0 && f.Group != lastGroup {
				buf.WriteString("\n")
			}
			for _, ann := range f.Annotations {
				fmt.Fprintf(&buf, "    %s\n", ann)
			}
			fmt.Fprintf(&buf, "    private %s %s;\n", f.JavaType, f.Name)
			lastGroup = f.Group
		}

		buf.WriteString("}\n")
	}

	return buf.Bytes(), nil
}

// jpaRelFieldName derives the Java field name for a @ManyToOne relationship.
// If the FK column ends with "_id", the suffix is stripped and the result is
// camelCased. Otherwise, the referenced table name is camelCased.
func jpaRelFieldName(fkColumn, refTable string) string {
	if strings.HasSuffix(fkColumn, "_id") {
		return toCamelCase(strings.TrimSuffix(fkColumn, "_id"))
	}
	return toCamelCase(refTable)
}

// findColumn looks up a column by name in a table. Returns nil if not found.
func findColumn(tbl model.Table, name string) *model.Column {
	for i := range tbl.Columns {
		if tbl.Columns[i].Name == name {
			return &tbl.Columns[i]
		}
	}
	return nil
}
