package codegen

import (
	"strings"
	"testing"

	"github.com/smm-h/pgdesign/internal/model"
)

// containsKotlinField checks that at least one line in s contains the Kotlin
// field declaration in the format "val fieldName: kotlinType".
func containsKotlinField(s, fieldName, kotlinType string) bool {
	for _, line := range strings.Split(s, "\n") {
		trimmed := strings.TrimSpace(line)
		trimmed = strings.TrimSuffix(trimmed, ",")
		if trimmed == "val "+fieldName+": "+kotlinType {
			return true
		}
	}
	return false
}

func TestKotlinTypesGenerator_Basic(t *testing.T) {
	schema := &model.Schema{
		Tables: []model.Table{
			{
				Name:    "users",
				Schema:  "public",
				Comment: "Application users",
				Columns: []model.Column{
					{Name: "id", PGType: "uuid", NotNull: true},
					{Name: "email", PGType: "text", NotNull: true},
					{Name: "score", PGType: "bigint", NotNull: true},
					{Name: "is_active", PGType: "boolean", NotNull: true},
					{Name: "created_at", PGType: "timestamptz", NotNull: true},
					{Name: "metadata", PGType: "jsonb", NotNull: true},
					{Name: "age", PGType: "integer", NotNull: true},
					{Name: "rating", PGType: "double precision", NotNull: true},
					{Name: "avatar", PGType: "bytea", NotNull: true},
					{Name: "balance", PGType: "numeric", NotNull: true},
				},
			},
		},
	}

	gen := &KotlinTypesGenerator{}
	out, diags := gen.Generate(schema)
	if len(diags) > 0 {
		t.Fatalf("unexpected diagnostics: %v", diags)
	}

	result := string(out)

	// Header.
	if !strings.Contains(result, "// Code generated by pgdesign -- do not edit.") {
		t.Error("missing generated header comment")
	}

	// Data class comment and declaration.
	if !strings.Contains(result, "/** Represents the users table. */") {
		t.Error("missing data class comment")
	}
	if !strings.Contains(result, "data class Users(") {
		t.Error("missing data class declaration")
	}

	// Fields with correct types.
	if !containsKotlinField(result, "id", "UUID") {
		t.Error("missing or incorrect id field (expected UUID for uuid)")
	}
	if !containsKotlinField(result, "email", "String") {
		t.Error("missing or incorrect email field (expected String)")
	}
	if !containsKotlinField(result, "score", "Long") {
		t.Error("missing or incorrect score field (expected Long for bigint)")
	}
	if !containsKotlinField(result, "isActive", "Boolean") {
		t.Error("missing or incorrect isActive field (expected Boolean)")
	}
	if !containsKotlinField(result, "createdAt", "Instant") {
		t.Error("missing or incorrect createdAt field (expected Instant for timestamptz)")
	}
	if !containsKotlinField(result, "metadata", "JsonNode") {
		t.Error("missing or incorrect metadata field (expected JsonNode for jsonb)")
	}
	if !containsKotlinField(result, "age", "Int") {
		t.Error("missing or incorrect age field (expected Int for integer)")
	}
	if !containsKotlinField(result, "rating", "Double") {
		t.Error("missing or incorrect rating field (expected Double for double precision)")
	}
	if !containsKotlinField(result, "avatar", "ByteArray") {
		t.Error("missing or incorrect avatar field (expected ByteArray for bytea)")
	}
	if !containsKotlinField(result, "balance", "BigDecimal") {
		t.Error("missing or incorrect balance field (expected BigDecimal for numeric)")
	}

	// Check imports are present.
	if !strings.Contains(result, "import java.math.BigDecimal") {
		t.Error("missing BigDecimal import")
	}
	if !strings.Contains(result, "import java.time.Instant") {
		t.Error("missing Instant import")
	}
	if !strings.Contains(result, "import java.util.UUID") {
		t.Error("missing UUID import")
	}
	if !strings.Contains(result, "import com.fasterxml.jackson.databind.JsonNode") {
		t.Error("missing JsonNode import")
	}
}

func TestKotlinTypesGenerator_NullableAndArray(t *testing.T) {
	schema := &model.Schema{
		Tables: []model.Table{
			{
				Name:    "items",
				Comment: "Test items",
				Columns: []model.Column{
					{Name: "id", PGType: "integer", NotNull: true},
					{Name: "name", PGType: "text", NotNull: false},
					{Name: "tags", PGType: "text", NotNull: true, Array: true},
					{Name: "scores", PGType: "integer", NotNull: false, Array: true},
					{Name: "status", PGType: "user_status", NotNull: true},
				},
			},
		},
	}

	gen := &KotlinTypesGenerator{}
	out, diags := gen.Generate(schema)
	if len(diags) > 0 {
		t.Fatalf("unexpected diagnostics: %v", diags)
	}

	result := string(out)

	// Not-null, not-array: plain type.
	if !containsKotlinField(result, "id", "Int") {
		t.Error("missing or incorrect id field (expected Int)")
	}

	// Nullable: T?.
	if !containsKotlinField(result, "name", "String?") {
		t.Error("missing or incorrect name field (expected String?)")
	}

	// Array: List<T>.
	if !containsKotlinField(result, "tags", "List<String>") {
		t.Error("missing or incorrect tags field (expected List<String>)")
	}

	// Nullable + array: List<T>?.
	if !containsKotlinField(result, "scores", "List<Int>?") {
		t.Error("missing or incorrect scores field (expected List<Int>?)")
	}

	// Enum (unrecognized PG type): String.
	if !containsKotlinField(result, "status", "String") {
		t.Error("missing or incorrect status field (expected String for enum)")
	}
}

func TestKotlinTypesGenerator_EmptySchema(t *testing.T) {
	schema := &model.Schema{Tables: []model.Table{}}

	gen := &KotlinTypesGenerator{}
	out, diags := gen.Generate(schema)
	if len(diags) > 0 {
		t.Fatalf("unexpected diagnostics: %v", diags)
	}

	result := string(out)

	if !strings.Contains(result, "// Code generated by pgdesign -- do not edit.") {
		t.Error("missing generated header comment")
	}
	if strings.Contains(result, "data class") {
		t.Error("empty schema should not have data class declarations")
	}
	if strings.Contains(result, "import ") {
		t.Error("empty schema should not have imports")
	}
}

func TestKotlinTypesGenerator_MoneySemanticType(t *testing.T) {
	schema := &model.Schema{
		Tables: []model.Table{
			{
				Name:    "products",
				Comment: "Products",
				Columns: []model.Column{
					{Name: "id", PGType: "integer", NotNull: true},
					{Name: "price", PGType: "bigint", NotNull: true, SemanticTypeName: "money"},
				},
			},
		},
	}

	gen := &KotlinTypesGenerator{}
	out, diags := gen.Generate(schema)
	if len(diags) > 0 {
		t.Fatalf("unexpected diagnostics: %v", diags)
	}

	result := string(out)

	// Money semantic type should map to Long.
	if !containsKotlinField(result, "price", "Long") {
		t.Error("missing or incorrect price field (expected Long for money semantic type)")
	}
}

func TestKotlinTypesGenerator_MultipleTables(t *testing.T) {
	schema := &model.Schema{
		Tables: []model.Table{
			{
				Name:    "orders",
				Comment: "Orders",
				Columns: []model.Column{
					{Name: "id", PGType: "uuid", NotNull: true},
					{Name: "total", PGType: "numeric", NotNull: true},
				},
			},
			{
				Name:    "order_items",
				Comment: "Order items",
				Columns: []model.Column{
					{Name: "id", PGType: "integer", NotNull: true},
					{Name: "quantity", PGType: "smallint", NotNull: true},
				},
			},
		},
	}

	gen := &KotlinTypesGenerator{}
	out, diags := gen.Generate(schema)
	if len(diags) > 0 {
		t.Fatalf("unexpected diagnostics: %v", diags)
	}

	result := string(out)

	// Both data class declarations present.
	if !strings.Contains(result, "data class Orders(") {
		t.Error("missing Orders data class declaration")
	}
	if !strings.Contains(result, "data class OrderItems(") {
		t.Error("missing OrderItems data class declaration")
	}

	// Spot-check a field from the second table.
	if !containsKotlinField(result, "quantity", "Short") {
		t.Error("missing or incorrect quantity field (expected Short)")
	}
}
