package codegen

import (
	"bytes"
	"fmt"
	"sort"

	"github.com/smm-h/pgdesign/internal/diagnostic"
	"github.com/smm-h/pgdesign/internal/model"
)

// KotlinTypesGenerator generates Kotlin data classes corresponding to database tables.
type KotlinTypesGenerator struct{}

// Generate produces a Kotlin source file with one data class per table in the schema.
func (g *KotlinTypesGenerator) Generate(schema *model.Schema) ([]byte, []diagnostic.Diagnostic) {
	var buf bytes.Buffer
	header := "// Code generated by pgdesign -- do not edit.\n"

	if len(schema.Tables) == 0 {
		buf.WriteString(header)
		return buf.Bytes(), nil
	}

	// First pass: collect type info and imports.
	type fieldInfo struct {
		Name       string
		KotlinType string
	}
	type classInfo struct {
		Name      string
		TableName string
		Fields    []fieldInfo
	}

	imports := make(map[string]bool)
	var classes []classInfo

	for _, tbl := range schema.Tables {
		ci := classInfo{
			Name:      toPascalCase(tbl.Name),
			TableName: tbl.Name,
		}
		for _, col := range tbl.Columns {
			kotlinType, typeImports := pgTypeToKotlin(col)
			for _, imp := range typeImports {
				imports[imp] = true
			}
			ci.Fields = append(ci.Fields, fieldInfo{
				Name:       toCamelCase(col.Name),
				KotlinType: kotlinType,
			})
		}
		classes = append(classes, ci)
	}

	// Sort imports alphabetically.
	var sortedImports []string
	for imp := range imports {
		sortedImports = append(sortedImports, imp)
	}
	sort.Strings(sortedImports)

	// Second pass: write output.
	buf.WriteString(header)

	if len(sortedImports) > 0 {
		buf.WriteString("\n")
		for _, imp := range sortedImports {
			fmt.Fprintf(&buf, "import %s\n", imp)
		}
	}

	// Write enums.
	enumBlock := GenerateEnums(schema.Enums, LangKotlin)
	if enumBlock != "" {
		buf.WriteString("\n")
		buf.WriteString(enumBlock)
	}

	// Write state machine transition maps.
	smBlock := GenerateTransitionMaps(schema.StateMachineTransitions, LangKotlin)
	if smBlock != "" {
		buf.WriteString("\n")
		buf.WriteString(smBlock)
	}

	for _, ci := range classes {
		buf.WriteString("\n")
		fmt.Fprintf(&buf, "/** Represents the %s table. */\n", ci.TableName)
		fmt.Fprintf(&buf, "data class %s(\n", ci.Name)
		for i, f := range ci.Fields {
			if i < len(ci.Fields)-1 {
				fmt.Fprintf(&buf, "    val %s: %s,\n", f.Name, f.KotlinType)
			} else {
				fmt.Fprintf(&buf, "    val %s: %s\n", f.Name, f.KotlinType)
			}
		}
		buf.WriteString(")\n")
	}

	return buf.Bytes(), nil
}

// pgTypeToKotlin maps a column's PostgreSQL type to a Kotlin type string and
// returns any import paths needed.
func pgTypeToKotlin(col model.Column) (string, []string) {
	baseType, baseImports := pgBaseTypeToKotlin(col)
	return applyKotlinModifiers(baseType, baseImports, col), baseImports
}

// pgBaseTypeToKotlin returns the Kotlin type and imports for a column,
// ignoring array and nullable modifiers.
func pgBaseTypeToKotlin(col model.Column) (string, []string) {
	resolver := NewTypeResolver(LangKotlin)
	m := resolver.Resolve(col)
	if m.Import != "" {
		return m.Type, []string{m.Import}
	}
	return m.Type, nil
}

// applyKotlinModifiers applies array and nullable modifiers to a Kotlin type.
func applyKotlinModifiers(baseType string, imports []string, col model.Column) string {
	if col.Array && !col.NotNull {
		return "List<" + baseType + ">?"
	}
	if col.Array {
		return "List<" + baseType + ">"
	}
	if !col.NotNull {
		return baseType + "?"
	}
	return baseType
}
