package codegen

import (
	"strings"
	"testing"

	"github.com/smm-h/pgdesign/internal/diagnostic"
	"github.com/smm-h/pgdesign/internal/model"
	"github.com/smm-h/pgdesign/internal/sqlexpr"
)

func TestDetectExistsLookup(t *testing.T) {
	tests := []struct {
		name     string
		expr     string
		wantNil  bool
		wantLook string
		wantFlag string
	}{
		{
			name:     "chat_enabled with sender_id",
			expr:     "sender_id::text = current_setting('app.player_id') AND EXISTS (SELECT 1 FROM game.player_privacy_settings WHERE player_id = sender_id AND chat_enabled = true)",
			wantLook: "sender_id",
			wantFlag: "chat_enabled",
		},
		{
			name:     "friends_enabled with followed_id",
			expr:     "follower_id::text = current_setting('app.player_id') AND EXISTS (SELECT 1 FROM game.player_privacy_settings WHERE player_id = followed_id AND friends_enabled = true)",
			wantLook: "followed_id",
			wantFlag: "friends_enabled",
		},
		{
			name:     "qualified table reference",
			expr:     "player_id::text = current_setting('app.player_id') AND EXISTS (SELECT 1 FROM game.player_privacy_settings WHERE player_id = game_comment.player_id AND chat_enabled = true)",
			wantLook: "player_id",
			wantFlag: "chat_enabled",
		},
		{
			name:    "no privacy reference",
			expr:    "player_id::text = current_setting('app.player_id')",
			wantNil: true,
		},
		{
			name:    "read all",
			expr:    "true",
			wantNil: true,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			ast, err := sqlexpr.Parse(tt.expr)
			if err != nil {
				t.Fatalf("failed to parse expression: %v", err)
			}
			results := detectAllExistsLookups(ast)
			if tt.wantNil {
				if len(results) != 0 {
					t.Errorf("expected no results, got %d", len(results))
				}
				return
			}
			if len(results) == 0 {
				t.Fatal("expected at least one result")
			}
			if results[0].lookupColumn != tt.wantLook {
				t.Errorf("lookupColumn: expected %q, got %q", tt.wantLook, results[0].lookupColumn)
			}
			if results[0].flagColumn != tt.wantFlag {
				t.Errorf("flagColumn: expected %q, got %q", tt.wantFlag, results[0].flagColumn)
			}
		})
	}
}

func TestPythonGenerator_Generate(t *testing.T) {
	schema := &model.Schema{
		Name: "game",
		Tables: []model.Table{
			{
				Name:   "chat_messages",
				Schema: "game",
				Policies: []model.Policy{
					{
						Name:      "chat_read_all",
						Operation: "SELECT",
						Using:     "true",
					},
					{
						Name:         "chat_requires_enabled",
						Operation:    "INSERT",
						WithCheck:    "sender_id::text = current_setting('app.player_id') AND EXISTS (SELECT 1 FROM game.player_privacy_settings WHERE player_id = sender_id AND chat_enabled = true)",
						ErrorCode:    "chat_disabled",
						ErrorMessage: "Chat is disabled in your privacy settings",
					},
				},
			},
			{
				Name:   "follow",
				Schema: "game",
				Policies: []model.Policy{
					{
						Name:         "follow_requires_friends_enabled",
						Operation:    "INSERT",
						WithCheck:    "follower_id::text = current_setting('app.player_id') AND EXISTS (SELECT 1 FROM game.player_privacy_settings WHERE player_id = followed_id AND friends_enabled = true)",
						ErrorCode:    "target_friends_disabled",
						ErrorMessage: "This player has disabled friend/follow requests",
					},
				},
			},
		},
	}

	gen := &PythonGenerator{}
	out, diags := gen.Generate(schema)
	if len(diags) > 0 {
		t.Fatalf("unexpected diagnostics: %v", diags)
	}

	result := string(out)

	// Header checks.
	if !strings.Contains(result, "# Generated by pgdesign -- do not edit manually.") {
		t.Error("missing header comment")
	}
	if !strings.Contains(result, "# Regenerate with: pgdesign codegen --lang python <schema-files>") {
		t.Error("missing regenerate instruction in header")
	}
	if !strings.Contains(result, "class PolicyResult:") {
		t.Error("missing PolicyResult dataclass")
	}
	if !strings.Contains(result, "from dataclasses import dataclass") {
		t.Error("missing dataclass import")
	}

	// chat_requires_enabled validator.
	if !strings.Contains(result, "async def check_chat_requires_enabled(conn, sender_id: str) -> PolicyResult:") {
		t.Error("missing chat_requires_enabled function signature")
	}
	if !strings.Contains(result, "SELECT chat_enabled FROM game.player_privacy_settings WHERE player_id = $1") {
		t.Error("missing chat_enabled query")
	}
	if !strings.Contains(result, `code="chat_disabled"`) {
		t.Error("missing chat_disabled error code")
	}

	// follow_requires_friends_enabled validator.
	if !strings.Contains(result, "async def check_follow_requires_friends_enabled(conn, followed_id: str) -> PolicyResult:") {
		t.Error("missing follow_requires_friends_enabled function signature")
	}
	if !strings.Contains(result, "SELECT friends_enabled FROM game.player_privacy_settings WHERE player_id = $1") {
		t.Error("missing friends_enabled query")
	}
	if !strings.Contains(result, `code="target_friends_disabled"`) {
		t.Error("missing target_friends_disabled error code")
	}

	// Should NOT contain the read_all policy (no error code).
	if strings.Contains(result, "check_chat_read_all") {
		t.Error("should not generate validator for read_all policy")
	}
}

func TestPythonGenerator_NoPolicies(t *testing.T) {
	schema := &model.Schema{
		Name: "empty",
		Tables: []model.Table{
			{
				Name:   "items",
				Schema: "empty",
			},
		},
	}

	gen := &PythonGenerator{}
	out, diags := gen.Generate(schema)
	if len(diags) > 0 {
		t.Fatalf("unexpected diagnostics: %v", diags)
	}

	result := string(out)
	if !strings.Contains(result, "No generatable policies found") {
		t.Error("expected 'no generatable policies' message")
	}
}

func TestDetectOwnership(t *testing.T) {
	tests := []struct {
		name    string
		expr    string
		wantNil bool
		wantCol string
	}{
		{
			name:    "simple ownership",
			expr:    "player_id::text = current_setting('app.player_id')",
			wantCol: "player_id",
		},
		{
			name:    "compound with privacy ref - still detects ownership",
			expr:    "player_id::text = current_setting('app.player_id') AND EXISTS (SELECT 1 FROM game.player_privacy_settings WHERE player_id = sender_id AND chat_enabled = true)",
			wantCol: "player_id",
		},
		{
			name:    "no current_setting",
			expr:    "player_id = some_other_func()",
			wantNil: true,
		},
		{
			name:    "true",
			expr:    "true",
			wantNil: true,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			ast, err := sqlexpr.Parse(tt.expr)
			if err != nil {
				t.Fatalf("failed to parse expression: %v", err)
			}
			result := detectOwnership(ast)
			if tt.wantNil {
				if result != nil {
					t.Errorf("expected nil, got %+v", result)
				}
				return
			}
			if result == nil {
				t.Fatal("expected non-nil result")
			}
			if result.column != tt.wantCol {
				t.Errorf("column: expected %q, got %q", tt.wantCol, result.column)
			}
		})
	}
}

func TestDetectDualExistsLookup(t *testing.T) {
	tests := []struct {
		name       string
		expr       string
		wantCount  int // expected number of exists lookups (0 = none, 1 = single, 2+ = dual)
		wantFirst  privacyCheck
		wantSecond privacyCheck
	}{
		{
			name:      "two privacy references",
			expr:      "EXISTS (SELECT 1 FROM game.player_privacy_settings WHERE player_id = requester_id AND friends_enabled = true) AND EXISTS (SELECT 1 FROM game.player_privacy_settings WHERE player_id = target_id AND friends_enabled = true)",
			wantCount: 2,
			wantFirst: privacyCheck{
				lookupColumn: "requester_id",
				flagColumn:   "friends_enabled",
			},
			wantSecond: privacyCheck{
				lookupColumn: "target_id",
				flagColumn:   "friends_enabled",
			},
		},
		{
			name:      "single privacy reference",
			expr:      "EXISTS (SELECT 1 FROM game.player_privacy_settings WHERE player_id = sender_id AND chat_enabled = true)",
			wantCount: 1,
		},
		{
			name:      "no privacy reference",
			expr:      "player_id::text = current_setting('app.player_id')",
			wantCount: 0,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			ast, err := sqlexpr.Parse(tt.expr)
			if err != nil {
				t.Fatalf("failed to parse expression: %v", err)
			}
			results := detectAllExistsLookups(ast)
			if len(results) != tt.wantCount {
				t.Fatalf("expected %d exists lookups, got %d", tt.wantCount, len(results))
			}
			if tt.wantCount >= 2 {
				if results[0].lookupColumn != tt.wantFirst.lookupColumn {
					t.Errorf("first lookupColumn: expected %q, got %q", tt.wantFirst.lookupColumn, results[0].lookupColumn)
				}
				if results[0].flagColumn != tt.wantFirst.flagColumn {
					t.Errorf("first flagColumn: expected %q, got %q", tt.wantFirst.flagColumn, results[0].flagColumn)
				}
				if results[1].lookupColumn != tt.wantSecond.lookupColumn {
					t.Errorf("second lookupColumn: expected %q, got %q", tt.wantSecond.lookupColumn, results[1].lookupColumn)
				}
				if results[1].flagColumn != tt.wantSecond.flagColumn {
					t.Errorf("second flagColumn: expected %q, got %q", tt.wantSecond.flagColumn, results[1].flagColumn)
				}
			}
		})
	}
}

func TestPythonGenerator_OwnershipPattern(t *testing.T) {
	schema := &model.Schema{
		Name: "game",
		Tables: []model.Table{
			{
				Name:   "notification",
				Schema: "game",
				Policies: []model.Policy{
					{
						Name:         "notification_own_only",
						Operation:    "SELECT",
						Using:        "player_id::text = current_setting('app.player_id')",
						ErrorCode:    "not_owner",
						ErrorMessage: "You can only access your own notifications",
					},
				},
			},
		},
	}

	gen := &PythonGenerator{}
	out, diags := gen.Generate(schema)
	if len(diags) > 0 {
		t.Fatalf("unexpected diagnostics: %v", diags)
	}

	result := string(out)

	if !strings.Contains(result, "async def check_notification_own_only(conn, player_id: str, target_player_id: str) -> PolicyResult:") {
		t.Error("missing ownership function signature")
	}
	if !strings.Contains(result, "if player_id != target_player_id:") {
		t.Error("missing ownership comparison")
	}
	if !strings.Contains(result, `code="not_owner"`) {
		t.Error("missing not_owner error code")
	}
	// Ownership validators do not query the database.
	if strings.Contains(result, "fetchrow") {
		t.Error("ownership validator should not query the database")
	}
}

func TestPythonGenerator_DualPrivacyPattern(t *testing.T) {
	schema := &model.Schema{
		Name: "game",
		Tables: []model.Table{
			{
				Name:   "friendships",
				Schema: "game",
				Policies: []model.Policy{
					{
						Name:         "friendship_requires_friends_enabled",
						Operation:    "INSERT",
						WithCheck:    "EXISTS (SELECT 1 FROM game.player_privacy_settings WHERE player_id = requester_id AND friends_enabled = true) AND EXISTS (SELECT 1 FROM game.player_privacy_settings WHERE player_id = target_id AND friends_enabled = true)",
						ErrorCode:    "friends_disabled",
						ErrorMessage: "Friend requests require friends_enabled",
					},
				},
			},
		},
	}

	gen := &PythonGenerator{}
	out, diags := gen.Generate(schema)
	if len(diags) > 0 {
		t.Fatalf("unexpected diagnostics: %v", diags)
	}

	result := string(out)

	if !strings.Contains(result, "async def check_friendship_requires_friends_enabled(conn, requester_id: str, target_id: str) -> PolicyResult:") {
		t.Error("missing dual-privacy function signature")
	}
	// Should query twice.
	if strings.Count(result, "fetchrow") != 2 {
		t.Errorf("expected 2 fetchrow calls, got %d", strings.Count(result, "fetchrow"))
	}
	if !strings.Contains(result, `code="friends_disabled"`) {
		t.Error("missing friends_disabled error code")
	}
}

func TestPythonGenerator_UnparsableExpression(t *testing.T) {
	schema := &model.Schema{
		Name: "game",
		Tables: []model.Table{
			{
				Name:   "exotic",
				Schema: "game",
				Policies: []model.Policy{
					{
						Name:         "exotic_policy",
						Operation:    "INSERT",
						WithCheck:    "some_complex_expression(player_privacy_settings)",
						ErrorCode:    "exotic_error",
						ErrorMessage: "Exotic failure",
					},
				},
			},
		},
	}

	gen := &PythonGenerator{}
	out, diags := gen.Generate(schema)

	result := string(out)
	// The expression parses as a valid FuncCall but matches no generatable
	// pattern, so FilterGeneratable excludes it. With no generatable policies,
	// the output contains "No generatable policies found."
	if !strings.Contains(result, "No generatable policies found") {
		t.Error("expected 'No generatable policies found' message")
	}

	// Verify diagnostic was emitted by FilterGeneratable.
	if len(diags) != 1 {
		t.Fatalf("expected 1 diagnostic, got %d", len(diags))
	}
	if diags[0].Code != "C001" {
		t.Errorf("expected code C001, got %s", diags[0].Code)
	}
	if diags[0].Severity != diagnostic.Warning {
		t.Errorf("expected Warning severity, got %s", diags[0].Severity)
	}
}
