package codegen

import (
	"strings"
	"testing"

	"github.com/smm-h/pgdesign/internal/model"
)

// containsSAField checks that at least one line in s contains a SQLAlchemy
// mapped_column field declaration matching "    fieldName: Mapped[mappedType] = mapped_column(".
func containsSAField(s, fieldName, mappedType string) bool {
	target := "    " + fieldName + ": Mapped[" + mappedType + "] = mapped_column("
	return strings.Contains(s, target)
}

// containsSARel checks that at least one line contains a SQLAlchemy relationship
// field with the given field name and mapped type.
func containsSARel(s, fieldName, mappedType string) bool {
	target := "    " + fieldName + ": Mapped[" + mappedType + "] = relationship("
	return strings.Contains(s, target)
}

func TestPythonSQLAlchemyGenerator_Basic(t *testing.T) {
	schema := &model.Schema{
		Tables: []model.Table{
			{
				Name:    "users",
				Schema:  "public",
				Comment: "Application users",
				Columns: []model.Column{
					{Name: "id", PGType: "uuid", NotNull: true},
					{Name: "email", PGType: "text", NotNull: true},
					{Name: "score", PGType: "bigint", NotNull: true},
					{Name: "is_active", PGType: "boolean", NotNull: true},
					{Name: "created_at", PGType: "timestamptz", NotNull: true},
					{Name: "metadata", PGType: "jsonb", NotNull: true},
					{Name: "age", PGType: "integer", NotNull: true},
					{Name: "rating", PGType: "double precision", NotNull: true},
					{Name: "avatar", PGType: "bytea", NotNull: true},
					{Name: "balance", PGType: "numeric", NotNull: true},
				},
			},
		},
	}

	gen := &PythonSQLAlchemyGenerator{}
	out, diags := gen.Generate(schema)
	if len(diags) > 0 {
		t.Fatalf("unexpected diagnostics: %v", diags)
	}

	result := string(out)

	// Header.
	if !strings.Contains(result, "# Code generated by pgdesign -- do not edit.") {
		t.Error("missing generated header comment")
	}

	// Future annotations.
	if !strings.Contains(result, "from __future__ import annotations") {
		t.Error("missing future annotations import")
	}

	// Base class.
	if !strings.Contains(result, "class Base(DeclarativeBase):\n    pass") {
		t.Error("missing Base class declaration")
	}

	// Table class.
	if !strings.Contains(result, "class Users(Base):") {
		t.Error("missing Users class declaration")
	}
	if !strings.Contains(result, `__tablename__ = "users"`) {
		t.Error("missing __tablename__ for users")
	}

	// Column fields.
	if !containsSAField(result, "id", "uuid.UUID") {
		t.Error("missing or incorrect id field (expected uuid.UUID)")
	}
	if !containsSAField(result, "email", "str") {
		t.Error("missing or incorrect email field (expected str)")
	}
	if !containsSAField(result, "score", "int") {
		t.Error("missing or incorrect score field (expected int)")
	}
	if !containsSAField(result, "is_active", "bool") {
		t.Error("missing or incorrect is_active field (expected bool)")
	}
	if !containsSAField(result, "created_at", "datetime") {
		t.Error("missing or incorrect created_at field (expected datetime)")
	}
	if !containsSAField(result, "metadata", "dict[str, Any]") {
		t.Error("missing or incorrect metadata field (expected dict[str, Any])")
	}
	if !containsSAField(result, "age", "int") {
		t.Error("missing or incorrect age field (expected int)")
	}
	if !containsSAField(result, "rating", "float") {
		t.Error("missing or incorrect rating field (expected float)")
	}
	if !containsSAField(result, "avatar", "bytes") {
		t.Error("missing or incorrect avatar field (expected bytes)")
	}
	if !containsSAField(result, "balance", "Decimal") {
		t.Error("missing or incorrect balance field (expected Decimal)")
	}

	// ORM imports.
	if !strings.Contains(result, "from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship") {
		t.Error("missing ORM imports")
	}

	// Dialect imports should contain UUID.
	if !strings.Contains(result, "from sqlalchemy.dialects.postgresql import") {
		t.Error("missing dialect imports")
	}
	if !strings.Contains(result, "UUID") {
		t.Error("missing UUID in dialect imports")
	}

	// Stdlib imports.
	if !strings.Contains(result, "import uuid") {
		t.Error("missing uuid import")
	}
	if !strings.Contains(result, "from datetime import datetime") {
		t.Error("missing datetime import")
	}
	if !strings.Contains(result, "from decimal import Decimal") {
		t.Error("missing Decimal import")
	}
}

func TestPythonSQLAlchemyGenerator_NullableAndArray(t *testing.T) {
	schema := &model.Schema{
		Tables: []model.Table{
			{
				Name:    "items",
				Comment: "Test items",
				Columns: []model.Column{
					{Name: "id", PGType: "integer", NotNull: true},
					{Name: "name", PGType: "text", NotNull: false},
					{Name: "tags", PGType: "text", NotNull: true, Array: true},
					{Name: "scores", PGType: "integer", NotNull: false, Array: true},
					{Name: "status", PGType: "user_status", NotNull: true},
				},
			},
		},
	}

	gen := &PythonSQLAlchemyGenerator{}
	out, diags := gen.Generate(schema)
	if len(diags) > 0 {
		t.Fatalf("unexpected diagnostics: %v", diags)
	}

	result := string(out)

	// Not-null, not-array: plain type.
	if !containsSAField(result, "id", "int") {
		t.Error("missing or incorrect id field (expected int)")
	}

	// Nullable: Optional wrapper.
	if !containsSAField(result, "name", "Optional[str]") {
		t.Error("missing or incorrect name field (expected Optional[str])")
	}

	// Array: list wrapper.
	if !containsSAField(result, "tags", "list[str]") {
		t.Error("missing or incorrect tags field (expected list[str])")
	}

	// Nullable + array: Optional[list[...]].
	if !containsSAField(result, "scores", "Optional[list[int]]") {
		t.Error("missing or incorrect scores field (expected Optional[list[int]])")
	}

	// Enum (unrecognized PG type): str.
	if !containsSAField(result, "status", "str") {
		t.Error("missing or incorrect status field (expected str for enum)")
	}

	// Should have Optional in typing import.
	if !strings.Contains(result, "from typing import") || !strings.Contains(result, "Optional") {
		t.Error("missing Optional in typing import")
	}

	// Should not import datetime or uuid (not needed).
	if strings.Contains(result, "from datetime import datetime") {
		t.Error("unexpected datetime import")
	}
	if strings.Contains(result, "import uuid") {
		t.Error("unexpected uuid import")
	}
}

func TestPythonSQLAlchemyGenerator_EmptySchema(t *testing.T) {
	schema := &model.Schema{Tables: []model.Table{}}

	gen := &PythonSQLAlchemyGenerator{}
	out, diags := gen.Generate(schema)
	if len(diags) > 0 {
		t.Fatalf("unexpected diagnostics: %v", diags)
	}

	result := string(out)

	// Header must be present.
	if !strings.Contains(result, "# Code generated by pgdesign -- do not edit.") {
		t.Error("missing generated header comment")
	}

	// No classes.
	if strings.Contains(result, "class ") {
		t.Error("empty schema should not have class declarations")
	}

	// No imports.
	if strings.Contains(result, "import") {
		t.Error("empty schema should not have imports")
	}
}

func TestPythonSQLAlchemyGenerator_MoneySemanticType(t *testing.T) {
	schema := &model.Schema{
		Tables: []model.Table{
			{
				Name:    "products",
				Comment: "Products",
				Columns: []model.Column{
					{Name: "id", PGType: "integer", NotNull: true},
					{Name: "price", PGType: "bigint", NotNull: true, SemanticTypeName: "money"},
				},
			},
		},
	}

	gen := &PythonSQLAlchemyGenerator{}
	out, diags := gen.Generate(schema)
	if len(diags) > 0 {
		t.Fatalf("unexpected diagnostics: %v", diags)
	}

	result := string(out)

	// Money semantic type should map to int (Integer SA type).
	if !containsSAField(result, "price", "int") {
		t.Error("missing or incorrect price field (expected int for money semantic type)")
	}
}

func TestPythonSQLAlchemyGenerator_ForeignKeys(t *testing.T) {
	schema := &model.Schema{
		Tables: []model.Table{
			{
				Name:    "users",
				Comment: "Users",
				Columns: []model.Column{
					{Name: "id", PGType: "uuid", NotNull: true},
				},
				PK: []string{"id"},
			},
			{
				Name:    "orders",
				Comment: "Orders",
				Columns: []model.Column{
					{Name: "id", PGType: "uuid", NotNull: true},
					{Name: "user_id", PGType: "uuid", NotNull: true},
				},
				PK: []string{"id"},
				FKs: []model.FK{
					{
						Name:       "fk_orders_user",
						Columns:    []string{"user_id"},
						RefTable:   "users",
						RefColumns: []string{"id"},
						OnDelete:   "CASCADE",
					},
				},
			},
		},
	}

	gen := &PythonSQLAlchemyGenerator{}
	out, diags := gen.Generate(schema)
	if len(diags) > 0 {
		t.Fatalf("unexpected diagnostics: %v", diags)
	}

	result := string(out)

	// FK reference in the mapped_column.
	if !strings.Contains(result, `ForeignKey("users.id")`) {
		t.Error("missing ForeignKey reference in user_id column")
	}

	// ForeignKey in sqlalchemy imports.
	if !strings.Contains(result, "from sqlalchemy import") || !strings.Contains(result, "ForeignKey") {
		t.Error("missing ForeignKey in sqlalchemy imports")
	}

	// BelongsTo relationship on orders: user -> Users.
	if !containsSARel(result, "user", `"Users"`) {
		t.Error("missing belongs-to relationship on orders (user -> Users)")
	}

	// HasMany relationship on users: orders -> list[Orders].
	if !containsSARel(result, "orders", `list["Orders"]`) {
		t.Error("missing has-many relationship on users (orders -> list[Orders])")
	}

	// back_populates present.
	if !strings.Contains(result, "back_populates=") {
		t.Error("missing back_populates in relationships")
	}
}

func TestPythonSQLAlchemyGenerator_ServerDefault(t *testing.T) {
	schema := &model.Schema{
		Tables: []model.Table{
			{
				Name:    "events",
				Comment: "Events",
				Columns: []model.Column{
					{Name: "id", PGType: "uuid", NotNull: true, Default: model.StrPtr("gen_random_uuid()")},
					{Name: "created_at", PGType: "timestamptz", NotNull: true, Default: model.StrPtr("now()")},
				},
			},
		},
	}

	gen := &PythonSQLAlchemyGenerator{}
	out, diags := gen.Generate(schema)
	if len(diags) > 0 {
		t.Fatalf("unexpected diagnostics: %v", diags)
	}

	result := string(out)

	// Server defaults.
	if !strings.Contains(result, `server_default=text("gen_random_uuid()")`) {
		t.Error("missing server_default for gen_random_uuid()")
	}
	if !strings.Contains(result, `server_default=text("now()")`) {
		t.Error("missing server_default for now()")
	}

	// text must be in sqlalchemy imports.
	if !strings.Contains(result, "from sqlalchemy import") || !strings.Contains(result, "text") {
		t.Error("missing text in sqlalchemy imports")
	}
}

func TestPythonSQLAlchemyGenerator_MultipleTables(t *testing.T) {
	schema := &model.Schema{
		Tables: []model.Table{
			{
				Name:    "orders",
				Comment: "Orders",
				Columns: []model.Column{
					{Name: "id", PGType: "uuid", NotNull: true},
					{Name: "total", PGType: "numeric", NotNull: true},
				},
			},
			{
				Name:    "order_items",
				Comment: "Order items",
				Columns: []model.Column{
					{Name: "id", PGType: "integer", NotNull: true},
					{Name: "quantity", PGType: "smallint", NotNull: true},
				},
			},
		},
	}

	gen := &PythonSQLAlchemyGenerator{}
	out, diags := gen.Generate(schema)
	if len(diags) > 0 {
		t.Fatalf("unexpected diagnostics: %v", diags)
	}

	result := string(out)

	// Both class declarations present.
	if !strings.Contains(result, "class Orders(Base):") {
		t.Error("missing Orders class declaration")
	}
	if !strings.Contains(result, "class OrderItems(Base):") {
		t.Error("missing OrderItems class declaration")
	}

	// Tablenames.
	if !strings.Contains(result, `__tablename__ = "orders"`) {
		t.Error("missing __tablename__ for orders")
	}
	if !strings.Contains(result, `__tablename__ = "order_items"`) {
		t.Error("missing __tablename__ for order_items")
	}

	// Spot-check a field from the second table.
	if !containsSAField(result, "quantity", "int") {
		t.Error("missing or incorrect quantity field (expected int)")
	}
}
