package codegen

import (
	"bytes"
	"fmt"
	"sort"
	"strings"

	"github.com/smm-h/pgdesign/internal/diagnostic"
	"github.com/smm-h/pgdesign/internal/model"
)

// PythonQueryLayerGenerator generates Python protocol definitions and row
// dataclasses for a type-safe query layer. It produces multiple files:
// protocols.py contains context types, row dataclasses, and Reader/Writer/Backend
// protocols with methods derived from the schema's tables, FKs, uniques, and
// state machine transitions.
type PythonQueryLayerGenerator struct {
	// Backends controls which backend implementations to generate.
	// Valid values: "pg", "memory". When empty, both backends are generated.
	Backends []string
}

// Generate satisfies the Generator interface. For single-file output it
// concatenates all generated files separated by headers.
func (g *PythonQueryLayerGenerator) Generate(schema *model.Schema) ([]byte, []diagnostic.Diagnostic) {
	files, diags := g.GenerateFiles(schema)
	if len(files) == 0 {
		return nil, diags
	}
	var buf bytes.Buffer
	for _, name := range sortedKeys(files) {
		fmt.Fprintf(&buf, "# === %s ===\n", name)
		buf.Write(files[name])
		buf.WriteString("\n")
	}
	return buf.Bytes(), diags
}

// GenerateFiles satisfies the MultiFileGenerator interface. It returns a map
// of relative file paths to their contents.
func (g *PythonQueryLayerGenerator) GenerateFiles(schema *model.Schema) (map[string][]byte, []diagnostic.Diagnostic) {
	files := make(map[string][]byte)
	var diags []diagnostic.Diagnostic

	wantPg := g.wantBackend("pg")
	wantMem := g.wantBackend("memory")

	protocols, protoDiags := generateProtocolsFile(schema)
	diags = append(diags, protoDiags...)
	files["protocols.py"] = protocols

	// _constraints.py is always generated -- it is needed by the memory backend
	// but is also useful as a standalone constraint introspection module.
	files["_constraints.py"] = generateConstraintsFile(schema)

	tables := schema.TableOrder()
	if len(tables) == 0 {
		files["__init__.py"] = generateInitFile(schema, wantPg, wantMem)
		return files, diags
	}

	smMap := buildSMTypeMap(schema)

	if wantPg {
		// Per-table PG delegate files.
		for _, tbl := range tables {
			fileName := fmt.Sprintf("_%s_pg.py", tbl.Name)
			files[fileName] = generatePerTablePgFile(&tbl, schema, smMap)
		}

		// Composite PgBackend file.
		files["pg_backend.py"] = generatePgBackendFile(tables, schema, smMap)
	}

	if wantMem {
		// Per-table InMemory delegate files.
		for _, tbl := range tables {
			fileName := fmt.Sprintf("_%s_mem.py", tbl.Name)
			files[fileName] = generatePerTableMemFile(&tbl, schema, smMap)
		}

		// Composite InMemoryBackend file.
		files["memory_backend.py"] = generateMemoryBackendFile(tables, schema, smMap)
	}

	// __init__.py barrel file.
	files["__init__.py"] = generateInitFile(schema, wantPg, wantMem)

	return files, diags
}

// wantBackend returns true if the given backend name should be generated.
// When Backends is empty, both backends are generated.
func (g *PythonQueryLayerGenerator) wantBackend(name string) bool {
	if len(g.Backends) == 0 {
		return true
	}
	for _, b := range g.Backends {
		if b == name {
			return true
		}
	}
	return false
}

// generateInitFile produces __init__.py with re-exports for the generated package.
func generateInitFile(schema *model.Schema, wantPg, wantMem bool) []byte {
	var buf bytes.Buffer

	buf.WriteString("# Generated by pgdesign -- do not edit manually.\n")
	buf.WriteString("# Regenerate with: pgdesign codegen --lang python --mode query-layer <schema-files>\n")

	tables := schema.TableOrder()

	// Always export Backend protocol and Row types from protocols.
	var protoImports []string
	protoImports = append(protoImports, "Backend")
	for _, tbl := range tables {
		protoImports = append(protoImports, toPascalCase(tbl.Name)+"Row")
	}
	// Sort for deterministic output (Backend first, then rows alphabetically).
	sort.Strings(protoImports[1:])
	fmt.Fprintf(&buf, "\nfrom .protocols import %s\n", strings.Join(protoImports, ", "))

	if wantPg && len(tables) > 0 {
		buf.WriteString("from .pg_backend import PgBackend\n")
	}
	if wantMem && len(tables) > 0 {
		buf.WriteString("from .memory_backend import InMemoryBackend\n")
	}

	// __all__ for explicit re-export.
	var allItems []string
	allItems = append(allItems, `"Backend"`)
	for _, tbl := range tables {
		allItems = append(allItems, fmt.Sprintf("%q", toPascalCase(tbl.Name)+"Row"))
	}
	if wantPg && len(tables) > 0 {
		allItems = append(allItems, `"PgBackend"`)
	}
	if wantMem && len(tables) > 0 {
		allItems = append(allItems, `"InMemoryBackend"`)
	}
	sort.Strings(allItems)
	fmt.Fprintf(&buf, "\n__all__ = [\n")
	for _, item := range allItems {
		fmt.Fprintf(&buf, "    %s,\n", item)
	}
	buf.WriteString("]\n")

	return buf.Bytes()
}

// generateProtocolsFile produces the protocols.py file content.
func generateProtocolsFile(schema *model.Schema) ([]byte, []diagnostic.Diagnostic) {
	var buf bytes.Buffer
	var diags []diagnostic.Diagnostic

	tables := schema.TableOrder()

	// Collect imports needed across all tables.
	imports := newImportCollector()

	// Pre-scan all columns to determine imports.
	resolver := NewTypeResolver(LangPython)
	for _, tbl := range tables {
		for _, col := range tbl.Columns {
			m := resolver.Resolve(col)
			imports.addFromMapping(m, col)
		}
	}

	// SM transitions may have requires params with PG types.
	smMap := buildSMTypeMap(schema)
	for _, tbl := range tables {
		for _, col := range tbl.Columns {
			if smt, ok := smMap[col.SemanticTypeName]; ok {
				for _, nt := range smt.NamedTransitions {
					for _, pgType := range sortedMapKeys(nt.Requires) {
						m := LookupType(nt.Requires[pgType], LangPython)
						imports.addFromType(m)
					}
				}
			}
		}
	}

	// Write header.
	buf.WriteString("# Generated by pgdesign -- do not edit manually.\n")
	buf.WriteString("# Regenerate with: pgdesign codegen --lang python --mode query-layer <schema-files>\n")

	// Write imports.
	buf.WriteString("\nfrom __future__ import annotations\n")
	buf.WriteString("\nfrom dataclasses import dataclass, field\n")
	buf.WriteString("from typing import Any, Optional, Protocol\n")

	if imports.needs["datetime"] {
		buf.WriteString("from datetime import datetime\n")
	}
	if imports.needs["Decimal"] {
		buf.WriteString("from decimal import Decimal\n")
	}
	if imports.needs["UUID"] {
		buf.WriteString("from uuid import UUID\n")
	}

	// Context types.
	buf.WriteString("\n\n# --- Context Types ---\n")
	buf.WriteString("\n\n@dataclass\nclass PgContext:\n")
	buf.WriteString("    pool: Any  # asyncpg.Pool\n")
	buf.WriteString("\n\n@dataclass\nclass InMemoryContext:\n")
	buf.WriteString("    stores: dict[str, dict] = field(default_factory=dict)\n")
	buf.WriteString("    unique_indexes: dict[str, dict] = field(default_factory=dict)\n")

	if len(tables) == 0 {
		return buf.Bytes(), diags
	}

	// Row dataclasses.
	buf.WriteString("\n\n# --- Row Dataclasses ---\n")
	for _, tbl := range tables {
		writeRowDataclass(&buf, &tbl)
	}

	// Per-table Writer protocols.
	buf.WriteString("\n\n# --- Writer Protocols ---\n")
	for _, tbl := range tables {
		writeWriterProtocol(&buf, &tbl, smMap)
	}

	// Per-table Reader protocols.
	buf.WriteString("\n\n# --- Reader Protocols ---\n")
	for _, tbl := range tables {
		writeReaderProtocol(&buf, &tbl, schema.FKGraph)
	}

	// Combined Backend protocol.
	buf.WriteString("\n\n# --- Combined Backend Protocol ---\n")
	writeBackendProtocol(&buf, tables, smMap, schema.FKGraph)

	return buf.Bytes(), diags
}

// --- Import tracking ---

type importCollector struct {
	needs map[string]bool
}

func newImportCollector() *importCollector {
	return &importCollector{needs: make(map[string]bool)}
}

func (ic *importCollector) addFromMapping(m TypeMapping, col model.Column) {
	ic.addFromType(m)
	if !col.NotNull {
		ic.needs["Optional"] = true
	}
}

func (ic *importCollector) addFromType(m TypeMapping) {
	if m.Import != "" {
		ic.needs[m.Import] = true
	}
}

// --- Row dataclass ---

func writeRowDataclass(buf *bytes.Buffer, tbl *model.Table) {
	className := toPascalCase(tbl.Name)
	buf.WriteString("\n\n@dataclass\n")
	fmt.Fprintf(buf, "class %sRow:\n", className)
	fmt.Fprintf(buf, "    \"\"\"Row type for the %s table.\"\"\"\n", tbl.Name)

	for _, col := range tbl.Columns {
		pyType := columnPythonType(col)
		fmt.Fprintf(buf, "    %s: %s\n", col.Name, pyType)
	}
}

// --- Writer protocol ---

func writeWriterProtocol(buf *bytes.Buffer, tbl *model.Table, smMap map[string]*model.SMTransitionMap) {
	className := toPascalCase(tbl.Name)
	buf.WriteString("\n\n")
	fmt.Fprintf(buf, "class %sWriter(Protocol):\n", className)

	// create method
	writeCreateMethod(buf, tbl)

	// update method (skip if append-only)
	if !tbl.AppendOnly {
		writeUpdateMethod(buf, tbl)
	}

	// delete method (skip if append-only)
	if !tbl.AppendOnly {
		writeDeleteMethod(buf, tbl)
	}

	// SM transition methods
	writeSMTransitionMethods(buf, tbl, smMap)
}

func writeCreateMethod(buf *bytes.Buffer, tbl *model.Table) {
	pkCols := pkColumns(tbl)
	if len(pkCols) == 0 {
		return
	}

	// Determine writable columns: exclude PK with Identity or DefaultExpr,
	// Generated columns, and Identity columns.
	var required []model.Column
	var optional []model.Column

	for _, col := range tbl.Columns {
		if isAutoColumn(col, tbl.PK) {
			continue
		}
		if col.Generated != "" {
			continue
		}
		if col.Identity != "" {
			continue
		}

		// Required = NOT NULL without Default.
		// Optional = nullable or has Default.
		hasDefault := col.Default != nil || col.DefaultExpr != ""
		if col.NotNull && !hasDefault {
			required = append(required, col)
		} else {
			optional = append(optional, col)
		}
	}

	// Return type is the PK type.
	returnType := pkReturnType(tbl)

	fmt.Fprintf(buf, "\n    async def create_%s(\n        self,\n        *,\n", tbl.Name)
	for _, col := range required {
		pyType := columnPythonType(col)
		fmt.Fprintf(buf, "        %s: %s,\n", col.Name, pyType)
	}
	for _, col := range optional {
		pyType := baseColumnPythonType(col)
		optType := ApplyNullable(pyType, LangPython)
		fmt.Fprintf(buf, "        %s: %s = None,\n", col.Name, optType)
	}
	fmt.Fprintf(buf, "    ) -> %s: ...\n", returnType)
}

func writeUpdateMethod(buf *bytes.Buffer, tbl *model.Table) {
	pkCols := pkColumns(tbl)
	if len(pkCols) == 0 {
		return
	}

	fmt.Fprintf(buf, "\n    async def update_%s(\n        self,\n", tbl.Name)

	// PK as positional params.
	for _, col := range pkCols {
		pyType := columnPythonType(col)
		fmt.Fprintf(buf, "        %s: %s,\n", col.Name, pyType)
	}
	buf.WriteString("        *,\n")

	// All writable columns as Optional[T] = None.
	for _, col := range tbl.Columns {
		if isPKColumn(col.Name, tbl.PK) {
			continue
		}
		if col.Generated != "" {
			continue
		}
		if col.Identity != "" {
			continue
		}
		pyType := baseColumnPythonType(col)
		optType := ApplyNullable(pyType, LangPython)
		fmt.Fprintf(buf, "        %s: %s = None,\n", col.Name, optType)
	}
	buf.WriteString("    ) -> None: ...\n")
}

func writeDeleteMethod(buf *bytes.Buffer, tbl *model.Table) {
	pkCols := pkColumns(tbl)
	if len(pkCols) == 0 {
		return
	}

	fmt.Fprintf(buf, "\n    async def delete_%s(\n        self,\n", tbl.Name)
	for _, col := range pkCols {
		pyType := columnPythonType(col)
		fmt.Fprintf(buf, "        %s: %s,\n", col.Name, pyType)
	}
	buf.WriteString("    ) -> bool: ...\n")
}

func writeSMTransitionMethods(buf *bytes.Buffer, tbl *model.Table, smMap map[string]*model.SMTransitionMap) {
	pkCols := pkColumns(tbl)
	if len(pkCols) == 0 {
		return
	}

	for _, col := range tbl.Columns {
		smt, ok := smMap[col.SemanticTypeName]
		if !ok {
			continue
		}
		for _, nt := range smt.NamedTransitions {
			fmt.Fprintf(buf, "\n    async def %s_%s(\n        self,\n", nt.Name, tbl.Name)
			// PK as positional params.
			for _, pkCol := range pkCols {
				pyType := columnPythonType(pkCol)
				fmt.Fprintf(buf, "        %s: %s,\n", pkCol.Name, pyType)
			}

			if len(nt.Requires) > 0 {
				buf.WriteString("        *,\n")
				for _, paramName := range sortedMapKeys(nt.Requires) {
					pgType := nt.Requires[paramName]
					m := LookupType(pgType, LangPython)
					fmt.Fprintf(buf, "        %s: %s,\n", paramName, m.Type)
				}
			}
			buf.WriteString("    ) -> None: ...\n")
		}
	}
}

// --- Reader protocol ---

func writeReaderProtocol(buf *bytes.Buffer, tbl *model.Table, fkGraph *model.FKGraph) {
	className := toPascalCase(tbl.Name)
	rowType := className + "Row"
	buf.WriteString("\n\n")
	fmt.Fprintf(buf, "class %sReader(Protocol):\n", className)

	// get_<table>: PK params -> Optional[Row]
	pkCols := pkColumns(tbl)
	if len(pkCols) > 0 {
		fmt.Fprintf(buf, "\n    async def get_%s(\n        self,\n", tbl.Name)
		for _, col := range pkCols {
			pyType := columnPythonType(col)
			fmt.Fprintf(buf, "        %s: %s,\n", col.Name, pyType)
		}
		fmt.Fprintf(buf, "    ) -> Optional[%s]: ...\n", rowType)
	}

	// get_<table>_by_<fk_col>: one per incoming FK (single-column only)
	if fkGraph != nil {
		// Collect and deduplicate incoming FK edges.
		type fkByMethod struct {
			colName string
			pyType  string
		}
		seen := make(map[string]bool)
		var fkMethods []fkByMethod

		for _, edge := range fkGraph.Reverse[tbl.Name] {
			// Only single-column FKs.
			methodName := edge.FromColumn
			if seen[methodName] {
				continue
			}
			seen[methodName] = true

			// Use the target column on this table to determine type.
			pyType := "Any"
			if toCol := qlFindColumn(tbl, edge.ToColumn); toCol != nil {
				pyType = columnPythonType(*toCol)
			}

			fkMethods = append(fkMethods, fkByMethod{colName: methodName, pyType: pyType})
		}

		// Sort for deterministic output.
		sort.Slice(fkMethods, func(i, j int) bool {
			return fkMethods[i].colName < fkMethods[j].colName
		})

		for _, fm := range fkMethods {
			fmt.Fprintf(buf, "\n    async def get_%s_by_%s(\n        self,\n        %s: %s,\n    ) -> list[%s]: ...\n",
				tbl.Name, fm.colName, fm.colName, fm.pyType, rowType)
		}
	}

	// get_<table>_by_<unique_cols>: one per UniqueConstraint
	for _, uq := range tbl.Uniques {
		suffix := strings.Join(uq.Columns, "_")
		fmt.Fprintf(buf, "\n    async def get_%s_by_%s(\n        self,\n", tbl.Name, suffix)
		for _, colName := range uq.Columns {
			col := qlFindColumn(tbl, colName)
			if col != nil {
				pyType := columnPythonType(*col)
				fmt.Fprintf(buf, "        %s: %s,\n", colName, pyType)
			} else {
				fmt.Fprintf(buf, "        %s: Any,\n", colName)
			}
		}
		fmt.Fprintf(buf, "    ) -> Optional[%s]: ...\n", rowType)
	}

	// list_<table>: limit, offset -> list[Row]
	fmt.Fprintf(buf, "\n    async def list_%s(\n        self,\n        limit: int = 100,\n        offset: int = 0,\n    ) -> list[%s]: ...\n",
		tbl.Name, rowType)
}

// --- Backend protocol ---

func writeBackendProtocol(buf *bytes.Buffer, tables []model.Table, smMap map[string]*model.SMTransitionMap, fkGraph *model.FKGraph) {
	buf.WriteString("\n\nclass Backend(Protocol):\n")
	buf.WriteString("    \"\"\"Combined protocol declaring all Reader and Writer methods.\"\"\"\n")

	for _, tbl := range tables {
		// Writer methods
		writeCreateMethodForBackend(buf, &tbl)
		if !tbl.AppendOnly {
			writeUpdateMethodForBackend(buf, &tbl)
			writeDeleteMethodForBackend(buf, &tbl)
		}
		writeSMTransitionMethodsForBackend(buf, &tbl, smMap)

		// Reader methods
		writeReaderMethodsForBackend(buf, &tbl, fkGraph)
	}
}

// Backend versions of write methods (same signature, on Backend class).

func writeCreateMethodForBackend(buf *bytes.Buffer, tbl *model.Table) {
	pkCols := pkColumns(tbl)
	if len(pkCols) == 0 {
		return
	}

	var required []model.Column
	var optional []model.Column

	for _, col := range tbl.Columns {
		if isAutoColumn(col, tbl.PK) {
			continue
		}
		if col.Generated != "" {
			continue
		}
		if col.Identity != "" {
			continue
		}
		hasDefault := col.Default != nil || col.DefaultExpr != ""
		if col.NotNull && !hasDefault {
			required = append(required, col)
		} else {
			optional = append(optional, col)
		}
	}

	returnType := pkReturnType(tbl)

	fmt.Fprintf(buf, "\n    async def create_%s(\n        self,\n        *,\n", tbl.Name)
	for _, col := range required {
		pyType := columnPythonType(col)
		fmt.Fprintf(buf, "        %s: %s,\n", col.Name, pyType)
	}
	for _, col := range optional {
		pyType := baseColumnPythonType(col)
		optType := ApplyNullable(pyType, LangPython)
		fmt.Fprintf(buf, "        %s: %s = None,\n", col.Name, optType)
	}
	fmt.Fprintf(buf, "    ) -> %s: ...\n", returnType)
}

func writeUpdateMethodForBackend(buf *bytes.Buffer, tbl *model.Table) {
	pkCols := pkColumns(tbl)
	if len(pkCols) == 0 {
		return
	}

	fmt.Fprintf(buf, "\n    async def update_%s(\n        self,\n", tbl.Name)
	for _, col := range pkCols {
		pyType := columnPythonType(col)
		fmt.Fprintf(buf, "        %s: %s,\n", col.Name, pyType)
	}
	buf.WriteString("        *,\n")
	for _, col := range tbl.Columns {
		if isPKColumn(col.Name, tbl.PK) {
			continue
		}
		if col.Generated != "" {
			continue
		}
		if col.Identity != "" {
			continue
		}
		pyType := baseColumnPythonType(col)
		optType := ApplyNullable(pyType, LangPython)
		fmt.Fprintf(buf, "        %s: %s = None,\n", col.Name, optType)
	}
	buf.WriteString("    ) -> None: ...\n")
}

func writeDeleteMethodForBackend(buf *bytes.Buffer, tbl *model.Table) {
	pkCols := pkColumns(tbl)
	if len(pkCols) == 0 {
		return
	}

	fmt.Fprintf(buf, "\n    async def delete_%s(\n        self,\n", tbl.Name)
	for _, col := range pkCols {
		pyType := columnPythonType(col)
		fmt.Fprintf(buf, "        %s: %s,\n", col.Name, pyType)
	}
	buf.WriteString("    ) -> bool: ...\n")
}

func writeSMTransitionMethodsForBackend(buf *bytes.Buffer, tbl *model.Table, smMap map[string]*model.SMTransitionMap) {
	pkCols := pkColumns(tbl)
	if len(pkCols) == 0 {
		return
	}

	for _, col := range tbl.Columns {
		smt, ok := smMap[col.SemanticTypeName]
		if !ok {
			continue
		}
		for _, nt := range smt.NamedTransitions {
			fmt.Fprintf(buf, "\n    async def %s_%s(\n        self,\n", nt.Name, tbl.Name)
			for _, pkCol := range pkCols {
				pyType := columnPythonType(pkCol)
				fmt.Fprintf(buf, "        %s: %s,\n", pkCol.Name, pyType)
			}
			if len(nt.Requires) > 0 {
				buf.WriteString("        *,\n")
				for _, paramName := range sortedMapKeys(nt.Requires) {
					pgType := nt.Requires[paramName]
					m := LookupType(pgType, LangPython)
					fmt.Fprintf(buf, "        %s: %s,\n", paramName, m.Type)
				}
			}
			buf.WriteString("    ) -> None: ...\n")
		}
	}
}

func writeReaderMethodsForBackend(buf *bytes.Buffer, tbl *model.Table, fkGraph *model.FKGraph) {
	className := toPascalCase(tbl.Name)
	rowType := className + "Row"

	// get_<table>
	pkCols := pkColumns(tbl)
	if len(pkCols) > 0 {
		fmt.Fprintf(buf, "\n    async def get_%s(\n        self,\n", tbl.Name)
		for _, col := range pkCols {
			pyType := columnPythonType(col)
			fmt.Fprintf(buf, "        %s: %s,\n", col.Name, pyType)
		}
		fmt.Fprintf(buf, "    ) -> Optional[%s]: ...\n", rowType)
	}

	// get_<table>_by_<fk_col>
	if fkGraph != nil {
		type fkByMethod struct {
			colName string
			pyType  string
		}
		seen := make(map[string]bool)
		var fkMethods []fkByMethod

		for _, edge := range fkGraph.Reverse[tbl.Name] {
			methodName := edge.FromColumn
			if seen[methodName] {
				continue
			}
			seen[methodName] = true

			pyType := "Any"
			if toCol := qlFindColumn(tbl, edge.ToColumn); toCol != nil {
				pyType = columnPythonType(*toCol)
			}

			fkMethods = append(fkMethods, fkByMethod{colName: methodName, pyType: pyType})
		}

		sort.Slice(fkMethods, func(i, j int) bool {
			return fkMethods[i].colName < fkMethods[j].colName
		})

		for _, fm := range fkMethods {
			fmt.Fprintf(buf, "\n    async def get_%s_by_%s(\n        self,\n        %s: %s,\n    ) -> list[%s]: ...\n",
				tbl.Name, fm.colName, fm.colName, fm.pyType, rowType)
		}
	}

	// get_<table>_by_<unique_cols>
	for _, uq := range tbl.Uniques {
		suffix := strings.Join(uq.Columns, "_")
		fmt.Fprintf(buf, "\n    async def get_%s_by_%s(\n        self,\n", tbl.Name, suffix)
		for _, colName := range uq.Columns {
			col := qlFindColumn(tbl, colName)
			if col != nil {
				pyType := columnPythonType(*col)
				fmt.Fprintf(buf, "        %s: %s,\n", colName, pyType)
			} else {
				fmt.Fprintf(buf, "        %s: Any,\n", colName)
			}
		}
		fmt.Fprintf(buf, "    ) -> Optional[%s]: ...\n", rowType)
	}

	// list_<table>
	fmt.Fprintf(buf, "\n    async def list_%s(\n        self,\n        limit: int = 100,\n        offset: int = 0,\n    ) -> list[%s]: ...\n",
		tbl.Name, rowType)
}

// --- Helpers ---

// buildSMTypeMap creates a lookup from semantic type name to its SMTransitionMap.
func buildSMTypeMap(schema *model.Schema) map[string]*model.SMTransitionMap {
	m := make(map[string]*model.SMTransitionMap, len(schema.StateMachineTransitions))
	for i := range schema.StateMachineTransitions {
		smt := &schema.StateMachineTransitions[i]
		m[smt.TypeName] = smt
	}
	return m
}

// baseColumnPythonType returns the Python type for a column without nullable
// wrapping. Used for method parameters where Optional is applied separately.
func baseColumnPythonType(col model.Column) string {
	resolver := NewTypeResolver(LangPython)
	baseType := resolver.Resolve(col).Type
	if col.Array {
		baseType = ApplyArray(baseType, LangPython)
	}
	return baseType
}

// columnPythonType returns the Python type string for a column, applying
// nullable and array modifiers.
func columnPythonType(col model.Column) string {
	resolver := NewTypeResolver(LangPython)
	baseType := resolver.Resolve(col).Type

	if col.Array {
		baseType = ApplyArray(baseType, LangPython)
	}
	if !col.NotNull {
		baseType = ApplyNullable(baseType, LangPython)
	}
	return baseType
}

// pkColumns returns the Column objects for the table's primary key.
func pkColumns(tbl *model.Table) []model.Column {
	var result []model.Column
	for _, pkName := range tbl.PK {
		for _, col := range tbl.Columns {
			if col.Name == pkName {
				result = append(result, col)
				break
			}
		}
	}
	return result
}

// isPKColumn checks if a column name is part of the table's primary key.
func isPKColumn(name string, pk []string) bool {
	for _, p := range pk {
		if p == name {
			return true
		}
	}
	return false
}

// isAutoColumn returns true if the column is a PK column with Identity or
// DefaultExpr set (auto-generated values that should be excluded from create params).
func isAutoColumn(col model.Column, pk []string) bool {
	if !isPKColumn(col.Name, pk) {
		return false
	}
	return col.Identity != "" || col.DefaultExpr != ""
}

// pkReturnType returns the Python type for the table's PK. For single-column
// PKs it's the column type; for composite PKs it's a tuple.
func pkReturnType(tbl *model.Table) string {
	pkCols := pkColumns(tbl)
	if len(pkCols) == 1 {
		return columnPythonType(pkCols[0])
	}
	var parts []string
	for _, col := range pkCols {
		parts = append(parts, columnPythonType(col))
	}
	return "tuple[" + strings.Join(parts, ", ") + "]"
}

// qlFindColumn finds a column by name in a table. Separate from java_jpa's
// findColumn to accept a pointer receiver.
func qlFindColumn(tbl *model.Table, name string) *model.Column {
	for i := range tbl.Columns {
		if tbl.Columns[i].Name == name {
			return &tbl.Columns[i]
		}
	}
	return nil
}

// sortedMapKeys returns the keys of a map[string]string in sorted order.
func sortedMapKeys(m map[string]string) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}
