package codegen

import (
	"bytes"
	"fmt"
	"sort"
	"strings"

	"github.com/smm-h/pgdesign/internal/model"
)

// generatePerTableMemFile produces a _<table>_mem.py file for a single table.
// The file contains a class <PascalCase>Mem that implements the table's Writer
// and Reader protocol methods using in-memory dict stores with constraint
// validation via ConstraintEngine.
func generatePerTableMemFile(tbl *model.Table, schema *model.Schema, smMap map[string]*model.SMTransitionMap) []byte {
	var buf bytes.Buffer
	className := toPascalCase(tbl.Name)
	rowType := className + "Row"

	// Collect imports.
	imports := newImportCollector()
	for _, col := range tbl.Columns {
		m := LookupType(col.PGType, LangPython)
		imports.addFromMapping(m, col)
	}
	for _, col := range tbl.Columns {
		if smt, ok := smMap[col.SemanticTypeName]; ok {
			for _, nt := range smt.NamedTransitions {
				for _, pgType := range sortedMapKeys(nt.Requires) {
					m := LookupType(nt.Requires[pgType], LangPython)
					imports.addFromType(m)
				}
			}
		}
	}

	// Header.
	buf.WriteString("# Generated by pgdesign -- do not edit manually.\n")
	buf.WriteString("# Regenerate with: pgdesign codegen --lang python --mode query-layer <schema-files>\n")

	// Imports.
	buf.WriteString("\nfrom __future__ import annotations\n")
	buf.WriteString("\nfrom typing import Any, Optional\n")

	if imports.needs["datetime"] {
		buf.WriteString("from datetime import datetime\n")
	}
	if imports.needs["Decimal"] {
		buf.WriteString("from decimal import Decimal\n")
	}
	if imports.needs["UUID"] {
		buf.WriteString("from uuid import UUID\n")
	}

	// Need uuid4 for auto-generated UUID PKs.
	pkCols := pkColumns(tbl)
	needsUUID4 := false
	for _, col := range pkCols {
		if isAutoColumn(col, tbl.PK) && col.PGType == "uuid" {
			needsUUID4 = true
			break
		}
	}
	if needsUUID4 && !imports.needs["UUID"] {
		buf.WriteString("from uuid import UUID\n")
	}
	if needsUUID4 {
		buf.WriteString("from uuid import uuid4\n")
	}

	fmt.Fprintf(&buf, "\nfrom .protocols import InMemoryContext, %s\n", rowType)

	// Import constraints.
	constraintVar := strings.ToUpper(tbl.Name) + "_CONSTRAINTS"
	// Always import ALL_CONSTRAINTS for delete cascade processing.
	fmt.Fprintf(&buf, "from ._constraints import ALL_CONSTRAINTS, ConstraintEngine, %s\n", constraintVar)

	// Class.
	fmt.Fprintf(&buf, "\n\nclass %sMem:\n", className)
	fmt.Fprintf(&buf, "    \"\"\"In-memory delegate for the %s table.\"\"\"\n", tbl.Name)
	buf.WriteString("\n    def __init__(self, ctx: InMemoryContext) -> None:\n")
	buf.WriteString("        self._ctx = ctx\n")
	fmt.Fprintf(&buf, "        self._ctx.stores.setdefault(%q, {})\n", tbl.Name)

	// Initialize unique indexes for this table.
	for _, uq := range tbl.Uniques {
		idxName := fmt.Sprintf("%s_%s", tbl.Name, strings.Join(uq.Columns, "_"))
		fmt.Fprintf(&buf, "        self._ctx.unique_indexes.setdefault(%q, {})\n", idxName)
	}

	// create method.
	writeMemCreateMethod(&buf, tbl, smMap)

	// get method.
	writeMemGetMethod(&buf, tbl, rowType)

	// update method (skip if append-only).
	if !tbl.AppendOnly {
		writeMemUpdateMethod(&buf, tbl, smMap)
	}

	// delete method (skip if append-only).
	if !tbl.AppendOnly {
		writeMemDeleteMethod(&buf, tbl)
	}

	// get_by_fk methods.
	writeMemGetByFKMethods(&buf, tbl, schema.FKGraph, rowType)

	// get_by_unique methods.
	writeMemGetByUniqueMethods(&buf, tbl, rowType)

	// list method.
	writeMemListMethod(&buf, tbl, rowType)

	// SM transition methods.
	writeMemSMTransitionMethods(&buf, tbl, smMap)

	return buf.Bytes()
}

// writeMemCreateMethod generates the in-memory create method with PK generation
// and constraint validation.
func writeMemCreateMethod(buf *bytes.Buffer, tbl *model.Table, smMap map[string]*model.SMTransitionMap) {
	pkCols := pkColumns(tbl)
	if len(pkCols) == 0 {
		return
	}

	var required []model.Column
	var optional []model.Column
	for _, col := range tbl.Columns {
		if isAutoColumn(col, tbl.PK) {
			continue
		}
		if col.Generated != "" {
			continue
		}
		if col.Identity != "" {
			continue
		}
		hasDefault := col.Default != nil || col.DefaultExpr != ""
		if col.NotNull && !hasDefault {
			required = append(required, col)
		} else {
			optional = append(optional, col)
		}
	}

	returnType := pkReturnType(tbl)
	constraintVar := strings.ToUpper(tbl.Name) + "_CONSTRAINTS"

	// Method signature.
	fmt.Fprintf(buf, "\n    async def create_%s(\n        self,\n        *,\n", tbl.Name)
	for _, col := range required {
		pyType := columnPythonType(col)
		fmt.Fprintf(buf, "        %s: %s,\n", col.Name, pyType)
	}
	for _, col := range optional {
		pyType := baseColumnPythonType(col)
		optType := ApplyNullable(pyType, LangPython)
		fmt.Fprintf(buf, "        %s: %s = None,\n", col.Name, optType)
	}
	fmt.Fprintf(buf, "    ) -> %s:\n", returnType)

	// Generate PK if auto.
	for _, col := range pkCols {
		if isAutoColumn(col, tbl.PK) {
			if col.PGType == "uuid" {
				fmt.Fprintf(buf, "        %s = uuid4()\n", col.Name)
			} else if col.Identity != "" || col.PGType == "integer" || col.PGType == "bigint" || col.PGType == "serial" || col.PGType == "bigserial" {
				// Auto-increment: use max existing key + 1.
				fmt.Fprintf(buf, "        store = self._ctx.stores[%q]\n", tbl.Name)
				fmt.Fprintf(buf, "        %s = max(store.keys(), default=0) + 1\n", col.Name)
			}
		}
	}

	// Build row dict.
	buf.WriteString("        row = {\n")
	for _, col := range tbl.Columns {
		if col.Generated != "" {
			continue
		}
		fmt.Fprintf(buf, "            %q: %s,\n", col.Name, col.Name)
	}
	buf.WriteString("        }\n")

	// Validate constraints.
	fmt.Fprintf(buf, "        errors = ConstraintEngine.validate_insert(\n")
	fmt.Fprintf(buf, "            %q, %s, row,\n", tbl.Name, constraintVar)
	buf.WriteString("            self._ctx.stores, self._ctx.unique_indexes,\n")
	buf.WriteString("        )\n")
	buf.WriteString("        if errors:\n")
	buf.WriteString("            raise ValueError(f\"Constraint violation: {'; '.join(errors)}\")\n")

	// Update unique indexes.
	for _, uq := range tbl.Uniques {
		idxName := fmt.Sprintf("%s_%s", tbl.Name, strings.Join(uq.Columns, "_"))
		colTuple := memColumnTuple("row", uq.Columns)
		fmt.Fprintf(buf, "        self._ctx.unique_indexes[%q][%s] = True\n", idxName, colTuple)
	}

	// Store the row.
	if len(pkCols) == 1 {
		fmt.Fprintf(buf, "        self._ctx.stores[%q][%s] = row\n", tbl.Name, pkCols[0].Name)
	} else {
		pkTuple := memPKTuple(pkCols)
		fmt.Fprintf(buf, "        self._ctx.stores[%q][%s] = row\n", tbl.Name, pkTuple)
	}

	// Return PK.
	if len(pkCols) == 1 {
		fmt.Fprintf(buf, "        return %s\n", pkCols[0].Name)
	} else {
		fmt.Fprintf(buf, "        return %s\n", memPKTuple(pkCols))
	}
}

// writeMemGetMethod generates the in-memory get method.
func writeMemGetMethod(buf *bytes.Buffer, tbl *model.Table, rowType string) {
	pkCols := pkColumns(tbl)
	if len(pkCols) == 0 {
		return
	}

	fmt.Fprintf(buf, "\n    async def get_%s(\n        self,\n", tbl.Name)
	for _, col := range pkCols {
		pyType := columnPythonType(col)
		fmt.Fprintf(buf, "        %s: %s,\n", col.Name, pyType)
	}
	fmt.Fprintf(buf, "    ) -> Optional[%s]:\n", rowType)

	pkKey := memPKKey(pkCols)
	fmt.Fprintf(buf, "        row = self._ctx.stores[%q].get(%s)\n", tbl.Name, pkKey)
	fmt.Fprintf(buf, "        return %s(**row) if row else None\n", rowType)
}

// writeMemUpdateMethod generates the in-memory update method with constraint validation.
func writeMemUpdateMethod(buf *bytes.Buffer, tbl *model.Table, smMap map[string]*model.SMTransitionMap) {
	pkCols := pkColumns(tbl)
	if len(pkCols) == 0 {
		return
	}

	var updatableCols []model.Column
	for _, col := range tbl.Columns {
		if isPKColumn(col.Name, tbl.PK) {
			continue
		}
		if col.Generated != "" {
			continue
		}
		if col.Identity != "" {
			continue
		}
		updatableCols = append(updatableCols, col)
	}

	constraintVar := strings.ToUpper(tbl.Name) + "_CONSTRAINTS"

	fmt.Fprintf(buf, "\n    async def update_%s(\n        self,\n", tbl.Name)
	for _, col := range pkCols {
		pyType := columnPythonType(col)
		fmt.Fprintf(buf, "        %s: %s,\n", col.Name, pyType)
	}
	buf.WriteString("        *,\n")
	for _, col := range updatableCols {
		pyType := baseColumnPythonType(col)
		optType := ApplyNullable(pyType, LangPython)
		fmt.Fprintf(buf, "        %s: %s = None,\n", col.Name, optType)
	}
	buf.WriteString("    ) -> None:\n")

	// Get existing row.
	pkKey := memPKKey(pkCols)
	fmt.Fprintf(buf, "        old_row = self._ctx.stores[%q].get(%s)\n", tbl.Name, pkKey)
	buf.WriteString("        if old_row is None:\n")
	buf.WriteString("            raise ValueError(\"Row not found\")\n")

	// Build new_row dict from non-None kwargs.
	buf.WriteString("        new_row: dict[str, Any] = {}\n")
	for _, col := range updatableCols {
		fmt.Fprintf(buf, "        if %s is not None:\n", col.Name)
		fmt.Fprintf(buf, "            new_row[%q] = %s\n", col.Name, col.Name)
	}

	// PK columns list for the engine.
	var pkNames []string
	for _, col := range pkCols {
		pkNames = append(pkNames, fmt.Sprintf("%q", col.Name))
	}

	// Validate constraints.
	fmt.Fprintf(buf, "        errors = ConstraintEngine.validate_update(\n")
	fmt.Fprintf(buf, "            %q, %s, old_row, new_row,\n", tbl.Name, constraintVar)
	fmt.Fprintf(buf, "            [%s],\n", strings.Join(pkNames, ", "))
	buf.WriteString("            self._ctx.stores, self._ctx.unique_indexes,\n")
	buf.WriteString("        )\n")
	buf.WriteString("        if errors:\n")
	buf.WriteString("            raise ValueError(f\"Constraint violation: {'; '.join(errors)}\")\n")

	// Merge and update.
	buf.WriteString("        merged = dict(old_row)\n")
	buf.WriteString("        merged.update(new_row)\n")

	// Update unique indexes: remove old, add new.
	for _, uq := range tbl.Uniques {
		idxName := fmt.Sprintf("%s_%s", tbl.Name, strings.Join(uq.Columns, "_"))
		oldKey := memColumnTuple("old_row", uq.Columns)
		newKey := memColumnTuple("merged", uq.Columns)
		fmt.Fprintf(buf, "        self._ctx.unique_indexes[%q].pop(%s, None)\n", idxName, oldKey)
		fmt.Fprintf(buf, "        self._ctx.unique_indexes[%q][%s] = True\n", idxName, newKey)
	}

	fmt.Fprintf(buf, "        self._ctx.stores[%q][%s] = merged\n", tbl.Name, pkKey)
}

// writeMemDeleteMethod generates the in-memory delete method with cascade processing.
func writeMemDeleteMethod(buf *bytes.Buffer, tbl *model.Table) {
	pkCols := pkColumns(tbl)
	if len(pkCols) == 0 {
		return
	}

	fmt.Fprintf(buf, "\n    async def delete_%s(\n        self,\n", tbl.Name)
	for _, col := range pkCols {
		pyType := columnPythonType(col)
		fmt.Fprintf(buf, "        %s: %s,\n", col.Name, pyType)
	}
	buf.WriteString("    ) -> bool:\n")

	pkKey := memPKKey(pkCols)
	fmt.Fprintf(buf, "        if %s not in self._ctx.stores[%q]:\n", pkKey, tbl.Name)
	buf.WriteString("            return False\n")

	// Process cascading deletes via ConstraintEngine with ALL_CONSTRAINTS.
	fmt.Fprintf(buf, "        errors = ConstraintEngine.process_delete(\n")
	fmt.Fprintf(buf, "            %q, %s,\n", tbl.Name, pkKey)
	buf.WriteString("            ALL_CONSTRAINTS,\n")
	buf.WriteString("            self._ctx.stores, self._ctx.unique_indexes,\n")
	buf.WriteString("        )\n")
	buf.WriteString("        if errors:\n")
	buf.WriteString("            raise ValueError(f\"Cannot delete: {'; '.join(errors)}\")\n")

	// Remove unique index entries.
	fmt.Fprintf(buf, "        row = self._ctx.stores[%q][%s]\n", tbl.Name, pkKey)
	for _, uq := range tbl.Uniques {
		idxName := fmt.Sprintf("%s_%s", tbl.Name, strings.Join(uq.Columns, "_"))
		key := memColumnTuple("row", uq.Columns)
		fmt.Fprintf(buf, "        self._ctx.unique_indexes[%q].pop(%s, None)\n", idxName, key)
	}

	fmt.Fprintf(buf, "        del self._ctx.stores[%q][%s]\n", tbl.Name, pkKey)
	buf.WriteString("        return True\n")
}

// writeMemGetByFKMethods generates in-memory FK lookup methods.
func writeMemGetByFKMethods(buf *bytes.Buffer, tbl *model.Table, fkGraph *model.FKGraph, rowType string) {
	if fkGraph == nil {
		return
	}

	type fkByMethod struct {
		paramName string
		queryCol  string
		pyType    string
	}
	seen := make(map[string]bool)
	var methods []fkByMethod

	for _, edge := range fkGraph.Reverse[tbl.Name] {
		methodName := edge.FromColumn
		if seen[methodName] {
			continue
		}
		seen[methodName] = true

		pyType := "Any"
		if toCol := qlFindColumn(tbl, edge.ToColumn); toCol != nil {
			pyType = columnPythonType(*toCol)
		}

		methods = append(methods, fkByMethod{
			paramName: methodName,
			queryCol:  edge.ToColumn,
			pyType:    pyType,
		})
	}

	sort.Slice(methods, func(i, j int) bool {
		return methods[i].paramName < methods[j].paramName
	})

	for _, fm := range methods {
		fmt.Fprintf(buf, "\n    async def get_%s_by_%s(\n        self,\n        %s: %s,\n    ) -> list[%s]:\n",
			tbl.Name, fm.paramName, fm.paramName, fm.pyType, rowType)
		fmt.Fprintf(buf, "        return [\n")
		fmt.Fprintf(buf, "            %s(**row)\n", rowType)
		fmt.Fprintf(buf, "            for row in self._ctx.stores[%q].values()\n", tbl.Name)
		fmt.Fprintf(buf, "            if row.get(%q) == %s\n", fm.queryCol, fm.paramName)
		fmt.Fprintf(buf, "        ]\n")
	}
}

// writeMemGetByUniqueMethods generates in-memory unique constraint lookup methods.
func writeMemGetByUniqueMethods(buf *bytes.Buffer, tbl *model.Table, rowType string) {
	for _, uq := range tbl.Uniques {
		suffix := strings.Join(uq.Columns, "_")
		fmt.Fprintf(buf, "\n    async def get_%s_by_%s(\n        self,\n", tbl.Name, suffix)
		for _, colName := range uq.Columns {
			col := qlFindColumn(tbl, colName)
			if col != nil {
				pyType := columnPythonType(*col)
				fmt.Fprintf(buf, "        %s: %s,\n", colName, pyType)
			} else {
				fmt.Fprintf(buf, "        %s: Any,\n", colName)
			}
		}
		fmt.Fprintf(buf, "    ) -> Optional[%s]:\n", rowType)

		// Look up via unique index.
		idxName := fmt.Sprintf("%s_%s", tbl.Name, suffix)
		colTuple := memArgTuple(uq.Columns)
		fmt.Fprintf(buf, "        key = %s\n", colTuple)
		fmt.Fprintf(buf, "        if key not in self._ctx.unique_indexes.get(%q, {}):\n", idxName)
		buf.WriteString("            return None\n")

		// Scan store for matching row.
		fmt.Fprintf(buf, "        for row in self._ctx.stores[%q].values():\n", tbl.Name)
		var matchParts []string
		for _, colName := range uq.Columns {
			matchParts = append(matchParts, fmt.Sprintf("row.get(%q) == %s", colName, colName))
		}
		fmt.Fprintf(buf, "            if %s:\n", strings.Join(matchParts, " and "))
		fmt.Fprintf(buf, "                return %s(**row)\n", rowType)
		buf.WriteString("        return None\n")
	}
}

// writeMemListMethod generates the in-memory list method.
func writeMemListMethod(buf *bytes.Buffer, tbl *model.Table, rowType string) {
	fmt.Fprintf(buf, "\n    async def list_%s(\n        self,\n        limit: int = 100,\n        offset: int = 0,\n    ) -> list[%s]:\n",
		tbl.Name, rowType)
	fmt.Fprintf(buf, "        rows = list(self._ctx.stores[%q].values())\n", tbl.Name)
	fmt.Fprintf(buf, "        return [%s(**row) for row in rows[offset:offset + limit]]\n", rowType)
}

// writeMemSMTransitionMethods generates state machine transition methods for in-memory.
func writeMemSMTransitionMethods(buf *bytes.Buffer, tbl *model.Table, smMap map[string]*model.SMTransitionMap) {
	pkCols := pkColumns(tbl)
	if len(pkCols) == 0 {
		return
	}

	for _, col := range tbl.Columns {
		smt, ok := smMap[col.SemanticTypeName]
		if !ok {
			continue
		}
		constraintVar := strings.ToUpper(tbl.Name) + "_CONSTRAINTS"

		for _, nt := range smt.NamedTransitions {
			fmt.Fprintf(buf, "\n    async def %s_%s(\n        self,\n", nt.Name, tbl.Name)
			for _, pkCol := range pkCols {
				pyType := columnPythonType(pkCol)
				fmt.Fprintf(buf, "        %s: %s,\n", pkCol.Name, pyType)
			}

			if len(nt.Requires) > 0 {
				buf.WriteString("        *,\n")
				for _, paramName := range sortedMapKeys(nt.Requires) {
					pgType := nt.Requires[paramName]
					m := LookupType(pgType, LangPython)
					fmt.Fprintf(buf, "        %s: %s,\n", paramName, m.Type)
				}
			}
			buf.WriteString("    ) -> None:\n")

			// Get existing row.
			pkKey := memPKKey(pkCols)
			fmt.Fprintf(buf, "        row = self._ctx.stores[%q].get(%s)\n", tbl.Name, pkKey)
			buf.WriteString("        if row is None:\n")
			buf.WriteString("            raise ValueError(\"Row not found\")\n")

			// Build update dict with the new state.
			fmt.Fprintf(buf, "        new_row = {%q: %q", col.Name, nt.To)
			if len(nt.Requires) > 0 {
				for _, paramName := range sortedMapKeys(nt.Requires) {
					fmt.Fprintf(buf, ", %q: %s", paramName, paramName)
				}
			}
			buf.WriteString("}\n")

			// Validate via ConstraintEngine (checks SM transition).
			var pkNames []string
			for _, pkCol := range pkCols {
				pkNames = append(pkNames, fmt.Sprintf("%q", pkCol.Name))
			}
			fmt.Fprintf(buf, "        errors = ConstraintEngine.validate_update(\n")
			fmt.Fprintf(buf, "            %q, %s, row, new_row,\n", tbl.Name, constraintVar)
			fmt.Fprintf(buf, "            [%s],\n", strings.Join(pkNames, ", "))
			buf.WriteString("            self._ctx.stores, self._ctx.unique_indexes,\n")
			buf.WriteString("        )\n")
			buf.WriteString("        if errors:\n")
			fmt.Fprintf(buf, "            raise ValueError(f\"Cannot %s: {'; '.join(errors)}\")\n", nt.Name)

			// Update the row.
			buf.WriteString("        row.update(new_row)\n")
		}
	}
}

// generateMemoryBackendFile produces memory_backend.py with the composite InMemoryBackend class.
func generateMemoryBackendFile(tables []model.Table, schema *model.Schema, smMap map[string]*model.SMTransitionMap) []byte {
	var buf bytes.Buffer

	// Header.
	buf.WriteString("# Generated by pgdesign -- do not edit manually.\n")
	buf.WriteString("# Regenerate with: pgdesign codegen --lang python --mode query-layer <schema-files>\n")

	buf.WriteString("\nfrom __future__ import annotations\n")
	buf.WriteString("\nfrom typing import Any, Optional\n")

	// Collect imports needed for type annotations.
	imports := newImportCollector()
	for _, tbl := range tables {
		for _, col := range tbl.Columns {
			m := LookupType(col.PGType, LangPython)
			imports.addFromMapping(m, col)
		}
		for _, col := range tbl.Columns {
			if smt, ok := smMap[col.SemanticTypeName]; ok {
				for _, nt := range smt.NamedTransitions {
					for _, pgType := range sortedMapKeys(nt.Requires) {
						m := LookupType(nt.Requires[pgType], LangPython)
						imports.addFromType(m)
					}
				}
			}
		}
	}

	if imports.needs["datetime"] {
		buf.WriteString("from datetime import datetime\n")
	}
	if imports.needs["Decimal"] {
		buf.WriteString("from decimal import Decimal\n")
	}
	if imports.needs["UUID"] {
		buf.WriteString("from uuid import UUID\n")
	}

	// Import Row types from protocols.
	var rowImports []string
	for _, tbl := range tables {
		rowImports = append(rowImports, toPascalCase(tbl.Name)+"Row")
	}
	fmt.Fprintf(&buf, "\nfrom .protocols import InMemoryContext, %s\n", strings.Join(rowImports, ", "))

	// Import per-table delegates.
	for _, tbl := range tables {
		className := toPascalCase(tbl.Name) + "Mem"
		fmt.Fprintf(&buf, "from ._%s_mem import %s\n", tbl.Name, className)
	}

	// InMemoryBackend class.
	buf.WriteString("\n\nclass InMemoryBackend:\n")
	buf.WriteString("    \"\"\"Composite backend delegating to per-table in-memory implementations.\"\"\"\n")

	// __init__.
	buf.WriteString("\n    def __init__(self) -> None:\n")
	buf.WriteString("        ctx = InMemoryContext()\n")
	for _, tbl := range tables {
		className := toPascalCase(tbl.Name) + "Mem"
		attrName := "_" + tbl.Name
		fmt.Fprintf(&buf, "        self.%s = %s(ctx)\n", attrName, className)
	}

	// Forwarding methods for all tables.
	for _, tbl := range tables {
		writeMemBackendForwardingMethods(&buf, &tbl, schema, smMap)
	}

	return buf.Bytes()
}

// writeMemBackendForwardingMethods generates one-line forwarding methods on InMemoryBackend.
func writeMemBackendForwardingMethods(buf *bytes.Buffer, tbl *model.Table, schema *model.Schema, smMap map[string]*model.SMTransitionMap) {
	className := toPascalCase(tbl.Name)
	rowType := className + "Row"
	attrName := "_" + tbl.Name

	pkCols := pkColumns(tbl)

	// create forwarding.
	if len(pkCols) > 0 {
		var required []model.Column
		var optional []model.Column
		for _, col := range tbl.Columns {
			if isAutoColumn(col, tbl.PK) {
				continue
			}
			if col.Generated != "" {
				continue
			}
			if col.Identity != "" {
				continue
			}
			hasDefault := col.Default != nil || col.DefaultExpr != ""
			if col.NotNull && !hasDefault {
				required = append(required, col)
			} else {
				optional = append(optional, col)
			}
		}

		returnType := pkReturnType(tbl)
		fmt.Fprintf(buf, "\n    async def create_%s(\n        self,\n        *,\n", tbl.Name)
		for _, col := range required {
			pyType := columnPythonType(col)
			fmt.Fprintf(buf, "        %s: %s,\n", col.Name, pyType)
		}
		for _, col := range optional {
			pyType := baseColumnPythonType(col)
			optType := ApplyNullable(pyType, LangPython)
			fmt.Fprintf(buf, "        %s: %s = None,\n", col.Name, optType)
		}
		fmt.Fprintf(buf, "    ) -> %s:\n", returnType)

		allWritable := append(required, optional...)
		var kwArgs []string
		for _, col := range allWritable {
			kwArgs = append(kwArgs, fmt.Sprintf("%s=%s", col.Name, col.Name))
		}
		fmt.Fprintf(buf, "        return await self.%s.create_%s(%s)\n",
			attrName, tbl.Name, strings.Join(kwArgs, ", "))
	}

	// get forwarding.
	if len(pkCols) > 0 {
		fmt.Fprintf(buf, "\n    async def get_%s(\n        self,\n", tbl.Name)
		for _, col := range pkCols {
			pyType := columnPythonType(col)
			fmt.Fprintf(buf, "        %s: %s,\n", col.Name, pyType)
		}
		fmt.Fprintf(buf, "    ) -> Optional[%s]:\n", rowType)
		fmt.Fprintf(buf, "        return await self.%s.get_%s(%s)\n",
			attrName, tbl.Name, joinColumnNames(pkCols))
	}

	// update forwarding (skip if append-only).
	if !tbl.AppendOnly && len(pkCols) > 0 {
		var updatableCols []model.Column
		for _, col := range tbl.Columns {
			if isPKColumn(col.Name, tbl.PK) {
				continue
			}
			if col.Generated != "" {
				continue
			}
			if col.Identity != "" {
				continue
			}
			updatableCols = append(updatableCols, col)
		}

		fmt.Fprintf(buf, "\n    async def update_%s(\n        self,\n", tbl.Name)
		for _, col := range pkCols {
			pyType := columnPythonType(col)
			fmt.Fprintf(buf, "        %s: %s,\n", col.Name, pyType)
		}
		buf.WriteString("        *,\n")
		for _, col := range updatableCols {
			pyType := baseColumnPythonType(col)
			optType := ApplyNullable(pyType, LangPython)
			fmt.Fprintf(buf, "        %s: %s = None,\n", col.Name, optType)
		}
		buf.WriteString("    ) -> None:\n")

		var kwArgs []string
		for _, col := range updatableCols {
			kwArgs = append(kwArgs, fmt.Sprintf("%s=%s", col.Name, col.Name))
		}
		fmt.Fprintf(buf, "        return await self.%s.update_%s(%s, %s)\n",
			attrName, tbl.Name, joinColumnNames(pkCols), strings.Join(kwArgs, ", "))
	}

	// delete forwarding (skip if append-only).
	if !tbl.AppendOnly && len(pkCols) > 0 {
		fmt.Fprintf(buf, "\n    async def delete_%s(\n        self,\n", tbl.Name)
		for _, col := range pkCols {
			pyType := columnPythonType(col)
			fmt.Fprintf(buf, "        %s: %s,\n", col.Name, pyType)
		}
		buf.WriteString("    ) -> bool:\n")
		fmt.Fprintf(buf, "        return await self.%s.delete_%s(%s)\n",
			attrName, tbl.Name, joinColumnNames(pkCols))
	}

	// SM transition forwarding.
	if len(pkCols) > 0 {
		for _, col := range tbl.Columns {
			smt, ok := smMap[col.SemanticTypeName]
			if !ok {
				continue
			}
			for _, nt := range smt.NamedTransitions {
				fmt.Fprintf(buf, "\n    async def %s_%s(\n        self,\n", nt.Name, tbl.Name)
				for _, pkCol := range pkCols {
					pyType := columnPythonType(pkCol)
					fmt.Fprintf(buf, "        %s: %s,\n", pkCol.Name, pyType)
				}
				if len(nt.Requires) > 0 {
					buf.WriteString("        *,\n")
					for _, paramName := range sortedMapKeys(nt.Requires) {
						pgType := nt.Requires[paramName]
						m := LookupType(pgType, LangPython)
						fmt.Fprintf(buf, "        %s: %s,\n", paramName, m.Type)
					}
				}
				buf.WriteString("    ) -> None:\n")

				var args []string
				args = append(args, joinColumnNames(pkCols))
				if len(nt.Requires) > 0 {
					for _, paramName := range sortedMapKeys(nt.Requires) {
						args = append(args, fmt.Sprintf("%s=%s", paramName, paramName))
					}
				}
				fmt.Fprintf(buf, "        return await self.%s.%s_%s(%s)\n",
					attrName, nt.Name, tbl.Name, strings.Join(args, ", "))
			}
		}
	}

	// get_by_fk forwarding.
	if schema.FKGraph != nil {
		type fkByMethod struct {
			colName string
			pyType  string
		}
		seen := make(map[string]bool)
		var fkMethods []fkByMethod

		for _, edge := range schema.FKGraph.Reverse[tbl.Name] {
			methodName := edge.FromColumn
			if seen[methodName] {
				continue
			}
			seen[methodName] = true

			pyType := "Any"
			if toCol := qlFindColumn(tbl, edge.ToColumn); toCol != nil {
				pyType = columnPythonType(*toCol)
			}
			fkMethods = append(fkMethods, fkByMethod{colName: methodName, pyType: pyType})
		}

		sort.Slice(fkMethods, func(i, j int) bool {
			return fkMethods[i].colName < fkMethods[j].colName
		})

		for _, fm := range fkMethods {
			fmt.Fprintf(buf, "\n    async def get_%s_by_%s(\n        self,\n        %s: %s,\n    ) -> list[%s]:\n",
				tbl.Name, fm.colName, fm.colName, fm.pyType, rowType)
			fmt.Fprintf(buf, "        return await self.%s.get_%s_by_%s(%s)\n",
				attrName, tbl.Name, fm.colName, fm.colName)
		}
	}

	// get_by_unique forwarding.
	for _, uq := range tbl.Uniques {
		suffix := strings.Join(uq.Columns, "_")
		fmt.Fprintf(buf, "\n    async def get_%s_by_%s(\n        self,\n", tbl.Name, suffix)
		for _, colName := range uq.Columns {
			col := qlFindColumn(tbl, colName)
			if col != nil {
				pyType := columnPythonType(*col)
				fmt.Fprintf(buf, "        %s: %s,\n", colName, pyType)
			} else {
				fmt.Fprintf(buf, "        %s: Any,\n", colName)
			}
		}
		fmt.Fprintf(buf, "    ) -> Optional[%s]:\n", rowType)
		fmt.Fprintf(buf, "        return await self.%s.get_%s_by_%s(%s)\n",
			attrName, tbl.Name, suffix, strings.Join(uq.Columns, ", "))
	}

	// list forwarding.
	fmt.Fprintf(buf, "\n    async def list_%s(\n        self,\n        limit: int = 100,\n        offset: int = 0,\n    ) -> list[%s]:\n",
		tbl.Name, rowType)
	fmt.Fprintf(buf, "        return await self.%s.list_%s(limit, offset)\n",
		attrName, tbl.Name)
}

// memPKKey returns the Python expression for a PK lookup key.
func memPKKey(pkCols []model.Column) string {
	if len(pkCols) == 1 {
		return pkCols[0].Name
	}
	names := make([]string, len(pkCols))
	for i, col := range pkCols {
		names[i] = col.Name
	}
	return "(" + strings.Join(names, ", ") + ")"
}

// memPKTuple returns a Python tuple expression from PK column names.
func memPKTuple(pkCols []model.Column) string {
	names := make([]string, len(pkCols))
	for i, col := range pkCols {
		names[i] = col.Name
	}
	return "(" + strings.Join(names, ", ") + ")"
}

// memColumnTuple returns a Python tuple expression like (d["col1"], d["col2"]).
func memColumnTuple(dictName string, columns []string) string {
	parts := make([]string, len(columns))
	for i, col := range columns {
		parts[i] = fmt.Sprintf("%s.get(%q)", dictName, col)
	}
	if len(parts) == 1 {
		return "(" + parts[0] + ",)"
	}
	return "(" + strings.Join(parts, ", ") + ")"
}

// memArgTuple returns a Python tuple expression like (col1, col2) from arg names.
func memArgTuple(columns []string) string {
	if len(columns) == 1 {
		return "(" + columns[0] + ",)"
	}
	return "(" + strings.Join(columns, ", ") + ")"
}
