package codegen

import (
	"strings"
	"testing"

	"github.com/smm-h/pgdesign/internal/model"
)

// testSchema returns a schema with tables exercising all code paths:
// users (standard CRUD), orders (append-only, SM transitions), order_items (FK to orders).
func qlTestSchema() *model.Schema {
	schema := &model.Schema{
		Name: "app",
		Tables: []model.Table{
			{
				Name:   "users",
				Schema: "public",
				PK:     []string{"id"},
				Columns: []model.Column{
					{Name: "id", PGType: "uuid", NotNull: true, DefaultExpr: "gen_random_uuid()"},
					{Name: "email", PGType: "text", NotNull: true},
					{Name: "name", PGType: "text", NotNull: false},
					{Name: "score", PGType: "integer", NotNull: true, Default: model.StrPtr("0")},
					{Name: "created_at", PGType: "timestamptz", NotNull: true, DefaultExpr: "now()"},
				},
				Uniques: []model.UniqueConstraint{
					{Name: "uq_email", Columns: []string{"email"}},
				},
			},
			{
				Name:       "orders",
				Schema:     "public",
				PK:         []string{"id"},
				AppendOnly: true,
				Columns: []model.Column{
					{Name: "id", PGType: "uuid", NotNull: true, DefaultExpr: "gen_random_uuid()"},
					{Name: "user_id", PGType: "uuid", NotNull: true},
					{Name: "total", PGType: "numeric", NotNull: true},
					{Name: "status", PGType: "text", NotNull: true, SemanticTypeName: "order_status"},
					{Name: "suspended_at", PGType: "timestamptz", NotNull: false},
				},
				FKs: []model.FK{
					{Name: "fk_user", Columns: []string{"user_id"}, RefTable: "users", RefColumns: []string{"id"}, OnDelete: "CASCADE"},
				},
			},
			{
				Name:   "order_items",
				Schema: "public",
				PK:     []string{"id"},
				Columns: []model.Column{
					{Name: "id", PGType: "integer", NotNull: true, Identity: "ALWAYS"},
					{Name: "order_id", PGType: "uuid", NotNull: true},
					{Name: "product", PGType: "text", NotNull: true},
					{Name: "quantity", PGType: "integer", NotNull: true},
					{Name: "row_version", PGType: "integer", NotNull: true, Generated: "stored"},
				},
				FKs: []model.FK{
					{Name: "fk_order", Columns: []string{"order_id"}, RefTable: "orders", RefColumns: []string{"id"}, OnDelete: "CASCADE"},
				},
				Uniques: []model.UniqueConstraint{
					{Name: "uq_order_product", Columns: []string{"order_id", "product"}},
				},
			},
		},
		StateMachineTransitions: []model.SMTransitionMap{
			{
				TypeName: "order_status",
				Transitions: map[string][]string{
					"pending":   {"confirmed", "cancelled"},
					"confirmed": {"shipped", "suspended"},
					"suspended": {"confirmed"},
				},
				States: []string{"pending", "confirmed", "shipped", "suspended", "cancelled"},
				NamedTransitions: []model.NamedTransition{
					{Name: "cancel", From: []string{"pending"}, To: "cancelled"},
					{Name: "confirm", From: []string{"pending", "suspended"}, To: "confirmed"},
					{Name: "ship", From: []string{"confirmed"}, To: "shipped"},
					{Name: "suspend", From: []string{"confirmed"}, To: "suspended", Requires: map[string]string{"suspended_reason": "text"}},
				},
			},
		},
	}

	// Build FK graph.
	schema.BuildFKGraph()
	return schema
}

func TestPythonQueryLayer_ProtocolsFileProduced(t *testing.T) {
	schema := qlTestSchema()
	gen := &PythonQueryLayerGenerator{}
	files, diags := gen.GenerateFiles(schema)

	if len(diags) > 0 {
		t.Fatalf("unexpected diagnostics: %v", diags)
	}

	if _, ok := files["protocols.py"]; !ok {
		t.Fatal("protocols.py not found in generated files")
	}
}

func TestPythonQueryLayer_Header(t *testing.T) {
	schema := qlTestSchema()
	gen := &PythonQueryLayerGenerator{}
	files, _ := gen.GenerateFiles(schema)
	content := string(files["protocols.py"])

	if !strings.Contains(content, "# Generated by pgdesign -- do not edit manually.") {
		t.Error("missing generated header")
	}
	if !strings.Contains(content, "from __future__ import annotations") {
		t.Error("missing __future__ import")
	}
	if !strings.Contains(content, "from typing import Any, Optional, Protocol") {
		t.Error("missing typing imports")
	}
	if !strings.Contains(content, "from dataclasses import dataclass, field") {
		t.Error("missing dataclass/field import")
	}
}

func TestPythonQueryLayer_ContextTypes(t *testing.T) {
	schema := qlTestSchema()
	gen := &PythonQueryLayerGenerator{}
	files, _ := gen.GenerateFiles(schema)
	content := string(files["protocols.py"])

	if !strings.Contains(content, "class PgContext:") {
		t.Error("missing PgContext class")
	}
	if !strings.Contains(content, "pool: Any  # asyncpg.Pool") {
		t.Error("missing PgContext.pool field")
	}
	if !strings.Contains(content, "class InMemoryContext:") {
		t.Error("missing InMemoryContext class")
	}
	if !strings.Contains(content, "stores: dict[str, dict] = field(default_factory=dict)") {
		t.Error("missing InMemoryContext.stores field")
	}
	if !strings.Contains(content, "unique_indexes: dict[str, dict] = field(default_factory=dict)") {
		t.Error("missing InMemoryContext.unique_indexes field")
	}
}

func TestPythonQueryLayer_RowDataclasses(t *testing.T) {
	schema := qlTestSchema()
	gen := &PythonQueryLayerGenerator{}
	files, _ := gen.GenerateFiles(schema)
	content := string(files["protocols.py"])

	// Users row.
	if !strings.Contains(content, "class UsersRow:") {
		t.Error("missing UsersRow class")
	}
	if !strings.Contains(content, `"""Row type for the users table."""`) {
		t.Error("missing UsersRow docstring")
	}
	assertFieldPresent(t, content, "UsersRow", "id", "UUID")
	assertFieldPresent(t, content, "UsersRow", "email", "str")
	assertFieldPresent(t, content, "UsersRow", "name", "Optional[str]")
	assertFieldPresent(t, content, "UsersRow", "score", "int")
	assertFieldPresent(t, content, "UsersRow", "created_at", "datetime")

	// Orders row.
	if !strings.Contains(content, "class OrdersRow:") {
		t.Error("missing OrdersRow class")
	}
	assertFieldPresent(t, content, "OrdersRow", "total", "Decimal")
	assertFieldPresent(t, content, "OrdersRow", "suspended_at", "Optional[datetime]")

	// OrderItems row.
	if !strings.Contains(content, "class OrderItemsRow:") {
		t.Error("missing OrderItemsRow class")
	}
	assertFieldPresent(t, content, "OrderItemsRow", "quantity", "int")
	assertFieldPresent(t, content, "OrderItemsRow", "row_version", "int")
}

func TestPythonQueryLayer_WriterProtocol(t *testing.T) {
	schema := qlTestSchema()
	gen := &PythonQueryLayerGenerator{}
	files, _ := gen.GenerateFiles(schema)
	content := string(files["protocols.py"])

	// Users Writer.
	if !strings.Contains(content, "class UsersWriter(Protocol):") {
		t.Error("missing UsersWriter protocol")
	}

	// create_users: id excluded (auto PK), email required, name optional (nullable),
	// score optional (has default), created_at optional (has default_expr).
	if !strings.Contains(content, "async def create_users(") {
		t.Error("missing create_users method")
	}
	// email is required (NOT NULL, no default).
	assertMethodParam(t, content, "create_users", "email: str,")
	// name is optional (nullable).
	assertMethodParam(t, content, "create_users", "name: Optional[str] = None,")
	// score is optional (has default).
	assertMethodParam(t, content, "create_users", "score: Optional[int] = None,")
	// Return type is UUID (PK type).
	assertMethodReturn(t, content, "create_users", "UUID")

	// update_users.
	if !strings.Contains(content, "async def update_users(") {
		t.Error("missing update_users method")
	}
	// delete_users.
	if !strings.Contains(content, "async def delete_users(") {
		t.Error("missing delete_users method")
	}
	assertMethodReturn(t, content, "delete_users", "bool")
}

func TestPythonQueryLayer_AppendOnlySkipsUpdateDelete(t *testing.T) {
	schema := qlTestSchema()
	gen := &PythonQueryLayerGenerator{}
	files, _ := gen.GenerateFiles(schema)
	content := string(files["protocols.py"])

	// Orders is append-only: should have create but NOT update or delete.
	if !strings.Contains(content, "class OrdersWriter(Protocol):") {
		t.Error("missing OrdersWriter protocol")
	}
	if !strings.Contains(content, "async def create_orders(") {
		t.Error("missing create_orders method")
	}
	// Should NOT have update_orders or delete_orders.
	if strings.Contains(content, "async def update_orders(") {
		t.Error("update_orders should not exist on append-only table")
	}
	if strings.Contains(content, "async def delete_orders(") {
		t.Error("delete_orders should not exist on append-only table")
	}
}

func TestPythonQueryLayer_SMTransitionMethods(t *testing.T) {
	schema := qlTestSchema()
	gen := &PythonQueryLayerGenerator{}
	files, _ := gen.GenerateFiles(schema)
	content := string(files["protocols.py"])

	// SM transition methods on OrdersWriter.
	if !strings.Contains(content, "async def cancel_orders(") {
		t.Error("missing cancel_orders SM transition method")
	}
	if !strings.Contains(content, "async def confirm_orders(") {
		t.Error("missing confirm_orders SM transition method")
	}
	if !strings.Contains(content, "async def ship_orders(") {
		t.Error("missing ship_orders SM transition method")
	}
	if !strings.Contains(content, "async def suspend_orders(") {
		t.Error("missing suspend_orders SM transition method")
	}
	// suspend_orders should have suspended_reason as keyword-only param.
	assertMethodParam(t, content, "suspend_orders", "suspended_reason: str,")
}

func TestPythonQueryLayer_ReaderProtocol(t *testing.T) {
	schema := qlTestSchema()
	gen := &PythonQueryLayerGenerator{}
	files, _ := gen.GenerateFiles(schema)
	content := string(files["protocols.py"])

	// Users Reader.
	if !strings.Contains(content, "class UsersReader(Protocol):") {
		t.Error("missing UsersReader protocol")
	}
	if !strings.Contains(content, "async def get_users(") {
		t.Error("missing get_users method")
	}
	assertMethodReturn(t, content, "get_users", "Optional[UsersRow]")

	// list_users.
	if !strings.Contains(content, "async def list_users(") {
		t.Error("missing list_users method")
	}
	assertMethodParam(t, content, "list_users", "limit: int = 100,")
	assertMethodParam(t, content, "list_users", "offset: int = 0,")
	assertMethodReturn(t, content, "list_users", "list[UsersRow]")

	// get_users_by_email (unique constraint).
	if !strings.Contains(content, "async def get_users_by_email(") {
		t.Error("missing get_users_by_email method from unique constraint")
	}
	assertMethodReturn(t, content, "get_users_by_email", "Optional[UsersRow]")

	// Users should have get_users_by_user_id from orders FK.
	if !strings.Contains(content, "async def get_users_by_user_id(") {
		t.Error("missing get_users_by_user_id from FK reverse lookup")
	}
	assertMethodReturn(t, content, "get_users_by_user_id", "list[UsersRow]")
}

func TestPythonQueryLayer_ReaderFKByMethods(t *testing.T) {
	schema := qlTestSchema()
	gen := &PythonQueryLayerGenerator{}
	files, _ := gen.GenerateFiles(schema)
	content := string(files["protocols.py"])

	// Orders has incoming FK from order_items (order_id).
	if !strings.Contains(content, "async def get_orders_by_order_id(") {
		t.Error("missing get_orders_by_order_id from FK reverse lookup")
	}
	assertMethodReturn(t, content, "get_orders_by_order_id", "list[OrdersRow]")
}

func TestPythonQueryLayer_ReaderMultiColumnUnique(t *testing.T) {
	schema := qlTestSchema()
	gen := &PythonQueryLayerGenerator{}
	files, _ := gen.GenerateFiles(schema)
	content := string(files["protocols.py"])

	// order_items has a multi-column unique (order_id, product).
	if !strings.Contains(content, "async def get_order_items_by_order_id_product(") {
		t.Error("missing get_order_items_by_order_id_product from multi-column unique")
	}
	assertMethodReturn(t, content, "get_order_items_by_order_id_product", "Optional[OrderItemsRow]")
}

func TestPythonQueryLayer_BackendProtocol(t *testing.T) {
	schema := qlTestSchema()
	gen := &PythonQueryLayerGenerator{}
	files, _ := gen.GenerateFiles(schema)
	content := string(files["protocols.py"])

	if !strings.Contains(content, "class Backend(Protocol):") {
		t.Error("missing Backend protocol")
	}
	if !strings.Contains(content, `"""Combined protocol declaring all Reader and Writer methods."""`) {
		t.Error("missing Backend docstring")
	}

	// Backend should include methods from all tables.
	// Spot-check a few.
	backendSection := extractAfter(content, "class Backend(Protocol):")
	if backendSection == "" {
		t.Fatal("could not extract Backend section")
	}
	if !strings.Contains(backendSection, "async def create_users(") {
		t.Error("Backend missing create_users")
	}
	if !strings.Contains(backendSection, "async def get_users(") {
		t.Error("Backend missing get_users")
	}
	if !strings.Contains(backendSection, "async def list_orders(") {
		t.Error("Backend missing list_orders")
	}
	if !strings.Contains(backendSection, "async def create_order_items(") {
		t.Error("Backend missing create_order_items")
	}
	// SM transitions on Backend.
	if !strings.Contains(backendSection, "async def suspend_orders(") {
		t.Error("Backend missing suspend_orders")
	}
	// Append-only: no update/delete on Backend for orders.
	if strings.Contains(backendSection, "async def update_orders(") {
		t.Error("Backend should not have update_orders (append-only)")
	}
}

func TestPythonQueryLayer_GeneratedColumnExcluded(t *testing.T) {
	schema := qlTestSchema()
	gen := &PythonQueryLayerGenerator{}
	files, _ := gen.GenerateFiles(schema)
	content := string(files["protocols.py"])

	// row_version is generated -- should be in the Row but NOT in create params.
	assertFieldPresent(t, content, "OrderItemsRow", "row_version", "int")

	// Check that create_order_items does NOT have row_version.
	createSection := extractMethod(content, "create_order_items")
	if createSection != "" && strings.Contains(createSection, "row_version") {
		t.Error("create_order_items should not include generated column row_version")
	}
}

func TestPythonQueryLayer_IdentityColumnExcluded(t *testing.T) {
	schema := qlTestSchema()
	gen := &PythonQueryLayerGenerator{}
	files, _ := gen.GenerateFiles(schema)
	content := string(files["protocols.py"])

	// id on order_items is IDENTITY -- should not appear in create params.
	createSection := extractMethod(content, "create_order_items")
	if createSection == "" {
		t.Fatal("could not find create_order_items method")
	}
	// The id param should not be among the writable params.
	// It's the PK with Identity, so it's excluded.
	lines := strings.Split(createSection, "\n")
	for _, line := range lines {
		trimmed := strings.TrimSpace(line)
		if strings.HasPrefix(trimmed, "id:") || strings.HasPrefix(trimmed, "id :") {
			t.Error("create_order_items should not include identity PK column 'id'")
		}
	}
}

func TestPythonQueryLayer_EmptySchema(t *testing.T) {
	schema := &model.Schema{Tables: []model.Table{}}
	gen := &PythonQueryLayerGenerator{}
	files, diags := gen.GenerateFiles(schema)

	if len(diags) > 0 {
		t.Fatalf("unexpected diagnostics: %v", diags)
	}

	content := string(files["protocols.py"])
	if !strings.Contains(content, "class PgContext:") {
		t.Error("empty schema should still have PgContext")
	}
	if !strings.Contains(content, "class InMemoryContext:") {
		t.Error("empty schema should still have InMemoryContext")
	}
	// No table-specific classes.
	if strings.Contains(content, "class Backend(Protocol):") {
		t.Error("empty schema should not have Backend protocol")
	}
}

func TestPythonQueryLayer_SingleFileGenerate(t *testing.T) {
	schema := qlTestSchema()
	gen := &PythonQueryLayerGenerator{}
	out, diags := gen.Generate(schema)

	if len(diags) > 0 {
		t.Fatalf("unexpected diagnostics: %v", diags)
	}

	content := string(out)
	if !strings.Contains(content, "protocols.py") {
		t.Error("single-file output should contain filename header")
	}
	if !strings.Contains(content, "class Backend(Protocol):") {
		t.Error("single-file output should contain Backend protocol")
	}
}

func TestPythonQueryLayer_CompositePK(t *testing.T) {
	schema := &model.Schema{
		Tables: []model.Table{
			{
				Name:   "join_table",
				Schema: "public",
				PK:     []string{"left_id", "right_id"},
				Columns: []model.Column{
					{Name: "left_id", PGType: "uuid", NotNull: true},
					{Name: "right_id", PGType: "uuid", NotNull: true},
					{Name: "data", PGType: "text", NotNull: false},
				},
			},
		},
	}
	schema.BuildFKGraph()

	gen := &PythonQueryLayerGenerator{}
	files, diags := gen.GenerateFiles(schema)
	if len(diags) > 0 {
		t.Fatalf("unexpected diagnostics: %v", diags)
	}
	content := string(files["protocols.py"])

	// create should return tuple[UUID, UUID].
	assertMethodReturn(t, content, "create_join_table", "tuple[UUID, UUID]")

	// get should take both PK params.
	if !strings.Contains(content, "async def get_join_table(") {
		t.Error("missing get_join_table")
	}
	getSection := extractMethod(content, "get_join_table")
	if !strings.Contains(getSection, "left_id: UUID,") {
		t.Error("get_join_table missing left_id param")
	}
	if !strings.Contains(getSection, "right_id: UUID,") {
		t.Error("get_join_table missing right_id param")
	}
}

// --- Test Helpers ---

// assertFieldPresent checks that the content contains a field with the given
// name and type anywhere in the file (4-space indent for dataclass fields).
func assertFieldPresent(t *testing.T, content, className, fieldName, expectedType string) {
	t.Helper()
	expected := "    " + fieldName + ": " + expectedType
	if !containsLine(content, expected) {
		t.Errorf("%s: missing field %s: %s", className, fieldName, expectedType)
	}
}

// containsLine checks if any line in s exactly matches (after stripping trailing whitespace).
func containsLine(s, target string) bool {
	for _, line := range strings.Split(s, "\n") {
		if strings.TrimRight(line, " \t\r") == target {
			return true
		}
	}
	return false
}

// assertMethodParam checks that a method contains a specific parameter line.
func assertMethodParam(t *testing.T, content, methodName, param string) {
	t.Helper()
	section := extractMethod(content, methodName)
	if section == "" {
		t.Errorf("could not find method %s", methodName)
		return
	}
	if !strings.Contains(section, param) {
		t.Errorf("method %s missing param %q", methodName, param)
	}
}

// assertMethodReturn checks that a method's return type contains the expected type.
func assertMethodReturn(t *testing.T, content, methodName, returnType string) {
	t.Helper()
	section := extractMethod(content, methodName)
	if section == "" {
		t.Errorf("could not find method %s", methodName)
		return
	}
	expected := ") -> " + returnType + ":"
	if !strings.Contains(section, expected) {
		t.Errorf("method %s: expected return type %q, not found in: %s", methodName, returnType, section)
	}
}

// extractMethod extracts the first occurrence of a method definition from
// "async def <name>(" through the next "...\n" line.
func extractMethod(content, methodName string) string {
	marker := "async def " + methodName + "("
	idx := strings.Index(content, marker)
	if idx < 0 {
		return ""
	}
	// Find the end of the method (next "...\n").
	rest := content[idx:]
	endIdx := strings.Index(rest, "...\n")
	if endIdx < 0 {
		return rest
	}
	return rest[:endIdx+4]
}

// extractAfter returns everything after the first occurrence of marker.
func extractAfter(content, marker string) string {
	idx := strings.Index(content, marker)
	if idx < 0 {
		return ""
	}
	return content[idx:]
}
