package codegen

import (
	"bytes"
	"fmt"
	"sort"
	"strings"

	"github.com/smm-h/pgdesign/internal/model"
)

// generateConstraintsFile produces the _constraints.py file content for the
// InMemoryBackend constraint enforcement system. It generates:
// - ConstraintKind enum and Constraint dataclass
// - Per-table <TABLE>_CONSTRAINTS lists derived from the schema
// - ConstraintEngine class with validate_insert, validate_update, process_delete
func generateConstraintsFile(schema *model.Schema) []byte {
	var buf bytes.Buffer
	tables := schema.TableOrder()

	buf.WriteString("# Generated by pgdesign -- do not edit manually.\n")
	buf.WriteString("# Regenerate with: pgdesign codegen --lang python --mode query-layer <schema-files>\n")

	buf.WriteString("\nfrom __future__ import annotations\n")
	buf.WriteString("\nfrom dataclasses import dataclass\n")
	buf.WriteString("from enum import Enum\n")
	buf.WriteString("from typing import Any\n")

	// ConstraintKind enum.
	buf.WriteString("\n\nclass ConstraintKind(Enum):\n")
	buf.WriteString("    NOT_NULL = \"not_null\"\n")
	buf.WriteString("    ENUM = \"enum\"\n")
	buf.WriteString("    UNIQUE = \"unique\"\n")
	buf.WriteString("    FK = \"fk\"\n")
	buf.WriteString("    CHECK_RANGE = \"check_range\"\n")
	buf.WriteString("    CHECK_COMPARISON = \"check_comparison\"\n")
	buf.WriteString("    CHECK_LENGTH = \"check_length\"\n")
	buf.WriteString("    CHECK_PATTERN = \"check_pattern\"\n")
	buf.WriteString("    ON_DELETE_CASCADE = \"on_delete_cascade\"\n")
	buf.WriteString("    ON_DELETE_RESTRICT = \"on_delete_restrict\"\n")
	buf.WriteString("    ON_DELETE_SET_NULL = \"on_delete_set_null\"\n")
	buf.WriteString("    STATE_MACHINE_TRANSITION = \"state_machine_transition\"\n")

	// Constraint dataclass.
	buf.WriteString("\n\n@dataclass(frozen=True)\n")
	buf.WriteString("class Constraint:\n")
	buf.WriteString("    kind: ConstraintKind\n")
	buf.WriteString("    columns: tuple[str, ...]\n")
	buf.WriteString("    params: dict\n")
	buf.WriteString("    message: str\n")

	if len(tables) == 0 {
		return buf.Bytes()
	}

	smMap := buildSMTypeMap(schema)

	// Per-table constraint lists.
	buf.WriteString("\n\n# --- Per-Table Constraint Lists ---\n")
	for _, tbl := range tables {
		writeTableConstraints(&buf, &tbl, schema, smMap)
	}

	// ConstraintEngine class.
	buf.WriteString("\n\n# --- Constraint Engine ---\n")
	writeConstraintEngine(&buf)

	return buf.Bytes()
}

// constraintEntry holds the Python source for one Constraint(...) literal.
type constraintEntry struct {
	kind    string
	columns []string
	params  string // Python dict literal
	message string
}

func (e constraintEntry) write(buf *bytes.Buffer) {
	cols := make([]string, len(e.columns))
	for i, c := range e.columns {
		cols[i] = fmt.Sprintf("%q", c)
	}
	colTuple := strings.Join(cols, ", ")
	if len(cols) == 1 {
		colTuple += ","
	}
	fmt.Fprintf(buf, "    Constraint(\n")
	fmt.Fprintf(buf, "        kind=ConstraintKind.%s,\n", e.kind)
	fmt.Fprintf(buf, "        columns=(%s),\n", colTuple)
	fmt.Fprintf(buf, "        params=%s,\n", e.params)
	fmt.Fprintf(buf, "        message=%q,\n", e.message)
	fmt.Fprintf(buf, "    ),\n")
}

// writeTableConstraints generates the <TABLE>_CONSTRAINTS list for one table.
func writeTableConstraints(buf *bytes.Buffer, tbl *model.Table, schema *model.Schema, smMap map[string]*model.SMTransitionMap) {
	var entries []constraintEntry

	// Extract constraints via the shared constraint extractor.
	cs := ExtractConstraints(*tbl, *schema)

	// NOT_NULL constraints.
	for _, col := range cs.NotNullFields {
		entries = append(entries, constraintEntry{
			kind:    "NOT_NULL",
			columns: []string{col},
			params:  "{}",
			message: fmt.Sprintf("%s must not be null", col),
		})
	}

	// ENUM constraints.
	enumCols := sortedKeys(cs.EnumFields)
	for _, col := range enumCols {
		values := cs.EnumFields[col]
		quoted := make([]string, len(values))
		for i, v := range values {
			quoted[i] = fmt.Sprintf("%q", v)
		}
		entries = append(entries, constraintEntry{
			kind:    "ENUM",
			columns: []string{col},
			params:  fmt.Sprintf("{\"values\": [%s]}", strings.Join(quoted, ", ")),
			message: fmt.Sprintf("%s must be one of the allowed values", col),
		})
	}

	// CHECK constraints (from table checks and domain checks).
	checkCols := sortedKeys(cs.CheckExprs)
	for _, col := range checkCols {
		expr := cs.CheckExprs[col]
		pat := classifyCheck(expr)
		if pat == nil {
			continue
		}
		entry := checkPatternToConstraint(col, pat)
		if entry != nil {
			entries = append(entries, *entry)
		}
	}

	// UNIQUE constraints.
	for _, uq := range tbl.Uniques {
		entries = append(entries, constraintEntry{
			kind:    "UNIQUE",
			columns: uq.Columns,
			params:  "{}",
			message: fmt.Sprintf("%s must be unique", strings.Join(uq.Columns, ", ")),
		})
	}

	// FK constraints (outgoing — existence check on insert/update).
	for _, fk := range tbl.FKs {
		entries = append(entries, constraintEntry{
			kind:    "FK",
			columns: fk.Columns,
			params:  fmt.Sprintf("{\"ref_table\": %q, \"ref_columns\": %s}", fk.RefTable, pyStringList(fk.RefColumns)),
			message: fmt.Sprintf("referenced %s row must exist", fk.RefTable),
		})
	}

	// ON_DELETE constraints from incoming FKs (reverse graph edges).
	if schema.FKGraph != nil {
		// Sort incoming edges for deterministic output.
		type incomingFK struct {
			fromTable  string
			fromColumn string
			onDelete   string
		}
		seen := make(map[string]bool)
		var incoming []incomingFK
		for _, edge := range schema.FKGraph.Reverse[tbl.Name] {
			key := edge.FromTable + "." + edge.FromColumn
			if seen[key] {
				continue
			}
			seen[key] = true
			incoming = append(incoming, incomingFK{
				fromTable:  edge.FromTable,
				fromColumn: edge.FromColumn,
				onDelete:   edge.OnDelete,
			})
		}
		sort.Slice(incoming, func(i, j int) bool {
			if incoming[i].fromTable != incoming[j].fromTable {
				return incoming[i].fromTable < incoming[j].fromTable
			}
			return incoming[i].fromColumn < incoming[j].fromColumn
		})

		for _, inc := range incoming {
			kind := onDeleteToKind(inc.onDelete)
			if kind == "" {
				continue
			}
			// The columns here refer to the PK columns of this table that the child references.
			entries = append(entries, constraintEntry{
				kind:    kind,
				columns: tbl.PK,
				params:  fmt.Sprintf("{\"child_table\": %q, \"child_column\": %q}", inc.fromTable, inc.fromColumn),
				message: fmt.Sprintf("on delete from %s: %s %s", tbl.Name, strings.ToLower(strings.ReplaceAll(kind, "_", " ")), inc.fromTable),
			})
		}
	}

	// STATE_MACHINE_TRANSITION constraints.
	for _, col := range tbl.Columns {
		if smt, ok := smMap[col.SemanticTypeName]; ok {
			// Build transition map as Python dict literal.
			froms := sortedFromStates(*smt)
			var mapParts []string
			for _, from := range froms {
				tos := smt.Transitions[from]
				quotedTos := make([]string, len(tos))
				for i, to := range tos {
					quotedTos[i] = fmt.Sprintf("%q", to)
				}
				mapParts = append(mapParts, fmt.Sprintf("%q: [%s]", from, strings.Join(quotedTos, ", ")))
			}
			params := fmt.Sprintf("{\"transitions\": {%s}}", strings.Join(mapParts, ", "))
			entries = append(entries, constraintEntry{
				kind:    "STATE_MACHINE_TRANSITION",
				columns: []string{col.Name},
				params:  params,
				message: fmt.Sprintf("%s must follow valid state transitions", col.Name),
			})
		}
	}

	varName := strings.ToUpper(tbl.Name) + "_CONSTRAINTS"
	fmt.Fprintf(buf, "\n\n%s: list[Constraint] = [\n", varName)
	for _, entry := range entries {
		entry.write(buf)
	}
	buf.WriteString("]\n")
}

// checkPatternToConstraint converts a classified CHECK pattern into a constraint entry.
func checkPatternToConstraint(col string, pat checkPattern) *constraintEntry {
	switch p := pat.(type) {
	case *rangePattern:
		return &constraintEntry{
			kind:    "CHECK_RANGE",
			columns: []string{col},
			params: fmt.Sprintf("{\"low\": %s, \"high\": %s, \"low_inclusive\": %s, \"high_inclusive\": %s}",
				p.Low, p.High, pyBool(p.LowIncl), pyBool(p.HighIncl)),
			message: fmt.Sprintf("%s must be in range", col),
		}
	case *comparisonPattern:
		return &constraintEntry{
			kind:    "CHECK_COMPARISON",
			columns: []string{col},
			params:  fmt.Sprintf("{\"op\": %q, \"value\": %s}", p.Op, p.Value),
			message: fmt.Sprintf("%s must be %s %s", col, p.Op, p.Value),
		}
	case *lengthPattern:
		return &constraintEntry{
			kind:    "CHECK_LENGTH",
			columns: []string{col},
			params:  fmt.Sprintf("{\"op\": %q, \"value\": %d}", p.Op, p.Value),
			message: fmt.Sprintf("length of %s must be %s %d", col, p.Op, p.Value),
		}
	case *likePattern:
		regex := likeToRegex(p.Pattern)
		negated := strings.HasPrefix(strings.ToUpper(p.Op), "NOT")
		return &constraintEntry{
			kind:    "CHECK_PATTERN",
			columns: []string{col},
			params:  fmt.Sprintf("{\"pattern\": %q, \"negated\": %s}", regex, pyBool(negated)),
			message: fmt.Sprintf("%s must match the required pattern", col),
		}
	}
	return nil
}

// onDeleteToKind maps an ON DELETE action string to the constraint kind name.
func onDeleteToKind(onDelete string) string {
	switch strings.ToUpper(onDelete) {
	case "CASCADE":
		return "ON_DELETE_CASCADE"
	case "RESTRICT", "NO ACTION":
		return "ON_DELETE_RESTRICT"
	case "SET NULL":
		return "ON_DELETE_SET_NULL"
	default:
		return ""
	}
}

// pyBool returns "True" or "False" for a Go bool.
func pyBool(b bool) string {
	if b {
		return "True"
	}
	return "False"
}

// pyStringList produces a Python list literal from a Go string slice.
func pyStringList(ss []string) string {
	quoted := make([]string, len(ss))
	for i, s := range ss {
		quoted[i] = fmt.Sprintf("%q", s)
	}
	return "[" + strings.Join(quoted, ", ") + "]"
}

// sortedKeys returns the sorted keys of a map[string]T.
func sortedKeys[T any](m map[string]T) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

// writeConstraintEngine generates the ConstraintEngine class.
func writeConstraintEngine(buf *bytes.Buffer) {
	buf.WriteString(`

class ConstraintEngine:
    """Validates constraints for the InMemoryBackend.

    All methods are static -- the engine is stateless.
    Stores and unique_indexes are passed explicitly.
    """

    @staticmethod
    def validate_insert(
        table: str,
        constraints: list[Constraint],
        row: dict[str, Any],
        stores: dict[str, dict],
        unique_indexes: dict[str, dict],
    ) -> list[str]:
        """Validate a row before insertion. Returns a list of error messages."""
        errors: list[str] = []
        for c in constraints:
            match c.kind:
                case ConstraintKind.NOT_NULL:
                    col = c.columns[0]
                    if row.get(col) is None:
                        errors.append(c.message)
                case ConstraintKind.ENUM:
                    col = c.columns[0]
                    val = row.get(col)
                    if val is not None and val not in c.params["values"]:
                        errors.append(f"{c.message}: got {val!r}")
                case ConstraintKind.UNIQUE:
                    key = tuple(row.get(col) for col in c.columns)
                    idx_name = f"{table}_{'_'.join(c.columns)}"
                    idx = unique_indexes.get(idx_name, {})
                    if key in idx:
                        errors.append(c.message)
                case ConstraintKind.FK:
                    ref_table = c.params["ref_table"]
                    ref_cols = c.params["ref_columns"]
                    fk_vals = tuple(row.get(col) for col in c.columns)
                    if all(v is not None for v in fk_vals):
                        parent_store = stores.get(ref_table, {})
                        found = False
                        for parent_row in parent_store.values():
                            parent_key = tuple(parent_row.get(rc) for rc in ref_cols)
                            if parent_key == fk_vals:
                                found = True
                                break
                        if not found:
                            errors.append(c.message)
                case ConstraintKind.CHECK_RANGE:
                    col = c.columns[0]
                    val = row.get(col)
                    if val is not None:
                        low = c.params["low"]
                        high = c.params["high"]
                        low_ok = val >= low if c.params["low_inclusive"] else val > low
                        high_ok = val <= high if c.params["high_inclusive"] else val < high
                        if not (low_ok and high_ok):
                            errors.append(c.message)
                case ConstraintKind.CHECK_COMPARISON:
                    col = c.columns[0]
                    val = row.get(col)
                    if val is not None:
                        op = c.params["op"]
                        target = c.params["value"]
                        ok = (
                            (op == ">=" and val >= target) or
                            (op == "<=" and val <= target) or
                            (op == ">" and val > target) or
                            (op == "<" and val < target) or
                            (op == "=" and val == target) or
                            (op == "!=" and val != target) or
                            (op == "<>" and val != target)
                        )
                        if not ok:
                            errors.append(c.message)
                case ConstraintKind.CHECK_LENGTH:
                    col = c.columns[0]
                    val = row.get(col)
                    if val is not None:
                        length = len(val)
                        op = c.params["op"]
                        target = c.params["value"]
                        ok = (
                            (op == ">=" and length >= target) or
                            (op == "<=" and length <= target) or
                            (op == ">" and length > target) or
                            (op == "<" and length < target) or
                            (op == "=" and length == target)
                        )
                        if not ok:
                            errors.append(c.message)
                case ConstraintKind.CHECK_PATTERN:
                    import re
                    col = c.columns[0]
                    val = row.get(col)
                    if val is not None:
                        matches = bool(re.fullmatch(c.params["pattern"], val))
                        if c.params.get("negated"):
                            if matches:
                                errors.append(c.message)
                        else:
                            if not matches:
                                errors.append(c.message)
                case ConstraintKind.STATE_MACHINE_TRANSITION:
                    pass  # Not checked on insert (no old state to transition from)
        return errors

    @staticmethod
    def validate_update(
        table: str,
        constraints: list[Constraint],
        old_row: dict[str, Any],
        new_row: dict[str, Any],
        pk_columns: list[str],
        stores: dict[str, dict],
        unique_indexes: dict[str, dict],
    ) -> list[str]:
        """Validate a row before update. Returns a list of error messages."""
        errors: list[str] = []
        # Build the merged row: start with old, overlay with non-None new values.
        merged = dict(old_row)
        for k, v in new_row.items():
            if v is not None:
                merged[k] = v

        # Remove old unique index entries so re-insertion of same values works.
        for c in constraints:
            if c.kind == ConstraintKind.UNIQUE:
                idx_name = f"{table}_{'_'.join(c.columns)}"
                idx = unique_indexes.get(idx_name, {})
                old_key = tuple(old_row.get(col) for col in c.columns)
                idx.pop(old_key, None)

        # Validate the merged row using insert validation for most constraint types.
        insert_errors = ConstraintEngine.validate_insert(
            table, constraints, merged, stores, unique_indexes,
        )
        errors.extend(insert_errors)

        # State machine transition validation.
        for c in constraints:
            if c.kind == ConstraintKind.STATE_MACHINE_TRANSITION:
                col = c.columns[0]
                new_val = new_row.get(col)
                if new_val is None:
                    continue  # Not updating this column
                old_val = old_row.get(col)
                transitions = c.params["transitions"]
                allowed = transitions.get(old_val, [])
                if new_val not in allowed:
                    errors.append(
                        f"{c.message}: cannot transition from {old_val!r} to {new_val!r}"
                    )

        return errors

    @staticmethod
    def process_delete(
        table: str,
        pk_value: Any,
        all_constraints: dict[str, list[Constraint]],
        stores: dict[str, dict],
        unique_indexes: dict[str, dict],
    ) -> list[str]:
        """Process cascading effects of a delete. Returns error messages if blocked.

        all_constraints maps table name -> list of constraints for that table.
        pk_value is the primary key value of the row being deleted.
        """
        errors: list[str] = []
        table_constraints = all_constraints.get(table, [])

        for c in table_constraints:
            if c.kind == ConstraintKind.ON_DELETE_RESTRICT:
                child_table = c.params["child_table"]
                child_col = c.params["child_column"]
                child_store = stores.get(child_table, {})
                for child_row in child_store.values():
                    if child_row.get(child_col) == pk_value:
                        errors.append(
                            f"cannot delete from {table}: "
                            f"referenced by {child_table}.{child_col}"
                        )
                        break

            elif c.kind == ConstraintKind.ON_DELETE_CASCADE:
                child_table = c.params["child_table"]
                child_col = c.params["child_column"]
                child_store = stores.get(child_table, {})
                # Collect keys to delete (avoid modifying dict during iteration).
                to_delete = [
                    pk for pk, child_row in child_store.items()
                    if child_row.get(child_col) == pk_value
                ]
                for child_pk in to_delete:
                    # Recursively process delete on child.
                    child_errors = ConstraintEngine.process_delete(
                        child_table, child_pk,
                        all_constraints, stores, unique_indexes,
                    )
                    if child_errors:
                        errors.extend(child_errors)
                    else:
                        # Remove unique index entries for the child row.
                        child_row = child_store.get(child_pk)
                        if child_row:
                            child_constraints = all_constraints.get(child_table, [])
                            for cc in child_constraints:
                                if cc.kind == ConstraintKind.UNIQUE:
                                    idx_name = (
                                        f"{child_table}_{'_'.join(cc.columns)}"
                                    )
                                    idx = unique_indexes.get(idx_name, {})
                                    old_key = tuple(
                                        child_row.get(col) for col in cc.columns
                                    )
                                    idx.pop(old_key, None)
                            del child_store[child_pk]

            elif c.kind == ConstraintKind.ON_DELETE_SET_NULL:
                child_table = c.params["child_table"]
                child_col = c.params["child_column"]
                child_store = stores.get(child_table, {})
                for child_row in child_store.values():
                    if child_row.get(child_col) == pk_value:
                        child_row[child_col] = None

        return errors
`)
}
