package codegen

import (
	"bytes"
	"fmt"
	"strings"

	"github.com/smm-h/pgdesign/internal/diagnostic"
	"github.com/smm-h/pgdesign/internal/model"
)

// TSConstraintsGenerator generates TypeScript validation functions for table constraints.
type TSConstraintsGenerator struct{}

// Generate produces a TypeScript file with validate<TableName> functions for each
// table that has extractable constraints.
func (g *TSConstraintsGenerator) Generate(schema *model.Schema) ([]byte, []diagnostic.Diagnostic) {
	var buf bytes.Buffer
	buf.WriteString("// Code generated by pgdesign -- do not edit.\n")
	buf.WriteString("// Regenerate with: pgdesign codegen --lang ts --mode constraints <schema-files>\n")
	if schema.Name != "" {
		fmt.Fprintf(&buf, "// Schema: %s\n", schema.Name)
	}

	// Write shared types.
	buf.WriteString(`
export interface ValidationError {
  field: string
  message: string
}
`)

	// Collect tables with constraints.
	type tableWork struct {
		table model.Table
		cs    ConstraintSet
	}
	var work []tableWork
	for _, tbl := range schema.Tables {
		cs := ExtractConstraints(tbl, *schema)
		if !cs.HasConstraints() {
			continue
		}
		work = append(work, tableWork{table: tbl, cs: cs})
	}

	if len(work) == 0 {
		buf.WriteString("\n// No tables with extractable constraints.\n")
		return buf.Bytes(), nil
	}

	for _, tw := range work {
		writeTSValidator(&buf, tw.table, tw.cs)
	}

	return buf.Bytes(), nil
}

func writeTSValidator(buf *bytes.Buffer, table model.Table, cs ConstraintSet) {
	funcName := "validate" + toPascalCase(table.Name)
	typeName := toPascalCase(table.Name)

	fmt.Fprintf(buf, "\n// %s validates constraint rules for the %s table.\n", funcName, table.Name)
	fmt.Fprintf(buf, "export function %s(row: Partial<%s>): ValidationError[] {\n", funcName, typeName)
	buf.WriteString("  const errors: ValidationError[] = []\n")

	// NOT NULL checks.
	for _, col := range cs.NotNullFields {
		tsField := toCamelCase(col)
		pgType := columnPGType(table, col)
		if isStringPGType(pgType) {
			fmt.Fprintf(buf, "  if (row.%s == null || row.%s === \"\") {\n", tsField, tsField)
		} else {
			fmt.Fprintf(buf, "  if (row.%s == null) {\n", tsField)
		}
		fmt.Fprintf(buf, "    errors.push({ field: %q, message: \"must not be empty\" })\n", col)
		buf.WriteString("  }\n")
	}

	// Enum checks.
	for col, values := range cs.EnumFields {
		tsField := toCamelCase(col)
		quoted := make([]string, len(values))
		for i, v := range values {
			quoted[i] = fmt.Sprintf("%q", v)
		}
		fmt.Fprintf(buf, "  if (row.%s != null && ![%s].includes(row.%s)) {\n",
			tsField, strings.Join(quoted, ", "), tsField)
		fmt.Fprintf(buf, "    errors.push({ field: %q, message: `invalid value \"${row.%s}\"` })\n", col, tsField)
		buf.WriteString("  }\n")
	}

	// CHECK constraint checks.
	for col, expr := range cs.CheckExprs {
		tsField := toCamelCase(col)
		pat := classifyCheck(expr)
		if pat == nil {
			fmt.Fprintf(buf, "  // CHECK on %s: %s (unrecognized pattern, skipped)\n", col, expr)
			continue
		}
		writeTSCheckPattern(buf, col, tsField, pat)
	}

	buf.WriteString("  return errors\n")
	buf.WriteString("}\n")
}

func writeTSCheckPattern(buf *bytes.Buffer, col, tsField string, pat checkPattern) {
	switch p := pat.(type) {
	case *rangePattern:
		var lowOp, highOp string
		if p.LowIncl {
			lowOp = "<"
		} else {
			lowOp = "<="
		}
		if p.HighIncl {
			highOp = ">"
		} else {
			highOp = ">="
		}
		fmt.Fprintf(buf, "  if (row.%s != null && (row.%s %s %s || row.%s %s %s)) {\n",
			tsField, tsField, lowOp, p.Low, tsField, highOp, p.High)
		fmt.Fprintf(buf, "    errors.push({ field: %q, message: \"value out of range\" })\n", col)
		buf.WriteString("  }\n")

	case *comparisonPattern:
		failOp := invertComparisonOp(p.Op)
		tsOp := failOp
		if tsOp == "!=" {
			tsOp = "!=="
		} else if tsOp == "==" {
			tsOp = "==="
		}
		fmt.Fprintf(buf, "  if (row.%s != null && row.%s %s %s) {\n", tsField, tsField, tsOp, p.Value)
		fmt.Fprintf(buf, "    errors.push({ field: %q, message: \"failed check: %s %s\" })\n", col, p.Op, p.Value)
		buf.WriteString("  }\n")

	case *lengthPattern:
		failOp := invertComparisonOp(p.Op)
		fmt.Fprintf(buf, "  if (row.%s != null && row.%s.length %s %d) {\n", tsField, tsField, failOp, p.Value)
		fmt.Fprintf(buf, "    errors.push({ field: %q, message: `length must be %s %d, got ${row.%s.length}` })\n", col, p.Op, p.Value, tsField)
		buf.WriteString("  }\n")

	case *likePattern:
		regex := likeToRegex(p.Pattern)
		if strings.HasPrefix(strings.ToUpper(p.Op), "NOT") {
			fmt.Fprintf(buf, "  if (row.%s != null && /%s/.test(row.%s)) {\n", tsField, escapeJSRegex(regex), tsField)
		} else {
			fmt.Fprintf(buf, "  if (row.%s != null && !/%s/.test(row.%s)) {\n", tsField, escapeJSRegex(regex), tsField)
		}
		fmt.Fprintf(buf, "    errors.push({ field: %q, message: \"does not match required pattern\" })\n", col)
		buf.WriteString("  }\n")
	}
}
