package codegen

import (
	"strings"
	"testing"

	"github.com/smm-h/pgdesign/internal/model"
)

func TestTSConstraintsGenerator_Generate(t *testing.T) {
	schema := &model.Schema{
		Name: "app",
		Enums: []model.Enum{
			{Name: "role", Values: []string{"admin", "user", "guest"}},
		},
		Tables: []model.Table{
			{
				Name: "users",
				Columns: []model.Column{
					{Name: "id", PGType: "bigint", NotNull: true},
					{Name: "name", PGType: "text", NotNull: true},
					{Name: "email", PGType: "text", NotNull: true},
					{Name: "role", PGType: "role", NotNull: true},
					{Name: "age", PGType: "integer", NotNull: true},
					{Name: "slug", PGType: "varchar", NotNull: true},
					{Name: "profile_data", PGType: "jsonb", NotNull: true, JSONSchema: "schemas/profile.json"},
				},
				PK: []string{"id"},
				Checks: []model.CheckConstraint{
					{Name: "ck_users_age_range", Expr: "age >= 0 AND age <= 150"},
					{Name: "ck_users_email_fmt", Expr: "email LIKE '%@%'"},
					{Name: "ck_users_slug_len", Expr: "LENGTH(slug) <= 100"},
				},
			},
		},
	}

	gen := &TSConstraintsGenerator{}
	out, diags := gen.Generate(schema)
	if len(diags) > 0 {
		t.Fatalf("unexpected diagnostics: %v", diags)
	}

	result := string(out)

	// Header.
	if !strings.Contains(result, "Code generated by pgdesign") {
		t.Error("missing header comment")
	}

	// ValidationError interface.
	if !strings.Contains(result, "export interface ValidationError") {
		t.Error("missing ValidationError interface")
	}

	// Validate function.
	if !strings.Contains(result, "export function validateUsers(row: Partial<Users>): ValidationError[]") {
		t.Error("missing validateUsers function signature")
	}

	// NOT NULL checks for string-type columns.
	if !strings.Contains(result, `row.name == null || row.name === ""`) {
		t.Error("missing NOT NULL check for name")
	}
	if !strings.Contains(result, `row.email == null || row.email === ""`) {
		t.Error("missing NOT NULL check for email")
	}
	if !strings.Contains(result, `row.slug == null || row.slug === ""`) {
		t.Error("missing NOT NULL check for slug")
	}

	// NOT NULL check for non-string column (age is integer, check is != null only).
	if !strings.Contains(result, "row.age == null") {
		t.Error("missing NOT NULL check for age")
	}

	// Enum check.
	if !strings.Contains(result, `"admin"`) {
		t.Error("missing enum value 'admin'")
	}
	if !strings.Contains(result, `"user"`) {
		t.Error("missing enum value 'user'")
	}
	if !strings.Contains(result, `"guest"`) {
		t.Error("missing enum value 'guest'")
	}
	if !strings.Contains(result, ".includes(row.role)") {
		t.Error("missing .includes() call for enum check")
	}

	// Range check for age (guarded with null check).
	if !strings.Contains(result, "row.age != null") {
		t.Error("missing null guard for age range check")
	}
	if !strings.Contains(result, "150") {
		t.Error("missing age upper bound 150")
	}

	// LIKE check for email -> regex.
	if !strings.Contains(result, ".test(row.email)") {
		t.Error("missing regex .test() for email LIKE check")
	}

	// Length check for slug.
	if !strings.Contains(result, "row.slug.length") {
		t.Error("missing length check for slug")
	}
	if !strings.Contains(result, "100") {
		t.Error("missing length limit 100")
	}
}

func TestTSConstraintsGenerator_EmptySchema(t *testing.T) {
	schema := &model.Schema{
		Name: "empty",
	}

	gen := &TSConstraintsGenerator{}
	out, diags := gen.Generate(schema)
	if len(diags) > 0 {
		t.Fatalf("unexpected diagnostics: %v", diags)
	}

	result := string(out)
	if !strings.Contains(result, "No tables with extractable constraints.") {
		t.Error("missing empty-schema comment")
	}
	if strings.Contains(result, "export function validate") {
		t.Error("should not contain any validate functions for empty schema")
	}
}

func TestTSConstraintsGenerator_NoConstraints(t *testing.T) {
	schema := &model.Schema{
		Tables: []model.Table{
			{
				Name: "simple",
				Columns: []model.Column{
					{Name: "id", PGType: "bigint", NotNull: true},
				},
				PK: []string{"id"},
			},
		},
	}

	gen := &TSConstraintsGenerator{}
	out, diags := gen.Generate(schema)
	if len(diags) > 0 {
		t.Fatalf("unexpected diagnostics: %v", diags)
	}

	result := string(out)
	if !strings.Contains(result, "No tables with extractable constraints.") {
		t.Error("missing no-constraints comment")
	}
}
