package codegen

import (
	"bytes"
	"fmt"
	"sort"
	"strings"

	"github.com/smm-h/pgdesign/internal/diagnostic"
	"github.com/smm-h/pgdesign/internal/model"
)

// TSDrizzleGenerator generates Drizzle ORM schema TypeScript code corresponding
// to database tables, including column definitions, indexes, and relations.
type TSDrizzleGenerator struct{}

// Generate produces a TypeScript source file with Drizzle ORM table definitions,
// index declarations, and relation blocks for all tables in the schema.
func (g *TSDrizzleGenerator) Generate(schema *model.Schema) ([]byte, []diagnostic.Diagnostic) {
	var buf bytes.Buffer
	header := "// Code generated by pgdesign -- do not edit.\n"

	if len(schema.Tables) == 0 {
		buf.WriteString(header)
		return buf.Bytes(), nil
	}

	if schema.FKGraph == nil {
		schema.BuildFKGraph()
	}

	// First pass: collect all table info and track required imports.
	pgCoreImports := make(map[string]bool)
	pgCoreImports["pgTable"] = true // always needed
	needRelations := false
	needSqlTemplate := false

	type colInfo struct {
		FieldName string // camelCase JS field name
		ColName   string // original PG column name
		Builder   string // Drizzle builder function name
		Comment   string // optional trailing comment
		Modifiers string // chained method calls
	}

	type extraDef struct {
		Code string // e.g., primaryKey(...), uniqueIndex(...), index(...)
	}

	type tableInfo struct {
		VarName   string
		TableName string
		Columns   []colInfo
		Extras    []extraDef // third-argument entries (composite PK, indexes)
	}

	type oneRelation struct {
		FieldName string
		RefVar    string
		LocalCol  string
		RefCol    string
	}

	type manyRelation struct {
		FieldName string
		RefVar    string
	}

	type relationInfo struct {
		TableVar string
		Ones     []oneRelation
		Manys    []manyRelation
	}

	// Enum declarations: schema.Enums covers both enum and state_machine kinds
	// (build.go appends state machines to Enums). Each entry becomes a local
	// pgEnum const used as the column builder for columns of that type. The
	// "Enum" suffix avoids collisions with table variable names.
	type enumDecl struct {
		ConstName string
		TypeName  string
		Values    []string
	}
	var enumDecls []enumDecl
	// enumConstNames maps a column's PGType.Base to the local const name.
	// Keyed by both bare and schema-qualified names because introspection may
	// schema-qualify types outside the search path.
	enumConstNames := make(map[string]string, len(schema.Enums)*2)
	if len(schema.Enums) > 0 {
		pgCoreImports["pgEnum"] = true
		sortedEnums := make([]model.Enum, len(schema.Enums))
		copy(sortedEnums, schema.Enums)
		sort.Slice(sortedEnums, func(i, j int) bool { return sortedEnums[i].Name < sortedEnums[j].Name })
		for _, e := range sortedEnums {
			constName := toCamelCase(e.Name) + "Enum"
			enumDecls = append(enumDecls, enumDecl{ConstName: constName, TypeName: e.Name, Values: e.Values})
			enumConstNames[e.Name] = constName
			if e.Schema != "" {
				enumConstNames[e.Schema+"."+e.Name] = constName
			}
		}
	}

	var tables []tableInfo
	relationsMap := make(map[string]*relationInfo) // keyed by table name

	ensureRelInfo := func(tableName, varName string) *relationInfo {
		ri, ok := relationsMap[tableName]
		if !ok {
			ri = &relationInfo{TableVar: varName}
			relationsMap[tableName] = ri
		}
		return ri
	}

	for _, tbl := range schema.Tables {
		varName := toCamelCase(tbl.Name)
		ti := tableInfo{
			VarName:   varName,
			TableName: tbl.Name,
		}

		pkSet := make(map[string]bool, len(tbl.PK))
		for _, pk := range tbl.PK {
			pkSet[pk] = true
		}
		isSinglePK := len(tbl.PK) == 1

		for _, col := range tbl.Columns {
			var builder, comment string
			if constName, ok := enumConstNames[col.PGType.Base]; ok &&
				(col.TypeKind == "enum" || col.TypeKind == "state_machine") {
				// Local pgEnum const as builder. Must NOT be registered in
				// pgCoreImports -- it is a local declaration, not an import.
				builder = constName
			} else {
				builder, comment = pgTypeToDrizzleBuilder(col.PGType.Base)
				pgCoreImports[builder] = true
			}

			var mods strings.Builder

			// .primaryKey() for single-column PKs
			if isSinglePK && pkSet[col.Name] {
				mods.WriteString(".primaryKey()")
			}

			// .notNull()
			if col.NotNull {
				mods.WriteString(".notNull()")
			}

			// .default(...)
			if col.Default != nil {
				def := *col.Default
				mods.WriteString(drizzleDefault(def, &needSqlTemplate))
			} else if col.DefaultExpr != "" {
				needSqlTemplate = true
				mods.WriteString(fmt.Sprintf(".default(sql`%s`)", col.DefaultExpr))
			}

			// .array()
			if col.Array {
				mods.WriteString(".array()")
			}

			ti.Columns = append(ti.Columns, colInfo{
				FieldName: toCamelCase(col.Name),
				ColName:   col.Name,
				Builder:   builder,
				Comment:   comment,
				Modifiers: mods.String(),
			})
		}

		// Composite PK (>1 column).
		if len(tbl.PK) > 1 {
			pgCoreImports["primaryKey"] = true
			var cols []string
			for _, pk := range tbl.PK {
				cols = append(cols, "table."+toCamelCase(pk))
			}
			ti.Extras = append(ti.Extras, extraDef{
				Code: fmt.Sprintf("primaryKey({ columns: [%s] })", strings.Join(cols, ", ")),
			})
		}

		// Unique indexes.
		for _, idx := range tbl.Indexes {
			var cols []string
			for _, c := range idx.Columns {
				cols = append(cols, "table."+toCamelCase(c))
			}
			if idx.Unique {
				pgCoreImports["uniqueIndex"] = true
				ti.Extras = append(ti.Extras, extraDef{
					Code: fmt.Sprintf("uniqueIndex(%q).on(%s)", idx.Name, strings.Join(cols, ", ")),
				})
			} else {
				pgCoreImports["index"] = true
				ti.Extras = append(ti.Extras, extraDef{
					Code: fmt.Sprintf("index(%q).on(%s)", idx.Name, strings.Join(cols, ", ")),
				})
			}
		}

		// Unique constraints.
		for _, uc := range tbl.Uniques {
			pgCoreImports["uniqueIndex"] = true
			var cols []string
			for _, c := range uc.Columns {
				cols = append(cols, "table."+toCamelCase(c))
			}
			ti.Extras = append(ti.Extras, extraDef{
				Code: fmt.Sprintf("uniqueIndex(%q).on(%s)", uc.Name, strings.Join(cols, ", ")),
			})
		}

		tables = append(tables, ti)

		// Collect outgoing FK relations (one).
		for _, fk := range tbl.FKs {
			if len(fk.Columns) == 1 {
				needRelations = true
				ri := ensureRelInfo(tbl.Name, varName)
				ri.Ones = append(ri.Ones, oneRelation{
					FieldName: toCamelCase(fk.RefTable),
					RefVar:    toCamelCase(fk.RefTable),
					LocalCol:  toCamelCase(fk.Columns[0]),
					RefCol:    toCamelCase(fk.RefColumns[0]),
				})
			}
		}

		// Collect incoming FK relations (many).
		if edges := schema.FKGraph.Reverse[tbl.Name]; len(edges) > 0 {
			fkColCount := make(map[string]int)
			for _, e := range edges {
				fkColCount[e.FKName]++
			}
			seen := make(map[string]bool)
			for _, e := range edges {
				if fkColCount[e.FKName] != 1 || seen[e.FKName] {
					continue
				}
				seen[e.FKName] = true
				needRelations = true
				ri := ensureRelInfo(tbl.Name, varName)
				fieldName := toCamelCase(e.FromTable)
				if !strings.HasSuffix(fieldName, "s") {
					fieldName += "s"
				}
				ri.Manys = append(ri.Manys, manyRelation{
					FieldName: fieldName,
					RefVar:    toCamelCase(e.FromTable),
				})
			}
		}
	}

	// Second pass: write output.
	buf.WriteString(header)
	buf.WriteString("\n")

	// Build pg-core import list.
	var pgCoreNames []string
	for name := range pgCoreImports {
		pgCoreNames = append(pgCoreNames, name)
	}
	sort.Strings(pgCoreNames)

	fmt.Fprintf(&buf, "import { %s } from \"drizzle-orm/pg-core\";\n", strings.Join(pgCoreNames, ", "))

	if needRelations {
		buf.WriteString("import { relations } from \"drizzle-orm\";\n")
	}
	if needSqlTemplate {
		buf.WriteString("import { sql } from \"drizzle-orm\";\n")
	}

	// Write enum declarations before table definitions.
	if len(enumDecls) > 0 {
		buf.WriteString("\n")
		for _, d := range enumDecls {
			quoted := make([]string, len(d.Values))
			for i, v := range d.Values {
				quoted[i] = fmt.Sprintf("%q", v)
			}
			fmt.Fprintf(&buf, "export const %s = pgEnum(%q, [%s]);\n", d.ConstName, d.TypeName, strings.Join(quoted, ", "))
		}
	}

	// Write table definitions.
	for _, ti := range tables {
		buf.WriteString("\n")
		fmt.Fprintf(&buf, "export const %s = pgTable(%q, {\n", ti.VarName, ti.TableName)
		for _, col := range ti.Columns {
			line := fmt.Sprintf("  %s: %s(%q)%s,", col.FieldName, col.Builder, col.ColName, col.Modifiers)
			if col.Comment != "" {
				line += " " + col.Comment
			}
			buf.WriteString(line)
			buf.WriteString("\n")
		}
		if len(ti.Extras) > 0 {
			buf.WriteString("}, (table) => [\n")
			for _, extra := range ti.Extras {
				fmt.Fprintf(&buf, "  %s,\n", extra.Code)
			}
			buf.WriteString("]);\n")
		} else {
			buf.WriteString("});\n")
		}
	}

	// Write relations blocks.
	if needRelations {
		// Emit in deterministic order (same order as tables).
		for _, tbl := range schema.Tables {
			ri, ok := relationsMap[tbl.Name]
			if !ok {
				continue
			}
			if len(ri.Ones) == 0 && len(ri.Manys) == 0 {
				continue
			}

			// Determine destructuring.
			hasOne := len(ri.Ones) > 0
			hasMany := len(ri.Manys) > 0
			var destructure []string
			if hasOne {
				destructure = append(destructure, "one")
			}
			if hasMany {
				destructure = append(destructure, "many")
			}

			buf.WriteString("\n")
			fmt.Fprintf(&buf, "export const %sRelations = relations(%s, ({ %s }) => ({\n",
				ri.TableVar, ri.TableVar, strings.Join(destructure, ", "))

			for _, rel := range ri.Ones {
				fmt.Fprintf(&buf, "  %s: one(%s, {\n", rel.FieldName, rel.RefVar)
				fmt.Fprintf(&buf, "    fields: [%s.%s],\n", ri.TableVar, rel.LocalCol)
				fmt.Fprintf(&buf, "    references: [%s.%s],\n", rel.RefVar, rel.RefCol)
				buf.WriteString("  }),\n")
			}
			for _, rel := range ri.Manys {
				fmt.Fprintf(&buf, "  %s: many(%s),\n", rel.FieldName, rel.RefVar)
			}

			buf.WriteString("}));\n")
		}
	}

	return buf.Bytes(), nil
}

// pgTypeToDrizzleBuilder maps a PostgreSQL type to a Drizzle column builder
// function name and an optional trailing comment. Unrecognized types fall back
// to "text" with a comment noting the original type.
func pgTypeToDrizzleBuilder(pgType string) (builder string, comment string) {
	switch pgType {
	case "text", "varchar", "char", "bpchar":
		return "text", ""
	case "int4":
		return "integer", ""
	case "int8":
		return "bigint", ""
	case "int2":
		return "smallint", ""
	case "float4":
		return "real", ""
	case "float8":
		return "doublePrecision", ""
	case "bool":
		return "boolean", ""
	case "uuid":
		return "uuid", ""
	case "timestamptz", "timestamp":
		return "timestamp", ""
	case "date":
		return "date", ""
	case "numeric":
		return "numeric", ""
	case "jsonb":
		return "jsonb", ""
	case "json":
		return "json", ""
	case "bytea":
		return "text", "// bytea"
	case "interval":
		return "interval", ""
	case "serial":
		return "serial", ""
	default:
		return "text", "// " + pgType
	}
}

// drizzleDefault converts a PostgreSQL default value to a Drizzle modifier string.
// It sets *needSql to true if the sql“ template tag is required.
func drizzleDefault(def string, needSql *bool) string {
	lower := strings.ToLower(strings.TrimSpace(def))

	// Timestamp defaults.
	if lower == "now()" || lower == "current_timestamp" {
		return ".defaultNow()"
	}

	// Boolean defaults.
	if lower == "true" {
		return ".default(true)"
	}
	if lower == "false" {
		return ".default(false)"
	}

	// Numeric defaults: try to detect integer or float-like strings.
	if looksNumeric(def) {
		return fmt.Sprintf(".default(%s)", strings.TrimSpace(def))
	}

	// Everything else uses the sql template tag.
	*needSql = true
	return fmt.Sprintf(".default(sql`%s`)", def)
}

// looksNumeric returns true if s looks like a plain numeric literal (integer or
// decimal, optionally negative). It does not accept scientific notation or
// strings with embedded spaces.
func looksNumeric(s string) bool {
	s = strings.TrimSpace(s)
	if s == "" {
		return false
	}
	dotSeen := false
	for i, ch := range s {
		if ch == '-' && i == 0 {
			continue
		}
		if ch == '.' && !dotSeen {
			dotSeen = true
			continue
		}
		if ch < '0' || ch > '9' {
			return false
		}
	}
	// Reject bare "-" or bare "."
	stripped := strings.TrimLeft(s, "-")
	return stripped != "" && stripped != "."
}
