package codegen

import (
	"strings"
	"testing"

	"github.com/smm-h/pgdesign/internal/model"
	"github.com/smm-h/pgdesign/internal/typeinfo"
)

// containsTSField checks that at least one line in s contains the camelCase
// field name and the TypeScript type in the format "fieldName: type;".
func containsTSField(s, fieldName, tsType string) bool {
	for _, line := range strings.Split(s, "\n") {
		trimmed := strings.TrimSpace(line)
		if strings.Contains(trimmed, fieldName+": "+tsType+";") {
			return true
		}
	}
	return false
}

func TestTSTypesGenerator_Basic(t *testing.T) {
	schema := &model.Schema{
		Tables: []model.Table{
			{
				Name:    "users",
				Schema:  "public",
				Comment: "Application users",
				Columns: []model.Column{
					{Name: "id", PGType: typeinfo.MustParse("uuid"), NotNull: true},
					{Name: "email", PGType: typeinfo.MustParse("text"), NotNull: true},
					{Name: "score", PGType: typeinfo.MustParse("bigint"), NotNull: true},
					{Name: "is_active", PGType: typeinfo.MustParse("boolean"), NotNull: true},
					{Name: "created_at", PGType: typeinfo.MustParse("timestamptz"), NotNull: true},
					{Name: "metadata", PGType: typeinfo.MustParse("jsonb"), NotNull: true},
					{Name: "age", PGType: typeinfo.MustParse("integer"), NotNull: true},
					{Name: "rating", PGType: typeinfo.MustParse("double precision"), NotNull: true},
					{Name: "avatar", PGType: typeinfo.MustParse("bytea"), NotNull: true},
					{Name: "balance", PGType: typeinfo.MustParse("numeric"), NotNull: true},
				},
			},
		},
	}

	gen := &TSTypesGenerator{}
	out, diags := gen.Generate(schema)
	if len(diags) > 0 {
		t.Fatalf("unexpected diagnostics: %v", diags)
	}

	result := string(out)

	// Header.
	if !strings.Contains(result, "// Code generated by pgdesign -- do not edit.") {
		t.Error("missing generated header comment")
	}

	// Interface comment and declaration.
	if !strings.Contains(result, "/** Represents the users table. */") {
		t.Error("missing interface comment")
	}
	if !strings.Contains(result, "export interface Users {") {
		t.Error("missing interface declaration")
	}

	// Fields with correct types.
	if !containsTSField(result, "id", "string") {
		t.Error("missing or incorrect id field (expected string for uuid)")
	}
	if !containsTSField(result, "email", "string") {
		t.Error("missing or incorrect email field (expected string)")
	}
	if !containsTSField(result, "score", "number") {
		t.Error("missing or incorrect score field (expected number for bigint)")
	}
	if !containsTSField(result, "isActive", "boolean") {
		t.Error("missing or incorrect isActive field (expected boolean)")
	}
	if !containsTSField(result, "createdAt", "Date") {
		t.Error("missing or incorrect createdAt field (expected Date for timestamptz)")
	}
	if !containsTSField(result, "metadata", "Record<string, unknown>") {
		t.Error("missing or incorrect metadata field (expected Record<string, unknown> for jsonb)")
	}
	if !containsTSField(result, "age", "number") {
		t.Error("missing or incorrect age field (expected number for integer)")
	}
	if !containsTSField(result, "rating", "number") {
		t.Error("missing or incorrect rating field (expected number for double precision)")
	}
	if !containsTSField(result, "avatar", "Uint8Array") {
		t.Error("missing or incorrect avatar field (expected Uint8Array for bytea)")
	}
	if !containsTSField(result, "balance", "string") {
		t.Error("missing or incorrect balance field (expected string for numeric)")
	}

	// No imports should be present (TS types are all built-in).
	if strings.Contains(result, "import ") {
		t.Error("unexpected import statement")
	}
}

func TestTSTypesGenerator_NullableAndArray(t *testing.T) {
	schema := &model.Schema{
		Tables: []model.Table{
			{
				Name:    "items",
				Comment: "Test items",
				Columns: []model.Column{
					{Name: "id", PGType: typeinfo.MustParse("integer"), NotNull: true},
					{Name: "name", PGType: typeinfo.MustParse("text"), NotNull: false},
					{Name: "tags", PGType: typeinfo.MustParse("text"), NotNull: true, Array: true},
					{Name: "scores", PGType: typeinfo.MustParse("integer"), NotNull: false, Array: true},
					{Name: "status", PGType: typeinfo.MustParse("user_status"), NotNull: true},
				},
			},
		},
	}

	gen := &TSTypesGenerator{}
	out, diags := gen.Generate(schema)
	if len(diags) > 0 {
		t.Fatalf("unexpected diagnostics: %v", diags)
	}

	result := string(out)

	// Not-null, not-array: plain type.
	if !containsTSField(result, "id", "number") {
		t.Error("missing or incorrect id field (expected number)")
	}

	// Nullable: T | null.
	if !containsTSField(result, "name", "string | null") {
		t.Error("missing or incorrect name field (expected string | null)")
	}

	// Array: T[].
	if !containsTSField(result, "tags", "string[]") {
		t.Error("missing or incorrect tags field (expected string[])")
	}

	// Nullable + array: T[] | null.
	if !containsTSField(result, "scores", "number[] | null") {
		t.Error("missing or incorrect scores field (expected number[] | null)")
	}

	// Enum (unrecognized PG type): string.
	if !containsTSField(result, "status", "string") {
		t.Error("missing or incorrect status field (expected string for enum)")
	}
}

func TestTSTypesGenerator_EmptySchema(t *testing.T) {
	schema := &model.Schema{Tables: []model.Table{}}

	gen := &TSTypesGenerator{}
	out, diags := gen.Generate(schema)
	if len(diags) > 0 {
		t.Fatalf("unexpected diagnostics: %v", diags)
	}

	result := string(out)

	if !strings.Contains(result, "// Code generated by pgdesign -- do not edit.") {
		t.Error("missing generated header comment")
	}
	if strings.Contains(result, "export interface") {
		t.Error("empty schema should not have interface declarations")
	}
	if strings.Contains(result, "import ") {
		t.Error("empty schema should not have imports")
	}
}

func TestTSTypesGenerator_MoneySemanticType(t *testing.T) {
	schema := &model.Schema{
		Tables: []model.Table{
			{
				Name:    "products",
				Comment: "Products",
				Columns: []model.Column{
					{Name: "id", PGType: typeinfo.MustParse("integer"), NotNull: true},
					{Name: "price", PGType: typeinfo.MustParse("bigint"), NotNull: true, SemanticTypeName: "money"},
				},
			},
		},
	}

	gen := &TSTypesGenerator{}
	out, diags := gen.Generate(schema)
	if len(diags) > 0 {
		t.Fatalf("unexpected diagnostics: %v", diags)
	}

	result := string(out)

	// Money semantic type should map to number.
	if !containsTSField(result, "price", "number") {
		t.Error("missing or incorrect price field (expected number for money semantic type)")
	}
}

func TestTSTypesGenerator_MultipleTables(t *testing.T) {
	schema := &model.Schema{
		Tables: []model.Table{
			{
				Name:    "orders",
				Comment: "Orders",
				Columns: []model.Column{
					{Name: "id", PGType: typeinfo.MustParse("uuid"), NotNull: true},
					{Name: "total", PGType: typeinfo.MustParse("numeric"), NotNull: true},
				},
			},
			{
				Name:    "order_items",
				Comment: "Order items",
				Columns: []model.Column{
					{Name: "id", PGType: typeinfo.MustParse("integer"), NotNull: true},
					{Name: "quantity", PGType: typeinfo.MustParse("smallint"), NotNull: true},
				},
			},
		},
	}

	gen := &TSTypesGenerator{}
	out, diags := gen.Generate(schema)
	if len(diags) > 0 {
		t.Fatalf("unexpected diagnostics: %v", diags)
	}

	result := string(out)

	// Both interface declarations present.
	if !strings.Contains(result, "export interface Orders {") {
		t.Error("missing Orders interface declaration")
	}
	if !strings.Contains(result, "export interface OrderItems {") {
		t.Error("missing OrderItems interface declaration")
	}

	// Spot-check a field from the second table.
	if !containsTSField(result, "quantity", "number") {
		t.Error("missing or incorrect quantity field (expected number)")
	}
}
