package codegen

import (
	"strings"
	"testing"

	"github.com/smm-h/pgdesign/internal/diagnostic"
	"github.com/smm-h/pgdesign/internal/model"
)

func TestTSValidatorGenerator_Generate(t *testing.T) {
	schema := &model.Schema{
		Name: "game",
		Tables: []model.Table{
			{
				Name:   "chat_messages",
				Schema: "game",
				Policies: []model.Policy{
					{
						Name:      "chat_read_all",
						Operation: "SELECT",
						Using:     "true",
					},
					{
						Name:         "chat_requires_enabled",
						Operation:    "INSERT",
						WithCheck:    "sender_id::text = current_setting('app.player_id') AND EXISTS (SELECT 1 FROM game.player_privacy_settings WHERE player_id = sender_id AND chat_enabled = true)",
						ErrorCode:    "chat_disabled",
						ErrorMessage: "Chat is disabled in your privacy settings",
					},
				},
			},
			{
				Name:   "follow",
				Schema: "game",
				Policies: []model.Policy{
					{
						Name:         "follow_requires_friends_enabled",
						Operation:    "INSERT",
						WithCheck:    "follower_id::text = current_setting('app.player_id') AND EXISTS (SELECT 1 FROM game.player_privacy_settings WHERE player_id = followed_id AND friends_enabled = true)",
						ErrorCode:    "target_friends_disabled",
						ErrorMessage: "This player has disabled friend/follow requests",
					},
				},
			},
		},
	}

	gen := &TSValidatorGenerator{}
	out, diags := gen.Generate(schema)
	if len(diags) > 0 {
		t.Fatalf("unexpected diagnostics: %v", diags)
	}

	result := string(out)

	// Header checks.
	if !strings.Contains(result, "// Generated by pgdesign -- do not edit manually.") {
		t.Error("missing header comment")
	}
	if !strings.Contains(result, "// Regenerate with: pgdesign codegen --lang ts <schema-files>") {
		t.Error("missing regenerate instruction in header")
	}
	if !strings.Contains(result, "export interface PolicyResult {") {
		t.Error("missing PolicyResult interface")
	}
	if !strings.Contains(result, `import { PoolClient } from "pg"`) {
		t.Error("missing pg import")
	}

	// chat_requires_enabled validator.
	if !strings.Contains(result, "export async function checkChatRequiresEnabled(client: PoolClient, sender_id: string): Promise<PolicyResult> {") {
		t.Error("missing chat_requires_enabled function signature")
	}
	if !strings.Contains(result, "SELECT chat_enabled FROM game.player_privacy_settings WHERE player_id = $1") {
		t.Error("missing chat_enabled query")
	}
	if !strings.Contains(result, `code: "chat_disabled"`) {
		t.Error("missing chat_disabled error code")
	}

	// follow_requires_friends_enabled validator.
	if !strings.Contains(result, "export async function checkFollowRequiresFriendsEnabled(client: PoolClient, followed_id: string): Promise<PolicyResult> {") {
		t.Error("missing follow_requires_friends_enabled function signature")
	}
	if !strings.Contains(result, "SELECT friends_enabled FROM game.player_privacy_settings WHERE player_id = $1") {
		t.Error("missing friends_enabled query")
	}
	if !strings.Contains(result, `code: "target_friends_disabled"`) {
		t.Error("missing target_friends_disabled error code")
	}

	// Should NOT contain the read_all policy (no error code).
	if strings.Contains(result, "checkChatReadAll") {
		t.Error("should not generate validator for read_all policy")
	}
}

func TestTSValidatorGenerator_NoPolicies(t *testing.T) {
	schema := &model.Schema{
		Name: "empty",
		Tables: []model.Table{
			{
				Name:   "items",
				Schema: "empty",
			},
		},
	}

	gen := &TSValidatorGenerator{}
	out, diags := gen.Generate(schema)
	if len(diags) > 0 {
		t.Fatalf("unexpected diagnostics: %v", diags)
	}

	result := string(out)
	if !strings.Contains(result, "No generatable policies found") {
		t.Error("expected 'no generatable policies' message")
	}
}

func TestTSValidatorGenerator_OwnershipPattern(t *testing.T) {
	schema := &model.Schema{
		Name: "game",
		Tables: []model.Table{
			{
				Name:   "notification",
				Schema: "game",
				Policies: []model.Policy{
					{
						Name:         "notification_own_only",
						Operation:    "SELECT",
						Using:        "player_id::text = current_setting('app.player_id')",
						ErrorCode:    "not_owner",
						ErrorMessage: "You can only access your own notifications",
					},
				},
			},
		},
	}

	gen := &TSValidatorGenerator{}
	out, diags := gen.Generate(schema)
	if len(diags) > 0 {
		t.Fatalf("unexpected diagnostics: %v", diags)
	}

	result := string(out)

	if !strings.Contains(result, "export function checkNotificationOwnOnly(player_id: string, target_player_id: string): PolicyResult {") {
		t.Error("missing ownership function signature")
	}
	if !strings.Contains(result, "if (player_id !== target_player_id) {") {
		t.Error("missing ownership comparison")
	}
	if !strings.Contains(result, `code: "not_owner"`) {
		t.Error("missing not_owner error code")
	}
	// Ownership validators are not async and do not use client.
	if strings.Contains(result, "async") {
		t.Error("ownership validator should not be async")
	}
	if strings.Contains(result, "client: PoolClient") {
		t.Error("ownership validator should not take a client parameter")
	}
	if strings.Contains(result, "client.query") {
		t.Error("ownership validator should not query the database")
	}
}

func TestTSValidatorGenerator_OrCompound(t *testing.T) {
	schema := &model.Schema{
		Name: "app",
		Tables: []model.Table{
			{
				Name:   "messages",
				Schema: "app",
				Policies: []model.Policy{
					{
						Name:         "message_owner_or_public",
						Operation:    "SELECT",
						Using:        "author_id::text = current_setting('app.user_id') OR EXISTS (SELECT 1 FROM app.user_settings WHERE user_id = messages.author_id AND public_profile = true)",
						ErrorCode:    "MSG002",
						ErrorMessage: "message access denied",
					},
				},
			},
		},
	}

	gen := &TSValidatorGenerator{}
	out, diags := gen.Generate(schema)
	if len(diags) > 0 {
		t.Fatalf("unexpected diagnostics: %v", diags)
	}

	result := string(out)

	if !strings.Contains(result, "if (author_id === target_author_id) {") {
		t.Error("missing ownership comparison")
	}
	if !strings.Contains(result, "SELECT public_profile FROM app.user_settings WHERE user_id = $1") {
		t.Error("missing exists-lookup query for public_profile")
	}

	fnCount := strings.Count(result, "export async function checkMessageOwnerOrPublic")
	if fnCount != 1 {
		t.Errorf("expected exactly 1 function, got %d", fnCount)
	}

	if !strings.Contains(result, `ok: true, code: "", message: ""`) {
		t.Error("missing early return for ownership match")
	}
	if !strings.Contains(result, "client.query") {
		t.Error("missing client.query call for exists-lookup fallback")
	}
	if !strings.Contains(result, `code: "MSG002"`) {
		t.Error("missing MSG002 error code")
	}
	if !strings.Contains(result, "client: PoolClient") {
		t.Error("missing client parameter")
	}
}

func TestTSValidatorGenerator_NotExistsPattern(t *testing.T) {
	schema := &model.Schema{
		Name: "app",
		Tables: []model.Table{
			{
				Name:   "messages",
				Schema: "app",
				Policies: []model.Policy{
					{
						Name:         "message_not_blocked",
						Operation:    "SELECT",
						Using:        "NOT EXISTS (SELECT 1 FROM app.blocked_users WHERE user_id = author_id AND is_blocked = true)",
						ErrorCode:    "MSG004",
						ErrorMessage: "message blocked",
					},
				},
			},
		},
	}

	gen := &TSValidatorGenerator{}
	out, diags := gen.Generate(schema)
	if len(diags) > 0 {
		t.Fatalf("unexpected diagnostics: %v", diags)
	}

	result := string(out)

	if !strings.Contains(result, "export async function checkMessageNotBlocked(client: PoolClient, author_id: string): Promise<PolicyResult> {") {
		t.Error("missing function signature for checkMessageNotBlocked")
	}
	if !strings.Contains(result, "app.blocked_users") {
		t.Error("missing blocked_users table in query")
	}
	if !strings.Contains(result, "WHERE user_id = $1") {
		t.Error("missing WHERE user_id = $1 in query")
	}

	// NOT EXISTS inverts the logic: if the flag IS true, block.
	if !strings.Contains(result, "result.rows.length > 0 && result.rows[0].is_blocked") {
		t.Error("missing inverted logic: expected 'result.rows.length > 0 && result.rows[0].is_blocked' for NOT EXISTS pattern")
	}
	if strings.Contains(result, "result.rows.length === 0 || !result.rows[0].is_blocked") {
		t.Error("generated normal EXISTS logic instead of inverted NOT EXISTS logic")
	}

	if !strings.Contains(result, `code: "MSG004"`) {
		t.Error("missing MSG004 error code")
	}
}

func TestTSValidatorGenerator_UnparsableExpression(t *testing.T) {
	schema := &model.Schema{
		Name: "game",
		Tables: []model.Table{
			{
				Name:   "exotic",
				Schema: "game",
				Policies: []model.Policy{
					{
						Name:         "exotic_policy",
						Operation:    "INSERT",
						WithCheck:    "some_complex_expression(player_privacy_settings)",
						ErrorCode:    "exotic_error",
						ErrorMessage: "Exotic failure",
					},
				},
			},
		},
	}

	gen := &TSValidatorGenerator{}
	out, diags := gen.Generate(schema)

	result := string(out)
	if !strings.Contains(result, "No generatable policies found") {
		t.Error("expected 'No generatable policies found' message")
	}

	if len(diags) != 1 {
		t.Fatalf("expected 1 diagnostic, got %d", len(diags))
	}
	if diags[0].Code != "C001" {
		t.Errorf("expected code C001, got %s", diags[0].Code)
	}
	if diags[0].Severity != diagnostic.Warning {
		t.Errorf("expected Warning severity, got %s", diags[0].Severity)
	}
}
