package codegen

import (
	"strings"
	"testing"

	"github.com/smm-h/pgdesign/internal/diagnostic"
	"github.com/smm-h/pgdesign/internal/model"
)

func TestZigValidatorGenerator_Generate(t *testing.T) {
	schema := &model.Schema{
		Name: "game",
		Tables: []model.Table{
			{
				Name:   "chat_messages",
				Schema: "game",
				Policies: []model.Policy{
					{
						Name:      "chat_read_all",
						Operation: "SELECT",
						Using:     "true",
					},
					{
						Name:         "chat_requires_enabled",
						Operation:    "INSERT",
						WithCheck:    "sender_id::text = current_setting('app.player_id') AND EXISTS (SELECT 1 FROM game.player_privacy_settings WHERE player_id = sender_id AND chat_enabled = true)",
						ErrorCode:    "chat_disabled",
						ErrorMessage: "Chat is disabled in your privacy settings",
					},
				},
			},
			{
				Name:   "follow",
				Schema: "game",
				Policies: []model.Policy{
					{
						Name:         "follow_requires_friends_enabled",
						Operation:    "INSERT",
						WithCheck:    "follower_id::text = current_setting('app.player_id') AND EXISTS (SELECT 1 FROM game.player_privacy_settings WHERE player_id = followed_id AND friends_enabled = true)",
						ErrorCode:    "target_friends_disabled",
						ErrorMessage: "This player has disabled friend/follow requests",
					},
				},
			},
		},
	}

	gen := &ZigValidatorGenerator{}
	out, diags := gen.Generate(schema)
	if len(diags) > 0 {
		t.Fatalf("unexpected diagnostics: %v", diags)
	}

	result := string(out)

	// Header checks.
	if !strings.Contains(result, "// Generated by pgdesign -- do not edit manually.") {
		t.Error("missing header comment")
	}
	if !strings.Contains(result, "// Regenerate with: pgdesign codegen --lang zig <schema-files>") {
		t.Error("missing regenerate instruction in header")
	}
	if !strings.Contains(result, "pub const PolicyResult = struct {") {
		t.Error("missing PolicyResult struct")
	}
	if !strings.Contains(result, `const std = @import("std");`) {
		t.Error("missing std import")
	}

	// chat_requires_enabled validator.
	if !strings.Contains(result, "pub fn check_chat_requires_enabled(conn: *pg.Conn, sender_id: []const u8) !PolicyResult {") {
		t.Error("missing chat_requires_enabled function signature")
	}
	if !strings.Contains(result, "SELECT chat_enabled FROM game.player_privacy_settings WHERE player_id = $1") {
		t.Error("missing chat_enabled query")
	}
	if !strings.Contains(result, `.code = "chat_disabled"`) {
		t.Error("missing chat_disabled error code")
	}

	// follow_requires_friends_enabled validator.
	if !strings.Contains(result, "pub fn check_follow_requires_friends_enabled(conn: *pg.Conn, followed_id: []const u8) !PolicyResult {") {
		t.Error("missing follow_requires_friends_enabled function signature")
	}
	if !strings.Contains(result, "SELECT friends_enabled FROM game.player_privacy_settings WHERE player_id = $1") {
		t.Error("missing friends_enabled query")
	}
	if !strings.Contains(result, `.code = "target_friends_disabled"`) {
		t.Error("missing target_friends_disabled error code")
	}

	// Should NOT contain the read_all policy (no error code).
	if strings.Contains(result, "check_chat_read_all") {
		t.Error("should not generate validator for read_all policy")
	}
}

func TestZigValidatorGenerator_NoPolicies(t *testing.T) {
	schema := &model.Schema{
		Name: "empty",
		Tables: []model.Table{
			{
				Name:   "items",
				Schema: "empty",
			},
		},
	}

	gen := &ZigValidatorGenerator{}
	out, diags := gen.Generate(schema)
	if len(diags) > 0 {
		t.Fatalf("unexpected diagnostics: %v", diags)
	}

	result := string(out)
	if !strings.Contains(result, "No generatable policies found") {
		t.Error("expected 'no generatable policies' message")
	}
}

func TestZigValidatorGenerator_OwnershipPattern(t *testing.T) {
	schema := &model.Schema{
		Name: "game",
		Tables: []model.Table{
			{
				Name:   "notification",
				Schema: "game",
				Policies: []model.Policy{
					{
						Name:         "notification_own_only",
						Operation:    "SELECT",
						Using:        "player_id::text = current_setting('app.player_id')",
						ErrorCode:    "not_owner",
						ErrorMessage: "You can only access your own notifications",
					},
				},
			},
		},
	}

	gen := &ZigValidatorGenerator{}
	out, diags := gen.Generate(schema)
	if len(diags) > 0 {
		t.Fatalf("unexpected diagnostics: %v", diags)
	}

	result := string(out)

	if !strings.Contains(result, "pub fn check_notification_own_only(player_id: []const u8, target_player_id: []const u8) PolicyResult {") {
		t.Error("missing ownership function signature")
	}
	if !strings.Contains(result, "std.mem.eql(u8, player_id, target_player_id)") {
		t.Error("missing ownership comparison")
	}
	if !strings.Contains(result, `.code = "not_owner"`) {
		t.Error("missing not_owner error code")
	}
	// Ownership validators do not query the database.
	if strings.Contains(result, "conn: *pg.Conn") {
		t.Error("ownership validator should not take a connection parameter")
	}
	if strings.Contains(result, "queryRow") {
		t.Error("ownership validator should not query the database")
	}
}

func TestZigValidatorGenerator_DualPrivacyPattern(t *testing.T) {
	schema := &model.Schema{
		Name: "game",
		Tables: []model.Table{
			{
				Name:   "friendships",
				Schema: "game",
				Policies: []model.Policy{
					{
						Name:         "friendship_requires_friends_enabled",
						Operation:    "INSERT",
						WithCheck:    "EXISTS (SELECT 1 FROM game.player_privacy_settings WHERE player_id = requester_id AND friends_enabled = true) AND EXISTS (SELECT 1 FROM game.player_privacy_settings WHERE player_id = target_id AND friends_enabled = true)",
						ErrorCode:    "friends_disabled",
						ErrorMessage: "Friend requests require friends_enabled",
					},
				},
			},
		},
	}

	gen := &ZigValidatorGenerator{}
	out, diags := gen.Generate(schema)
	if len(diags) > 0 {
		t.Fatalf("unexpected diagnostics: %v", diags)
	}

	result := string(out)

	if !strings.Contains(result, "pub fn check_friendship_requires_friends_enabled(conn: *pg.Conn, requester_id: []const u8, target_id: []const u8) !PolicyResult {") {
		t.Error("missing dual-privacy function signature")
	}
	// Should query twice.
	if strings.Count(result, "queryRow") != 2 {
		t.Errorf("expected 2 queryRow calls, got %d", strings.Count(result, "queryRow"))
	}
	if !strings.Contains(result, `.code = "friends_disabled"`) {
		t.Error("missing friends_disabled error code")
	}
}

func TestZigValidatorGenerator_UnparsableExpression(t *testing.T) {
	schema := &model.Schema{
		Name: "game",
		Tables: []model.Table{
			{
				Name:   "exotic",
				Schema: "game",
				Policies: []model.Policy{
					{
						Name:         "exotic_policy",
						Operation:    "INSERT",
						WithCheck:    "some_complex_expression(player_privacy_settings)",
						ErrorCode:    "exotic_error",
						ErrorMessage: "Exotic failure",
					},
				},
			},
		},
	}

	gen := &ZigValidatorGenerator{}
	out, diags := gen.Generate(schema)

	result := string(out)
	// The expression parses as a valid FuncCall but matches no generatable
	// pattern, so FilterGeneratable excludes it. With no generatable policies,
	// the output contains "No generatable policies found."
	if !strings.Contains(result, "No generatable policies found") {
		t.Error("expected 'No generatable policies found' message")
	}

	// Verify diagnostic was emitted by FilterGeneratable.
	if len(diags) != 1 {
		t.Fatalf("expected 1 diagnostic, got %d", len(diags))
	}
	if diags[0].Code != "C001" {
		t.Errorf("expected code C001, got %s", diags[0].Code)
	}
	if diags[0].Severity != diagnostic.Warning {
		t.Errorf("expected Warning severity, got %s", diags[0].Severity)
	}
}
