package codegen

import (
	"bytes"
	"fmt"

	"github.com/smm-h/pgdesign/internal/diagnostic"
	"github.com/smm-h/pgdesign/internal/model"
)

// ZigTypesGenerator generates Zig struct types corresponding to database tables.
type ZigTypesGenerator struct{}

// Generate produces a Zig source file with one struct per table in the schema.
func (g *ZigTypesGenerator) Generate(schema *model.Schema) ([]byte, []diagnostic.Diagnostic) {
	var buf bytes.Buffer
	header := "// Code generated by pgdesign -- do not edit.\n"

	if len(schema.Tables) == 0 {
		buf.WriteString(header)
		return buf.Bytes(), nil
	}

	buf.WriteString(header)

	// Write enum constants.
	enumBlock := GenerateEnums(schema.Enums, LangZig)
	if enumBlock != "" {
		buf.WriteString("\n")
		buf.WriteString(enumBlock)
	}

	// Write state machine transition maps.
	smBlock := GenerateTransitionMaps(schema.StateMachineTransitions, LangZig)
	if smBlock != "" {
		buf.WriteString("\n")
		buf.WriteString(smBlock)
	}

	for i, tbl := range schema.Tables {
		if i > 0 {
			buf.WriteString("\n")
		}
		buf.WriteString("\n")
		fmt.Fprintf(&buf, "/// Represents the %s table.\n", tbl.Name)
		fmt.Fprintf(&buf, "pub const %s = struct {\n", toPascalCase(tbl.Name))
		for _, col := range tbl.Columns {
			zigType := pgTypeToZig(col)
			fmt.Fprintf(&buf, "    %s: %s,\n", col.Name, zigType)
		}
		buf.WriteString("};\n")
	}

	return buf.Bytes(), nil
}

// pgTypeToZig maps a column's PostgreSQL type to a Zig type string.
// It handles semantic types, arrays, and nullability.
func pgTypeToZig(col model.Column) string {
	baseType := zigBaseType(col)

	if col.Array && !col.NotNull {
		return "?[]" + baseType
	}
	if col.Array {
		return "[]" + baseType
	}
	if !col.NotNull {
		return "?" + baseType
	}
	return baseType
}

// zigBaseType returns the Zig type for a column's PostgreSQL type,
// without array or nullable modifiers.
func zigBaseType(col model.Column) string {
	// Semantic type overrides.
	if col.SemanticTypeName == "money" {
		return "i64"
	}

	pgType := col.PGType.Base

	switch pgType {
	case "text", "varchar", "char", "bpchar":
		return "[]const u8"
	case "int4":
		return "i32"
	case "int8":
		return "i64"
	case "int2":
		return "i16"
	case "float4":
		return "f32"
	case "float8":
		return "f64"
	case "bool":
		return "bool"
	case "timestamptz", "timestamp":
		return "i64"
	case "date":
		return "i64"
	case "uuid":
		return "[16]u8"
	case "jsonb", "json":
		return "[]const u8"
	case "numeric":
		return "[]const u8"
	case "bytea":
		return "[]const u8"
	case "interval":
		return "[]const u8"
	default:
		// Enum types and anything unrecognized fall back to []const u8.
		return "[]const u8"
	}
}
