package codegen

import (
	"strings"
	"testing"

	"github.com/smm-h/pgdesign/internal/model"
)

// containsZigField checks that at least one line in s contains a Zig
// field declaration matching "    fieldName: zigType," (4-space indent).
func containsZigField(s, fieldName, zigType string) bool {
	for _, line := range strings.Split(s, "\n") {
		if strings.TrimRight(line, " \t\r") == "    "+fieldName+": "+zigType+"," {
			return true
		}
	}
	return false
}

func TestZigTypesGenerator_Basic(t *testing.T) {
	schema := &model.Schema{
		Tables: []model.Table{
			{
				Name:    "users",
				Schema:  "public",
				Comment: "Application users",
				Columns: []model.Column{
					{Name: "id", PGType: "uuid", NotNull: true},
					{Name: "email", PGType: "text", NotNull: true},
					{Name: "score", PGType: "bigint", NotNull: true},
					{Name: "is_active", PGType: "boolean", NotNull: true},
					{Name: "created_at", PGType: "timestamptz", NotNull: true},
					{Name: "metadata", PGType: "jsonb", NotNull: true},
					{Name: "age", PGType: "integer", NotNull: true},
					{Name: "rating", PGType: "double precision", NotNull: true},
					{Name: "avatar", PGType: "bytea", NotNull: true},
					{Name: "balance", PGType: "numeric", NotNull: true},
				},
			},
		},
	}

	gen := &ZigTypesGenerator{}
	out, diags := gen.Generate(schema)
	if len(diags) > 0 {
		t.Fatalf("unexpected diagnostics: %v", diags)
	}

	result := string(out)

	// Header.
	if !strings.Contains(result, "// Code generated by pgdesign -- do not edit.") {
		t.Error("missing generated header comment")
	}

	// Doc comment and struct declaration.
	if !strings.Contains(result, "/// Represents the users table.") {
		t.Error("missing doc comment")
	}
	if !strings.Contains(result, "pub const Users = struct {") {
		t.Error("missing struct declaration")
	}

	// Fields with correct types.
	if !containsZigField(result, "id", "[16]u8") {
		t.Error("missing or incorrect id field (expected [16]u8)")
	}
	if !containsZigField(result, "email", "[]const u8") {
		t.Error("missing or incorrect email field (expected []const u8)")
	}
	if !containsZigField(result, "score", "i64") {
		t.Error("missing or incorrect score field (expected i64)")
	}
	if !containsZigField(result, "is_active", "bool") {
		t.Error("missing or incorrect is_active field (expected bool)")
	}
	if !containsZigField(result, "created_at", "i64") {
		t.Error("missing or incorrect created_at field (expected i64)")
	}
	if !containsZigField(result, "metadata", "[]const u8") {
		t.Error("missing or incorrect metadata field (expected []const u8)")
	}
	if !containsZigField(result, "age", "i32") {
		t.Error("missing or incorrect age field (expected i32)")
	}
	if !containsZigField(result, "rating", "f64") {
		t.Error("missing or incorrect rating field (expected f64)")
	}
	if !containsZigField(result, "avatar", "[]const u8") {
		t.Error("missing or incorrect avatar field (expected []const u8)")
	}
	if !containsZigField(result, "balance", "[]const u8") {
		t.Error("missing or incorrect balance field (expected []const u8)")
	}
}

func TestZigTypesGenerator_NullableAndArray(t *testing.T) {
	schema := &model.Schema{
		Tables: []model.Table{
			{
				Name:    "items",
				Comment: "Test items",
				Columns: []model.Column{
					{Name: "id", PGType: "integer", NotNull: true},
					{Name: "name", PGType: "text", NotNull: false},
					{Name: "tags", PGType: "text", NotNull: true, Array: true},
					{Name: "scores", PGType: "integer", NotNull: false, Array: true},
					{Name: "status", PGType: "user_status", NotNull: true},
				},
			},
		},
	}

	gen := &ZigTypesGenerator{}
	out, diags := gen.Generate(schema)
	if len(diags) > 0 {
		t.Fatalf("unexpected diagnostics: %v", diags)
	}

	result := string(out)

	// Not-null, not-array: plain type.
	if !containsZigField(result, "id", "i32") {
		t.Error("missing or incorrect id field (expected i32)")
	}

	// Nullable: optional.
	if !containsZigField(result, "name", "?[]const u8") {
		t.Error("missing or incorrect name field (expected ?[]const u8)")
	}

	// Array: slice.
	if !containsZigField(result, "tags", "[][]const u8") {
		t.Error("missing or incorrect tags field (expected [][]const u8)")
	}

	// Nullable + array: optional slice.
	if !containsZigField(result, "scores", "?[]i32") {
		t.Error("missing or incorrect scores field (expected ?[]i32)")
	}

	// Enum (unrecognized PG type): []const u8.
	if !containsZigField(result, "status", "[]const u8") {
		t.Error("missing or incorrect status field (expected []const u8 for enum)")
	}
}

func TestZigTypesGenerator_EmptySchema(t *testing.T) {
	schema := &model.Schema{Tables: []model.Table{}}

	gen := &ZigTypesGenerator{}
	out, diags := gen.Generate(schema)
	if len(diags) > 0 {
		t.Fatalf("unexpected diagnostics: %v", diags)
	}

	result := string(out)

	if !strings.Contains(result, "// Code generated by pgdesign -- do not edit.") {
		t.Error("missing generated header comment")
	}
	if strings.Contains(result, "pub const") {
		t.Error("empty schema should not have struct declarations")
	}
}

func TestZigTypesGenerator_MoneySemanticType(t *testing.T) {
	schema := &model.Schema{
		Tables: []model.Table{
			{
				Name:    "products",
				Comment: "Products",
				Columns: []model.Column{
					{Name: "id", PGType: "integer", NotNull: true},
					{Name: "price", PGType: "bigint", NotNull: true, SemanticTypeName: "money"},
				},
			},
		},
	}

	gen := &ZigTypesGenerator{}
	out, diags := gen.Generate(schema)
	if len(diags) > 0 {
		t.Fatalf("unexpected diagnostics: %v", diags)
	}

	result := string(out)

	// Money semantic type should map to i64.
	if !containsZigField(result, "price", "i64") {
		t.Error("missing or incorrect price field (expected i64 for money semantic type)")
	}
}

func TestZigTypesGenerator_MultipleTables(t *testing.T) {
	schema := &model.Schema{
		Tables: []model.Table{
			{
				Name:    "orders",
				Comment: "Orders",
				Columns: []model.Column{
					{Name: "id", PGType: "uuid", NotNull: true},
					{Name: "total", PGType: "numeric", NotNull: true},
				},
			},
			{
				Name:    "order_items",
				Comment: "Order items",
				Columns: []model.Column{
					{Name: "id", PGType: "integer", NotNull: true},
					{Name: "quantity", PGType: "smallint", NotNull: true},
				},
			},
		},
	}

	gen := &ZigTypesGenerator{}
	out, diags := gen.Generate(schema)
	if len(diags) > 0 {
		t.Fatalf("unexpected diagnostics: %v", diags)
	}

	result := string(out)

	// Both struct declarations present.
	if !strings.Contains(result, "pub const Orders = struct {") {
		t.Error("missing Orders struct declaration")
	}
	if !strings.Contains(result, "pub const OrderItems = struct {") {
		t.Error("missing OrderItems struct declaration")
	}

	// Spot-check a field from the second table.
	if !containsZigField(result, "quantity", "i16") {
		t.Error("missing or incorrect quantity field (expected i16)")
	}
}
