package codegen

import (
	"strings"
	"testing"

	"github.com/smm-h/pgdesign/internal/model"
	"github.com/smm-h/pgdesign/internal/typeinfo"
)

func TestZigConstraintsGenerator_Generate(t *testing.T) {
	schema := &model.Schema{
		Name: "app",
		Enums: []model.Enum{
			{Name: "role", Values: []string{"admin", "user", "guest"}},
		},
		Tables: []model.Table{
			{
				Name: "users",
				Columns: []model.Column{
					{Name: "id", PGType: typeinfo.MustParse("bigint"), NotNull: true},
					{Name: "name", PGType: typeinfo.MustParse("text"), NotNull: true},
					{Name: "email", PGType: typeinfo.MustParse("text"), NotNull: true},
					{Name: "role", PGType: typeinfo.MustParse("role"), NotNull: true},
					{Name: "age", PGType: typeinfo.MustParse("integer"), NotNull: true},
					{Name: "slug", PGType: typeinfo.MustParse("varchar"), NotNull: true},
				},
				PK: []string{"id"},
				Checks: []model.CheckConstraint{
					{Name: "ck_users_age_range", Expr: "age >= 0 AND age <= 150"},
					{Name: "ck_users_email_fmt", Expr: "email LIKE '%@%'"},
					{Name: "ck_users_slug_len", Expr: "LENGTH(slug) <= 100"},
				},
			},
		},
	}

	gen := &ZigConstraintsGenerator{}
	out, diags := gen.Generate(schema)
	if len(diags) > 0 {
		t.Fatalf("unexpected diagnostics: %v", diags)
	}

	result := string(out)

	// Header.
	if !strings.Contains(result, "Code generated by pgdesign") {
		t.Error("missing header comment")
	}

	// std import.
	if !strings.Contains(result, `const std = @import("std");`) {
		t.Error("missing std import")
	}

	// ValidationError struct.
	if !strings.Contains(result, "pub const ValidationError = struct") {
		t.Error("missing ValidationError struct")
	}

	// Function signature.
	if !strings.Contains(result, "pub fn validate_users(row: anytype, allocator: std.mem.Allocator) !std.ArrayList(ValidationError)") {
		t.Error("missing validate_users function signature")
	}

	// NOT NULL checks for string-type columns: empty-string check.
	if !strings.Contains(result, "row.name.len == 0") {
		t.Error("missing NOT NULL check for name (string type should check .len == 0)")
	}
	if !strings.Contains(result, "row.email.len == 0") {
		t.Error("missing NOT NULL check for email")
	}
	if !strings.Contains(result, "row.slug.len == 0") {
		t.Error("missing NOT NULL check for slug")
	}

	// NOT NULL check for non-string column (age is integer, check is == null).
	if !strings.Contains(result, "row.age == null") {
		t.Error("missing NOT NULL check for age (non-string type should check == null)")
	}

	// Enum check.
	if !strings.Contains(result, "std.mem.eql(u8, row.role, v)") {
		t.Error("missing std.mem.eql call for enum check")
	}
	if !strings.Contains(result, `"admin"`) {
		t.Error("missing enum value 'admin'")
	}
	if !strings.Contains(result, `"user"`) {
		t.Error("missing enum value 'user'")
	}
	if !strings.Contains(result, `"guest"`) {
		t.Error("missing enum value 'guest'")
	}

	// Range check for age.
	if !strings.Contains(result, "row.age") {
		t.Error("missing age range check")
	}
	if !strings.Contains(result, "150") {
		t.Error("missing age upper bound 150")
	}

	// LIKE contains check for email -> std.mem.indexOf.
	if !strings.Contains(result, "std.mem.indexOf(u8, row.email") {
		t.Error("missing std.mem.indexOf for email LIKE '%@%' check")
	}

	// Length check for slug.
	if !strings.Contains(result, "row.slug.len") {
		t.Error("missing length check for slug")
	}
	if !strings.Contains(result, "100") {
		t.Error("missing length limit 100")
	}
}

func TestZigConstraintsGenerator_LikePatterns(t *testing.T) {
	schema := &model.Schema{
		Tables: []model.Table{
			{
				Name: "patterns",
				Columns: []model.Column{
					{Name: "id", PGType: typeinfo.MustParse("bigint"), NotNull: true},
					{Name: "prefix_col", PGType: typeinfo.MustParse("text"), NotNull: true},
					{Name: "suffix_col", PGType: typeinfo.MustParse("text"), NotNull: true},
					{Name: "contains_col", PGType: typeinfo.MustParse("text"), NotNull: true},
					{Name: "complex_col", PGType: typeinfo.MustParse("text"), NotNull: true},
				},
				PK: []string{"id"},
				Checks: []model.CheckConstraint{
					{Name: "ck_prefix", Expr: "prefix_col LIKE 'A%'"},
					{Name: "ck_suffix", Expr: "suffix_col LIKE '%com'"},
					{Name: "ck_contains", Expr: "contains_col LIKE '%@%'"},
					{Name: "ck_complex", Expr: "complex_col LIKE '%a%b%'"},
				},
			},
		},
	}

	gen := &ZigConstraintsGenerator{}
	out, diags := gen.Generate(schema)
	if len(diags) > 0 {
		t.Fatalf("unexpected diagnostics: %v", diags)
	}

	result := string(out)

	// startsWith for A%.
	if !strings.Contains(result, `std.mem.startsWith(u8, row.prefix_col, "A")`) {
		t.Error("missing startsWith for 'A%' pattern")
	}

	// endsWith for %com.
	if !strings.Contains(result, `std.mem.endsWith(u8, row.suffix_col, "com")`) {
		t.Error("missing endsWith for endsWith pattern")
	}

	// indexOf for %@%.
	if !strings.Contains(result, `std.mem.indexOf(u8, row.contains_col, "@")`) {
		t.Error("missing indexOf for '%@%' pattern")
	}

	// Complex pattern %a%b% should be skipped.
	if !strings.Contains(result, "// LIKE pattern '%a%b%' not expressible without regex -- skipped") {
		t.Error("missing skip comment for complex LIKE pattern")
	}
}

func TestZigConstraintsGenerator_NotLikePatterns(t *testing.T) {
	schema := &model.Schema{
		Tables: []model.Table{
			{
				Name: "negated",
				Columns: []model.Column{
					{Name: "id", PGType: typeinfo.MustParse("bigint"), NotNull: true},
					{Name: "code", PGType: typeinfo.MustParse("text"), NotNull: true},
				},
				PK: []string{"id"},
				Checks: []model.CheckConstraint{
					{Name: "ck_not_prefix", Expr: "code NOT LIKE 'X%'"},
				},
			},
		},
	}

	gen := &ZigConstraintsGenerator{}
	out, diags := gen.Generate(schema)
	if len(diags) > 0 {
		t.Fatalf("unexpected diagnostics: %v", diags)
	}

	result := string(out)

	// NOT LIKE X% should invert: fail when it DOES start with X.
	if !strings.Contains(result, `std.mem.startsWith(u8, row.code, "X")`) {
		t.Error("missing startsWith for NOT LIKE 'X%' pattern")
	}
	// The condition should NOT have the negation prefix since NOT LIKE inverts.
	if strings.Contains(result, "!std.mem.startsWith") {
		t.Error("NOT LIKE pattern should not negate startsWith (it should fail when startsWith is true)")
	}
}

func TestZigConstraintsGenerator_Comparison(t *testing.T) {
	schema := &model.Schema{
		Tables: []model.Table{
			{
				Name: "orders",
				Columns: []model.Column{
					{Name: "id", PGType: typeinfo.MustParse("bigint"), NotNull: true},
					{Name: "amount", PGType: typeinfo.MustParse("numeric"), NotNull: true},
				},
				PK: []string{"id"},
				Checks: []model.CheckConstraint{
					{Name: "ck_positive", Expr: "amount > 0"},
				},
			},
		},
	}

	gen := &ZigConstraintsGenerator{}
	out, diags := gen.Generate(schema)
	if len(diags) > 0 {
		t.Fatalf("unexpected diagnostics: %v", diags)
	}

	result := string(out)

	// Comparison: amount > 0 inverts to amount <= 0.
	if !strings.Contains(result, "row.amount <= 0") {
		t.Error("missing inverted comparison check for amount > 0")
	}
	if !strings.Contains(result, "failed check: > 0") {
		t.Error("missing error message for comparison check")
	}
}

func TestZigConstraintsGenerator_EmptySchema(t *testing.T) {
	schema := &model.Schema{
		Name: "empty",
	}

	gen := &ZigConstraintsGenerator{}
	out, diags := gen.Generate(schema)
	if len(diags) > 0 {
		t.Fatalf("unexpected diagnostics: %v", diags)
	}

	result := string(out)
	if !strings.Contains(result, "No tables with extractable constraints.") {
		t.Error("missing empty-schema comment")
	}
	if strings.Contains(result, "pub fn validate_") {
		t.Error("should not contain any validate functions for empty schema")
	}
}

func TestZigConstraintsGenerator_NoConstraints(t *testing.T) {
	schema := &model.Schema{
		Tables: []model.Table{
			{
				Name: "simple",
				Columns: []model.Column{
					{Name: "id", PGType: typeinfo.MustParse("bigint"), NotNull: true},
				},
				PK: []string{"id"},
			},
		},
	}

	gen := &ZigConstraintsGenerator{}
	out, diags := gen.Generate(schema)
	if len(diags) > 0 {
		t.Fatalf("unexpected diagnostics: %v", diags)
	}

	result := string(out)
	if !strings.Contains(result, "No tables with extractable constraints.") {
		t.Error("missing no-constraints comment")
	}
}
