package codegen

import (
	"bytes"
	"fmt"
	"strings"

	"github.com/smm-h/pgdesign/internal/model"
)

// ZigConstantsGenerator generates Zig constants for table and column names.
type ZigConstantsGenerator struct{}

// Generate produces a Zig file with table name and column name constants
// for every table in the schema.
func (g *ZigConstantsGenerator) Generate(schema *model.Schema) ([]byte, error) {
	var buf bytes.Buffer

	buf.WriteString("// Generated by pgdesign -- do not edit manually.\n")
	buf.WriteString("// Regenerate with: pgdesign codegen --lang zig --mode constants <schema-files>\n")
	if schema.Name != "" {
		buf.WriteString(fmt.Sprintf("// Schema: %s\n", schema.Name))
	}

	for i, tbl := range schema.Tables {
		if i > 0 {
			buf.WriteString("\n")
		}

		fqn := tbl.Name
		if tbl.Schema != "" {
			fqn = tbl.Schema + "." + tbl.Name
		}

		lower := toLowerSnake(tbl.Name)

		buf.WriteString(fmt.Sprintf("\n// Table: %s\n", fqn))
		buf.WriteString(fmt.Sprintf("pub const table_%s = %q;\n", lower, fqn))

		cols := make([]string, len(tbl.Columns))
		for j, col := range tbl.Columns {
			cols[j] = fmt.Sprintf("%q", col.Name)
		}
		buf.WriteString(fmt.Sprintf("pub const %s_columns = [_][]const u8{ %s };\n", lower, strings.Join(cols, ", ")))
	}

	return buf.Bytes(), nil
}

// toLowerSnake returns the name as-is since pgdesign table names are already
// lower_snake_case.
func toLowerSnake(name string) string {
	return strings.ToLower(name)
}
