package codegen

import (
	"strings"
	"testing"

	"github.com/smm-h/pgdesign/internal/diagnostic"
	"github.com/smm-h/pgdesign/internal/model"
)

func TestZigValidatorGenerator_Generate(t *testing.T) {
	schema := &model.Schema{
		Name: "game",
		Tables: []model.Table{
			{
				Name:   "chat_messages",
				Schema: "game",
				Policies: []model.Policy{
					{
						Name:      "chat_read_all",
						Operation: "SELECT",
						Using:     "true",
					},
					{
						Name:         "chat_requires_enabled",
						Operation:    "INSERT",
						WithCheck:    "sender_id::text = current_setting('app.player_id') AND EXISTS (SELECT 1 FROM game.player_privacy_settings WHERE player_id = sender_id AND chat_enabled = true)",
						ErrorCode:    "chat_disabled",
						ErrorMessage: "Chat is disabled in your privacy settings",
					},
				},
			},
			{
				Name:   "follow",
				Schema: "game",
				Policies: []model.Policy{
					{
						Name:         "follow_requires_friends_enabled",
						Operation:    "INSERT",
						WithCheck:    "follower_id::text = current_setting('app.player_id') AND EXISTS (SELECT 1 FROM game.player_privacy_settings WHERE player_id = followed_id AND friends_enabled = true)",
						ErrorCode:    "target_friends_disabled",
						ErrorMessage: "This player has disabled friend/follow requests",
					},
				},
			},
		},
	}

	gen := &ZigValidatorGenerator{}
	out, diags := gen.Generate(schema)
	if len(diags) > 0 {
		t.Fatalf("unexpected diagnostics: %v", diags)
	}

	result := string(out)

	// Header checks.
	if !strings.Contains(result, "// Generated by pgdesign -- do not edit manually.") {
		t.Error("missing header comment")
	}
	if !strings.Contains(result, "// Regenerate with: pgdesign codegen --lang zig <schema-files>") {
		t.Error("missing regenerate instruction in header")
	}
	if !strings.Contains(result, "pub const PolicyResult = struct {") {
		t.Error("missing PolicyResult struct")
	}
	if !strings.Contains(result, `const std = @import("std");`) {
		t.Error("missing std import")
	}

	// chat_requires_enabled validator.
	if !strings.Contains(result, "pub fn check_chat_requires_enabled(conn: *pg.Conn, sender_id: []const u8) !PolicyResult {") {
		t.Error("missing chat_requires_enabled function signature")
	}
	if !strings.Contains(result, "SELECT chat_enabled FROM game.player_privacy_settings WHERE player_id = $1") {
		t.Error("missing chat_enabled query")
	}
	if !strings.Contains(result, `.code = "chat_disabled"`) {
		t.Error("missing chat_disabled error code")
	}

	// follow_requires_friends_enabled validator.
	if !strings.Contains(result, "pub fn check_follow_requires_friends_enabled(conn: *pg.Conn, followed_id: []const u8) !PolicyResult {") {
		t.Error("missing follow_requires_friends_enabled function signature")
	}
	if !strings.Contains(result, "SELECT friends_enabled FROM game.player_privacy_settings WHERE player_id = $1") {
		t.Error("missing friends_enabled query")
	}
	if !strings.Contains(result, `.code = "target_friends_disabled"`) {
		t.Error("missing target_friends_disabled error code")
	}

	// Should NOT contain the read_all policy (no error code).
	if strings.Contains(result, "check_chat_read_all") {
		t.Error("should not generate validator for read_all policy")
	}
}

func TestZigValidatorGenerator_NoPolicies(t *testing.T) {
	schema := &model.Schema{
		Name: "empty",
		Tables: []model.Table{
			{
				Name:   "items",
				Schema: "empty",
			},
		},
	}

	gen := &ZigValidatorGenerator{}
	out, diags := gen.Generate(schema)
	if len(diags) > 0 {
		t.Fatalf("unexpected diagnostics: %v", diags)
	}

	result := string(out)
	if !strings.Contains(result, "No generatable policies found") {
		t.Error("expected 'no generatable policies' message")
	}
}

func TestZigValidatorGenerator_OwnershipPattern(t *testing.T) {
	schema := &model.Schema{
		Name: "game",
		Tables: []model.Table{
			{
				Name:   "notification",
				Schema: "game",
				Policies: []model.Policy{
					{
						Name:         "notification_own_only",
						Operation:    "SELECT",
						Using:        "player_id::text = current_setting('app.player_id')",
						ErrorCode:    "not_owner",
						ErrorMessage: "You can only access your own notifications",
					},
				},
			},
		},
	}

	gen := &ZigValidatorGenerator{}
	out, diags := gen.Generate(schema)
	if len(diags) > 0 {
		t.Fatalf("unexpected diagnostics: %v", diags)
	}

	result := string(out)

	if !strings.Contains(result, "pub fn check_notification_own_only(player_id: []const u8, target_player_id: []const u8) PolicyResult {") {
		t.Error("missing ownership function signature")
	}
	if !strings.Contains(result, "std.mem.eql(u8, player_id, target_player_id)") {
		t.Error("missing ownership comparison")
	}
	if !strings.Contains(result, `.code = "not_owner"`) {
		t.Error("missing not_owner error code")
	}
	// Ownership validators do not query the database.
	if strings.Contains(result, "conn: *pg.Conn") {
		t.Error("ownership validator should not take a connection parameter")
	}
	if strings.Contains(result, "queryRow") {
		t.Error("ownership validator should not query the database")
	}
}

func TestZigValidatorGenerator_DualPrivacyPattern(t *testing.T) {
	schema := &model.Schema{
		Name: "game",
		Tables: []model.Table{
			{
				Name:   "friendships",
				Schema: "game",
				Policies: []model.Policy{
					{
						Name:         "friendship_requires_friends_enabled",
						Operation:    "INSERT",
						WithCheck:    "EXISTS (SELECT 1 FROM game.player_privacy_settings WHERE player_id = requester_id AND friends_enabled = true) AND EXISTS (SELECT 1 FROM game.player_privacy_settings WHERE player_id = target_id AND friends_enabled = true)",
						ErrorCode:    "friends_disabled",
						ErrorMessage: "Friend requests require friends_enabled",
					},
				},
			},
		},
	}

	gen := &ZigValidatorGenerator{}
	out, diags := gen.Generate(schema)
	if len(diags) > 0 {
		t.Fatalf("unexpected diagnostics: %v", diags)
	}

	result := string(out)

	if !strings.Contains(result, "pub fn check_friendship_requires_friends_enabled(conn: *pg.Conn, requester_id: []const u8, target_id: []const u8) !PolicyResult {") {
		t.Error("missing dual-privacy function signature")
	}
	// Should query twice.
	if strings.Count(result, "queryRow") != 2 {
		t.Errorf("expected 2 queryRow calls, got %d", strings.Count(result, "queryRow"))
	}
	if !strings.Contains(result, `.code = "friends_disabled"`) {
		t.Error("missing friends_disabled error code")
	}
}

func TestZigValidatorGenerator_DualPrivacyDifferentTables(t *testing.T) {
	// RED test: dual EXISTS referencing DIFFERENT tables exposes the bug where
	// the second query reuses the first lookup's tableParts instead of its own.
	schema := &model.Schema{
		Name: "app",
		Tables: []model.Table{
			{
				Name:   "messages",
				Schema: "app",
				Policies: []model.Policy{
					{
						Name:         "message_dual_privacy",
						Operation:    "SELECT",
						Using:        "EXISTS (SELECT 1 FROM app.user_settings WHERE user_id = author_id AND notifications_enabled = true) AND EXISTS (SELECT 1 FROM app.channel_settings WHERE channel_id = messages.channel_id AND is_public = true)",
						ErrorCode:    "MSG003",
						ErrorMessage: "message access requires both user and channel settings",
					},
				},
			},
		},
	}

	gen := &ZigValidatorGenerator{}
	out, diags := gen.Generate(schema)
	if len(diags) > 0 {
		t.Fatalf("unexpected diagnostics: %v", diags)
	}

	result := string(out)

	// First lookup's table must be present.
	if !strings.Contains(result, "user_settings") {
		t.Error("expected 'user_settings' (first lookup table) in generated output")
	}
	// Second lookup's table must be present (bug: reuses first table).
	if !strings.Contains(result, "channel_settings") {
		t.Error("expected 'channel_settings' (second lookup table) in generated output")
	}
	// First lookup's join column.
	if !strings.Contains(result, "WHERE user_id = $1") {
		t.Error("expected 'WHERE user_id = $1' for first lookup")
	}
	// Second lookup's join column.
	if !strings.Contains(result, "WHERE channel_id = $1") {
		t.Error("expected 'WHERE channel_id = $1' for second lookup")
	}
	// Should query twice.
	if strings.Count(result, "queryRow") != 2 {
		t.Errorf("expected 2 queryRow calls, got %d", strings.Count(result, "queryRow"))
	}
	// Error code must be present.
	if !strings.Contains(result, `.code = "MSG003"`) {
		t.Error("missing MSG003 error code")
	}
}

func TestZigValidatorGenerator_NonGamehomeNaming(t *testing.T) {
	// RED test: uses non-gamehome naming to expose the hardcoded "player_id" bug.
	// The generators should use the joinColumn from the AST ("user_id"), not
	// a hardcoded "player_id".
	schema := &model.Schema{
		Name: "app",
		Tables: []model.Table{
			{
				Name:   "messages",
				Schema: "app",
				Policies: []model.Policy{
					{
						Name:         "message_privacy",
						Operation:    "SELECT",
						Using:        "author_id::text = current_setting('app.user_id') AND EXISTS (SELECT 1 FROM app.user_settings WHERE user_id = messages.author_id AND notifications_enabled = true)",
						ErrorCode:    "MSG001",
						ErrorMessage: "message access denied",
					},
				},
			},
		},
	}

	gen := &ZigValidatorGenerator{}
	out, diags := gen.Generate(schema)
	if len(diags) > 0 {
		t.Fatalf("unexpected diagnostics: %v", diags)
	}

	result := string(out)

	// The generated query must reference the actual lookup table, not a
	// hardcoded gamehome table.
	if !strings.Contains(result, "user_settings") {
		t.Error("expected 'user_settings' in generated output, got hardcoded table name instead")
	}
	if strings.Contains(result, "player_privacy_settings") {
		t.Error("generated output contains hardcoded 'player_privacy_settings' instead of 'user_settings'")
	}

	// The WHERE clause must use the joinColumn from the AST ("user_id"), not
	// a hardcoded "player_id".
	if !strings.Contains(result, "WHERE user_id = $1") {
		t.Error("expected 'WHERE user_id = $1' in generated query, got hardcoded 'WHERE player_id = $1' instead")
	}
	if strings.Contains(result, "WHERE player_id = $1") {
		t.Error("generated query contains hardcoded 'WHERE player_id = $1' instead of 'WHERE user_id = $1'")
	}
}

func TestZigValidatorGenerator_OrCompound_OwnershipOrExists(t *testing.T) {
	// OR-compound policy: ownership OR exists-lookup.
	// "Show message if you own it OR the author's profile is public."
	schema := &model.Schema{
		Name: "app",
		Tables: []model.Table{
			{
				Name:   "messages",
				Schema: "app",
				Policies: []model.Policy{
					{
						Name:         "message_owner_or_public",
						Operation:    "SELECT",
						Using:        "author_id::text = current_setting('app.user_id') OR EXISTS (SELECT 1 FROM app.user_settings WHERE user_id = messages.author_id AND public_profile = true)",
						ErrorCode:    "MSG002",
						ErrorMessage: "message access denied",
					},
				},
			},
		},
	}

	gen := &ZigValidatorGenerator{}
	out, diags := gen.Generate(schema)
	if len(diags) > 0 {
		t.Fatalf("unexpected diagnostics: %v", diags)
	}

	result := string(out)

	// The validator must handle BOTH branches of the OR.
	// It should check ownership first (cheap), then fall back to exists-lookup.

	// Must have the ownership comparison.
	if !strings.Contains(result, "std.mem.eql(u8, author_id, target_author_id)") {
		t.Error("missing ownership comparison")
	}

	// Must have the exists-lookup query.
	if !strings.Contains(result, "SELECT public_profile FROM app.user_settings WHERE user_id = $1") {
		t.Error("missing exists-lookup query for public_profile")
	}

	// Both branches must be present in a single function.
	fnCount := strings.Count(result, "pub fn check_message_owner_or_public")
	if fnCount != 1 {
		t.Errorf("expected exactly 1 function, got %d", fnCount)
	}

	// The validator must return ok=true when the ownership check passes (short-circuit).
	if !strings.Contains(result, "return .{ .ok = true }") {
		t.Error("missing early return for ownership match")
	}

	// The validator must also query the database for the exists-lookup fallback.
	if !strings.Contains(result, "queryRow") {
		t.Error("missing queryRow call for exists-lookup fallback")
	}

	// Must have the error code for when NEITHER branch passes.
	if !strings.Contains(result, `.code = "MSG002"`) {
		t.Error("missing MSG002 error code")
	}

	// Must take a connection parameter (because of the exists-lookup branch).
	if !strings.Contains(result, "conn: *pg.Conn") {
		t.Error("missing connection parameter")
	}
}

func TestZigValidatorGenerator_UnparsableExpression(t *testing.T) {
	schema := &model.Schema{
		Name: "game",
		Tables: []model.Table{
			{
				Name:   "exotic",
				Schema: "game",
				Policies: []model.Policy{
					{
						Name:         "exotic_policy",
						Operation:    "INSERT",
						WithCheck:    "some_complex_expression(player_privacy_settings)",
						ErrorCode:    "exotic_error",
						ErrorMessage: "Exotic failure",
					},
				},
			},
		},
	}

	gen := &ZigValidatorGenerator{}
	out, diags := gen.Generate(schema)

	result := string(out)
	// The expression parses as a valid FuncCall but matches no generatable
	// pattern, so FilterGeneratable excludes it. With no generatable policies,
	// the output contains "No generatable policies found."
	if !strings.Contains(result, "No generatable policies found") {
		t.Error("expected 'No generatable policies found' message")
	}

	// Verify diagnostic was emitted by FilterGeneratable.
	if len(diags) != 1 {
		t.Fatalf("expected 1 diagnostic, got %d", len(diags))
	}
	if diags[0].Code != "C001" {
		t.Errorf("expected code C001, got %s", diags[0].Code)
	}
	if diags[0].Severity != diagnostic.Warning {
		t.Errorf("expected Warning severity, got %s", diags[0].Severity)
	}
}
