# Code generated by pgdesign -- do not edit.

from typing import Final

STATEMENTS: Final[list[tuple[str, str, str | None, int]]] = [
    ("CREATE SCHEMA shop;", "schema", None, 1),
    ("CREATE EXTENSION pgcrypto;", "extension", None, 2),
    ("CREATE DOMAIN shop.short_text AS text CHECK (LENGTH(VALUE) <= 255);", "domain", None, 3),
    ("CREATE DOMAIN shop.email AS text CHECK (VALUE ~ '^[^@]+@[^@]+\\.[^@]+$');", "domain", None, 3),
    ("""CREATE TABLE shop.customers (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    name short_text NOT NULL,
    email email NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT pk_customers PRIMARY KEY (id)
);""", "table", "customers", 4),
    ("""CREATE TABLE shop.orders (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    customer_id uuid NOT NULL,
    total bigint NOT NULL DEFAULT 0,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT pk_orders PRIMARY KEY (id)
);""", "table", "orders", 4),
    ("ALTER TABLE shop.orders ADD CONSTRAINT fk_orders_customers FOREIGN KEY (customer_id) REFERENCES shop.customers (id) ON DELETE CASCADE;", "fk", "orders", 6),
    ("ALTER TABLE shop.customers ADD CONSTRAINT uq_customers_email UNIQUE (email);", "unique", "customers", 7),
    ("ALTER TABLE shop.orders ADD CONSTRAINT ck_orders_positive_total CHECK (total >= 0);", "check", "orders", 8),
    ("CREATE INDEX idx_orders_customer ON shop.orders (customer_id);", "index", "orders", 9),
    ("COMMENT ON TABLE shop.customers IS 'Registered customers';", "comment", "customers", 10),
    ("COMMENT ON COLUMN shop.customers.name IS 'Full name';", "comment", "customers", 10),
    ("COMMENT ON TABLE shop.orders IS 'Customer orders';", "comment", "orders", 10),
]

TABLE_NAMES: Final[tuple[str, ...]] = ("customers", "orders")
