package genkit

import "strings"

// This file is the single writer AND reader of the provenance header that every
// pgdesign-generated artifact begins with. Nothing outside this file may emit
// or match the canonical banner literal -- that is what makes provenance
// enforcement total (roadmap L6): one wording, one grammar, one parser.
//
// The stamp helper is a PURE STRING FORMATTER. It must never import diagnostics
// (internal or pkg): seed stamps its output and lives in internal/, and dragging
// diagnostics across the internal/pkg boundary through the stamp path is a named
// hazard. Keep this file dependency-free beyond the standard library.

// Comment prefixes (including the trailing space) for the artifact kinds
// pgdesign emits. Every generated file's header lines carry one of these.
const (
	// CommentSlash prefixes Go, TypeScript, Java, Kotlin, and Zig.
	CommentSlash = "// "
	// CommentHash prefixes Python, D2, and GraphQL.
	CommentHash = "# "
	// CommentDash prefixes SQL and seed data.
	CommentDash = "-- "
)

// canonicalStamp is the provenance banner. The Go form
// (CommentSlash + canonicalStamp) is exactly the line the Go toolchain
// recognizes as a generated file: it matches ^// Code generated .* DO NOT EDIT\.$
const canonicalStamp = "Code generated by pgdesign. DO NOT EDIT."

// revisionPrefix labels the provenance revision line. The line itself is NOT
// emitted today: Stamp.Revision is empty at every current call site. Roadmap
// 4.2 threads a producing revision through the build pipeline, at which point
// Render emits the line and ParseStamp reads it back -- with no change to the
// grammar and no re-touch of the generator call sites (they already route
// through Stamp; the revision is an additional, currently-unset field).
const revisionPrefix = "pgdesign-revision: "

// stampFormatVersion identifies the header grammar. Version 1 is the canonical
// banner plus optional free-text info lines. The revision line (roadmap 4.2) is
// an additive line under the same version: ParseStamp tolerates it and any
// unknown trailing comment line, so enabling it is not a format break.
const stampFormatVersion = 1

// Stamp is a provenance header for a generated artifact and the ONLY writer of
// the canonical banner. It renders the banner with a per-language comment
// prefix, followed by optional free-text info lines (seed uses this for its
// "Seed data" note).
//
// Revision is reserved for roadmap 4.2. It is empty at every call site today,
// so no revision line is emitted; when 4.2 populates it at the build funnel,
// Render emits the line with zero changes to the generators that construct a
// Stamp.
type Stamp struct {
	// Comment is the comment prefix including the trailing space:
	// CommentSlash, CommentHash, or CommentDash.
	Comment string
	// Info holds optional free-text lines emitted after the banner, each
	// re-prefixed with Comment. Used for seed's descriptive note.
	Info []string
	// Revision is the producing revision id. Empty today (not emitted).
	Revision string
}

// Render returns the header block: the canonical banner line, an optional
// revision line, then any info lines -- every line carrying s.Comment and a
// trailing newline.
func (s Stamp) Render() string {
	var b strings.Builder
	b.WriteString(s.Comment)
	b.WriteString(canonicalStamp)
	b.WriteByte('\n')
	if s.Revision != "" {
		b.WriteString(s.Comment)
		b.WriteString(revisionPrefix)
		b.WriteString(s.Revision)
		b.WriteByte('\n')
	}
	for _, line := range s.Info {
		b.WriteString(s.Comment)
		b.WriteString(line)
		b.WriteByte('\n')
	}
	return b.String()
}

// Header renders a bare provenance banner (no info, no revision) for the given
// comment prefix. It is the convenience form for the generators that need only
// the canonical line.
func Header(comment string) string {
	return Stamp{Comment: comment}.Render()
}

// ParsedStamp is the result of parsing a generated artifact's header.
type ParsedStamp struct {
	// Comment is the detected comment prefix.
	Comment string
	// Revision is the producing revision id, or empty if none was present.
	Revision string
	// Info holds the free-text info lines that followed the banner.
	Info []string
	// FormatVersion is the grammar version recognized.
	FormatVersion int
}

// ParseStamp inspects the head of a generated artifact and reports whether it
// begins with the canonical provenance banner. It recognizes the //, #, and --
// comment prefixes and tolerates leading whitespace. When it matches, it also
// reads the contiguous comment lines that follow (the optional revision line
// and any free-text info) so the header round-trips.
//
// This is the single reader of provenance. Enforcement code asks this function
// "does this artifact carry the stamp?" rather than matching a literal.
func ParseStamp(data []byte) (ParsedStamp, bool) {
	text := strings.TrimLeft(string(data), " \t\r\n")
	if text == "" {
		return ParsedStamp{}, false
	}
	lines := strings.Split(text, "\n")
	first := strings.TrimRight(lines[0], "\r")

	var comment string
	for _, c := range []string{CommentSlash, CommentHash, CommentDash} {
		if first == c+canonicalStamp {
			comment = c
			break
		}
	}
	if comment == "" {
		return ParsedStamp{}, false
	}

	ps := ParsedStamp{Comment: comment, FormatVersion: stampFormatVersion}
	for _, ln := range lines[1:] {
		ln = strings.TrimRight(ln, "\r")
		if !strings.HasPrefix(ln, comment) {
			break
		}
		rest := strings.TrimPrefix(ln, comment)
		if r, ok := strings.CutPrefix(rest, revisionPrefix); ok {
			ps.Revision = r
			continue
		}
		ps.Info = append(ps.Info, rest)
	}
	return ps, true
}

// HasStamp reports whether data begins with the canonical provenance banner
// under any recognized comment prefix. It is the boolean form of ParseStamp,
// used where only presence matters (e.g. deciding whether to prepend a header).
func HasStamp(data []byte) bool {
	_, ok := ParseStamp(data)
	return ok
}
