package genkit

import (
	"github.com/smm-h/pgdesign/internal/testenv"
	"regexp"
	"testing"
)

// goGeneratedRe is the exact regexp the Go toolchain uses to recognize a
// generated file. The Go-prefixed banner must match it.
var goGeneratedRe = regexp.MustCompile(`^// Code generated .* DO NOT EDIT\.$`)

func TestHeaderMatchesGoToolingRegex(t *testing.T) {
	testenv.Isolate(t)
	h := Header(CommentSlash)
	// The banner is the first line, minus the trailing newline.
	line := h
	if i := indexByte(line, '\n'); i >= 0 {
		line = line[:i]
	}
	if !goGeneratedRe.MatchString(line) {
		t.Fatalf("Go header %q does not match the tooling regex %s", line, goGeneratedRe)
	}
}

func indexByte(s string, b byte) int {
	for i := 0; i < len(s); i++ {
		if s[i] == b {
			return i
		}
	}
	return -1
}

func TestParseStampRoundTripAllPrefixes(t *testing.T) {
	testenv.Isolate(t)
	for _, c := range []string{CommentSlash, CommentHash, CommentDash} {
		out := Header(c)
		ps, ok := ParseStamp([]byte(out))
		if !ok {
			t.Fatalf("ParseStamp rejected %q", out)
		}
		if ps.Comment != c {
			t.Errorf("prefix %q: parsed comment = %q", c, ps.Comment)
		}
		if ps.Revision != "" {
			t.Errorf("prefix %q: unexpected revision %q", c, ps.Revision)
		}
		if !HasStamp([]byte(out)) {
			t.Errorf("prefix %q: HasStamp = false", c)
		}
	}
}

func TestParseStampWithInfo(t *testing.T) {
	testenv.Isolate(t)
	out := Stamp{Comment: CommentDash, Info: []string{"Seed data.", "extra"}}.Render()
	ps, ok := ParseStamp([]byte(out))
	if !ok {
		t.Fatal("ParseStamp rejected stamp with info")
	}
	if len(ps.Info) != 2 || ps.Info[0] != "Seed data." || ps.Info[1] != "extra" {
		t.Errorf("info round-trip failed: %v", ps.Info)
	}
}

// TestRevisionLineRoundTrips proves the grammar already accommodates the
// provenance revision line (roadmap 4.2): setting Revision emits it, and the
// parser reads it back, with no grammar change.
func TestRevisionLineRoundTrips(t *testing.T) {
	testenv.Isolate(t)
	out := Stamp{Comment: CommentSlash, Revision: "abc123"}.Render()
	ps, ok := ParseStamp([]byte(out))
	if !ok {
		t.Fatal("ParseStamp rejected stamp with revision")
	}
	if ps.Revision != "abc123" {
		t.Errorf("revision round-trip failed: %q", ps.Revision)
	}
	// The banner line is still first and still Go-tooling-recognized.
	line := out[:indexByte(out, '\n')]
	if !goGeneratedRe.MatchString(line) {
		t.Errorf("banner line broke with revision present: %q", line)
	}
}

func TestParseStampRejectsNonStamp(t *testing.T) {
	testenv.Isolate(t)
	for _, bad := range []string{
		"",
		"package main\n",
		"// some other comment\n",
		"# not a stamp\n",
		"-- Generated by pgdesign -- do not edit\n", // the OLD wording must not parse
	} {
		if HasStamp([]byte(bad)) {
			t.Errorf("HasStamp accepted non-stamp %q", bad)
		}
	}
}

func TestParseStampToleratesLeadingWhitespace(t *testing.T) {
	testenv.Isolate(t)
	out := "\n\n  " + Header(CommentHash)
	if !HasStamp([]byte(out)) {
		t.Errorf("HasStamp rejected stamp with leading whitespace")
	}
}

// TestSetRevisionGuardRejectsReentry asserts the roadmap 4.2/6.1 obligation:
// stampRevision is package-global mutable state whose invariant is "no two
// generation funnels run concurrently in one process". SetRevision mechanically
// enforces it — setting a non-empty revision while one is already set is a hard
// error — so an accidental overlap can never silently stamp the wrong revision.
func TestSetRevisionGuardRejectsReentry(t *testing.T) {
	testenv.Isolate(t)
	// Ensure a clean slate regardless of test ordering.
	SetRevision("")
	defer SetRevision("")

	if err := SetRevision("rev-a"); err != nil {
		t.Fatalf("first SetRevision must succeed, got %v", err)
	}
	if CurrentRevision() != "rev-a" {
		t.Fatalf("expected current revision rev-a, got %q", CurrentRevision())
	}

	// A second non-empty SetRevision without a reset is the concurrency
	// violation — it must be refused, and the original revision must stand.
	err := SetRevision("rev-b")
	if err == nil {
		t.Fatal("re-entrant SetRevision must return an error")
	}
	if CurrentRevision() != "rev-a" {
		t.Fatalf("refused SetRevision must not mutate state; got %q", CurrentRevision())
	}

	// Resetting to "" is always allowed (the funnel exit)...
	if err := SetRevision(""); err != nil {
		t.Fatalf("reset SetRevision(\"\") must succeed, got %v", err)
	}
	// ...after which a fresh funnel may set again.
	if err := SetRevision("rev-c"); err != nil {
		t.Fatalf("SetRevision after reset must succeed, got %v", err)
	}
}
