package seed

import (
	"fmt"
	"math/rand"
	"strings"

	"github.com/smm-h/pgdesign/internal/model"
)

// Generate produces INSERT statements with type-aware test data for all tables
// in the schema. Tables are processed in TableOrder() (topological) order so
// that foreign key references resolve correctly.
func Generate(schema *model.Schema, rowsPerTable int, rng *rand.Rand) string {
	if rowsPerTable <= 0 {
		return "-- Seed data generated by pgdesign\n"
	}

	// Build enum lookup: both bare name and qualified name map to the same values.
	enumValues := make(map[string][]string)
	for _, e := range schema.Enums {
		enumValues[e.Name] = e.Values
		if e.Schema != "" {
			enumValues[e.Schema+"."+e.Name] = e.Values
		}
	}

	// Track generated values per table+column for FK resolution.
	generatedValues := make(map[string]map[string][]string)

	var buf strings.Builder
	buf.WriteString("-- Seed data generated by pgdesign\n")

	for _, table := range schema.TableOrder() {
		tableFQN := table.Schema + "." + table.Name

		// Determine which columns to include.
		var cols []model.Column
		for _, col := range table.Columns {
			if col.Generated != "" {
				continue
			}
			if col.Identity == "ALWAYS" {
				continue
			}
			if col.SemanticTypeName == "auto_id" {
				continue
			}
			cols = append(cols, col)
		}
		if len(cols) == 0 {
			continue
		}

		// Column names for the INSERT header.
		colNames := make([]string, len(cols))
		for i, col := range cols {
			colNames[i] = col.Name
		}

		// Initialize tracking for this table.
		tableVals := make(map[string][]string)

		// Generate rows.
		var rowStrings []string
		for rowIdx := 0; rowIdx < rowsPerTable; rowIdx++ {
			var vals []string
			for _, col := range cols {
				val := generateValue(col, table, rowIdx, rng, enumValues, generatedValues)
				vals = append(vals, val)
				tableVals[col.Name] = append(tableVals[col.Name], val)
			}
			rowStrings = append(rowStrings, "  ("+strings.Join(vals, ", ")+")")
		}

		generatedValues[tableFQN] = tableVals

		buf.WriteString("\n")
		buf.WriteString(fmt.Sprintf("INSERT INTO %s.%s (%s) VALUES\n", table.Schema, table.Name, strings.Join(colNames, ", ")))
		buf.WriteString(strings.Join(rowStrings, ",\n"))
		buf.WriteString(";\n")
	}

	return buf.String()
}

func generateValue(col model.Column, table model.Table, rowIdx int, rng *rand.Rand, enumValues map[string][]string, generatedValues map[string]map[string][]string) string {
	// Check semantic type first.
	if col.SemanticTypeName != "" {
		switch col.SemanticTypeName {
		case "id":
			return generateUUID(rng)
		case "auto_id":
			// Should not reach here (filtered above), but just in case.
			return "DEFAULT"
		case "ref":
			return generateRef(col, table, rng, generatedValues)
		case "email":
			return fmt.Sprintf("'user%d@example.com'", rowIdx)
		case "short_text":
			return fmt.Sprintf("'sample_%s_%s_%d'", table.Name, col.Name, rowIdx)
		case "timestamp", "timestamp_optional":
			return fmt.Sprintf("NOW() - interval '%d days'", rng.Intn(365))
		case "money", "counter":
			return fmt.Sprintf("%d", rng.Intn(10000))
		case "flag":
			if rng.Intn(2) == 0 {
				return "true"
			}
			return "false"
		case "slug":
			return fmt.Sprintf("'%s-%d'", table.Name, rowIdx)
		case "json":
			return "'{}'::jsonb"
		case "json_array":
			return "'[]'::jsonb"
		}

		// Check if semantic type name matches an enum.
		if vals, ok := enumValues[col.SemanticTypeName]; ok && len(vals) > 0 {
			return fmt.Sprintf("'%s'", vals[rng.Intn(len(vals))])
		}
	}

	// Check PGType against enums.
	if vals, ok := enumValues[col.PGType]; ok && len(vals) > 0 {
		return fmt.Sprintf("'%s'", vals[rng.Intn(len(vals))])
	}

	// Fall back to PGType.
	switch col.PGType {
	case "boolean":
		if rng.Intn(2) == 0 {
			return "true"
		}
		return "false"
	case "integer", "bigint", "smallint":
		return fmt.Sprintf("%d", rng.Intn(10000))
	case "uuid":
		return generateUUID(rng)
	case "jsonb":
		return "'{}'::jsonb"
	case "text":
		return fmt.Sprintf("'sample_%s_%s_%d'", table.Name, col.Name, rowIdx)
	}

	// Array types get empty array literal.
	if col.Array {
		return "'{}'"
	}

	return "'sample'"
}

func generateRef(col model.Column, table model.Table, rng *rand.Rand, generatedValues map[string]map[string][]string) string {
	for _, fk := range table.FKs {
		for i, fkCol := range fk.Columns {
			if fkCol == col.Name {
				refTableFQN := fk.RefSchema + "." + fk.RefTable
				refCol := fk.RefColumns[i]
				if tableVals, ok := generatedValues[refTableFQN]; ok {
					if colVals, ok := tableVals[refCol]; ok && len(colVals) > 0 {
						return colVals[rng.Intn(len(colVals))]
					}
				}
				// Fallback: generate a UUID.
				return generateUUID(rng)
			}
		}
	}
	// No FK found for this ref column; fallback UUID.
	return generateUUID(rng)
}

func generateUUID(rng *rand.Rand) string {
	var b [16]byte
	rng.Read(b[:])
	// Set version 4 bits.
	b[6] = (b[6] & 0x0f) | 0x40
	// Set variant bits.
	b[8] = (b[8] & 0x3f) | 0x80
	return fmt.Sprintf("'%02x%02x%02x%02x-%02x%02x-%02x%02x-%02x%02x-%02x%02x%02x%02x%02x%02x'",
		b[0], b[1], b[2], b[3],
		b[4], b[5],
		b[6], b[7],
		b[8], b[9],
		b[10], b[11], b[12], b[13], b[14], b[15])
}
