package seed

import (
	"math/rand"
	"strings"
	"testing"

	"github.com/smm-h/pgdesign/internal/model"
)

func testSchema() *model.Schema {
	return &model.Schema{
		Name: "public",
		Enums: []model.Enum{
			{Schema: "public", Name: "status", Values: []string{"active", "inactive", "pending"}},
		},
		Tables: []model.Table{
			{
				Name: "organizations", Schema: "public",
				Comment: "Organizations",
				PK:      []string{"id"},
				Columns: []model.Column{
					{Name: "id", PGType: "uuid", NotNull: true, SemanticTypeName: "id"},
					{Name: "name", PGType: "text", NotNull: true, SemanticTypeName: "short_text"},
					{Name: "created_at", PGType: "timestamptz", NotNull: true, SemanticTypeName: "timestamp"},
				},
			},
			{
				Name: "users", Schema: "public",
				Comment: "Users",
				PK:      []string{"id"},
				Columns: []model.Column{
					{Name: "id", PGType: "uuid", NotNull: true, SemanticTypeName: "id"},
					{Name: "org_id", PGType: "uuid", NotNull: true, SemanticTypeName: "ref"},
					{Name: "email", PGType: "text", NotNull: true, SemanticTypeName: "email"},
					{Name: "status", PGType: "public.status", NotNull: true},
					{Name: "is_active", PGType: "boolean", NotNull: true, SemanticTypeName: "flag"},
					{Name: "login_count", PGType: "bigint", NotNull: true, SemanticTypeName: "counter"},
					{Name: "slug", PGType: "text", NotNull: true, SemanticTypeName: "slug"},
					{Name: "bio", PGType: "text", NotNull: false},
					{Name: "score", PGType: "bigint", NotNull: true, Generated: "login_count * 10", Stored: true},
				},
				FKs: []model.FK{
					{Name: "fk_users_org", Columns: []string{"org_id"}, RefSchema: "public", RefTable: "organizations", RefColumns: []string{"id"}, OnDelete: "CASCADE"},
				},
			},
		},
	}
}

func TestGenerate_OrderAndStructure(t *testing.T) {
	schema := testSchema()
	rng := rand.New(rand.NewSource(42))
	out := Generate(schema, 3, rng)

	// Must start with the header comment.
	if !strings.HasPrefix(out, "-- Seed data generated by pgdesign") {
		t.Error("output does not start with expected header comment")
	}

	// Organizations must appear before users (topological order).
	orgIdx := strings.Index(out, "INSERT INTO public.organizations")
	usrIdx := strings.Index(out, "INSERT INTO public.users")
	if orgIdx < 0 {
		t.Fatal("missing INSERT INTO public.organizations")
	}
	if usrIdx < 0 {
		t.Fatal("missing INSERT INTO public.users")
	}
	if orgIdx >= usrIdx {
		t.Error("organizations INSERT must appear before users INSERT")
	}

	// Each table should have 3 value tuples.
	// Count occurrences of "(" at the start of value lines for organizations.
	orgBlock := out[orgIdx:usrIdx]
	orgRows := strings.Count(orgBlock, "  (")
	if orgRows != 3 {
		t.Errorf("expected 3 row tuples for organizations, got %d", orgRows)
	}

	usrBlock := out[usrIdx:]
	usrRows := strings.Count(usrBlock, "  (")
	if usrRows != 3 {
		t.Errorf("expected 3 row tuples for users, got %d", usrRows)
	}
}

func TestGenerate_SkipsGeneratedColumns(t *testing.T) {
	schema := testSchema()
	rng := rand.New(rand.NewSource(42))
	out := Generate(schema, 3, rng)

	// Find the users INSERT and extract the column list.
	usrIdx := strings.Index(out, "INSERT INTO public.users")
	if usrIdx < 0 {
		t.Fatal("missing INSERT INTO public.users")
	}
	// Extract from "(" to ")" in the column list.
	headerEnd := strings.Index(out[usrIdx:], ") VALUES")
	if headerEnd < 0 {
		t.Fatal("cannot find ') VALUES' in users INSERT")
	}
	colHeader := out[usrIdx : usrIdx+headerEnd]

	if strings.Contains(colHeader, "score") {
		t.Error("generated column 'score' should not appear in INSERT column list")
	}
}

func TestGenerate_EnumValues(t *testing.T) {
	schema := testSchema()
	rng := rand.New(rand.NewSource(42))
	out := Generate(schema, 10, rng)

	validEnums := map[string]bool{
		"'active'":   true,
		"'inactive'": true,
		"'pending'":  true,
	}

	// Find the users INSERT block.
	usrIdx := strings.Index(out, "INSERT INTO public.users")
	if usrIdx < 0 {
		t.Fatal("missing INSERT INTO public.users")
	}
	usrBlock := out[usrIdx:]

	// The status column is the 4th column (0-indexed: id, org_id, email, status).
	// Parse each row tuple and check the 4th value.
	lines := strings.Split(usrBlock, "\n")
	for _, line := range lines {
		line = strings.TrimSpace(line)
		if !strings.HasPrefix(line, "(") {
			continue
		}
		// Remove leading "(" and trailing ")," or ");"
		line = strings.TrimPrefix(line, "(")
		line = strings.TrimSuffix(line, "),")
		line = strings.TrimSuffix(line, ");")
		parts := strings.Split(line, ", ")
		if len(parts) < 4 {
			continue
		}
		statusVal := parts[3]
		if !validEnums[statusVal] {
			t.Errorf("unexpected enum value for status: %s", statusVal)
		}
	}
}

func TestGenerate_FKReferences(t *testing.T) {
	schema := testSchema()
	rng := rand.New(rand.NewSource(42))
	out := Generate(schema, 5, rng)

	// Collect organization IDs from the organizations INSERT.
	orgIdx := strings.Index(out, "INSERT INTO public.organizations")
	usrIdx := strings.Index(out, "INSERT INTO public.users")
	if orgIdx < 0 || usrIdx < 0 {
		t.Fatal("missing expected INSERT statements")
	}

	orgBlock := out[orgIdx:usrIdx]
	orgIDs := make(map[string]bool)
	for _, line := range strings.Split(orgBlock, "\n") {
		line = strings.TrimSpace(line)
		if !strings.HasPrefix(line, "(") {
			continue
		}
		line = strings.TrimPrefix(line, "(")
		line = strings.TrimSuffix(line, "),")
		line = strings.TrimSuffix(line, ");")
		parts := strings.Split(line, ", ")
		if len(parts) >= 1 {
			orgIDs[parts[0]] = true
		}
	}

	if len(orgIDs) == 0 {
		t.Fatal("no organization IDs found")
	}

	// Check that all user org_id values reference a known organization ID.
	usrBlock := out[usrIdx:]
	for _, line := range strings.Split(usrBlock, "\n") {
		line = strings.TrimSpace(line)
		if !strings.HasPrefix(line, "(") {
			continue
		}
		line = strings.TrimPrefix(line, "(")
		line = strings.TrimSuffix(line, "),")
		line = strings.TrimSuffix(line, ");")
		parts := strings.Split(line, ", ")
		if len(parts) < 2 {
			continue
		}
		orgID := parts[1] // org_id is the 2nd column
		if !orgIDs[orgID] {
			t.Errorf("user org_id %s does not match any organization ID", orgID)
		}
	}
}

func TestGenerate_Deterministic(t *testing.T) {
	schema := testSchema()

	rng1 := rand.New(rand.NewSource(42))
	out1 := Generate(schema, 5, rng1)

	rng2 := rand.New(rand.NewSource(42))
	out2 := Generate(schema, 5, rng2)

	if out1 != out2 {
		t.Error("Generate with the same seed should produce identical output")
	}
}
