package seed

import (
	"encoding/json"
	"fmt"
	"math"
	"math/rand"
	"strings"
	"time"

	"github.com/smm-h/pgdesign/internal/diagnostic"
	"github.com/smm-h/pgdesign/internal/model"
	"github.com/smm-h/pgdesign/internal/sqlexpr"
)

var wordList = []string{"alpha", "bravo", "charlie", "delta", "echo", "foxtrot", "golf", "hotel", "india", "juliet"}

func randomWord(rng *rand.Rand) string {
	return wordList[rng.Intn(len(wordList))]
}

func randomDate(rng *rand.Rand) string {
	base := time.Date(2025, 1, 1, 0, 0, 0, 0, time.UTC)
	d := base.AddDate(0, 0, -rng.Intn(365))
	return d.Format("2006-01-02")
}

func randomTimestamp(rng *rand.Rand) string {
	return fmt.Sprintf("%s %02d:%02d:%02d", randomDate(rng), rng.Intn(24), rng.Intn(60), rng.Intn(60))
}

// SeedConfig holds per-table seed configuration.
type SeedConfig struct {
	TableRows map[string]int // table name -> row count override
	Format    string         // "insert" (default) or "copy"
	Clean     bool           // emit TRUNCATE before data
	Mode      string         // "normal" (default) or "edge-cases"
	Apply     bool           // true when --apply mode (skip BEGIN/COMMIT wrapping)
}

// checkHint holds a parsed CHECK constraint that affects a specific column.
type checkHint struct {
	col     string
	kind    string // "range", "length", "regex"
	min     int    // for "range"
	max     int    // for "range" and "length"
	pattern string // for "regex"
}

// uniqueTracker enforces uniqueness for columns with unique constraints.
type uniqueTracker struct {
	seen map[string]map[string]bool // constraintKey -> set of seen value combos
}

func newUniqueTracker() *uniqueTracker {
	return &uniqueTracker{seen: make(map[string]map[string]bool)}
}

// check returns true if the value combo is new (not seen before), and records it.
func (u *uniqueTracker) check(key string, value string) bool {
	if u.seen[key] == nil {
		u.seen[key] = make(map[string]bool)
	}
	if u.seen[key][value] {
		return false
	}
	u.seen[key][value] = true
	return true
}

// Generate produces INSERT statements with type-aware test data for all tables
// in the schema. Tables are processed in TableOrder() (topological) order so
// that foreign key references resolve correctly. Tables in FK cycles use a
// two-pass approach: NULLs first, then UPDATEs.
func Generate(schema *model.Schema, rowsPerTable int, rng *rand.Rand, cfg *SeedConfig) (string, diagnostic.Diagnostics) {
	var diags diagnostic.Diagnostics

	// Normalize config defaults.
	if cfg == nil {
		cfg = &SeedConfig{}
	}
	if cfg.Format == "" {
		cfg.Format = "insert"
	}
	if cfg.Mode == "" {
		cfg.Mode = "normal"
	}

	// Edge-cases mode forces exactly 1 row per table.
	if cfg.Mode == "edge-cases" {
		rowsPerTable = 1
	}

	if rowsPerTable <= 0 {
		return "-- Seed data generated by pgdesign\n", nil
	}

	// Build enum lookup: both bare name and qualified name map to the same values.
	enumValues := make(map[string][]string)
	for _, e := range schema.Enums {
		enumValues[e.Name] = e.Values
		if e.Schema != "" {
			enumValues[e.Schema+"."+e.Name] = e.Values
		}
	}

	// Build cycle membership set from schema.CycleGroups.
	cycleMembers := make(map[string]map[string]bool) // table FQN -> set of other tables in cycle
	for _, group := range schema.CycleGroups {
		fqns := make([]string, len(group))
		for i, name := range group {
			for _, t := range schema.Tables {
				if t.Name == name {
					fqns[i] = t.Schema + "." + t.Name
					break
				}
			}
			if fqns[i] == "" {
				fqns[i] = name
			}
		}
		for _, fqn := range fqns {
			if cycleMembers[fqn] == nil {
				cycleMembers[fqn] = make(map[string]bool)
			}
			for _, other := range fqns {
				if other != fqn {
					cycleMembers[fqn][other] = true
				}
			}
		}
	}

	// Track generated values per table+column for FK resolution.
	generatedValues := make(map[string]map[string][]string)
	// Track PK values for cycle UPDATE statements.
	tablePKValues := make(map[string][][]string) // tableFQN -> list of PK value tuples

	var buf strings.Builder
	buf.WriteString("-- Seed data generated by pgdesign\n")

	// Transaction wrapping: only when not in apply mode (apply manages its own tx).
	if !cfg.Apply {
		buf.WriteString("BEGIN;\n")
	}

	// Clean: TRUNCATE tables in reverse dependency order.
	if cfg.Clean {
		order := schema.TableOrder()
		var tableNames []string
		for i := len(order) - 1; i >= 0; i-- {
			tableNames = append(tableNames, order[i].Schema+"."+order[i].Name)
		}
		buf.WriteString("\nTRUNCATE ")
		buf.WriteString(strings.Join(tableNames, ", "))
		buf.WriteString(" CASCADE;\n")
	}

	// Deferred UPDATE statements for FK cycle resolution.
	var deferredUpdates []string

	for _, table := range schema.TableOrder() {
		tableFQN := table.Schema + "." + table.Name

		// Pre-compute CHECK constraint hints for this table.
		hints := analyzeChecks(table.Checks)

		// Determine row count.
		rows := rowsPerTable
		if cfg != nil && cfg.TableRows != nil {
			if override, ok := cfg.TableRows[table.Name]; ok {
				rows = override
			}
		}

		// Determine which FK columns participate in cycles (need NULL-then-UPDATE).
		cycleFKCols := make(map[string]bool)
		if peers, inCycle := cycleMembers[tableFQN]; inCycle {
			for _, fk := range table.FKs {
				refFQN := fk.RefSchema + "." + fk.RefTable
				if peers[refFQN] {
					for _, c := range fk.Columns {
						cycleFKCols[c] = true
					}
					// Warn if cycle FK is NOT NULL.
					for _, c := range fk.Columns {
						for _, col := range table.Columns {
							if col.Name == c && col.NotNull {
								diags = append(diags, diagnostic.Diagnostic{
									Severity: diagnostic.Warning,
									Code:     "S001",
									Table:    table.Name,
									Column:   c,
									Message:  fmt.Sprintf("FK column %q in cycle is NOT NULL; two-pass seeding requires nullable FKs", c),
								})
							}
						}
					}
				}
			}
		}

		// Determine which columns to include.
		var cols []model.Column
		for _, col := range table.Columns {
			if col.Generated != "" {
				continue
			}
			if col.Identity == "ALWAYS" {
				continue
			}
			if col.SemanticTypeName == "auto_id" {
				continue
			}
			cols = append(cols, col)
		}
		if len(cols) == 0 {
			continue
		}

		// For COPY format, identify which columns produce DEFAULT (serial types)
		// and must be excluded since COPY cannot use DEFAULT.
		isDefaultCol := make([]bool, len(cols))
		if cfg.Format == "copy" {
			for i, col := range cols {
				switch col.PGType {
				case "serial", "bigserial", "smallserial":
					isDefaultCol[i] = true
				}
			}
		}

		// Build the column list (excluding DEFAULT columns in COPY mode).
		var colNames []string
		var colIndexes []int // indexes into cols for non-default columns
		for i, col := range cols {
			if cfg.Format == "copy" && isDefaultCol[i] {
				continue
			}
			colNames = append(colNames, col.Name)
			colIndexes = append(colIndexes, i)
		}

		// Initialize tracking for this table.
		tableVals := make(map[string][]string)
		ut := newUniqueTracker()

		// Build unique constraint column index sets for this table.
		type uniqueSpec struct {
			name    string
			colIdxs []int // indexes into cols
		}
		var uniqueSpecs []uniqueSpec
		for _, uc := range table.Uniques {
			var idxs []int
			for _, ucCol := range uc.Columns {
				for i, col := range cols {
					if col.Name == ucCol {
						idxs = append(idxs, i)
						break
					}
				}
			}
			if len(idxs) == len(uc.Columns) {
				uniqueSpecs = append(uniqueSpecs, uniqueSpec{name: uc.Name, colIdxs: idxs})
			}
		}
		// PK is also a unique constraint.
		if len(table.PK) > 0 {
			var pkIdxs []int
			for _, pkCol := range table.PK {
				for i, col := range cols {
					if col.Name == pkCol {
						pkIdxs = append(pkIdxs, i)
						break
					}
				}
			}
			if len(pkIdxs) == len(table.PK) {
				uniqueSpecs = append(uniqueSpecs, uniqueSpec{name: "_pk_", colIdxs: pkIdxs})
			}
		}

		// Track integer type counters for edge-cases mode (first=0, rest=max).
		intTypeCounter := make(map[string]int) // PGType -> count of columns seen

		// Generate rows.
		var allVals [][]string // allVals[rowIdx][colIdx] = INSERT-format value
		for rowIdx := 0; rowIdx < rows; rowIdx++ {
			var vals []string
			ok := false
			for attempt := 0; attempt < 100; attempt++ {
				vals = vals[:0]
				for _, col := range cols {
					if cycleFKCols[col.Name] {
						vals = append(vals, "NULL")
					} else if cfg.Mode == "edge-cases" {
						val := generateEdgeCaseValue(col, table, rng, enumValues, generatedValues, intTypeCounter)
						vals = append(vals, val)
					} else {
						val := generateValue(col, table, rowIdx, rng, enumValues, generatedValues, hints)
						vals = append(vals, val)
					}
				}
				// Check uniqueness.
				unique := true
				for _, us := range uniqueSpecs {
					var parts []string
					for _, idx := range us.colIdxs {
						parts = append(parts, vals[idx])
					}
					combo := strings.Join(parts, "\x00")
					if !ut.check(us.name, combo) {
						unique = false
						break
					}
				}
				if unique {
					ok = true
					break
				}
			}
			if !ok {
				// Exhausted retries; use the last generated values anyway.
			}
			for i, col := range cols {
				tableVals[col.Name] = append(tableVals[col.Name], vals[i])
			}
			allVals = append(allVals, vals)
		}

		generatedValues[tableFQN] = tableVals

		// Track PK values for cycle UPDATE statements.
		if len(cycleFKCols) > 0 && len(table.PK) > 0 {
			for rowIdx := 0; rowIdx < rows; rowIdx++ {
				var pkVals []string
				for _, pkCol := range table.PK {
					if v, ok := tableVals[pkCol]; ok && rowIdx < len(v) {
						pkVals = append(pkVals, v[rowIdx])
					}
				}
				tablePKValues[tableFQN] = append(tablePKValues[tableFQN], pkVals)
			}
		}

		// Emit data in the configured format.
		buf.WriteString("\n")
		if cfg.Format == "copy" {
			buf.WriteString(fmt.Sprintf("COPY %s.%s (%s) FROM stdin;\n", table.Schema, table.Name, strings.Join(colNames, ", ")))
			for _, vals := range allVals {
				var copyVals []string
				for _, idx := range colIndexes {
					copyVals = append(copyVals, toCopyValue(vals[idx], rng))
				}
				buf.WriteString(strings.Join(copyVals, "\t"))
				buf.WriteString("\n")
			}
			buf.WriteString("\\.\n")
		} else {
			// INSERT format with batching (1000 rows per statement).
			const batchSize = 1000
			for batchStart := 0; batchStart < len(allVals); batchStart += batchSize {
				batchEnd := batchStart + batchSize
				if batchEnd > len(allVals) {
					batchEnd = len(allVals)
				}
				batch := allVals[batchStart:batchEnd]
				var rowStrings []string
				for _, vals := range batch {
					rowStrings = append(rowStrings, "  ("+strings.Join(vals, ", ")+")")
				}
				if batchStart > 0 {
					buf.WriteString("\n")
				}
				buf.WriteString(fmt.Sprintf("INSERT INTO %s.%s (%s) VALUES\n", table.Schema, table.Name, strings.Join(colNames, ", ")))
				buf.WriteString(strings.Join(rowStrings, ",\n"))
				buf.WriteString(";\n")
			}
		}

		// Build deferred UPDATE statements for cycle FK columns.
		if len(cycleFKCols) > 0 && len(table.PK) > 0 {
			for _, fk := range table.FKs {
				refFQN := fk.RefSchema + "." + fk.RefTable
				if peers, inCycle := cycleMembers[tableFQN]; inCycle && peers[refFQN] {
					for rowIdx := 0; rowIdx < rows; rowIdx++ {
						pkVals := tablePKValues[tableFQN]
						if rowIdx >= len(pkVals) {
							continue
						}
						// Generate FK value now that the referenced table is seeded.
						var setClauses []string
						for i, fkCol := range fk.Columns {
							refCol := fk.RefColumns[i]
							refTableVals := generatedValues[refFQN]
							if refTableVals == nil {
								continue
							}
							refColVals := refTableVals[refCol]
							if len(refColVals) == 0 {
								continue
							}
							z := rand.NewZipf(rng, 1.5, 1, uint64(len(refColVals)-1))
							val := refColVals[z.Uint64()]
							setClauses = append(setClauses, fmt.Sprintf("%s = %s", fkCol, val))
						}
						if len(setClauses) == 0 {
							continue
						}
						// Build WHERE from PK.
						var whereParts []string
						for j, pkCol := range table.PK {
							if j < len(pkVals[rowIdx]) {
								whereParts = append(whereParts, fmt.Sprintf("%s = %s", pkCol, pkVals[rowIdx][j]))
							}
						}
						if len(whereParts) > 0 {
							deferredUpdates = append(deferredUpdates,
								fmt.Sprintf("UPDATE %s SET %s WHERE %s;",
									tableFQN,
									strings.Join(setClauses, ", "),
									strings.Join(whereParts, " AND ")))
						}
					}
				}
			}
		}
	}

	// Emit deferred UPDATE statements for FK cycle resolution.
	if len(deferredUpdates) > 0 {
		buf.WriteString("\n-- FK cycle resolution: backfill deferred foreign keys\n")
		for _, upd := range deferredUpdates {
			buf.WriteString(upd)
			buf.WriteString("\n")
		}
	}

	// Close transaction wrapping.
	if !cfg.Apply {
		buf.WriteString("\nCOMMIT;\n")
	}

	return buf.String(), diags
}

func generateValue(col model.Column, table model.Table, rowIdx int, rng *rand.Rand, enumValues map[string][]string, generatedValues map[string]map[string][]string, hints []checkHint) string {
	// Array population: generate 1-5 elements.
	if col.Array {
		count := 1 + rng.Intn(5)
		elemCol := col
		elemCol.Array = false
		var elems []string
		for i := 0; i < count; i++ {
			v := generateValue(elemCol, table, rowIdx+i, rng, enumValues, generatedValues, hints)
			elems = append(elems, v)
		}
		return fmt.Sprintf("ARRAY[%s]", strings.Join(elems, ", "))
	}

	// NULL injection for nullable columns.
	if !col.NotNull && rng.Float64() < 0.10 {
		return "NULL"
	}

	// Check for CHECK constraint hints that override default generation.
	for _, h := range hints {
		if h.col != col.Name {
			continue
		}
		switch h.kind {
		case "range":
			span := h.max - h.min + 1
			if span > 0 {
				return fmt.Sprintf("%d", h.min+rng.Intn(span))
			}
		case "length":
			base := generateBaseString(col, table, rowIdx, rng, enumValues)
			if len(base) > h.max {
				base = base[:h.max]
			}
			return fmt.Sprintf("'%s'", strings.ReplaceAll(base, "'", "''"))
		case "regex":
			if s, err := regenFromPattern(h.pattern, rng); err == nil && s != "" {
				return fmt.Sprintf("'%s'", strings.ReplaceAll(s, "'", "''"))
			}
		}
	}

	// Check semantic type first.
	if col.SemanticTypeName != "" {
		switch col.SemanticTypeName {
		case "id":
			return generateUUID(rng)
		case "auto_id":
			return "DEFAULT"
		case "ref":
			return generateRef(col, table, rng, generatedValues)
		case "email":
			return fmt.Sprintf("'user%d@example.com'", rowIdx)
		case "short_text":
			return fmt.Sprintf("'sample_%s_%s_%d'", table.Name, col.Name, rowIdx)
		case "timestamp", "timestamp_optional":
			return fmt.Sprintf("NOW() - interval '%d days'", rng.Intn(365))
		case "money":
			// Log-normal distribution for realistic money values.
			v := math.Exp(rng.NormFloat64()*1.0 + 4.0)
			cents := int(math.Abs(v))
			if cents > 999999 {
				cents = 999999
			}
			return fmt.Sprintf("%d", cents)
		case "counter":
			return fmt.Sprintf("%d", rng.Intn(10000))
		case "flag":
			if rng.Intn(2) == 0 {
				return "true"
			}
			return "false"
		case "slug":
			return fmt.Sprintf("'%s-%d'", table.Name, rowIdx)
		case "json":
			if col.JSONSchema != "" {
				return generateJSONFromSchema(col.JSONSchema, rng)
			}
			return "'{}'::jsonb"
		case "json_array":
			return "'[]'::jsonb"
		}

		// Check if semantic type name matches an enum.
		if vals, ok := enumValues[col.SemanticTypeName]; ok && len(vals) > 0 {
			return fmt.Sprintf("'%s'", vals[rng.Intn(len(vals))])
		}
	}

	// Check PGType against enums.
	if vals, ok := enumValues[col.PGType]; ok && len(vals) > 0 {
		return fmt.Sprintf("'%s'", vals[rng.Intn(len(vals))])
	}

	// Fall back to PGType.
	switch col.PGType {
	case "boolean":
		if rng.Intn(2) == 0 {
			return "true"
		}
		return "false"
	case "integer", "bigint", "smallint":
		return fmt.Sprintf("%d", rng.Intn(10000))
	case "serial", "bigserial", "smallserial":
		return "DEFAULT"
	case "numeric":
		return fmt.Sprintf("'%d.%02d'", rng.Intn(10000), rng.Intn(100))
	case "real", "float4":
		return fmt.Sprintf("%f", rng.Float32()*1000)
	case "float8":
		return fmt.Sprintf("%f", rng.Float64()*1000)
	case "uuid":
		return generateUUID(rng)
	case "text", "citext":
		return fmt.Sprintf("'sample_%s_%s_%d'", table.Name, col.Name, rowIdx)
	case "varchar", "char":
		return fmt.Sprintf("'txt_%s_%d'", col.Name, rowIdx)
	case "bytea":
		var b [8]byte
		rng.Read(b[:])
		return fmt.Sprintf("'\\x%02x%02x%02x%02x%02x%02x%02x%02x'", b[0], b[1], b[2], b[3], b[4], b[5], b[6], b[7])
	case "date":
		return fmt.Sprintf("'%s'", randomDate(rng))
	case "time":
		return fmt.Sprintf("'%02d:%02d:%02d'", rng.Intn(24), rng.Intn(60), rng.Intn(60))
	case "timetz":
		return fmt.Sprintf("'%02d:%02d:%02d+00'", rng.Intn(24), rng.Intn(60), rng.Intn(60))
	case "timestamp":
		return fmt.Sprintf("'%s'", randomTimestamp(rng))
	case "timestamptz":
		return fmt.Sprintf("'%s'", randomTimestamp(rng))
	case "interval":
		return fmt.Sprintf("'%d days %d hours %d minutes'", rng.Intn(30), rng.Intn(24), rng.Intn(60))
	case "jsonb":
		if col.JSONSchema != "" {
			return generateJSONFromSchema(col.JSONSchema, rng)
		}
		return "'{}'::jsonb"
	case "json":
		return "'{}'::json"
	case "xml":
		return fmt.Sprintf("'<val>item_%d</val>'", rowIdx)
	case "inet":
		return fmt.Sprintf("'%d.%d.%d.%d'", rng.Intn(256), rng.Intn(256), rng.Intn(256), rng.Intn(256))
	case "cidr":
		return fmt.Sprintf("'%d.%d.%d.0/24'", rng.Intn(256), rng.Intn(256), rng.Intn(256))
	case "macaddr":
		return fmt.Sprintf("'%02x:%02x:%02x:%02x:%02x:%02x'", rng.Intn(256), rng.Intn(256), rng.Intn(256), rng.Intn(256), rng.Intn(256), rng.Intn(256))
	case "tsvector":
		return fmt.Sprintf("'%s %s'::tsvector", randomWord(rng), randomWord(rng))
	case "tsquery":
		return fmt.Sprintf("'%s & %s'::tsquery", randomWord(rng), randomWord(rng))
	case "oid":
		return fmt.Sprintf("%d", rng.Intn(100000)+1)
	case "int4range":
		lo := rng.Intn(1000)
		return fmt.Sprintf("'[%d,%d)'", lo, lo+rng.Intn(100)+1)
	case "int8range":
		lo := rng.Intn(1000)
		return fmt.Sprintf("'[%d,%d)'", lo, lo+rng.Intn(100)+1)
	case "numrange":
		lo := rng.Intn(1000)
		hi := lo + rng.Intn(100) + 1
		return fmt.Sprintf("'[%d.00,%d.00)'", lo, hi)
	case "daterange":
		d1 := randomDate(rng)
		d2 := randomDate(rng)
		if d1 > d2 {
			d1, d2 = d2, d1
		}
		return fmt.Sprintf("'[%s,%s)'", d1, d2)
	case "tsrange":
		t1 := randomTimestamp(rng)
		t2 := randomTimestamp(rng)
		if t1 > t2 {
			t1, t2 = t2, t1
		}
		return fmt.Sprintf("'[%s,%s)'", t1, t2)
	case "tstzrange":
		t1 := randomTimestamp(rng)
		t2 := randomTimestamp(rng)
		if t1 > t2 {
			t1, t2 = t2, t1
		}
		return fmt.Sprintf("'[%s,%s)'", t1, t2)
	case "int4multirange":
		lo := rng.Intn(1000)
		return fmt.Sprintf("'{[%d,%d)}'", lo, lo+rng.Intn(100)+1)
	case "int8multirange":
		lo := rng.Intn(1000)
		return fmt.Sprintf("'{[%d,%d)}'", lo, lo+rng.Intn(100)+1)
	case "nummultirange":
		lo := rng.Intn(1000)
		hi := lo + rng.Intn(100) + 1
		return fmt.Sprintf("'{[%d.00,%d.00)}'", lo, hi)
	case "datemultirange":
		d1 := randomDate(rng)
		d2 := randomDate(rng)
		if d1 > d2 {
			d1, d2 = d2, d1
		}
		return fmt.Sprintf("'{[%s,%s)}'", d1, d2)
	case "tsmultirange":
		t1 := randomTimestamp(rng)
		t2 := randomTimestamp(rng)
		if t1 > t2 {
			t1, t2 = t2, t1
		}
		return fmt.Sprintf("'{[%s,%s)}'", t1, t2)
	case "tstzmultirange":
		t1 := randomTimestamp(rng)
		t2 := randomTimestamp(rng)
		if t1 > t2 {
			t1, t2 = t2, t1
		}
		return fmt.Sprintf("'{[%s,%s)}'", t1, t2)
	}

	// Unknown types get a NULL cast so SQL still executes and the gap is visible.
	return fmt.Sprintf("NULL::%s /* unsupported seed type */", col.PGType)
}

// toCopyValue transforms an INSERT-format SQL value to COPY-format (tab-separated stdin).
func toCopyValue(insertVal string, rng *rand.Rand) string {
	if insertVal == "NULL" {
		return `\N`
	}
	if insertVal == "true" {
		return "t"
	}
	if insertVal == "false" {
		return "f"
	}
	if insertVal == "DEFAULT" {
		// Should not reach here; DEFAULT columns are excluded in COPY mode.
		return `\N`
	}

	// Strip type casts: ::jsonb, ::json, ::tsvector, ::tsquery, etc.
	val := stripTypeCast(insertVal)

	// Handle function calls like NOW() - interval '...' -> literal timestamp.
	if isFunctionCall(val) {
		return randomTimestamp(rng)
	}

	// Handle ARRAY[...] -> PG array literal {...}.
	if strings.HasPrefix(val, "ARRAY[") {
		return arrayToCopyLiteral(val)
	}

	// Handle quoted strings: strip outer single quotes, unescape, re-escape for COPY.
	if len(val) >= 2 && val[0] == '\'' && val[len(val)-1] == '\'' {
		inner := val[1 : len(val)-1]
		// Unescape SQL doubled quotes.
		inner = strings.ReplaceAll(inner, "''", "'")
		// Escape for COPY format.
		inner = escapeCopy(inner)
		return inner
	}

	// Numeric and other literal values pass through.
	return val
}

// stripTypeCast removes PostgreSQL type cast suffixes (e.g., ::jsonb, ::json).
func stripTypeCast(val string) string {
	// Handle ::type[] and ::type suffixes, possibly with /* comment */.
	for {
		idx := strings.Index(val, "::")
		if idx < 0 {
			break
		}
		val = val[:idx]
	}
	return val
}

// isFunctionCall detects SQL function calls like NOW(), current_timestamp, etc.
func isFunctionCall(val string) bool {
	upper := strings.ToUpper(strings.TrimSpace(val))
	return strings.HasPrefix(upper, "NOW()") ||
		strings.HasPrefix(upper, "CURRENT_TIMESTAMP") ||
		strings.HasPrefix(upper, "CURRENT_DATE") ||
		strings.HasPrefix(upper, "CURRENT_TIME")
}

// arrayToCopyLiteral converts ARRAY[val1, val2, ...] to {val1,val2,...}.
func arrayToCopyLiteral(val string) string {
	// Strip "ARRAY[" prefix and "]" suffix.
	inner := val[6:]
	if strings.HasSuffix(inner, "]") {
		inner = inner[:len(inner)-1]
	}
	// Split elements and unquote.
	var elems []string
	for _, elem := range splitArrayElements(inner) {
		elem = strings.TrimSpace(elem)
		elem = stripTypeCast(elem)
		// Unquote SQL strings.
		if len(elem) >= 2 && elem[0] == '\'' && elem[len(elem)-1] == '\'' {
			elem = elem[1 : len(elem)-1]
			elem = strings.ReplaceAll(elem, "''", "'")
		}
		elems = append(elems, elem)
	}
	return "{" + strings.Join(elems, ",") + "}"
}

// splitArrayElements splits a comma-separated list respecting SQL quoting.
func splitArrayElements(s string) []string {
	var result []string
	var current strings.Builder
	inQuote := false
	for i := 0; i < len(s); i++ {
		ch := s[i]
		if ch == '\'' && !inQuote {
			inQuote = true
			current.WriteByte(ch)
		} else if ch == '\'' && inQuote {
			current.WriteByte(ch)
			// Check for doubled quote.
			if i+1 < len(s) && s[i+1] == '\'' {
				current.WriteByte(s[i+1])
				i++
			} else {
				inQuote = false
			}
		} else if ch == ',' && !inQuote {
			result = append(result, current.String())
			current.Reset()
		} else {
			current.WriteByte(ch)
		}
	}
	if current.Len() > 0 {
		result = append(result, current.String())
	}
	return result
}

// escapeCopy escapes a string for COPY format (backslash-escape special chars).
func escapeCopy(s string) string {
	var buf strings.Builder
	for _, ch := range s {
		switch ch {
		case '\\':
			buf.WriteString(`\\`)
		case '\t':
			buf.WriteString(`\t`)
		case '\n':
			buf.WriteString(`\n`)
		case '\r':
			buf.WriteString(`\r`)
		default:
			buf.WriteRune(ch)
		}
	}
	return buf.String()
}

// generateEdgeCaseValue produces boundary/edge-case values for testing.
func generateEdgeCaseValue(col model.Column, table model.Table, rng *rand.Rand, enumValues map[string][]string, generatedValues map[string]map[string][]string, intTypeCounter map[string]int) string {
	// Array columns: empty array with cast.
	if col.Array {
		return fmt.Sprintf("ARRAY[]::%s[]", col.PGType)
	}

	// Nullable columns: NULL.
	if !col.NotNull {
		return "NULL"
	}

	// FK reference columns: use first value from parent table.
	if col.SemanticTypeName == "ref" {
		return generateEdgeCaseRef(col, table, generatedValues)
	}

	// Check semantic type first.
	if col.SemanticTypeName != "" {
		switch col.SemanticTypeName {
		case "id":
			return "'00000000-0000-0000-0000-000000000000'"
		case "auto_id":
			return "DEFAULT"
		case "email":
			return "''"
		case "short_text", "slug":
			return "''"
		case "timestamp", "timestamp_optional":
			return "'0001-01-01 00:00:00'"
		case "money":
			return "0"
		case "counter":
			return "0"
		case "flag":
			return "true"
		case "json":
			return "'null'::jsonb"
		case "json_array":
			return "'null'::jsonb"
		}
		// Enum semantic types: use first value.
		if vals, ok := enumValues[col.SemanticTypeName]; ok && len(vals) > 0 {
			return fmt.Sprintf("'%s'", vals[0])
		}
	}

	// Check PGType against enums.
	if vals, ok := enumValues[col.PGType]; ok && len(vals) > 0 {
		return fmt.Sprintf("'%s'", vals[0])
	}

	// Fall back to PGType.
	switch col.PGType {
	case "boolean":
		return "true"
	case "integer":
		cnt := intTypeCounter["integer"]
		intTypeCounter["integer"] = cnt + 1
		if cnt == 0 {
			return "0"
		}
		return "2147483647"
	case "bigint":
		cnt := intTypeCounter["bigint"]
		intTypeCounter["bigint"] = cnt + 1
		if cnt == 0 {
			return "0"
		}
		return "9223372036854775807"
	case "smallint":
		cnt := intTypeCounter["smallint"]
		intTypeCounter["smallint"] = cnt + 1
		if cnt == 0 {
			return "0"
		}
		return "32767"
	case "serial", "bigserial", "smallserial":
		return "DEFAULT"
	case "numeric":
		return "0"
	case "real", "float4", "float8":
		return "0.0"
	case "uuid":
		return "'00000000-0000-0000-0000-000000000000'"
	case "text", "citext", "varchar", "char":
		return "''"
	case "bytea":
		return "'\\x'"
	case "date":
		return "'0001-01-01'"
	case "time", "timetz":
		return "'00:00:00'"
	case "timestamp", "timestamptz":
		return "'0001-01-01 00:00:00'"
	case "interval":
		return "'0'"
	case "jsonb":
		return "'null'::jsonb"
	case "json":
		return "'null'::json"
	case "xml":
		return "'<empty/>'"
	case "inet":
		return "'0.0.0.0'"
	case "cidr":
		return "'0.0.0.0/0'"
	case "macaddr":
		return "'00:00:00:00:00:00'"
	case "tsvector":
		return "''::tsvector"
	case "tsquery":
		return "''::tsquery"
	case "oid":
		return "0"
	case "int4range", "int8range":
		return "'empty'"
	case "numrange":
		return "'empty'"
	case "daterange":
		return "'empty'"
	case "tsrange", "tstzrange":
		return "'empty'"
	case "int4multirange", "int8multirange":
		return "'{}'::int4multirange"
	case "nummultirange":
		return "'{}'::nummultirange"
	case "datemultirange":
		return "'{}'::datemultirange"
	case "tsmultirange", "tstzmultirange":
		return "'{}'::tsmultirange"
	}

	return fmt.Sprintf("NULL::%s /* unsupported seed type */", col.PGType)
}

// generateEdgeCaseRef returns the first generated value from the parent table.
func generateEdgeCaseRef(col model.Column, table model.Table, generatedValues map[string]map[string][]string) string {
	for _, fk := range table.FKs {
		for i, fkCol := range fk.Columns {
			if fkCol == col.Name {
				refTableFQN := fk.RefSchema + "." + fk.RefTable
				refCol := fk.RefColumns[i]
				if tableVals, ok := generatedValues[refTableFQN]; ok {
					if colVals, ok := tableVals[refCol]; ok && len(colVals) > 0 {
						return colVals[0]
					}
				}
				return "'00000000-0000-0000-0000-000000000000'"
			}
		}
	}
	return "'00000000-0000-0000-0000-000000000000'"
}

// generateBaseString produces an unquoted string value for truncation by length hints.
func generateBaseString(col model.Column, table model.Table, rowIdx int, rng *rand.Rand, enumValues map[string][]string) string {
	if col.SemanticTypeName == "short_text" || col.SemanticTypeName == "slug" {
		return fmt.Sprintf("sample_%s_%s_%d", table.Name, col.Name, rowIdx)
	}
	if col.SemanticTypeName == "email" {
		return fmt.Sprintf("user%d@example.com", rowIdx)
	}
	switch col.PGType {
	case "text", "citext":
		return fmt.Sprintf("sample_%s_%s_%d", table.Name, col.Name, rowIdx)
	case "varchar", "char":
		return fmt.Sprintf("txt_%s_%d", col.Name, rowIdx)
	}
	return fmt.Sprintf("val_%d", rowIdx)
}

func generateRef(col model.Column, table model.Table, rng *rand.Rand, generatedValues map[string]map[string][]string) string {
	for _, fk := range table.FKs {
		for i, fkCol := range fk.Columns {
			if fkCol == col.Name {
				refTableFQN := fk.RefSchema + "." + fk.RefTable
				refCol := fk.RefColumns[i]
				if tableVals, ok := generatedValues[refTableFQN]; ok {
					if colVals, ok := tableVals[refCol]; ok && len(colVals) > 0 {
						// Zipf distribution for realistic FK skew.
						z := rand.NewZipf(rng, 1.5, 1, uint64(len(colVals)-1))
						return colVals[z.Uint64()]
					}
				}
				// Fallback: generate a UUID.
				return generateUUID(rng)
			}
		}
	}
	// No FK found for this ref column; fallback UUID.
	return generateUUID(rng)
}

func generateUUID(rng *rand.Rand) string {
	var b [16]byte
	rng.Read(b[:])
	b[6] = (b[6] & 0x0f) | 0x40
	b[8] = (b[8] & 0x3f) | 0x80
	return fmt.Sprintf("'%02x%02x%02x%02x-%02x%02x-%02x%02x-%02x%02x-%02x%02x%02x%02x%02x%02x'",
		b[0], b[1], b[2], b[3],
		b[4], b[5],
		b[6], b[7],
		b[8], b[9],
		b[10], b[11], b[12], b[13], b[14], b[15])
}

// generateJSONFromSchema generates a JSON value with a schema marker.
func generateJSONFromSchema(schemaRef string, rng *rand.Rand) string {
	obj := map[string]interface{}{
		"_schema": schemaRef,
		"id":      rng.Intn(10000),
	}
	data, err := json.Marshal(obj)
	if err != nil {
		return "'{}'::jsonb"
	}
	return fmt.Sprintf("'%s'::jsonb", strings.ReplaceAll(string(data), "'", "''"))
}

// analyzeChecks parses CHECK constraints and extracts hints for value generation.
func analyzeChecks(checks []model.CheckConstraint) []checkHint {
	var hints []checkHint
	for _, ck := range checks {
		expr, err := sqlexpr.Parse(ck.Expr)
		if err != nil {
			continue
		}
		if h, ok := extractRange(expr); ok {
			hints = append(hints, h)
			continue
		}
		if h, ok := extractLength(expr); ok {
			hints = append(hints, h)
			continue
		}
		if h, ok := extractRegex(expr); ok {
			hints = append(hints, h)
			continue
		}
	}
	return hints
}

func extractRange(node sqlexpr.Node) (checkHint, bool) {
	bin, ok := node.(*sqlexpr.BinaryOp)
	if !ok || strings.ToUpper(bin.Op) != "AND" {
		return checkHint{}, false
	}
	left, lok := bin.Left.(*sqlexpr.BinaryOp)
	right, rok := bin.Right.(*sqlexpr.BinaryOp)
	if !lok || !rok {
		return checkHint{}, false
	}

	var col string
	var lo, hi int
	var foundLo, foundHi bool

	for _, side := range []*sqlexpr.BinaryOp{left, right} {
		colName := extractColName(side.Left)
		valNode := side.Right
		if colName == "" {
			colName = extractColName(side.Right)
			valNode = side.Left
		}
		if colName == "" {
			continue
		}
		if col == "" {
			col = colName
		} else if col != colName {
			return checkHint{}, false
		}

		colOnLeft := extractColName(side.Left) != ""

		switch side.Op {
		case ">=":
			if v, ok := extractIntLit(valNode); ok {
				if colOnLeft {
					lo = v
					foundLo = true
				} else {
					hi = v
					foundHi = true
				}
			}
		case "<=":
			if v, ok := extractIntLit(valNode); ok {
				if colOnLeft {
					hi = v
					foundHi = true
				} else {
					lo = v
					foundLo = true
				}
			}
		case ">":
			if v, ok := extractIntLit(valNode); ok {
				if colOnLeft {
					lo = v + 1
					foundLo = true
				} else {
					hi = v - 1
					foundHi = true
				}
			}
		case "<":
			if v, ok := extractIntLit(valNode); ok {
				if colOnLeft {
					hi = v - 1
					foundHi = true
				} else {
					lo = v + 1
					foundLo = true
				}
			}
		}
	}

	if col != "" && foundLo && foundHi && lo <= hi {
		return checkHint{col: col, kind: "range", min: lo, max: hi}, true
	}
	return checkHint{}, false
}

func extractLength(node sqlexpr.Node) (checkHint, bool) {
	bin, ok := node.(*sqlexpr.BinaryOp)
	if !ok {
		return checkHint{}, false
	}
	if bin.Op != "<=" && bin.Op != "<" {
		return checkHint{}, false
	}
	fc, ok := bin.Left.(*sqlexpr.FuncCall)
	if !ok {
		return checkHint{}, false
	}
	name := strings.ToLower(fc.Name)
	if name != "length" && name != "char_length" && name != "character_length" {
		return checkHint{}, false
	}
	if len(fc.Args) != 1 {
		return checkHint{}, false
	}
	colName := extractColName(fc.Args[0])
	if colName == "" {
		return checkHint{}, false
	}
	v, ok := extractIntLit(bin.Right)
	if !ok {
		return checkHint{}, false
	}
	maxLen := v
	if bin.Op == "<" {
		maxLen = v - 1
	}
	if maxLen <= 0 {
		return checkHint{}, false
	}
	return checkHint{col: colName, kind: "length", max: maxLen}, true
}

func extractRegex(node sqlexpr.Node) (checkHint, bool) {
	bin, ok := node.(*sqlexpr.BinaryOp)
	if !ok {
		return checkHint{}, false
	}
	if bin.Op != "~" && bin.Op != "~*" {
		return checkHint{}, false
	}
	colName := extractColName(bin.Left)
	if colName == "" {
		return checkHint{}, false
	}
	lit, ok := bin.Right.(*sqlexpr.StringLiteral)
	if !ok {
		return checkHint{}, false
	}
	return checkHint{col: colName, kind: "regex", pattern: lit.Value}, true
}

func extractColName(node sqlexpr.Node) string {
	cr, ok := node.(*sqlexpr.ColumnRef)
	if !ok {
		return ""
	}
	if len(cr.Parts) > 0 {
		return cr.Parts[len(cr.Parts)-1]
	}
	return ""
}

func extractIntLit(node sqlexpr.Node) (int, bool) {
	il, ok := node.(*sqlexpr.IntLiteral)
	if ok {
		return il.Value, true
	}
	return 0, false
}
