package seed

import (
	"math/rand"
	"regexp"
	"strconv"
	"strings"
	"testing"

	"github.com/smm-h/pgdesign/internal/model"
)

func testSchema() *model.Schema {
	return &model.Schema{
		Name: "public",
		Enums: []model.Enum{
			{Schema: "public", Name: "status", Values: []string{"active", "inactive", "pending"}},
		},
		Tables: []model.Table{
			{
				Name: "organizations", Schema: "public",
				Comment: "Organizations",
				PK:      []string{"id"},
				Columns: []model.Column{
					{Name: "id", PGType: "uuid", NotNull: true, SemanticTypeName: "id"},
					{Name: "name", PGType: "text", NotNull: true, SemanticTypeName: "short_text"},
					{Name: "created_at", PGType: "timestamptz", NotNull: true, SemanticTypeName: "timestamp"},
				},
			},
			{
				Name: "users", Schema: "public",
				Comment: "Users",
				PK:      []string{"id"},
				Columns: []model.Column{
					{Name: "id", PGType: "uuid", NotNull: true, SemanticTypeName: "id"},
					{Name: "org_id", PGType: "uuid", NotNull: true, SemanticTypeName: "ref"},
					{Name: "email", PGType: "text", NotNull: true, SemanticTypeName: "email"},
					{Name: "status", PGType: "public.status", NotNull: true},
					{Name: "is_active", PGType: "boolean", NotNull: true, SemanticTypeName: "flag"},
					{Name: "login_count", PGType: "bigint", NotNull: true, SemanticTypeName: "counter"},
					{Name: "slug", PGType: "text", NotNull: true, SemanticTypeName: "slug"},
					{Name: "bio", PGType: "text", NotNull: false},
					{Name: "score", PGType: "bigint", NotNull: true, Generated: "login_count * 10", Stored: true},
				},
				FKs: []model.FK{
					{Name: "fk_users_org", Columns: []string{"org_id"}, RefSchema: "public", RefTable: "organizations", RefColumns: []string{"id"}, OnDelete: "CASCADE"},
				},
			},
		},
	}
}

func TestGenerate_OrderAndStructure(t *testing.T) {
	schema := testSchema()
	rng := rand.New(rand.NewSource(42))
	out, _ := Generate(schema, 3, rng, nil)

	// Must start with the header comment.
	if !strings.HasPrefix(out, "-- Seed data generated by pgdesign") {
		t.Error("output does not start with expected header comment")
	}

	// Organizations must appear before users (topological order).
	orgIdx := strings.Index(out, "INSERT INTO public.organizations")
	usrIdx := strings.Index(out, "INSERT INTO public.users")
	if orgIdx < 0 {
		t.Fatal("missing INSERT INTO public.organizations")
	}
	if usrIdx < 0 {
		t.Fatal("missing INSERT INTO public.users")
	}
	if orgIdx >= usrIdx {
		t.Error("organizations INSERT must appear before users INSERT")
	}

	// Each table should have 3 value tuples.
	// Count occurrences of "(" at the start of value lines for organizations.
	orgBlock := out[orgIdx:usrIdx]
	orgRows := strings.Count(orgBlock, "  (")
	if orgRows != 3 {
		t.Errorf("expected 3 row tuples for organizations, got %d", orgRows)
	}

	usrBlock := out[usrIdx:]
	usrRows := strings.Count(usrBlock, "  (")
	if usrRows != 3 {
		t.Errorf("expected 3 row tuples for users, got %d", usrRows)
	}
}

func TestGenerate_SkipsGeneratedColumns(t *testing.T) {
	schema := testSchema()
	rng := rand.New(rand.NewSource(42))
	out, _ := Generate(schema, 3, rng, nil)

	// Find the users INSERT and extract the column list.
	usrIdx := strings.Index(out, "INSERT INTO public.users")
	if usrIdx < 0 {
		t.Fatal("missing INSERT INTO public.users")
	}
	// Extract from "(" to ")" in the column list.
	headerEnd := strings.Index(out[usrIdx:], ") VALUES")
	if headerEnd < 0 {
		t.Fatal("cannot find ') VALUES' in users INSERT")
	}
	colHeader := out[usrIdx : usrIdx+headerEnd]

	if strings.Contains(colHeader, "score") {
		t.Error("generated column 'score' should not appear in INSERT column list")
	}
}

func TestGenerate_EnumValues(t *testing.T) {
	schema := testSchema()
	rng := rand.New(rand.NewSource(42))
	out, _ := Generate(schema, 10, rng, nil)

	validEnums := map[string]bool{
		"'active'":   true,
		"'inactive'": true,
		"'pending'":  true,
	}

	// Find the users INSERT block.
	usrIdx := strings.Index(out, "INSERT INTO public.users")
	if usrIdx < 0 {
		t.Fatal("missing INSERT INTO public.users")
	}
	usrBlock := out[usrIdx:]

	// The status column is the 4th column (0-indexed: id, org_id, email, status).
	// Parse each row tuple and check the 4th value.
	lines := strings.Split(usrBlock, "\n")
	for _, line := range lines {
		line = strings.TrimSpace(line)
		if !strings.HasPrefix(line, "(") {
			continue
		}
		// Remove leading "(" and trailing ")," or ");"
		line = strings.TrimPrefix(line, "(")
		line = strings.TrimSuffix(line, "),")
		line = strings.TrimSuffix(line, ");")
		parts := strings.Split(line, ", ")
		if len(parts) < 4 {
			continue
		}
		statusVal := parts[3]
		if !validEnums[statusVal] {
			t.Errorf("unexpected enum value for status: %s", statusVal)
		}
	}
}

func TestGenerate_FKReferences(t *testing.T) {
	schema := testSchema()
	rng := rand.New(rand.NewSource(42))
	out, _ := Generate(schema, 5, rng, nil)

	// Collect organization IDs from the organizations INSERT.
	orgIdx := strings.Index(out, "INSERT INTO public.organizations")
	usrIdx := strings.Index(out, "INSERT INTO public.users")
	if orgIdx < 0 || usrIdx < 0 {
		t.Fatal("missing expected INSERT statements")
	}

	orgBlock := out[orgIdx:usrIdx]
	orgIDs := make(map[string]bool)
	for _, line := range strings.Split(orgBlock, "\n") {
		line = strings.TrimSpace(line)
		if !strings.HasPrefix(line, "(") {
			continue
		}
		line = strings.TrimPrefix(line, "(")
		line = strings.TrimSuffix(line, "),")
		line = strings.TrimSuffix(line, ");")
		parts := strings.Split(line, ", ")
		if len(parts) >= 1 {
			orgIDs[parts[0]] = true
		}
	}

	if len(orgIDs) == 0 {
		t.Fatal("no organization IDs found")
	}

	// Check that all user org_id values reference a known organization ID.
	usrBlock := out[usrIdx:]
	for _, line := range strings.Split(usrBlock, "\n") {
		line = strings.TrimSpace(line)
		if !strings.HasPrefix(line, "(") {
			continue
		}
		line = strings.TrimPrefix(line, "(")
		line = strings.TrimSuffix(line, "),")
		line = strings.TrimSuffix(line, ");")
		parts := strings.Split(line, ", ")
		if len(parts) < 2 {
			continue
		}
		orgID := parts[1] // org_id is the 2nd column
		if !orgIDs[orgID] {
			t.Errorf("user org_id %s does not match any organization ID", orgID)
		}
	}
}

func TestGenerate_Deterministic(t *testing.T) {
	schema := testSchema()

	rng1 := rand.New(rand.NewSource(42))
	out1, _ := Generate(schema, 5, rng1, nil)

	rng2 := rand.New(rand.NewSource(42))
	out2, _ := Generate(schema, 5, rng2, nil)

	if out1 != out2 {
		t.Error("Generate with the same seed should produce identical output")
	}
}

func TestGenerate_AllPGTypes(t *testing.T) {
	// Every PG type the seed generator handles, each as a separate column.
	// All are NOT NULL so NULL injection does not interfere.
	pgTypes := []string{
		"boolean",
		"integer", "bigint", "smallint",
		"serial", "bigserial", "smallserial",
		"numeric",
		"real", "float4", "float8",
		"uuid",
		"text", "varchar", "char",
		"bytea",
		"date", "time", "timetz",
		"timestamp", "timestamptz",
		"interval",
		"json", "jsonb",
		"xml",
		"inet", "cidr", "macaddr",
		"tsvector", "tsquery",
		"oid",
		"citext",
		"int4range", "int8range", "numrange", "daterange", "tsrange", "tstzrange",
		"int4multirange", "int8multirange", "nummultirange", "datemultirange", "tsmultirange", "tstzmultirange",
	}

	var cols []model.Column
	for _, pgType := range pgTypes {
		cols = append(cols, model.Column{
			Name:    "col_" + strings.ReplaceAll(pgType, " ", "_"),
			PGType:  pgType,
			NotNull: true,
		})
	}

	schema := &model.Schema{
		Name: "public",
		Tables: []model.Table{
			{
				Name:    "test_types",
				Schema:  "public",
				Comment: "Test types",
				PK:      []string{"col_boolean"},
				Columns: cols,
			},
		},
	}

	rng := rand.New(rand.NewSource(99))
	out, _ := Generate(schema, 1, rng, nil)

	// Find the INSERT and extract the single row tuple.
	insertIdx := strings.Index(out, "INSERT INTO public.test_types")
	if insertIdx < 0 {
		t.Fatal("missing INSERT INTO public.test_types")
	}

	// Extract the row between the first "  (" and ");"
	block := out[insertIdx:]
	rowStart := strings.Index(block, "  (")
	if rowStart < 0 {
		t.Fatal("no row tuple found")
	}
	rowEnd := strings.Index(block[rowStart:], ");")
	if rowEnd < 0 {
		t.Fatal("no row terminator found")
	}
	rowStr := block[rowStart : rowStart+rowEnd+2]
	rowStr = strings.TrimPrefix(strings.TrimSpace(rowStr), "(")
	rowStr = strings.TrimSuffix(rowStr, ");")

	// Split values by ", " -- this is fragile for values containing ", " but
	// works for the known generator output because quoted strings use underscores
	// and ranges use commas without spaces after them.
	values := splitRow(rowStr)
	if len(values) != len(pgTypes) {
		t.Fatalf("expected %d values, got %d\nrow: %s", len(pgTypes), len(values), rowStr)
	}

	// Build a map for easy lookup.
	valMap := make(map[string]string)
	for i, pgType := range pgTypes {
		valMap[pgType] = values[i]
	}

	// Global check: no value should be the fallback "'sample'" used for unknown types.
	for _, pgType := range pgTypes {
		v := valMap[pgType]
		if v == "'sample'" {
			t.Errorf("%s: got fallback 'sample' value", pgType)
		}
		if v == "" {
			t.Errorf("%s: got empty value", pgType)
		}
	}

	// Per-type format checks.
	checks := []struct {
		pgType string
		check  func(string) bool
		desc   string
	}{
		{"boolean", func(v string) bool { return v == "true" || v == "false" }, "must be 'true' or 'false'"},
		{"integer", func(v string) bool { return regexp.MustCompile(`^\d+$`).MatchString(v) }, "must be all digits"},
		{"bigint", func(v string) bool { return regexp.MustCompile(`^\d+$`).MatchString(v) }, "must be all digits"},
		{"smallint", func(v string) bool { return regexp.MustCompile(`^\d+$`).MatchString(v) }, "must be all digits"},
		{"serial", func(v string) bool { return v == "DEFAULT" }, "must be DEFAULT"},
		{"bigserial", func(v string) bool { return v == "DEFAULT" }, "must be DEFAULT"},
		{"smallserial", func(v string) bool { return v == "DEFAULT" }, "must be DEFAULT"},
		{"numeric", func(v string) bool { return strings.Contains(v, ".") }, "must contain a decimal point"},
		{"real", func(v string) bool { return strings.Contains(v, ".") }, "must contain a decimal point"},
		{"float4", func(v string) bool { return strings.Contains(v, ".") }, "must contain a decimal point"},
		{"float8", func(v string) bool { return strings.Contains(v, ".") }, "must contain a decimal point"},
		{"uuid", func(v string) bool {
			return regexp.MustCompile(`^'[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}'$`).MatchString(v)
		}, "must be a quoted UUID v4"},
		{"date", func(v string) bool {
			return regexp.MustCompile(`^'\d{4}-\d{2}-\d{2}'$`).MatchString(v)
		}, "must match 'YYYY-MM-DD'"},
		{"time", func(v string) bool {
			return regexp.MustCompile(`^'\d{2}:\d{2}:\d{2}'$`).MatchString(v)
		}, "must match 'HH:MM:SS'"},
		{"timetz", func(v string) bool {
			return regexp.MustCompile(`^'\d{2}:\d{2}:\d{2}\+00'$`).MatchString(v)
		}, "must match 'HH:MM:SS+00'"},
		{"timestamp", func(v string) bool {
			return strings.Contains(v, "-") && strings.Contains(v, ":")
		}, "must contain date and time parts"},
		{"timestamptz", func(v string) bool {
			return strings.Contains(v, "-") && strings.Contains(v, ":")
		}, "must contain date and time parts"},
		{"interval", func(v string) bool {
			return strings.Contains(v, "days") || strings.Contains(v, "hours") || strings.Contains(v, "minutes")
		}, "must contain 'days', 'hours', or 'minutes'"},
		{"varchar", func(v string) bool { return strings.HasPrefix(v, "'") }, "must start with quote"},
		{"char", func(v string) bool { return strings.HasPrefix(v, "'") }, "must start with quote"},
		{"bytea", func(v string) bool { return strings.HasPrefix(v, "'\\x") }, "must start with '\\x"},
		{"inet", func(v string) bool {
			return regexp.MustCompile(`^'\d+\.\d+\.\d+\.\d+'$`).MatchString(v)
		}, "must be dotted quad like 'N.N.N.N'"},
		{"cidr", func(v string) bool { return strings.HasSuffix(v, "/24'") }, "must end with /24'"},
		{"macaddr", func(v string) bool {
			return regexp.MustCompile(`^'[0-9a-f]{2}:[0-9a-f]{2}:[0-9a-f]{2}:[0-9a-f]{2}:[0-9a-f]{2}:[0-9a-f]{2}'$`).MatchString(v)
		}, "must be colon-separated hex"},
		{"xml", func(v string) bool { return strings.Contains(v, "<val>") }, "must contain '<val>'"},
		{"tsvector", func(v string) bool { return strings.Contains(v, "::tsvector") }, "must contain '::tsvector'"},
		{"tsquery", func(v string) bool { return strings.Contains(v, "::tsquery") }, "must contain '::tsquery'"},
		{"oid", func(v string) bool { return regexp.MustCompile(`^\d+$`).MatchString(v) }, "must be all digits"},
		{"json", func(v string) bool { return strings.Contains(v, "::json") }, "must contain '::json'"},
		{"jsonb", func(v string) bool { return strings.Contains(v, "::jsonb") }, "must contain '::jsonb'"},
		{"citext", func(v string) bool { return strings.HasPrefix(v, "'") }, "must start with quote"},
		// Range types
		{"int4range", func(v string) bool { return strings.Contains(v, "[") && strings.Contains(v, ")") }, "must contain '[' and ')'"},
		{"int8range", func(v string) bool { return strings.Contains(v, "[") && strings.Contains(v, ")") }, "must contain '[' and ')'"},
		{"numrange", func(v string) bool { return strings.Contains(v, "[") && strings.Contains(v, ")") }, "must contain '[' and ')'"},
		{"daterange", func(v string) bool { return strings.Contains(v, "[") && strings.Contains(v, ")") }, "must contain '[' and ')'"},
		{"tsrange", func(v string) bool { return strings.Contains(v, "[") && strings.Contains(v, ")") }, "must contain '[' and ')'"},
		{"tstzrange", func(v string) bool { return strings.Contains(v, "[") && strings.Contains(v, ")") }, "must contain '[' and ')'"},
		// Multirange types
		{"int4multirange", func(v string) bool { return strings.Contains(v, "{[") && strings.Contains(v, ")}") }, "must contain '{[' and ')}'"},
		{"int8multirange", func(v string) bool { return strings.Contains(v, "{[") && strings.Contains(v, ")}") }, "must contain '{[' and ')}'"},
		{"nummultirange", func(v string) bool { return strings.Contains(v, "{[") && strings.Contains(v, ")}") }, "must contain '{[' and ')}'"},
		{"datemultirange", func(v string) bool { return strings.Contains(v, "{[") && strings.Contains(v, ")}") }, "must contain '{[' and ')}'"},
		{"tsmultirange", func(v string) bool { return strings.Contains(v, "{[") && strings.Contains(v, ")}") }, "must contain '{[' and ')}'"},
		{"tstzmultirange", func(v string) bool { return strings.Contains(v, "{[") && strings.Contains(v, ")}") }, "must contain '{[' and ')}'"},
	}

	for _, c := range checks {
		v := valMap[c.pgType]
		if !c.check(v) {
			t.Errorf("%s: value %q failed check: %s", c.pgType, v, c.desc)
		}
	}
}

// splitRow splits a SQL row tuple by ", " while respecting quoted strings and
// nested structures (ranges contain commas without trailing spaces).
func splitRow(row string) []string {
	var parts []string
	var current strings.Builder
	inQuote := false
	depth := 0 // tracks nesting inside '...' for range literals

	for i := 0; i < len(row); i++ {
		ch := row[i]

		if ch == '\'' && !inQuote {
			inQuote = true
			current.WriteByte(ch)
			continue
		}
		if ch == '\'' && inQuote {
			// Check for escaped quotes ('')
			if i+1 < len(row) && row[i+1] == '\'' {
				current.WriteByte(ch)
				current.WriteByte(ch)
				i++
				continue
			}
			inQuote = false
			current.WriteByte(ch)
			continue
		}
		if inQuote {
			current.WriteByte(ch)
			continue
		}

		// Outside quotes: track parenthesis depth for cast expressions.
		if ch == '(' {
			depth++
			current.WriteByte(ch)
			continue
		}
		if ch == ')' {
			depth--
			current.WriteByte(ch)
			continue
		}

		// Split on ", " only at top level.
		if depth == 0 && ch == ',' && i+1 < len(row) && row[i+1] == ' ' {
			parts = append(parts, current.String())
			current.Reset()
			i++ // skip the space
			continue
		}

		current.WriteByte(ch)
	}
	if current.Len() > 0 {
		parts = append(parts, current.String())
	}
	return parts
}

func TestGenerate_NullInjection(t *testing.T) {
	schema := &model.Schema{
		Name: "public",
		Tables: []model.Table{
			{
				Name:    "test_nulls",
				Schema:  "public",
				Comment: "Test nulls",
				PK:      []string{"id"},
				Columns: []model.Column{
					{Name: "id", PGType: "integer", NotNull: true},
					{Name: "col_text", PGType: "text", NotNull: false},
				},
			},
		},
	}

	rng := rand.New(rand.NewSource(77))
	out, _ := Generate(schema, 1000, rng, nil)

	// Count NULL values in the col_text column (2nd column).
	insertIdx := strings.Index(out, "INSERT INTO public.test_nulls")
	if insertIdx < 0 {
		t.Fatal("missing INSERT INTO public.test_nulls")
	}

	block := out[insertIdx:]
	nullCount := 0
	totalCount := 0
	for _, line := range strings.Split(block, "\n") {
		line = strings.TrimSpace(line)
		if !strings.HasPrefix(line, "(") {
			continue
		}
		totalCount++
		// Extract the col_text value (2nd column): strip parens and split.
		row := strings.TrimPrefix(line, "(")
		row = strings.TrimSuffix(row, "),")
		row = strings.TrimSuffix(row, ");")
		parts := strings.SplitN(row, ", ", 2)
		if len(parts) >= 2 && parts[1] == "NULL" {
			nullCount++
		}
	}

	if totalCount != 1000 {
		t.Fatalf("expected 1000 rows, got %d", totalCount)
	}

	pct := float64(nullCount) / float64(totalCount) * 100
	t.Logf("NULL injection: %d/%d = %.1f%%", nullCount, totalCount, pct)

	if pct < 5.0 || pct > 20.0 {
		t.Errorf("NULL percentage %.1f%% is outside expected range [5%%, 20%%]", pct)
	}
}

func TestGenerate_NullNeverForNotNull(t *testing.T) {
	schema := &model.Schema{
		Name: "public",
		Tables: []model.Table{
			{
				Name:    "test_notnull",
				Schema:  "public",
				Comment: "Test not null",
				PK:      []string{"col_text"},
				Columns: []model.Column{
					{Name: "col_text", PGType: "text", NotNull: true},
				},
			},
		},
	}

	rng := rand.New(rand.NewSource(77))
	out, _ := Generate(schema, 100, rng, nil)

	insertIdx := strings.Index(out, "INSERT INTO public.test_notnull")
	if insertIdx < 0 {
		t.Fatal("missing INSERT INTO public.test_notnull")
	}

	block := out[insertIdx:]
	for _, line := range strings.Split(block, "\n") {
		line = strings.TrimSpace(line)
		if !strings.HasPrefix(line, "(") {
			continue
		}
		val := strings.TrimPrefix(line, "(")
		val = strings.TrimSuffix(val, "),")
		val = strings.TrimSuffix(val, ");")
		if val == "NULL" {
			t.Fatal("got NULL for a NOT NULL column")
		}
	}
}

func TestGenerate_CheckRange(t *testing.T) {
	schema := &model.Schema{
		Name: "public",
		Tables: []model.Table{
			{
				Name: "test_checks", Schema: "public",
				Comment: "Test CHECK constraints",
				PK:      []string{"id"},
				Columns: []model.Column{
					{Name: "id", PGType: "integer", NotNull: true},
					{Name: "age", PGType: "integer", NotNull: true},
				},
				Checks: []model.CheckConstraint{
					{Name: "chk_age", Expr: "age >= 18 AND age <= 65"},
				},
			},
		},
	}

	rng := rand.New(rand.NewSource(42))
	out, diags := Generate(schema, 100, rng, nil)
	if diags.HasErrors() {
		t.Fatalf("unexpected errors: %v", diags)
	}

	insertIdx := strings.Index(out, "INSERT INTO public.test_checks")
	if insertIdx < 0 {
		t.Fatal("missing INSERT INTO public.test_checks")
	}

	block := out[insertIdx:]
	for _, line := range strings.Split(block, "\n") {
		line = strings.TrimSpace(line)
		if !strings.HasPrefix(line, "(") {
			continue
		}
		row := strings.TrimPrefix(line, "(")
		row = strings.TrimSuffix(row, "),")
		row = strings.TrimSuffix(row, ");")
		parts := strings.SplitN(row, ", ", 2)
		if len(parts) < 2 {
			continue
		}
		ageStr := parts[1]
		age, err := strconv.Atoi(ageStr)
		if err != nil {
			t.Errorf("could not parse age %q: %v", ageStr, err)
			continue
		}
		if age < 18 || age > 65 {
			t.Errorf("age %d outside CHECK range [18, 65]", age)
		}
	}
}

func TestGenerate_CheckLength(t *testing.T) {
	schema := &model.Schema{
		Name: "public",
		Tables: []model.Table{
			{
				Name: "test_length", Schema: "public",
				Comment: "Test length CHECK",
				PK:      []string{"id"},
				Columns: []model.Column{
					{Name: "id", PGType: "integer", NotNull: true},
					{Name: "code", PGType: "text", NotNull: true},
				},
				Checks: []model.CheckConstraint{
					{Name: "chk_code_len", Expr: "length(code) <= 5"},
				},
			},
		},
	}

	rng := rand.New(rand.NewSource(42))
	out, _ := Generate(schema, 50, rng, nil)

	insertIdx := strings.Index(out, "INSERT INTO public.test_length")
	if insertIdx < 0 {
		t.Fatal("missing INSERT INTO public.test_length")
	}

	block := out[insertIdx:]
	for _, line := range strings.Split(block, "\n") {
		line = strings.TrimSpace(line)
		if !strings.HasPrefix(line, "(") {
			continue
		}
		row := strings.TrimPrefix(line, "(")
		row = strings.TrimSuffix(row, "),")
		row = strings.TrimSuffix(row, ");")
		parts := strings.SplitN(row, ", ", 2)
		if len(parts) < 2 {
			continue
		}
		val := parts[1]
		// Strip surrounding quotes.
		if strings.HasPrefix(val, "'") && strings.HasSuffix(val, "'") {
			val = val[1 : len(val)-1]
		}
		if len(val) > 5 {
			t.Errorf("code value %q exceeds length 5 (len=%d)", val, len(val))
		}
	}
}

func TestGenerate_CheckRegex(t *testing.T) {
	schema := &model.Schema{
		Name: "public",
		Tables: []model.Table{
			{
				Name: "test_regex", Schema: "public",
				Comment: "Test regex CHECK",
				PK:      []string{"id"},
				Columns: []model.Column{
					{Name: "id", PGType: "integer", NotNull: true},
					{Name: "code", PGType: "text", NotNull: true},
				},
				Checks: []model.CheckConstraint{
					{Name: "chk_code_fmt", Expr: "code ~ '^[A-Z]{3}-[0-9]{4}$'"},
				},
			},
		},
	}

	rng := rand.New(rand.NewSource(42))
	out, _ := Generate(schema, 50, rng, nil)

	re := regexp.MustCompile(`^[A-Z]{3}-[0-9]{4}$`)

	insertIdx := strings.Index(out, "INSERT INTO public.test_regex")
	if insertIdx < 0 {
		t.Fatal("missing INSERT INTO public.test_regex")
	}

	block := out[insertIdx:]
	matched := 0
	for _, line := range strings.Split(block, "\n") {
		line = strings.TrimSpace(line)
		if !strings.HasPrefix(line, "(") {
			continue
		}
		row := strings.TrimPrefix(line, "(")
		row = strings.TrimSuffix(row, "),")
		row = strings.TrimSuffix(row, ");")
		parts := strings.SplitN(row, ", ", 2)
		if len(parts) < 2 {
			continue
		}
		val := parts[1]
		if strings.HasPrefix(val, "'") && strings.HasSuffix(val, "'") {
			val = val[1 : len(val)-1]
		}
		if !re.MatchString(val) {
			t.Errorf("code value %q does not match regex ^[A-Z]{3}-[0-9]{4}$", val)
		}
		matched++
	}
	if matched == 0 {
		t.Error("no rows checked")
	}
}

func TestGenerate_UniqueConstraint(t *testing.T) {
	schema := &model.Schema{
		Name: "public",
		Tables: []model.Table{
			{
				Name: "test_unique", Schema: "public",
				Comment: "Test unique",
				PK:      []string{"id"},
				Columns: []model.Column{
					{Name: "id", PGType: "uuid", NotNull: true, SemanticTypeName: "id"},
					{Name: "email", PGType: "text", NotNull: true, SemanticTypeName: "email"},
				},
				Uniques: []model.UniqueConstraint{
					{Name: "uq_email", Columns: []string{"email"}},
				},
			},
		},
	}

	rng := rand.New(rand.NewSource(42))
	out, _ := Generate(schema, 20, rng, nil)

	insertIdx := strings.Index(out, "INSERT INTO public.test_unique")
	if insertIdx < 0 {
		t.Fatal("missing INSERT INTO public.test_unique")
	}

	block := out[insertIdx:]
	emails := make(map[string]bool)
	for _, line := range strings.Split(block, "\n") {
		line = strings.TrimSpace(line)
		if !strings.HasPrefix(line, "(") {
			continue
		}
		row := strings.TrimPrefix(line, "(")
		row = strings.TrimSuffix(row, "),")
		row = strings.TrimSuffix(row, ");")
		parts := strings.SplitN(row, ", ", 2)
		if len(parts) < 2 {
			continue
		}
		email := parts[1]
		if emails[email] {
			t.Errorf("duplicate email: %s", email)
		}
		emails[email] = true
	}
}

func TestGenerate_ZipfFKDistribution(t *testing.T) {
	schema := &model.Schema{
		Name: "public",
		Tables: []model.Table{
			{
				Name: "categories", Schema: "public",
				Comment: "Categories",
				PK:      []string{"id"},
				Columns: []model.Column{
					{Name: "id", PGType: "uuid", NotNull: true, SemanticTypeName: "id"},
					{Name: "name", PGType: "text", NotNull: true},
				},
			},
			{
				Name: "items", Schema: "public",
				Comment: "Items",
				PK:      []string{"id"},
				Columns: []model.Column{
					{Name: "id", PGType: "uuid", NotNull: true, SemanticTypeName: "id"},
					{Name: "cat_id", PGType: "uuid", NotNull: true, SemanticTypeName: "ref"},
				},
				FKs: []model.FK{
					{Name: "fk_items_cat", Columns: []string{"cat_id"}, RefSchema: "public", RefTable: "categories", RefColumns: []string{"id"}, OnDelete: "CASCADE"},
				},
			},
		},
	}

	rng := rand.New(rand.NewSource(42))
	out, _ := Generate(schema, 100, rng, nil)

	catIdx := strings.Index(out, "INSERT INTO public.categories")
	itemIdx := strings.Index(out, "INSERT INTO public.items")
	if catIdx < 0 || itemIdx < 0 {
		t.Fatal("missing expected INSERT statements")
	}

	// Collect category IDs.
	catBlock := out[catIdx:itemIdx]
	var catIDs []string
	for _, line := range strings.Split(catBlock, "\n") {
		line = strings.TrimSpace(line)
		if !strings.HasPrefix(line, "(") {
			continue
		}
		row := strings.TrimPrefix(line, "(")
		row = strings.TrimSuffix(row, "),")
		row = strings.TrimSuffix(row, ");")
		parts := strings.SplitN(row, ", ", 2)
		if len(parts) >= 1 {
			catIDs = append(catIDs, parts[0])
		}
	}

	// Count references per category from items.
	refCounts := make(map[string]int)
	itemBlock := out[itemIdx:]
	for _, line := range strings.Split(itemBlock, "\n") {
		line = strings.TrimSpace(line)
		if !strings.HasPrefix(line, "(") {
			continue
		}
		row := strings.TrimPrefix(line, "(")
		row = strings.TrimSuffix(row, "),")
		row = strings.TrimSuffix(row, ");")
		parts := strings.SplitN(row, ", ", 2)
		if len(parts) >= 2 {
			refCounts[parts[1]]++
		}
	}

	// With Zipf, the first category should have more references than the last.
	// At minimum, the distribution should not be perfectly uniform.
	if len(catIDs) < 2 {
		t.Skip("too few categories for distribution check")
	}
	firstCount := refCounts[catIDs[0]]
	lastCount := refCounts[catIDs[len(catIDs)-1]]
	t.Logf("Zipf FK distribution: first=%d, last=%d (out of 100 items, %d categories)",
		firstCount, lastCount, len(catIDs))
	// The first should be referenced notably more (Zipf skew). With s=1.5 and
	// 100 categories, the first should be referenced ~50% of the time.
	if firstCount <= lastCount && firstCount < 5 {
		t.Error("Zipf distribution not detected: first category not referenced more than last")
	}
}

func TestGenerate_LogNormalMoney(t *testing.T) {
	schema := &model.Schema{
		Name: "public",
		Tables: []model.Table{
			{
				Name: "test_money", Schema: "public",
				Comment: "Test money",
				PK:      []string{"id"},
				Columns: []model.Column{
					{Name: "id", PGType: "uuid", NotNull: true, SemanticTypeName: "id"},
					{Name: "amount", PGType: "bigint", NotNull: true, SemanticTypeName: "money"},
				},
			},
		},
	}

	rng := rand.New(rand.NewSource(42))
	out, _ := Generate(schema, 200, rng, nil)

	insertIdx := strings.Index(out, "INSERT INTO public.test_money")
	if insertIdx < 0 {
		t.Fatal("missing INSERT INTO public.test_money")
	}

	block := out[insertIdx:]
	var amounts []int
	for _, line := range strings.Split(block, "\n") {
		line = strings.TrimSpace(line)
		if !strings.HasPrefix(line, "(") {
			continue
		}
		row := strings.TrimPrefix(line, "(")
		row = strings.TrimSuffix(row, "),")
		row = strings.TrimSuffix(row, ");")
		parts := strings.SplitN(row, ", ", 2)
		if len(parts) < 2 {
			continue
		}
		v, err := strconv.Atoi(parts[1])
		if err != nil {
			t.Errorf("could not parse money %q: %v", parts[1], err)
			continue
		}
		amounts = append(amounts, v)
	}

	if len(amounts) < 100 {
		t.Fatalf("expected at least 100 amounts, got %d", len(amounts))
	}

	// Log-normal produces varied values; check that not all values are identical
	// and that the max is capped at 999999.
	seen := make(map[int]bool)
	for _, a := range amounts {
		seen[a] = true
		if a > 999999 {
			t.Errorf("money amount %d exceeds cap of 999999", a)
		}
		if a < 0 {
			t.Errorf("money amount %d is negative", a)
		}
	}
	if len(seen) < 10 {
		t.Errorf("expected variety in money amounts, got only %d distinct values", len(seen))
	}
}

func TestGenerate_ArrayPopulation(t *testing.T) {
	schema := &model.Schema{
		Name: "public",
		Tables: []model.Table{
			{
				Name: "test_arrays", Schema: "public",
				Comment: "Test arrays",
				PK:      []string{"id"},
				Columns: []model.Column{
					{Name: "id", PGType: "integer", NotNull: true},
					{Name: "tags", PGType: "text", NotNull: true, Array: true},
				},
			},
		},
	}

	rng := rand.New(rand.NewSource(42))
	out, _ := Generate(schema, 10, rng, nil)

	insertIdx := strings.Index(out, "INSERT INTO public.test_arrays")
	if insertIdx < 0 {
		t.Fatal("missing INSERT INTO public.test_arrays")
	}

	// Check that arrays use ARRAY[...] syntax, not '{}'.
	if strings.Contains(out[insertIdx:], "'{}'") {
		t.Error("arrays should not use empty '{}' syntax; expected ARRAY[...]")
	}

	block := out[insertIdx:]
	foundArray := false
	for _, line := range strings.Split(block, "\n") {
		line = strings.TrimSpace(line)
		if !strings.HasPrefix(line, "(") {
			continue
		}
		if strings.Contains(line, "ARRAY[") {
			foundArray = true
			break
		}
	}
	if !foundArray {
		t.Error("expected ARRAY[...] syntax in output")
	}
}

func TestGenerate_PerTableRowCount(t *testing.T) {
	schema := testSchema()
	rng := rand.New(rand.NewSource(42))
	cfg := &SeedConfig{
		TableRows: map[string]int{
			"organizations": 2,
			"users":         7,
		},
	}
	out, _ := Generate(schema, 10, rng, cfg)

	// Organizations should have 2 rows (overridden from default 10).
	orgIdx := strings.Index(out, "INSERT INTO public.organizations")
	usrIdx := strings.Index(out, "INSERT INTO public.users")
	if orgIdx < 0 || usrIdx < 0 {
		t.Fatal("missing expected INSERT statements")
	}

	orgBlock := out[orgIdx:usrIdx]
	orgRows := strings.Count(orgBlock, "  (")
	if orgRows != 2 {
		t.Errorf("expected 2 organization rows, got %d", orgRows)
	}

	usrBlock := out[usrIdx:]
	usrRows := strings.Count(usrBlock, "  (")
	if usrRows != 7 {
		t.Errorf("expected 7 user rows, got %d", usrRows)
	}
}

func TestGenerate_FKCycleHandling(t *testing.T) {
	// Two tables that reference each other (cycle).
	schema := &model.Schema{
		Name: "public",
		CycleGroups: [][]string{{"departments", "employees"}},
		Tables: []model.Table{
			{
				Name: "departments", Schema: "public",
				Comment: "Departments",
				PK:      []string{"id"},
				Columns: []model.Column{
					{Name: "id", PGType: "uuid", NotNull: true, SemanticTypeName: "id"},
					{Name: "name", PGType: "text", NotNull: true},
					{Name: "head_id", PGType: "uuid", NotNull: false, SemanticTypeName: "ref"},
				},
				FKs: []model.FK{
					{Name: "fk_dept_head", Columns: []string{"head_id"}, RefSchema: "public", RefTable: "employees", RefColumns: []string{"id"}, OnDelete: "SET NULL"},
				},
			},
			{
				Name: "employees", Schema: "public",
				Comment: "Employees",
				PK:      []string{"id"},
				Columns: []model.Column{
					{Name: "id", PGType: "uuid", NotNull: true, SemanticTypeName: "id"},
					{Name: "name", PGType: "text", NotNull: true},
					{Name: "dept_id", PGType: "uuid", NotNull: false, SemanticTypeName: "ref"},
				},
				FKs: []model.FK{
					{Name: "fk_emp_dept", Columns: []string{"dept_id"}, RefSchema: "public", RefTable: "departments", RefColumns: []string{"id"}, OnDelete: "SET NULL"},
				},
			},
		},
	}

	rng := rand.New(rand.NewSource(42))
	out, diags := Generate(schema, 3, rng, nil)

	// Should not have errors.
	if diags.HasErrors() {
		t.Fatalf("unexpected errors: %v", diags)
	}

	// The output should contain INSERT statements.
	if !strings.Contains(out, "INSERT INTO public.departments") {
		t.Error("missing departments INSERT")
	}
	if !strings.Contains(out, "INSERT INTO public.employees") {
		t.Error("missing employees INSERT")
	}

	// The cycle FK columns should be NULL in the initial INSERT.
	// Look for the deferred UPDATE section.
	if !strings.Contains(out, "FK cycle resolution") {
		t.Error("missing FK cycle resolution UPDATE section")
	}
	if !strings.Contains(out, "UPDATE public.") {
		t.Error("missing UPDATE statements for cycle resolution")
	}
}

func TestGenerate_FKCycleNotNull(t *testing.T) {
	schema := &model.Schema{
		Name: "public",
		CycleGroups: [][]string{{"alpha", "beta"}},
		Tables: []model.Table{
			{
				Name: "alpha", Schema: "public",
				Comment: "Alpha",
				PK:      []string{"id"},
				Columns: []model.Column{
					{Name: "id", PGType: "uuid", NotNull: true, SemanticTypeName: "id"},
					{Name: "beta_id", PGType: "uuid", NotNull: true, SemanticTypeName: "ref"},
				},
				FKs: []model.FK{
					{Name: "fk_alpha_beta", Columns: []string{"beta_id"}, RefSchema: "public", RefTable: "beta", RefColumns: []string{"id"}, OnDelete: "CASCADE"},
				},
			},
			{
				Name: "beta", Schema: "public",
				Comment: "Beta",
				PK:      []string{"id"},
				Columns: []model.Column{
					{Name: "id", PGType: "uuid", NotNull: true, SemanticTypeName: "id"},
					{Name: "alpha_id", PGType: "uuid", NotNull: true, SemanticTypeName: "ref"},
				},
				FKs: []model.FK{
					{Name: "fk_beta_alpha", Columns: []string{"alpha_id"}, RefSchema: "public", RefTable: "alpha", RefColumns: []string{"id"}, OnDelete: "CASCADE"},
				},
			},
		},
	}

	rng := rand.New(rand.NewSource(42))
	_, diags := Generate(schema, 3, rng, nil)

	// Should emit S001 warnings for NOT NULL FK columns in cycles.
	hasS001 := false
	for _, d := range diags {
		if d.Code == "S001" {
			hasS001 = true
			break
		}
	}
	if !hasS001 {
		t.Error("expected S001 diagnostic for NOT NULL FK column in cycle")
	}
}

func TestGenerate_JSONBWithSchema(t *testing.T) {
	schema := &model.Schema{
		Name: "public",
		Tables: []model.Table{
			{
				Name: "test_jsonb", Schema: "public",
				Comment: "Test JSONB",
				PK:      []string{"id"},
				Columns: []model.Column{
					{Name: "id", PGType: "integer", NotNull: true},
					{Name: "data", PGType: "jsonb", NotNull: true, JSONSchema: "schemas/data.json"},
				},
			},
		},
	}

	rng := rand.New(rand.NewSource(42))
	out, _ := Generate(schema, 5, rng, nil)

	insertIdx := strings.Index(out, "INSERT INTO public.test_jsonb")
	if insertIdx < 0 {
		t.Fatal("missing INSERT INTO public.test_jsonb")
	}

	block := out[insertIdx:]
	// Each row should have a JSON object with _schema key, not empty '{}'.
	if strings.Contains(block, "'{}'::jsonb") {
		t.Error("expected JSON with _schema marker, got empty object")
	}
	if !strings.Contains(block, "_schema") {
		t.Error("expected _schema key in generated JSON")
	}
	if !strings.Contains(block, "schemas/data.json") {
		t.Error("expected json_schema path in generated JSON")
	}
}

func TestRegenFromPattern(t *testing.T) {
	rng := rand.New(rand.NewSource(42))

	tests := []struct {
		pattern string
		re      string // go regex to validate output
	}{
		{`^[A-Z]{3}$`, `^[A-Z]{3}$`},
		{`^[0-9]{4}-[0-9]{2}$`, `^[0-9]{4}-[0-9]{2}$`},
		{`^(foo|bar|baz)$`, `^(foo|bar|baz)$`},
		{`^[a-z]+$`, `^[a-z]+$`},
		{`^test_[0-9]?$`, `^test_[0-9]?$`},
	}

	for _, tc := range tests {
		for i := 0; i < 20; i++ {
			got, err := regenFromPattern(tc.pattern, rng)
			if err != nil {
				t.Errorf("regenFromPattern(%q): %v", tc.pattern, err)
				break
			}
			re := regexp.MustCompile(tc.re)
			if !re.MatchString(got) {
				t.Errorf("regenFromPattern(%q) = %q, does not match %s", tc.pattern, got, tc.re)
			}
		}
	}
}
