package seed

import (
	"math/rand"
	"regexp"
	"strings"
	"testing"

	"github.com/smm-h/pgdesign/internal/model"
)

func testSchema() *model.Schema {
	return &model.Schema{
		Name: "public",
		Enums: []model.Enum{
			{Schema: "public", Name: "status", Values: []string{"active", "inactive", "pending"}},
		},
		Tables: []model.Table{
			{
				Name: "organizations", Schema: "public",
				Comment: "Organizations",
				PK:      []string{"id"},
				Columns: []model.Column{
					{Name: "id", PGType: "uuid", NotNull: true, SemanticTypeName: "id"},
					{Name: "name", PGType: "text", NotNull: true, SemanticTypeName: "short_text"},
					{Name: "created_at", PGType: "timestamptz", NotNull: true, SemanticTypeName: "timestamp"},
				},
			},
			{
				Name: "users", Schema: "public",
				Comment: "Users",
				PK:      []string{"id"},
				Columns: []model.Column{
					{Name: "id", PGType: "uuid", NotNull: true, SemanticTypeName: "id"},
					{Name: "org_id", PGType: "uuid", NotNull: true, SemanticTypeName: "ref"},
					{Name: "email", PGType: "text", NotNull: true, SemanticTypeName: "email"},
					{Name: "status", PGType: "public.status", NotNull: true},
					{Name: "is_active", PGType: "boolean", NotNull: true, SemanticTypeName: "flag"},
					{Name: "login_count", PGType: "bigint", NotNull: true, SemanticTypeName: "counter"},
					{Name: "slug", PGType: "text", NotNull: true, SemanticTypeName: "slug"},
					{Name: "bio", PGType: "text", NotNull: false},
					{Name: "score", PGType: "bigint", NotNull: true, Generated: "login_count * 10", Stored: true},
				},
				FKs: []model.FK{
					{Name: "fk_users_org", Columns: []string{"org_id"}, RefSchema: "public", RefTable: "organizations", RefColumns: []string{"id"}, OnDelete: "CASCADE"},
				},
			},
		},
	}
}

func TestGenerate_OrderAndStructure(t *testing.T) {
	schema := testSchema()
	rng := rand.New(rand.NewSource(42))
	out, _ := Generate(schema, 3, rng, nil)

	// Must start with the header comment.
	if !strings.HasPrefix(out, "-- Seed data generated by pgdesign") {
		t.Error("output does not start with expected header comment")
	}

	// Organizations must appear before users (topological order).
	orgIdx := strings.Index(out, "INSERT INTO public.organizations")
	usrIdx := strings.Index(out, "INSERT INTO public.users")
	if orgIdx < 0 {
		t.Fatal("missing INSERT INTO public.organizations")
	}
	if usrIdx < 0 {
		t.Fatal("missing INSERT INTO public.users")
	}
	if orgIdx >= usrIdx {
		t.Error("organizations INSERT must appear before users INSERT")
	}

	// Each table should have 3 value tuples.
	// Count occurrences of "(" at the start of value lines for organizations.
	orgBlock := out[orgIdx:usrIdx]
	orgRows := strings.Count(orgBlock, "  (")
	if orgRows != 3 {
		t.Errorf("expected 3 row tuples for organizations, got %d", orgRows)
	}

	usrBlock := out[usrIdx:]
	usrRows := strings.Count(usrBlock, "  (")
	if usrRows != 3 {
		t.Errorf("expected 3 row tuples for users, got %d", usrRows)
	}
}

func TestGenerate_SkipsGeneratedColumns(t *testing.T) {
	schema := testSchema()
	rng := rand.New(rand.NewSource(42))
	out, _ := Generate(schema, 3, rng, nil)

	// Find the users INSERT and extract the column list.
	usrIdx := strings.Index(out, "INSERT INTO public.users")
	if usrIdx < 0 {
		t.Fatal("missing INSERT INTO public.users")
	}
	// Extract from "(" to ")" in the column list.
	headerEnd := strings.Index(out[usrIdx:], ") VALUES")
	if headerEnd < 0 {
		t.Fatal("cannot find ') VALUES' in users INSERT")
	}
	colHeader := out[usrIdx : usrIdx+headerEnd]

	if strings.Contains(colHeader, "score") {
		t.Error("generated column 'score' should not appear in INSERT column list")
	}
}

func TestGenerate_EnumValues(t *testing.T) {
	schema := testSchema()
	rng := rand.New(rand.NewSource(42))
	out, _ := Generate(schema, 10, rng, nil)

	validEnums := map[string]bool{
		"'active'":   true,
		"'inactive'": true,
		"'pending'":  true,
	}

	// Find the users INSERT block.
	usrIdx := strings.Index(out, "INSERT INTO public.users")
	if usrIdx < 0 {
		t.Fatal("missing INSERT INTO public.users")
	}
	usrBlock := out[usrIdx:]

	// The status column is the 4th column (0-indexed: id, org_id, email, status).
	// Parse each row tuple and check the 4th value.
	lines := strings.Split(usrBlock, "\n")
	for _, line := range lines {
		line = strings.TrimSpace(line)
		if !strings.HasPrefix(line, "(") {
			continue
		}
		// Remove leading "(" and trailing ")," or ");"
		line = strings.TrimPrefix(line, "(")
		line = strings.TrimSuffix(line, "),")
		line = strings.TrimSuffix(line, ");")
		parts := strings.Split(line, ", ")
		if len(parts) < 4 {
			continue
		}
		statusVal := parts[3]
		if !validEnums[statusVal] {
			t.Errorf("unexpected enum value for status: %s", statusVal)
		}
	}
}

func TestGenerate_FKReferences(t *testing.T) {
	schema := testSchema()
	rng := rand.New(rand.NewSource(42))
	out, _ := Generate(schema, 5, rng, nil)

	// Collect organization IDs from the organizations INSERT.
	orgIdx := strings.Index(out, "INSERT INTO public.organizations")
	usrIdx := strings.Index(out, "INSERT INTO public.users")
	if orgIdx < 0 || usrIdx < 0 {
		t.Fatal("missing expected INSERT statements")
	}

	orgBlock := out[orgIdx:usrIdx]
	orgIDs := make(map[string]bool)
	for _, line := range strings.Split(orgBlock, "\n") {
		line = strings.TrimSpace(line)
		if !strings.HasPrefix(line, "(") {
			continue
		}
		line = strings.TrimPrefix(line, "(")
		line = strings.TrimSuffix(line, "),")
		line = strings.TrimSuffix(line, ");")
		parts := strings.Split(line, ", ")
		if len(parts) >= 1 {
			orgIDs[parts[0]] = true
		}
	}

	if len(orgIDs) == 0 {
		t.Fatal("no organization IDs found")
	}

	// Check that all user org_id values reference a known organization ID.
	usrBlock := out[usrIdx:]
	for _, line := range strings.Split(usrBlock, "\n") {
		line = strings.TrimSpace(line)
		if !strings.HasPrefix(line, "(") {
			continue
		}
		line = strings.TrimPrefix(line, "(")
		line = strings.TrimSuffix(line, "),")
		line = strings.TrimSuffix(line, ");")
		parts := strings.Split(line, ", ")
		if len(parts) < 2 {
			continue
		}
		orgID := parts[1] // org_id is the 2nd column
		if !orgIDs[orgID] {
			t.Errorf("user org_id %s does not match any organization ID", orgID)
		}
	}
}

func TestGenerate_Deterministic(t *testing.T) {
	schema := testSchema()

	rng1 := rand.New(rand.NewSource(42))
	out1, _ := Generate(schema, 5, rng1, nil)

	rng2 := rand.New(rand.NewSource(42))
	out2, _ := Generate(schema, 5, rng2, nil)

	if out1 != out2 {
		t.Error("Generate with the same seed should produce identical output")
	}
}

func TestGenerate_AllPGTypes(t *testing.T) {
	// Every PG type the seed generator handles, each as a separate column.
	// All are NOT NULL so NULL injection does not interfere.
	pgTypes := []string{
		"boolean",
		"integer", "bigint", "smallint",
		"serial", "bigserial", "smallserial",
		"numeric",
		"real", "float4", "float8",
		"uuid",
		"text", "varchar", "char",
		"bytea",
		"date", "time", "timetz",
		"timestamp", "timestamptz",
		"interval",
		"json", "jsonb",
		"xml",
		"inet", "cidr", "macaddr",
		"tsvector", "tsquery",
		"oid",
		"citext",
		"int4range", "int8range", "numrange", "daterange", "tsrange", "tstzrange",
		"int4multirange", "int8multirange", "nummultirange", "datemultirange", "tsmultirange", "tstzmultirange",
	}

	var cols []model.Column
	for _, pgType := range pgTypes {
		cols = append(cols, model.Column{
			Name:    "col_" + strings.ReplaceAll(pgType, " ", "_"),
			PGType:  pgType,
			NotNull: true,
		})
	}

	schema := &model.Schema{
		Name: "public",
		Tables: []model.Table{
			{
				Name:    "test_types",
				Schema:  "public",
				Comment: "Test types",
				PK:      []string{"col_boolean"},
				Columns: cols,
			},
		},
	}

	rng := rand.New(rand.NewSource(99))
	out, _ := Generate(schema, 1, rng, nil)

	// Find the INSERT and extract the single row tuple.
	insertIdx := strings.Index(out, "INSERT INTO public.test_types")
	if insertIdx < 0 {
		t.Fatal("missing INSERT INTO public.test_types")
	}

	// Extract the row between the first "  (" and ");"
	block := out[insertIdx:]
	rowStart := strings.Index(block, "  (")
	if rowStart < 0 {
		t.Fatal("no row tuple found")
	}
	rowEnd := strings.Index(block[rowStart:], ");")
	if rowEnd < 0 {
		t.Fatal("no row terminator found")
	}
	rowStr := block[rowStart : rowStart+rowEnd+2]
	rowStr = strings.TrimPrefix(strings.TrimSpace(rowStr), "(")
	rowStr = strings.TrimSuffix(rowStr, ");")

	// Split values by ", " -- this is fragile for values containing ", " but
	// works for the known generator output because quoted strings use underscores
	// and ranges use commas without spaces after them.
	values := splitRow(rowStr)
	if len(values) != len(pgTypes) {
		t.Fatalf("expected %d values, got %d\nrow: %s", len(pgTypes), len(values), rowStr)
	}

	// Build a map for easy lookup.
	valMap := make(map[string]string)
	for i, pgType := range pgTypes {
		valMap[pgType] = values[i]
	}

	// Global check: no value should be the fallback "'sample'" used for unknown types.
	for _, pgType := range pgTypes {
		v := valMap[pgType]
		if v == "'sample'" {
			t.Errorf("%s: got fallback 'sample' value", pgType)
		}
		if v == "" {
			t.Errorf("%s: got empty value", pgType)
		}
	}

	// Per-type format checks.
	checks := []struct {
		pgType string
		check  func(string) bool
		desc   string
	}{
		{"boolean", func(v string) bool { return v == "true" || v == "false" }, "must be 'true' or 'false'"},
		{"integer", func(v string) bool { return regexp.MustCompile(`^\d+$`).MatchString(v) }, "must be all digits"},
		{"bigint", func(v string) bool { return regexp.MustCompile(`^\d+$`).MatchString(v) }, "must be all digits"},
		{"smallint", func(v string) bool { return regexp.MustCompile(`^\d+$`).MatchString(v) }, "must be all digits"},
		{"serial", func(v string) bool { return v == "DEFAULT" }, "must be DEFAULT"},
		{"bigserial", func(v string) bool { return v == "DEFAULT" }, "must be DEFAULT"},
		{"smallserial", func(v string) bool { return v == "DEFAULT" }, "must be DEFAULT"},
		{"numeric", func(v string) bool { return strings.Contains(v, ".") }, "must contain a decimal point"},
		{"real", func(v string) bool { return strings.Contains(v, ".") }, "must contain a decimal point"},
		{"float4", func(v string) bool { return strings.Contains(v, ".") }, "must contain a decimal point"},
		{"float8", func(v string) bool { return strings.Contains(v, ".") }, "must contain a decimal point"},
		{"uuid", func(v string) bool {
			return regexp.MustCompile(`^'[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}'$`).MatchString(v)
		}, "must be a quoted UUID v4"},
		{"date", func(v string) bool {
			return regexp.MustCompile(`^'\d{4}-\d{2}-\d{2}'$`).MatchString(v)
		}, "must match 'YYYY-MM-DD'"},
		{"time", func(v string) bool {
			return regexp.MustCompile(`^'\d{2}:\d{2}:\d{2}'$`).MatchString(v)
		}, "must match 'HH:MM:SS'"},
		{"timetz", func(v string) bool {
			return regexp.MustCompile(`^'\d{2}:\d{2}:\d{2}\+00'$`).MatchString(v)
		}, "must match 'HH:MM:SS+00'"},
		{"timestamp", func(v string) bool {
			return strings.Contains(v, "-") && strings.Contains(v, ":")
		}, "must contain date and time parts"},
		{"timestamptz", func(v string) bool {
			return strings.Contains(v, "-") && strings.Contains(v, ":")
		}, "must contain date and time parts"},
		{"interval", func(v string) bool {
			return strings.Contains(v, "days") || strings.Contains(v, "hours") || strings.Contains(v, "minutes")
		}, "must contain 'days', 'hours', or 'minutes'"},
		{"varchar", func(v string) bool { return strings.HasPrefix(v, "'") }, "must start with quote"},
		{"char", func(v string) bool { return strings.HasPrefix(v, "'") }, "must start with quote"},
		{"bytea", func(v string) bool { return strings.HasPrefix(v, "'\\x") }, "must start with '\\x"},
		{"inet", func(v string) bool {
			return regexp.MustCompile(`^'\d+\.\d+\.\d+\.\d+'$`).MatchString(v)
		}, "must be dotted quad like 'N.N.N.N'"},
		{"cidr", func(v string) bool { return strings.HasSuffix(v, "/24'") }, "must end with /24'"},
		{"macaddr", func(v string) bool {
			return regexp.MustCompile(`^'[0-9a-f]{2}:[0-9a-f]{2}:[0-9a-f]{2}:[0-9a-f]{2}:[0-9a-f]{2}:[0-9a-f]{2}'$`).MatchString(v)
		}, "must be colon-separated hex"},
		{"xml", func(v string) bool { return strings.Contains(v, "<val>") }, "must contain '<val>'"},
		{"tsvector", func(v string) bool { return strings.Contains(v, "::tsvector") }, "must contain '::tsvector'"},
		{"tsquery", func(v string) bool { return strings.Contains(v, "::tsquery") }, "must contain '::tsquery'"},
		{"oid", func(v string) bool { return regexp.MustCompile(`^\d+$`).MatchString(v) }, "must be all digits"},
		{"json", func(v string) bool { return strings.Contains(v, "::json") }, "must contain '::json'"},
		{"jsonb", func(v string) bool { return strings.Contains(v, "::jsonb") }, "must contain '::jsonb'"},
		{"citext", func(v string) bool { return strings.HasPrefix(v, "'") }, "must start with quote"},
		// Range types
		{"int4range", func(v string) bool { return strings.Contains(v, "[") && strings.Contains(v, ")") }, "must contain '[' and ')'"},
		{"int8range", func(v string) bool { return strings.Contains(v, "[") && strings.Contains(v, ")") }, "must contain '[' and ')'"},
		{"numrange", func(v string) bool { return strings.Contains(v, "[") && strings.Contains(v, ")") }, "must contain '[' and ')'"},
		{"daterange", func(v string) bool { return strings.Contains(v, "[") && strings.Contains(v, ")") }, "must contain '[' and ')'"},
		{"tsrange", func(v string) bool { return strings.Contains(v, "[") && strings.Contains(v, ")") }, "must contain '[' and ')'"},
		{"tstzrange", func(v string) bool { return strings.Contains(v, "[") && strings.Contains(v, ")") }, "must contain '[' and ')'"},
		// Multirange types
		{"int4multirange", func(v string) bool { return strings.Contains(v, "{[") && strings.Contains(v, ")}") }, "must contain '{[' and ')}'"},
		{"int8multirange", func(v string) bool { return strings.Contains(v, "{[") && strings.Contains(v, ")}") }, "must contain '{[' and ')}'"},
		{"nummultirange", func(v string) bool { return strings.Contains(v, "{[") && strings.Contains(v, ")}") }, "must contain '{[' and ')}'"},
		{"datemultirange", func(v string) bool { return strings.Contains(v, "{[") && strings.Contains(v, ")}") }, "must contain '{[' and ')}'"},
		{"tsmultirange", func(v string) bool { return strings.Contains(v, "{[") && strings.Contains(v, ")}") }, "must contain '{[' and ')}'"},
		{"tstzmultirange", func(v string) bool { return strings.Contains(v, "{[") && strings.Contains(v, ")}") }, "must contain '{[' and ')}'"},
	}

	for _, c := range checks {
		v := valMap[c.pgType]
		if !c.check(v) {
			t.Errorf("%s: value %q failed check: %s", c.pgType, v, c.desc)
		}
	}
}

// splitRow splits a SQL row tuple by ", " while respecting quoted strings and
// nested structures (ranges contain commas without trailing spaces).
func splitRow(row string) []string {
	var parts []string
	var current strings.Builder
	inQuote := false
	depth := 0 // tracks nesting inside '...' for range literals

	for i := 0; i < len(row); i++ {
		ch := row[i]

		if ch == '\'' && !inQuote {
			inQuote = true
			current.WriteByte(ch)
			continue
		}
		if ch == '\'' && inQuote {
			// Check for escaped quotes ('')
			if i+1 < len(row) && row[i+1] == '\'' {
				current.WriteByte(ch)
				current.WriteByte(ch)
				i++
				continue
			}
			inQuote = false
			current.WriteByte(ch)
			continue
		}
		if inQuote {
			current.WriteByte(ch)
			continue
		}

		// Outside quotes: track parenthesis depth for cast expressions.
		if ch == '(' {
			depth++
			current.WriteByte(ch)
			continue
		}
		if ch == ')' {
			depth--
			current.WriteByte(ch)
			continue
		}

		// Split on ", " only at top level.
		if depth == 0 && ch == ',' && i+1 < len(row) && row[i+1] == ' ' {
			parts = append(parts, current.String())
			current.Reset()
			i++ // skip the space
			continue
		}

		current.WriteByte(ch)
	}
	if current.Len() > 0 {
		parts = append(parts, current.String())
	}
	return parts
}

func TestGenerate_NullInjection(t *testing.T) {
	schema := &model.Schema{
		Name: "public",
		Tables: []model.Table{
			{
				Name:    "test_nulls",
				Schema:  "public",
				Comment: "Test nulls",
				PK:      []string{"id"},
				Columns: []model.Column{
					{Name: "id", PGType: "integer", NotNull: true},
					{Name: "col_text", PGType: "text", NotNull: false},
				},
			},
		},
	}

	rng := rand.New(rand.NewSource(77))
	out, _ := Generate(schema, 1000, rng, nil)

	// Count NULL values in the col_text column (2nd column).
	insertIdx := strings.Index(out, "INSERT INTO public.test_nulls")
	if insertIdx < 0 {
		t.Fatal("missing INSERT INTO public.test_nulls")
	}

	block := out[insertIdx:]
	nullCount := 0
	totalCount := 0
	for _, line := range strings.Split(block, "\n") {
		line = strings.TrimSpace(line)
		if !strings.HasPrefix(line, "(") {
			continue
		}
		totalCount++
		// Extract the col_text value (2nd column): strip parens and split.
		row := strings.TrimPrefix(line, "(")
		row = strings.TrimSuffix(row, "),")
		row = strings.TrimSuffix(row, ");")
		parts := strings.SplitN(row, ", ", 2)
		if len(parts) >= 2 && parts[1] == "NULL" {
			nullCount++
		}
	}

	if totalCount != 1000 {
		t.Fatalf("expected 1000 rows, got %d", totalCount)
	}

	pct := float64(nullCount) / float64(totalCount) * 100
	t.Logf("NULL injection: %d/%d = %.1f%%", nullCount, totalCount, pct)

	if pct < 5.0 || pct > 20.0 {
		t.Errorf("NULL percentage %.1f%% is outside expected range [5%%, 20%%]", pct)
	}
}

func TestGenerate_NullNeverForNotNull(t *testing.T) {
	schema := &model.Schema{
		Name: "public",
		Tables: []model.Table{
			{
				Name:    "test_notnull",
				Schema:  "public",
				Comment: "Test not null",
				PK:      []string{"col_text"},
				Columns: []model.Column{
					{Name: "col_text", PGType: "text", NotNull: true},
				},
			},
		},
	}

	rng := rand.New(rand.NewSource(77))
	out, _ := Generate(schema, 100, rng, nil)

	insertIdx := strings.Index(out, "INSERT INTO public.test_notnull")
	if insertIdx < 0 {
		t.Fatal("missing INSERT INTO public.test_notnull")
	}

	block := out[insertIdx:]
	for _, line := range strings.Split(block, "\n") {
		line = strings.TrimSpace(line)
		if !strings.HasPrefix(line, "(") {
			continue
		}
		val := strings.TrimPrefix(line, "(")
		val = strings.TrimSuffix(val, "),")
		val = strings.TrimSuffix(val, ");")
		if val == "NULL" {
			t.Fatal("got NULL for a NOT NULL column")
		}
	}
}
