package testdb

import (
	"strings"
	"testing"
)

func TestRenderTemplate(t *testing.T) {
	for _, lang := range []string{"go", "python", "ts", "java", "kotlin", "zig"} {
		t.Run(lang, func(t *testing.T) {
			out, err := RenderTemplate(lang, "schema.sql.sqlsplit", "postgres://localhost/mydb", "mydb")
			if err != nil {
				t.Fatalf("RenderTemplate(%q): %v", lang, err)
			}
			s := string(out)
			// Verify placeholders are replaced.
			if strings.Contains(s, "{{DDL_PATH}}") {
				t.Error("unreplaced {{DDL_PATH}}")
			}
			if strings.Contains(s, "{{BASE_URL}}") {
				t.Error("unreplaced {{BASE_URL}}")
			}
			if strings.Contains(s, "{{BASE_NAME}}") {
				t.Error("unreplaced {{BASE_NAME}}")
			}
			// Verify substituted values are present.
			if !strings.Contains(s, "schema.sql.sqlsplit") {
				t.Error("DDL path not in output")
			}
			if !strings.Contains(s, "postgres://localhost/mydb") {
				t.Error("base URL not in output")
			}
			if !strings.Contains(s, "mydb") {
				t.Error("base name not in output")
			}
			// Verify protocol version.
			if !strings.Contains(s, "protocol v1") {
				t.Error("protocol version not in output")
			}
		})
	}
}

func TestRenderTemplateGoNameAssertion(t *testing.T) {
	out, err := RenderTemplate("go", "schema.sql.sqlsplit", "postgres://localhost/mydb", "mydb")
	if err != nil {
		t.Fatalf("RenderTemplate(go): %v", err)
	}
	s := string(out)
	if !strings.Contains(s, "panic(") {
		t.Error("Go template missing panic call for name length assertion")
	}
	if !strings.Contains(s, "exceeds 63 bytes") {
		t.Error("Go template missing 'exceeds 63 bytes' assertion message")
	}
}

func TestRenderTemplateUnsupportedLang(t *testing.T) {
	_, err := RenderTemplate("ruby", "x.sql", "postgres://localhost/db", "db")
	if err == nil {
		t.Fatal("expected error for unsupported language")
	}
	if !strings.Contains(err.Error(), "unsupported language") {
		t.Errorf("unexpected error: %v", err)
	}
}

func TestWrapperOutputPath(t *testing.T) {
	tests := map[string]string{
		"go":     "internal/testdb/pgdesign_testdb.go",
		"python": "tests/pgdesign_testdb.py",
		"ts":     "test/pgdesign-testdb.ts",
		"java":   "src/test/java/pgdesign/TestDB.java",
		"kotlin": "src/test/kotlin/pgdesign/TestDB.kt",
		"zig":    "src/test/pgdesign_testdb.zig",
	}
	for lang, expected := range tests {
		if got := WrapperOutputPath(lang); got != expected {
			t.Errorf("WrapperOutputPath(%q) = %q, want %q", lang, got, expected)
		}
	}
}

func TestWrapperOutputPathUnknown(t *testing.T) {
	if got := WrapperOutputPath("ruby"); got != "" {
		t.Errorf("WrapperOutputPath(%q) = %q, want empty", "ruby", got)
	}
}

func TestRenderCITemplate(t *testing.T) {
	out, err := RenderCITemplate("github-actions", "16", []string{"go", "python", "ts"})
	if err != nil {
		t.Fatalf("RenderCITemplate: %v", err)
	}
	s := string(out)

	// PG version substituted.
	if !strings.Contains(s, "postgres:16") {
		t.Error("expected postgres:16 in output")
	}

	// Languages in matrix.
	if !strings.Contains(s, "go") {
		t.Error("expected 'go' in output")
	}
	if !strings.Contains(s, "python") {
		t.Error("expected 'python' in output")
	}
	if !strings.Contains(s, "ts") {
		t.Error("expected 'ts' in output")
	}

	// Env var present.
	if !strings.Contains(s, "PGDESIGN_DB") {
		t.Error("expected PGDESIGN_DB in output")
	}

	// Looks like valid YAML.
	if !strings.HasPrefix(s, "# Generated by pgdesign") {
		t.Error("expected output to start with generated comment")
	}

	// No unreplaced placeholders.
	if strings.Contains(s, "{{") {
		t.Error("unreplaced {{ placeholder in output")
	}
}

func TestRenderCITemplateUnsupportedProvider(t *testing.T) {
	_, err := RenderCITemplate("gitlab", "16", []string{"go"})
	if err == nil {
		t.Fatal("expected error for unsupported CI provider")
	}
	if !strings.Contains(err.Error(), "unsupported CI provider") {
		t.Errorf("unexpected error: %v", err)
	}
}

func TestTemplateTruncationUTF8Safe(t *testing.T) {
	// 36 'a' + 2 'é' (each 2 bytes in UTF-8) = 40 bytes total.
	// maxBase is 38. Character-based truncation at position 38 takes all 38
	// characters = 40 bytes (over limit). Byte-based truncation at 38 splits
	// the second 'é'. Correct truncation: 36 'a' + 1 'é' = 38 bytes.
	baseName := strings.Repeat("a", 36) + "éé"

	checks := map[string][]string{
		"go":     {"0xC0", "0x80"},
		"python": {"encode", "decode", "ignore"},
		"ts":     {"Buffer.from", "subarray", "0xC0", "0x80"},
		"java":   {"0xC0", "0x80"},
		"kotlin": {"0xC0", "0x80"},
		"zig":    {"0xC0", "0x80"},
	}

	for _, lang := range SupportedLanguages() {
		t.Run(lang, func(t *testing.T) {
			out, err := RenderTemplate(lang, "schema.sql.sqlsplit", "postgres://localhost/db", baseName)
			if err != nil {
				t.Fatalf("RenderTemplate(%q): %v", lang, err)
			}
			s := string(out)
			patterns, ok := checks[lang]
			if !ok {
				t.Fatalf("no truncation patterns defined for %q", lang)
			}
			for _, pat := range patterns {
				if !strings.Contains(s, pat) {
					t.Errorf("rendered %s template missing UTF-8 truncation pattern %q", lang, pat)
				}
			}
		})
	}
}

func TestSupportedLanguages(t *testing.T) {
	langs := SupportedLanguages()
	if len(langs) != 6 {
		t.Errorf("expected 6 supported languages, got %d", len(langs))
	}
	// Each supported language should have a template and an output path.
	for _, lang := range langs {
		if _, ok := langTemplates[lang]; !ok {
			t.Errorf("language %q missing from langTemplates", lang)
		}
		if _, ok := langOutputPaths[lang]; !ok {
			t.Errorf("language %q missing from langOutputPaths", lang)
		}
	}
}
