package main

import (
	"fmt"
	"path/filepath"
	"sort"
	"strings"

	"github.com/smm-h/pgdesign/internal/codegen"
	"github.com/smm-h/pgdesign/internal/config"
	"github.com/smm-h/pgdesign/internal/diagnostic"
	"github.com/smm-h/pgdesign/internal/extregistry"
	"github.com/smm-h/pgdesign/internal/generate"
	"github.com/smm-h/pgdesign/internal/model"
	"github.com/smm-h/pgdesign/internal/semtype"
	"github.com/smm-h/pgdesign/internal/splitfmt"
	"github.com/smm-h/pgdesign/internal/sqlparse"
)

// PlanResult holds the output of Plan: a map of absolute file paths to their
// planned content, plus any diagnostics collected during generation.
type PlanResult struct {
	// Files maps absolute file path to planned content.
	Files map[string][]byte
	// OwnedDirs maps each output directory owned by a multi-file codegen
	// output to the set of slash-separated relative file paths planned
	// inside it. Files found on disk inside an owned directory that are
	// neither in this set nor on the orphan ignore list (see orphanIgnored)
	// are orphans -- a hard error during build and check. Single-file
	// outputs own nothing; only MultiFileGenerator outputs own their
	// directory. Two outputs sharing a directory union their sets.
	OwnedDirs map[string]map[string]bool
	// Diagnostics collected during generation (warnings, info).
	Diagnostics []diagnostic.Diagnostic
}

// Plan generates all configured build outputs in memory without writing to disk.
// It iterates cfg.Output, generates content for each output, and returns a map
// of absolute file path to file content. SVG outputs are excluded because d2
// rendering is non-deterministic (layout engine produces different coordinates
// across runs), making byte-for-byte comparison unreliable.
func Plan(schema *model.Schema, cfg *config.ResolvedConfig, registry *semtype.Registry, pgVersion int) (*PlanResult, error) {
	result := &PlanResult{
		Files:     make(map[string][]byte),
		OwnedDirs: make(map[string]map[string]bool),
	}

	extReg := extregistry.NewBuiltinRegistry()
	extReg.LoadUserExtensions(configToUserExtensions(cfg.Extensions))

	// Sort output names for deterministic ordering.
	names := make([]string, 0, len(cfg.Output))
	for name := range cfg.Output {
		names = append(names, name)
	}
	sort.Strings(names)

	for _, name := range names {
		out := cfg.Output[name]
		outPath := string(out.Path)

		// SVG outputs are excluded: d2 rendering is non-deterministic (the
		// layout engine produces different coordinates across runs), so
		// byte-for-byte comparison is unreliable for freshness checks.
		if out.Format == "svg" {
			continue
		}

		// Filter schema tables by groups and/or source files when configured.
		// Both filters compose via AND: groups narrows first, source narrows further.
		outputSchema := schema
		if len(out.Groups) > 0 {
			outputSchema = outputSchema.FilterByGroups(out.Groups)
		}
		if len(out.Source) > 0 {
			outputSchema = outputSchema.FilterBySource(out.Source)
		}

		switch out.Format {
		case "sql":
			content, err := planSQL(name, outputSchema, out, outPath, registry, extReg, pgVersion, result)
			if err != nil {
				return nil, err
			}
			result.Files[outPath] = content

		case "d2":
			content, err := planGenerate(name, outputSchema, "d2", out, registry, extReg, pgVersion, result)
			if err != nil {
				return nil, err
			}
			result.Files[outPath] = []byte("# Generated by pgdesign -- do not edit\n\n" + string(content))

		case "json":
			content, err := planGenerate(name, outputSchema, "json", out, registry, extReg, pgVersion, result)
			if err != nil {
				return nil, err
			}
			result.Files[outPath] = content

		case "doc":
			content, err := planGenerate(name, outputSchema, "doc", out, registry, extReg, pgVersion, result)
			if err != nil {
				return nil, err
			}
			result.Files[outPath] = content

		case "graphql":
			content, err := planGenerate(name, outputSchema, "graphql", out, registry, extReg, pgVersion, result)
			if err != nil {
				return nil, err
			}
			result.Files[outPath] = []byte("# Generated by pgdesign -- do not edit\n\n" + string(content))

		case "codegen":
			if err := planCodegen(name, outputSchema, out, outPath, result); err != nil {
				return nil, err
			}

		default:
			return nil, fmt.Errorf("build: output %q: unsupported format %q", name, out.Format)
		}
	}

	// Any configured output path (any format, including SVG outputs that are
	// skipped from planning because d2 rendering is non-deterministic) that
	// falls inside an owned directory is treated as owned, not orphaned. The
	// same applies to companion files already in the plan (e.g., .sqlsplit).
	if len(result.OwnedDirs) > 0 {
		for _, name := range names {
			result.markOwnedIfInside(string(cfg.Output[name].Path))
		}
		for fp := range result.Files {
			result.markOwnedIfInside(fp)
		}
	}

	return result, nil
}

// markOwnedIfInside adds path to the owned set of any owned directory that
// contains it, so planned or configured outputs inside an owned directory are
// never classified as orphans.
func (r *PlanResult) markOwnedIfInside(path string) {
	for dir, owned := range r.OwnedDirs {
		rel, err := filepath.Rel(dir, path)
		if err != nil || rel == "." {
			continue
		}
		rel = filepath.ToSlash(rel)
		if rel == ".." || strings.HasPrefix(rel, "../") {
			continue
		}
		owned[rel] = true
	}
}

// planGenerate handles generation via generate.Generate for a single format.
func planGenerate(name string, schema *model.Schema, format string, out config.OutputConfig[config.AbsolutePath], registry *semtype.Registry, extReg *extregistry.Registry, pgVersion int, result *PlanResult) ([]byte, error) {
	opts := generate.Options{
		Format:       format,
		PGVersion:    pgVersion,
		TypeRegistry: registry,
		ExtRegistry:  extReg,
	}

	content, genDiags, err := generate.Generate(schema, opts)
	if err != nil {
		return nil, fmt.Errorf("build: output %q: %w", name, err)
	}
	result.Diagnostics = append(result.Diagnostics, genDiags...)
	return []byte(content), nil
}

// planSQL generates the SQL output plus its .sqlsplit companion file.
func planSQL(name string, schema *model.Schema, out config.OutputConfig[config.AbsolutePath], outPath string, registry *semtype.Registry, extReg *extregistry.Registry, pgVersion int, result *PlanResult) ([]byte, error) {
	comments := true
	if out.Comments != nil {
		comments = *out.Comments
	}

	sqlResult, genDiags, err := generate.Generate(schema, generate.Options{
		Idempotent:      out.Idempotent,
		IncludeComments: comments,
		Format:          "sql",
		PGVersion:       pgVersion,
		TypeRegistry:    registry,
		ExtRegistry:     extReg,
	})
	if err != nil {
		return nil, fmt.Errorf("build: output %q: %w", name, err)
	}
	result.Diagnostics = append(result.Diagnostics, genDiags...)

	header := "-- Generated by pgdesign -- do not edit\n\n"
	content := []byte(header + sqlResult)

	// Generate .sqlsplit companion file using the splitfmt format.
	splitPath := outPath + ".sqlsplit"
	stmts, splitErr := sqlparse.SplitStatements(sqlResult)
	if splitErr != nil {
		result.Diagnostics = append(result.Diagnostics, diagnostic.Diagnostic{
			Severity: diagnostic.Warning,
			Message:  fmt.Sprintf("sqlsplit for %q: %v", name, splitErr),
		})
	} else {
		result.Files[splitPath] = splitfmt.Encode(stmts)
	}

	return content, nil
}

// planCodegen handles codegen outputs, including both single-file and multi-file generators.
func planCodegen(name string, schema *model.Schema, out config.OutputConfig[config.AbsolutePath], outPath string, result *PlanResult) error {
	gen, ok := selectCodegenGenerator(name, out.Lang, out.Mode)
	if !ok {
		return fmt.Errorf("build: output %q: unsupported codegen lang=%q mode=%q", name, out.Lang, out.Mode)
	}

	// Configure backend selection for query-layer generators.
	if qlg, ok := gen.(*codegen.PythonQueryLayerGenerator); ok && len(out.Backends) > 0 {
		qlg.Backends = out.Backends
	}

	// Configure split mode for Python DDL generators.
	if ddlGen, ok := gen.(*codegen.PythonDDLGenerator); ok && out.SplitMode != "" {
		ddlGen.SplitMode = codegen.SplitMode(out.SplitMode)
	}

	// MultiFileGenerator: collect all files into the plan. The output path is
	// a directory that the output now owns (see PlanResult.OwnedDirs); when
	// two outputs share a directory, their owned sets are unioned.
	if mfg, ok := gen.(codegen.MultiFileGenerator); ok {
		files, diags := mfg.GenerateFiles(schema)
		result.Diagnostics = append(result.Diagnostics, diags...)
		owned := result.OwnedDirs[outPath]
		if owned == nil {
			owned = make(map[string]bool, len(files))
			result.OwnedDirs[outPath] = owned
		}
		for relPath, data := range files {
			fp := filepath.Join(outPath, relPath)
			result.Files[fp] = data
			owned[filepath.ToSlash(filepath.Clean(relPath))] = true
		}
		return nil
	}

	// Single-file codegen.
	genResult, diags := gen.Generate(schema)
	result.Diagnostics = append(result.Diagnostics, diags...)

	header := codegenHeader(out.Lang)
	if hasCommentHeader(genResult) {
		result.Files[outPath] = genResult
	} else {
		content := make([]byte, len(header)+len(genResult))
		copy(content, header)
		copy(content[len(header):], genResult)
		result.Files[outPath] = content
	}

	return nil
}
