package main

import (
	"strings"
	"testing"

	"github.com/smm-h/pgdesign/internal/config"
	"github.com/smm-h/pgdesign/internal/model"
	"github.com/smm-h/pgdesign/internal/semtype"
	"github.com/smm-h/pgdesign/internal/splitfmt"
	"github.com/smm-h/pgdesign/internal/typeinfo"
)

// minimalSchema returns a schema with one table (two columns: id uuid PK, name text).
func minimalSchema() *model.Schema {
	return &model.Schema{
		Tables: []model.Table{{
			Name:    "users",
			Schema:  "public",
			Comment: "User accounts",
			Columns: []model.Column{
				{Name: "id", PGType: typeinfo.T("uuid"), NotNull: true},
				{Name: "name", PGType: typeinfo.T("text"), NotNull: true},
			},
			PK: []string{"id"},
		}},
	}
}

func TestPlan_SQLOutput(t *testing.T) {
	if testing.Short() {
		t.Skip("Plan() generates .sqlsplit via WASM parser")
	}
	schema := minimalSchema()
	cfg := &config.ResolvedConfig{
		Output: map[string]config.OutputConfig[config.AbsolutePath]{
			"main": {
				Format: "sql",
				Path:   "/tmp/test-plan/test.sql",
			},
		},
	}
	registry := semtype.NewRegistry()

	result, err := Plan(schema, cfg, registry, 16)
	if err != nil {
		t.Fatalf("Plan returned error: %v", err)
	}

	// Verify SQL file is present.
	sqlContent, ok := result.Files["/tmp/test-plan/test.sql"]
	if !ok {
		t.Fatal("expected /tmp/test-plan/test.sql in result.Files")
	}

	// Verify .sqlsplit companion is present.
	splitContent, ok := result.Files["/tmp/test-plan/test.sql.sqlsplit"]
	if !ok {
		t.Fatal("expected /tmp/test-plan/test.sql.sqlsplit in result.Files")
	}

	// SQL content starts with the generated header.
	if !strings.HasPrefix(string(sqlContent), "-- Generated by pgdesign") {
		t.Errorf("SQL content should start with generated header, got: %s", string(sqlContent[:80]))
	}

	// SQL content contains CREATE TABLE.
	if !strings.Contains(string(sqlContent), "CREATE TABLE") {
		t.Error("SQL content should contain CREATE TABLE")
	}

	// .sqlsplit content is decodeable.
	stmts, decErr := splitfmt.Decode(splitContent)
	if decErr != nil {
		t.Fatalf("splitfmt.Decode failed: %v", decErr)
	}
	if len(stmts) == 0 {
		t.Error("expected at least one statement from splitfmt.Decode")
	}
}

func TestPlan_IdempotentSQL(t *testing.T) {
	if testing.Short() {
		t.Skip("Plan() generates .sqlsplit via WASM parser")
	}
	schema := minimalSchema()
	cfg := &config.ResolvedConfig{
		Output: map[string]config.OutputConfig[config.AbsolutePath]{
			"main": {
				Format:     "sql",
				Path:       "/tmp/test-plan/idempotent.sql",
				Idempotent: true,
			},
		},
	}
	registry := semtype.NewRegistry()

	result, err := Plan(schema, cfg, registry, 16)
	if err != nil {
		t.Fatalf("Plan returned error: %v", err)
	}

	sqlContent, ok := result.Files["/tmp/test-plan/idempotent.sql"]
	if !ok {
		t.Fatal("expected /tmp/test-plan/idempotent.sql in result.Files")
	}

	if !strings.Contains(string(sqlContent), "IF NOT EXISTS") {
		t.Error("idempotent SQL should contain IF NOT EXISTS")
	}
}

func TestPlan_CodegenConstants(t *testing.T) {
	schema := minimalSchema()
	cfg := &config.ResolvedConfig{
		Output: map[string]config.OutputConfig[config.AbsolutePath]{
			"constants": {
				Format: "codegen",
				Path:   "/tmp/test-plan/tables.go",
				Lang:   "go",
				Mode:   "constants",
			},
		},
	}

	result, err := Plan(schema, cfg, nil, 16)
	if err != nil {
		t.Fatalf("Plan returned error: %v", err)
	}

	content, ok := result.Files["/tmp/test-plan/tables.go"]
	if !ok {
		t.Fatal("expected /tmp/test-plan/tables.go in result.Files")
	}

	s := string(content)
	// Go constants codegen should reference the table name.
	if !strings.Contains(s, "users") {
		t.Errorf("constants output should contain table name 'users', got:\n%s", s)
	}
}

func TestPlan_SVGExcluded(t *testing.T) {
	schema := minimalSchema()
	cfg := &config.ResolvedConfig{
		Output: map[string]config.OutputConfig[config.AbsolutePath]{
			"diagram": {
				Format: "svg",
				Path:   "/tmp/test-plan/schema.svg",
			},
		},
	}
	registry := semtype.NewRegistry()

	result, err := Plan(schema, cfg, registry, 16)
	if err != nil {
		t.Fatalf("Plan returned error: %v", err)
	}

	if len(result.Files) != 0 {
		t.Errorf("expected empty Files for SVG output, got %d files", len(result.Files))
	}
}

func TestPlan_GroupFiltering(t *testing.T) {
	if testing.Short() {
		t.Skip("Plan() generates .sqlsplit via WASM parser")
	}
	schema := &model.Schema{
		Tables: []model.Table{
			{
				Name:    "users",
				Schema:  "public",
				Comment: "User accounts",
				Columns: []model.Column{
					{Name: "id", PGType: typeinfo.T("uuid"), NotNull: true},
					{Name: "name", PGType: typeinfo.T("text"), NotNull: true},
				},
				PK: []string{"id"},
			},
			{
				Name:    "orders",
				Schema:  "public",
				Comment: "Order records",
				Columns: []model.Column{
					{Name: "id", PGType: typeinfo.T("uuid"), NotNull: true},
					{Name: "total", PGType: typeinfo.T("numeric"), NotNull: true},
				},
				PK: []string{"id"},
			},
		},
		Groups: map[string][]string{
			"core": {"users"},
		},
	}
	cfg := &config.ResolvedConfig{
		Output: map[string]config.OutputConfig[config.AbsolutePath]{
			"core_sql": {
				Format: "sql",
				Path:   "/tmp/test-plan/core.sql",
				Groups: []string{"core"},
			},
		},
	}
	registry := semtype.NewRegistry()

	result, err := Plan(schema, cfg, registry, 16)
	if err != nil {
		t.Fatalf("Plan returned error: %v", err)
	}

	sqlContent, ok := result.Files["/tmp/test-plan/core.sql"]
	if !ok {
		t.Fatal("expected /tmp/test-plan/core.sql in result.Files")
	}

	s := string(sqlContent)
	if !strings.Contains(s, "users") {
		t.Error("filtered SQL should contain 'users' table")
	}
	if strings.Contains(s, "orders") {
		t.Error("filtered SQL should NOT contain 'orders' table (not in 'core' group)")
	}
}
