package main

import (
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"

	"github.com/smm-h/pgdesign/internal/codegen"
	"github.com/smm-h/pgdesign/internal/config"
	"github.com/smm-h/pgdesign/internal/diagnostic"
	"github.com/smm-h/pgdesign/internal/generate"
	"github.com/smm-h/pgdesign/internal/sqlparse"
)

func handleBuild(kwargs map[string]interface{}) int {
	quiet := kwargs["quiet"].(bool)
	dryRun := kwargs["dry_run"].(bool)
	noCommit := kwargs["no_commit"].(bool)

	cwd, err := os.Getwd()
	if err != nil {
		fmt.Fprintf(os.Stderr, "error: %v\n", err)
		return 1
	}

	configPath, found := config.FindConfig(cwd)
	if !found {
		fmt.Fprintln(os.Stderr, "error: no pgdesign.toml in current directory")
		return 1
	}

	cfg, err := config.Load(configPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "error: %v\n", err)
		return 1
	}

	if len(cfg.Output) == 0 {
		fmt.Fprintln(os.Stderr, "error: no [output] section in pgdesign.toml")
		return 1
	}

	// Resolve schema paths.
	var schemaPaths []string
	if len(cfg.Project.Schemas) > 0 {
		schemaPaths = cfg.SchemaFiles(cwd)
	} else {
		schemaPaths, err = resolveFromConfig(configPath)
		if err != nil {
			fmt.Fprintf(os.Stderr, "error: %v\n", err)
			return 1
		}
	}

	schema, typeReg, exitCode := parseAndBuild(schemaPaths)
	if exitCode != 0 {
		return exitCode
	}

	pgVersion := resolvePGVersion(0, cfg.Database.PGVersion, schema.PGVersion)

	// Sort output names for deterministic ordering.
	names := make([]string, 0, len(cfg.Output))
	for name := range cfg.Output {
		names = append(names, name)
	}
	sort.Strings(names)

	var writtenFiles []string

	for _, name := range names {
		out := cfg.Output[name]
		outPath := out.Path
		if !filepath.IsAbs(outPath) {
			outPath = filepath.Join(cwd, outPath)
		}

		// Filter schema tables by groups when configured.
		outputSchema := schema
		if len(out.Groups) > 0 {
			outputSchema = schema.FilterByGroups(out.Groups)
		}

		var content []byte

		switch out.Format {
		case "sql":
			comments := true
			if out.Comments != nil {
				comments = *out.Comments
			}
			result, genDiags, err := generate.Generate(outputSchema, generate.Options{
				Idempotent:      out.Idempotent,
				IncludeComments: comments,
				Format:          "sql",
				PGVersion:       pgVersion,
				TypeRegistry:    typeReg,
			})
			if err != nil {
				fmt.Fprintf(os.Stderr, "build: output %q: %v\n", name, err)
				return 1
			}
			if len(genDiags) > 0 {
				fmt.Fprint(os.Stderr, diagnostic.RenderTerminal(genDiags, true))
			}
			content = []byte("-- Generated by pgdesign -- do not edit\n\n" + result)

		case "d2":
			result, genDiags, err := generate.Generate(outputSchema, generate.Options{Format: "d2", PGVersion: pgVersion, TypeRegistry: typeReg})
			if err != nil {
				fmt.Fprintf(os.Stderr, "build: output %q: %v\n", name, err)
				return 1
			}
			if len(genDiags) > 0 {
				fmt.Fprint(os.Stderr, diagnostic.RenderTerminal(genDiags, true))
			}
			content = []byte("# Generated by pgdesign -- do not edit\n\n" + result)

		case "json":
			result, genDiags, err := generate.Generate(outputSchema, generate.Options{Format: "json", PGVersion: pgVersion, TypeRegistry: typeReg})
			if err != nil {
				fmt.Fprintf(os.Stderr, "build: output %q: %v\n", name, err)
				return 1
			}
			if len(genDiags) > 0 {
				fmt.Fprint(os.Stderr, diagnostic.RenderTerminal(genDiags, true))
			}
			content = []byte(result)

		case "svg":
			result, genDiags, err := generate.Generate(outputSchema, generate.Options{Format: "svg", PGVersion: pgVersion, TypeRegistry: typeReg})
			if err != nil {
				fmt.Fprintf(os.Stderr, "build: output %q: %v\n", name, err)
				return 1
			}
			if len(genDiags) > 0 {
				fmt.Fprint(os.Stderr, diagnostic.RenderTerminal(genDiags, true))
			}
			content = []byte(result)

		case "doc":
			result, genDiags, err := generate.Generate(outputSchema, generate.Options{Format: "doc", PGVersion: pgVersion, TypeRegistry: typeReg})
			if err != nil {
				fmt.Fprintf(os.Stderr, "build: output %q: %v\n", name, err)
				return 1
			}
			if len(genDiags) > 0 {
				fmt.Fprint(os.Stderr, diagnostic.RenderTerminal(genDiags, true))
			}
			content = []byte(result)

		case "graphql":
			result, genDiags, err := generate.Generate(outputSchema, generate.Options{Format: "graphql", PGVersion: pgVersion, TypeRegistry: typeReg})
			if err != nil {
				fmt.Fprintf(os.Stderr, "build: output %q: %v\n", name, err)
				return 1
			}
			if len(genDiags) > 0 {
				fmt.Fprint(os.Stderr, diagnostic.RenderTerminal(genDiags, true))
			}
			content = []byte("# Generated by pgdesign -- do not edit\n\n" + result)

		case "codegen":
			gen, ok := selectCodegenGenerator(name, out.Lang, out.Mode)
			if !ok {
				return 1
			}

			// Configure backend selection for query-layer generators.
			if qlg, ok := gen.(*codegen.PythonQueryLayerGenerator); ok && len(out.Backends) > 0 {
				qlg.Backends = out.Backends
			}

			// MultiFileGenerator: write multiple files into a directory.
			if mfg, ok := gen.(codegen.MultiFileGenerator); ok {
				files, diags := mfg.GenerateFiles(outputSchema)
				for _, d := range diags {
					fmt.Fprintf(os.Stderr, "%s: %s\n", d.Severity, d.Message)
				}
				if dryRun {
					for relPath, data := range files {
						fmt.Fprintf(os.Stderr, "would write %s (%d bytes)\n", filepath.Join(outPath, relPath), len(data))
					}
					continue
				}
				if err := os.MkdirAll(outPath, 0o755); err != nil {
					fmt.Fprintf(os.Stderr, "build: output %q: %v\n", name, err)
					return 1
				}
				for relPath, data := range files {
					fp := filepath.Join(outPath, relPath)
					if err := os.MkdirAll(filepath.Dir(fp), 0o755); err != nil {
						fmt.Fprintf(os.Stderr, "build: output %q: %v\n", name, err)
						return 1
					}
					if err := os.WriteFile(fp, data, 0o644); err != nil {
						fmt.Fprintf(os.Stderr, "build: output %q: %v\n", name, err)
						return 1
					}
					if !quiet {
						fmt.Fprintf(os.Stderr, "wrote %s (%d bytes)\n", fp, len(data))
					}
					writtenFiles = append(writtenFiles, fp)
				}
				continue
			}

			result, diags := gen.Generate(outputSchema)
			for _, d := range diags {
				fmt.Fprintf(os.Stderr, "%s: %s\n", d.Severity, d.Message)
			}
			header := codegenHeader(out.Lang)
			if hasCommentHeader(result) {
				content = result
			} else {
				content = append([]byte(header), result...)
			}

		default:
			fmt.Fprintf(os.Stderr, "build: output %q: unsupported format %q\n", name, out.Format)
			return 1
		}

		if dryRun {
			fmt.Fprintf(os.Stderr, "would write %s (%d bytes)\n", outPath, len(content))
			if out.Format == "sql" {
				fmt.Fprintf(os.Stderr, "would write %s.split.json\n", outPath)
			}
			continue
		}

		if err := os.MkdirAll(filepath.Dir(outPath), 0o755); err != nil {
			fmt.Fprintf(os.Stderr, "build: output %q: %v\n", name, err)
			return 1
		}
		if err := os.WriteFile(outPath, content, 0o644); err != nil {
			fmt.Fprintf(os.Stderr, "build: output %q: %v\n", name, err)
			return 1
		}
		if !quiet {
			fmt.Fprintf(os.Stderr, "wrote %s (%d bytes)\n", outPath, len(content))
		}
		writtenFiles = append(writtenFiles, outPath)

		// Generate .split.json companion for SQL outputs.
		if out.Format == "sql" {
			splitPath := outPath + ".split.json"
			header := "-- Generated by pgdesign -- do not edit\n\n"
			ddl := strings.TrimPrefix(string(content), header)
			stmts, splitErr := sqlparse.SplitStatements(ddl)
			if splitErr != nil {
				fmt.Fprintf(os.Stderr, "warning: split.json for %q: %v\n", name, splitErr)
			} else {
				type splitJSONPayload struct {
					Version    int      `json:"version"`
					Statements []string `json:"statements"`
				}
				payload := splitJSONPayload{Version: 1, Statements: stmts}
				splitJSON, jsonErr := json.MarshalIndent(payload, "", "  ")
				if jsonErr != nil {
					fmt.Fprintf(os.Stderr, "warning: split.json for %q: %v\n", name, jsonErr)
				} else {
					if err := os.WriteFile(splitPath, splitJSON, 0o644); err != nil {
						fmt.Fprintf(os.Stderr, "warning: split.json for %q: %v\n", name, err)
					} else {
						if !quiet {
							fmt.Fprintf(os.Stderr, "wrote %s (%d bytes)\n", splitPath, len(splitJSON))
						}
						writtenFiles = append(writtenFiles, splitPath)
					}
				}
			}
		}
	}

	if !dryRun && !noCommit && len(writtenFiles) > 0 {
		args := []string{"commit", "-m", "pgdesign build: regenerate outputs", "--"}
		args = append(args, writtenFiles...)
		cmd := exec.Command("safegit", args...)
		cmd.Stdout = os.Stdout
		cmd.Stderr = os.Stderr
		if err := cmd.Run(); err != nil {
			fmt.Fprintf(os.Stderr, "warning: safegit commit failed: %v\n", err)
		}
	}

	return 0
}

// selectCodegenGenerator selects the appropriate codegen.Generator for the given
// lang and mode. Returns the generator and true on success, or prints an error
// and returns false if the combination is unsupported.
func selectCodegenGenerator(outputName, lang, mode string) (codegen.Generator, bool) {
	gen, err := SelectGenerator(lang, mode)
	if err != nil {
		fmt.Fprintf(os.Stderr, "build: output %q: %v\n", outputName, err)
		return nil, false
	}
	return gen, true
}

// codegenHeader returns the generated-file header comment for the given language.
func codegenHeader(lang string) string {
	switch lang {
	case "python":
		return "# Generated by pgdesign -- do not edit\n\n"
	case "go", "zig", "ts", "java", "kotlin":
		return "// Generated by pgdesign -- do not edit\n\n"
	default:
		return ""
	}
}

// hasCommentHeader reports whether the generated output already starts with
// a comment marker (// or #), indicating the generator manages its own header.
func hasCommentHeader(data []byte) bool {
	s := strings.TrimLeft(string(data), " \t\n\r")
	return strings.HasPrefix(s, "//") || strings.HasPrefix(s, "#")
}
