package main

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sort"

	"github.com/smm-h/pgdesign/internal/codegen"
	"github.com/smm-h/pgdesign/internal/config"
	"github.com/smm-h/pgdesign/internal/diagnostic"
	"github.com/smm-h/pgdesign/internal/generate"
)

func handleBuild(kwargs map[string]interface{}) int {
	quiet := kwargs["quiet"].(bool)
	dryRun := kwargs["dry_run"].(bool)
	noCommit := kwargs["no_commit"].(bool)

	cwd, err := os.Getwd()
	if err != nil {
		fmt.Fprintf(os.Stderr, "error: %v\n", err)
		return 1
	}

	configPath, found := config.FindConfig(cwd)
	if !found {
		fmt.Fprintln(os.Stderr, "error: no pgdesign.toml in current directory")
		return 1
	}

	cfg, err := config.Load(configPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "error: %v\n", err)
		return 1
	}

	if len(cfg.Output) == 0 {
		fmt.Fprintln(os.Stderr, "error: no [output] section in pgdesign.toml")
		return 1
	}

	// Resolve schema paths.
	var schemaPaths []string
	if len(cfg.Project.Schemas) > 0 {
		schemaPaths = cfg.SchemaFiles(cwd)
	} else {
		schemaPaths, err = resolveFromConfig(configPath)
		if err != nil {
			fmt.Fprintf(os.Stderr, "error: %v\n", err)
			return 1
		}
	}

	schema, exitCode := parseAndBuild(schemaPaths)
	if exitCode != 0 {
		return exitCode
	}

	pgVersion := resolvePGVersion(0, cfg.Database.PGVersion, schema.PGVersion)

	// Sort output names for deterministic ordering.
	names := make([]string, 0, len(cfg.Output))
	for name := range cfg.Output {
		names = append(names, name)
	}
	sort.Strings(names)

	var writtenFiles []string

	for _, name := range names {
		out := cfg.Output[name]
		outPath := out.Path
		if !filepath.IsAbs(outPath) {
			outPath = filepath.Join(cwd, outPath)
		}

		var content []byte

		switch out.Format {
		case "sql":
			comments := true
			if out.Comments != nil {
				comments = *out.Comments
			}
			result, genDiags, err := generate.Generate(schema, generate.Options{
				Idempotent:      out.Idempotent,
				IncludeComments: comments,
				Format:          "sql",
				PGVersion:       pgVersion,
			})
			if err != nil {
				fmt.Fprintf(os.Stderr, "build: output %q: %v\n", name, err)
				return 1
			}
			if len(genDiags) > 0 {
				fmt.Fprint(os.Stderr, diagnostic.RenderTerminal(genDiags, true))
			}
			content = []byte("-- Generated by pgdesign -- do not edit\n\n" + result)

		case "d2":
			result, genDiags, err := generate.Generate(schema, generate.Options{Format: "d2", PGVersion: pgVersion})
			if err != nil {
				fmt.Fprintf(os.Stderr, "build: output %q: %v\n", name, err)
				return 1
			}
			if len(genDiags) > 0 {
				fmt.Fprint(os.Stderr, diagnostic.RenderTerminal(genDiags, true))
			}
			content = []byte("# Generated by pgdesign -- do not edit\n\n" + result)

		case "json":
			result, genDiags, err := generate.Generate(schema, generate.Options{Format: "json", PGVersion: pgVersion})
			if err != nil {
				fmt.Fprintf(os.Stderr, "build: output %q: %v\n", name, err)
				return 1
			}
			if len(genDiags) > 0 {
				fmt.Fprint(os.Stderr, diagnostic.RenderTerminal(genDiags, true))
			}
			content = []byte(result)

		case "svg":
			result, genDiags, err := generate.Generate(schema, generate.Options{Format: "svg", PGVersion: pgVersion})
			if err != nil {
				fmt.Fprintf(os.Stderr, "build: output %q: %v\n", name, err)
				return 1
			}
			if len(genDiags) > 0 {
				fmt.Fprint(os.Stderr, diagnostic.RenderTerminal(genDiags, true))
			}
			content = []byte(result)

		case "doc":
			result, genDiags, err := generate.Generate(schema, generate.Options{Format: "doc", PGVersion: pgVersion})
			if err != nil {
				fmt.Fprintf(os.Stderr, "build: output %q: %v\n", name, err)
				return 1
			}
			if len(genDiags) > 0 {
				fmt.Fprint(os.Stderr, diagnostic.RenderTerminal(genDiags, true))
			}
			content = []byte(result)

		case "graphql":
			result, genDiags, err := generate.Generate(schema, generate.Options{Format: "graphql", PGVersion: pgVersion})
			if err != nil {
				fmt.Fprintf(os.Stderr, "build: output %q: %v\n", name, err)
				return 1
			}
			if len(genDiags) > 0 {
				fmt.Fprint(os.Stderr, diagnostic.RenderTerminal(genDiags, true))
			}
			content = []byte("# Generated by pgdesign -- do not edit\n\n" + result)

		case "codegen":
			gen, ok := selectCodegenGenerator(name, out.Lang, out.Mode)
			if !ok {
				return 1
			}
			result, diags := gen.Generate(schema)
			for _, d := range diags {
				fmt.Fprintf(os.Stderr, "%s: %s\n", d.Severity, d.Message)
			}
			header := codegenHeader(out.Lang)
			content = append([]byte(header), result...)

		default:
			fmt.Fprintf(os.Stderr, "build: output %q: unsupported format %q\n", name, out.Format)
			return 1
		}

		if dryRun {
			fmt.Fprintf(os.Stderr, "would write %s (%d bytes)\n", outPath, len(content))
			continue
		}

		if err := os.MkdirAll(filepath.Dir(outPath), 0o755); err != nil {
			fmt.Fprintf(os.Stderr, "build: output %q: %v\n", name, err)
			return 1
		}
		if err := os.WriteFile(outPath, content, 0o644); err != nil {
			fmt.Fprintf(os.Stderr, "build: output %q: %v\n", name, err)
			return 1
		}
		if !quiet {
			fmt.Fprintf(os.Stderr, "wrote %s (%d bytes)\n", outPath, len(content))
		}
		writtenFiles = append(writtenFiles, outPath)
	}

	if !dryRun && !noCommit && len(writtenFiles) > 0 {
		args := []string{"commit", "-m", "pgdesign build: regenerate outputs", "--"}
		args = append(args, writtenFiles...)
		cmd := exec.Command("safegit", args...)
		cmd.Stdout = os.Stdout
		cmd.Stderr = os.Stderr
		if err := cmd.Run(); err != nil {
			fmt.Fprintf(os.Stderr, "warning: safegit commit failed: %v\n", err)
		}
	}

	return 0
}

// selectCodegenGenerator selects the appropriate codegen.Generator for the given
// lang and mode. Returns the generator and true on success, or prints an error
// and returns false if the combination is unsupported.
func selectCodegenGenerator(outputName, lang, mode string) (codegen.Generator, bool) {
	gen, err := SelectGenerator(lang, mode)
	if err != nil {
		fmt.Fprintf(os.Stderr, "build: output %q: %v\n", outputName, err)
		return nil, false
	}
	return gen, true
}

// codegenHeader returns the generated-file header comment for the given language.
func codegenHeader(lang string) string {
	switch lang {
	case "python":
		return "# Generated by pgdesign -- do not edit\n\n"
	case "go", "zig", "ts", "java", "kotlin":
		return "// Generated by pgdesign -- do not edit\n\n"
	default:
		return ""
	}
}
