CREATE TYPE status AS ENUM ('active', 'inactive', 'banned');
COMMENT ON TYPE status IS 'User account status';

CREATE TABLE users (
    id bigserial PRIMARY KEY,
    name text NOT NULL,
    email text NOT NULL,
    status status NOT NULL DEFAULT 'active',
    bio text,
    tags text[] NOT NULL DEFAULT '{}',
    created_at timestamptz NOT NULL DEFAULT now()
);
COMMENT ON TABLE users IS 'User accounts';
COMMENT ON COLUMN users.name IS 'Full name';
COMMENT ON COLUMN users.email IS 'Email address';

ALTER TABLE users
    ADD CONSTRAINT uq_users_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT ck_users_name_not_empty CHECK (length(name) > 0);

CREATE INDEX idx_users_status ON users (status);
CREATE INDEX idx_users_email_lower ON users (lower(email));

CREATE TABLE posts (
    id bigserial PRIMARY KEY,
    author_id bigint NOT NULL,
    title text NOT NULL,
    body text,
    published boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT now()
);
COMMENT ON TABLE posts IS 'Blog posts';

ALTER TABLE posts
    ADD CONSTRAINT fk_posts_author
    FOREIGN KEY (author_id) REFERENCES users(id) ON DELETE CASCADE;

CREATE INDEX idx_posts_author ON posts (author_id);

ALTER TABLE posts
    ADD CONSTRAINT ck_posts_title_not_empty CHECK (length(title) > 0);

-- Identity column table: GENERATED ALWAYS and GENERATED BY DEFAULT
CREATE TABLE identity_test (
    id_always bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    id_default bigint GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL
);
COMMENT ON TABLE identity_test IS 'Identity column test';

-- Partitioned table: range partitioning on created_at
CREATE TABLE events (
    id bigserial,
    event_type text NOT NULL,
    created_at timestamptz NOT NULL,
    payload jsonb,
    PRIMARY KEY (id, created_at)
) PARTITION BY RANGE (created_at);

CREATE TABLE events_2024
    PARTITION OF events
    FOR VALUES FROM ('2024-01-01') TO ('2025-01-01');

CREATE TABLE events_2025
    PARTITION OF events
    FOR VALUES FROM ('2025-01-01') TO ('2026-01-01');

-- Partitioned table: list partitioning on region
CREATE TABLE orders (
    id bigserial,
    region text NOT NULL,
    total numeric NOT NULL,
    PRIMARY KEY (id, region)
) PARTITION BY LIST (region);

CREATE TABLE orders_us
    PARTITION OF orders
    FOR VALUES IN ('us-east', 'us-west');

CREATE TABLE orders_eu
    PARTITION OF orders
    FOR VALUES IN ('eu-west', 'eu-central');

-- View: depends on users
CREATE VIEW active_users AS
    SELECT id, name, email FROM users WHERE status = 'active';
COMMENT ON VIEW active_users IS 'Active users only';

-- View: depends on users AND posts (multi-table)
CREATE VIEW user_posts AS
    SELECT u.name, p.title
    FROM users u
    JOIN posts p ON p.author_id = u.id;
COMMENT ON VIEW user_posts IS 'User post listing';

-- Materialized view: depends on posts
CREATE MATERIALIZED VIEW recent_posts AS
    SELECT id, title, created_at FROM posts
    WHERE published = true
    ORDER BY created_at DESC;
COMMENT ON MATERIALIZED VIEW recent_posts IS 'Recent published posts';

-- RLS: enable RLS on users table and create policies
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE users FORCE ROW LEVEL SECURITY;

CREATE POLICY users_select_policy ON users
    FOR SELECT
    USING (status = 'active');

CREATE POLICY users_insert_policy ON users
    FOR INSERT
    WITH CHECK (length(name) > 0);

CREATE POLICY users_restrictive ON users
    AS RESTRICTIVE
    FOR UPDATE
    USING (id = current_setting('app.user_id')::bigint)
    WITH CHECK (id = current_setting('app.user_id')::bigint);
